### ISSUE TITLE
Release, trigger, insert (etc.) a whole sub-graph

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc-flow#1314]
Maybe we should have some logic in `cylc release` (and the GUI equivalent) to
release a section of the suite graph, starting with a given task and optionally
ending at a given cycle point (although the runahead limiting and other dependencies
will probably naturally limit it).

**Comment by matthewrmshin** [comment]
Similarly a reset (to waiting) of a dependency chain would be useful.

**Comment by hjoliver** [comment]
Good idea.

**Comment by hjoliver** [comment]
Similarly, insertion a sub-graph (/dependency chain): https://github.com/cylc/cylc/issues/1704#issuecomment-166947884

**Comment by hjoliver** [comment]
[meeting] Could be a trigger option - reset downstream tasks

**Comment by oliver-sanders** [comment]
Have just met with a user who needed to re-run a section of their graph in the event that any of the tasks within this section failed. This could potentially be useful for them.

**Comment by matthewrmshin** [comment]
(In addition, any downstream tasks that are in the submitted/running state will need to be killed before being reset to waiting.)

**Comment by matthewrmshin** [comment]
(And the users want to automate this work flow - recover and retry a group of tasks and their dependencies.)

**Comment by hjoliver** [comment]
I think this is also a good fit with something that GFDL wants to do.  Any comment @chanwilson?

**Comment by matthewrmshin** [comment]
See also #2143.

**Comment by hjoliver** [comment]
Closed by spawn-on-demand #3515
