### ISSUE TITLE
Bug in at-3.1.16 breaks 'at' job log filenames.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#1410]
I've just upgraded my laptop to Fedora 21, which has at-3.1.16.

With `job submission method = at` our job err logs get names like this:

```
job.errmarcinDELIMITER598a4064
```

This is clearly something to do with this patch to at
   https://bugzilla.redhat.com/show_bug.cgi?id=486844
or this follow-up to it:
   http://pkgs.fedoraproject.org/cgit/at.git/commit/?id=50be86ebdad7bf4ff2b0809334f3c4445b1e51d4

**Comment by hjoliver** [comment]
This works:
```
at now << __END__
exho Hello 1> job.out 2> job.err
__END__
```
I get ```/bin/bash: line 1: exho: command not found``` in ```foo.err```.

This (as in ```lib/cylc/batch_sys_manager.py:job_submit()```) doesn't:
```
#/usr/bin/env python
from subprocess import Popen, PIPE
p = Popen( ['at', 'now'], stdin=-1, stdout=PIPE, stderr=PIPE)
o, e = p.communicate( "exho Hello 1> foo.out 2> foo.err")
p.wait()
```
I get ```/bin/bash: line1: exho: command not found``` in ```foo.errmarcinDELIMITER41c3544c```.

**Comment by hjoliver** [comment]
@matthewrmshin - any suggestions?  This will come to bite as all in the near future.  Maybe we need to execute ```at now``` via a shell wrapper, something like this works (tested):

```
#!/usr/bin/python
from subprocess import Popen, PIPE
p = Popen('at.sh "exho hello 1> job.out 2> job.err"', stdout=PIPE, stderr=PIPE)
o, e = p.communicate()
p.wait()
```
and ```at.sh```:
```
#!/bin/bash
at now <<__END__
$@
__END__
```
(or with the output redirection in the bash script).

Why this doesn't have the same result from the Python-only version, I'm not sure...

**Comment by matthewrmshin** [comment]
Does it work with `at -f FILE now`?

**Comment by hjoliver** [comment]
@matthewrmshin - that won't work unless we get the job script to redirect its own output to the standard cylc logs, or use a wrapper script that does the same, because ```at``` provides no way to capture output other than in an email to the user. (currently we pass a simple redirection wrapper constructed on the fly to at stdin).

**Comment by matthewrmshin** [comment]
Sorry, I meant writing the stdin script to a temporary file and then use `at -f tmpfile now`.

**Comment by hjoliver** [comment]
Yes, I think that would work, will test later...

**Comment by matthewrmshin** [comment]
An alternate approach is to modify the header of the job file to have something like:

```sh
if [[ "${1:-}" == '--wrap-me' ]]; then
    exec "$0" "$@" 1>"$0.out" 2>"$0.err"
fi
```

And we'll supply the STDIN of `at` with something like:

```sh
/home/user/cylc-run/suite/log/job/20150414T00Z/t1/01/job --wrap-me
```

**Comment by hjoliver** [comment]
I think I would prefer not to modify the header of the job file to redirect the output streams - better to have simple job scripts that emit output in the normal way if you want to run them manually for testing or debugging (I know the redirection is optional, but it still adds some extra complexity to the job script that users sometimes need to look at). Do you agree?  If so, I vote we go the way of ```at -f tmpfile now```.

**Comment by matthewrmshin** [comment]
Please try `at -f tmpfile now` to see if it works or not.

**Comment by hjoliver** [comment]
(I don't currently have a Fedora 21 VM to test this on...)

**Comment by matthewrmshin** [comment]
I am running `at-3.1.18` on my Ubuntu 16.04 VM, and `at` submit appears to behave correctly.

**Comment by hjoliver** [comment]
[meeting] - bumping to 'never', leave there in case anyone hits this 'at' problem
