### ISSUE TITLE
Require matching client-server cylc versions.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#1522]
From an email exchange between @matthewrmshin and myself:

> I am thinking that perhaps we can have a setting in place to force matching versions by default. We can have the setting switched off for development or debugging purpose. CLI clients should fail if versions don't match (or re-launch, "remrun" style?) GUI can display a dialog with a small delay then re-launch with the correct version?

**Comment by hjoliver** [comment]
(note we had an unsophisticated version of this back at cylc-4, which I called "pseudo backward compatibility": a required version had to be specified in a comment at the top of the suite definition, and commands would re-invoke themselves at that version).

**Comment by matthewrmshin** [comment]
It doesn't sound too unsophisticated. Perl, package managers, etc all have something similar (although they tend to fail if they cannot find the matching versions.)

**Comment by hjoliver** [comment]
I suppose this should be achieved via info stored in the suite run directory, so that by default the cylc version remains the same even after a shutdown.

@matthewrmshin - `rose suite-run` already does this for cylc via `log/rose-suite-run.conf`, but there's nothing to stop users from running `cylc restart` on a Rose-cylc suite, in which case the cylc version recorded by `rose suite-run` can differ from the actual version in use, which can screw up subsequent user of `rose suite-run`.  I guess this will be resolved when `rose suite-run` functionality is migrated to cylc.

**Comment by matthewrmshin** [comment]
> I guess this will be resolved when `rose suite-run` functionality is migrated to cylc.

Yes, this is one of the functionalities to migrate.

**Comment by benfitzpatrick** [comment]
Can we have an API version string for the comms layer (see #1872).

**Comment by hjoliver** [comment]
Agreed:
 * Needed. Do this after #1872, and tie it an API version string rather than cylc version.

**Comment by oliver-sanders** [comment]
#2123 would supersede this.

**Comment by matthewrmshin** [comment]
Suggest a review of this issue before releasing cylc-8.0.0.

**Comment by oliver-sanders** [comment]
Closing this here as it's no longer a Cylc Flow issue and the version forcing approach is not compatible with the new framework. We will instead attempt to either detect compatibility or support a version range.
