### ISSUE TITLE
"start with succeeded" special tasks?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#1523]
This is a user request.  An R1 build task takes some time to run.  During suite development it is often convenient to exclude the task at suite start-up, because the build already completed in a previous run.  The current `[special tasks]exclude at start-up` can be used to exclude the build task from the task pool, but then any tasks that depend on the build have to be triggered manually to get the suite going, which can be confusing to non-expert users, or else some Jinja2 graph hacking is required to make the suite start properly with or without the build task [UPDATE: or switches under runtime to dummy out the tasks in question].  It might be convenient instead to allow the first instance of a task to be inserted in the `succeeded` state.

**Comment by hjoliver** [comment]
Starting a suite with --hold and then manually setting the build task to succeeded is another option that works already, but again, that's arguably an advanced maneuver.  The suite in question is being designed with a Rose interface for non-experts, including a "switch the build off" button.

**Comment by matthewrmshin** [comment]
I would imagine that an already completed build should be very fast to run in incremental mode?

Otherwise, the `switch the build off` button can probably alter the behaviour of the suite, like so:

```
[runtime]
    [[my-build-task]]
{% if build_mode %}
        script=true
        [[[job submission]]]
            method=background
{% else %}
        script=rose task-run
        [[[job submission]]]
            method=slurm  # or whatever
        [[[directives]]]
            # slurm directives or whatever
{% endif %}
```

**Comment by hjoliver** [comment]
@matthewrmshin - sorry, in a misguided effort to simplify the problem description as much as possible I was a little fast and loose with the term "build" (and "task")!   It is actually several non-FCM non-Rose-app tasks that extract a bunch of stuff from a bunch of small git repositories, invoking their native systems if necessary, and then installing the extracted and/or built files into the suite.   The equivalent of an incremental build is not an option here.   We can achieve the desired result with Jinja2 switches as  per your example - that's exactly what I told the user initially - but on reflection I like his "start with succeeded" suggestion:
 * with lots of suite components involved the Jinja2 switches can easily get messy.
 * the proposed "start with succeeded" method concisely expresses exactly what the user wants: even though the suite is being cold-started, several initial tasks have already executed successfully, so the suite should start up with them in the 'succeeded' state.
 * (and your example is arguably abusing the [runtime] section to achieve something that should be expressed under [scheduling] :-).

**Comment by matthewrmshin** [comment]
OK. I can see what is being proposed here now. In a way, I guess this is suggesting that we have some kind of an incremental mode at the suite-task level. (Skip if target exists and up to date.)

> (and your example is arguably abusing the [runtime] section to achieve something that should be expressed under [scheduling] :-).

Yes and no. The problem is very similar to a retry of a command that supports incremental mode, e.g. a task to archive 10 big files may require a lot more resources the 1st time round, but on retry, it may require a lot less resources because it only needs to retry 2 files that failed to archive.

It would be desirable if we have a way to adjust the run time resources accordingly.

**Comment by hjoliver** [comment]
>  I guess this is suggesting that we have some kind of an incremental mode at the suite-task level.

That's an interesting way of looking at it, that I hadn't thought of.  Ah, but isn't that pretty much exactly what a restart is?  Come to think of it, couldn't my user just do a restart here?! (that question is directed at myself).  I guess during suite development it can be useful to do a lot of repeated cold-starts.

**Comment by benfitzpatrick** [comment]
I don't like the special tasks section!

How about a `--state` option to cylc run:
```
cylc run --state=succeeded:my_build_task
```
as a kind of form of almost-restart. That way, we don't have to invent new Jinja2 or edit-in-and-out a special tasks entry.

**Comment by matthewrmshin** [comment]
> Ah, but isn't that pretty much exactly what a restart is?

Yes, although I'd imagine that it is probably a bit more like a restart +reload + resetting the state of some tasks - we are only interested in re-running any tasks that require re-running (e.g. re-build something if the source has changed, re-run a task (and any downstream tasks) if its configurations are modified, etc).

**Comment by hjoliver** [comment]
To answer my own question, I think the typical use case for this - unlike a restart from previous state - is during suite development to start again from scratch but without re-running some long-running start-up tasks (typically build/install type tasks that don't have an incremental mode).

**Comment by hjoliver** [comment]
> I don't like the special tasks section!

@benfitzpatrick - I know what you mean, and I like your suggestion, but the CLI option is harder to use repeatedly, particularly if many tasks are affected (and if the suite is run from a Rose config interface).   Maybe we need to support both options, and at the same time make a CLI analogue of the existing similar special task options, ```exclude at start-up``` and ```include at start-up```?

**Comment by hjoliver** [comment]
[meeting] agreed on special-tasks interface.

**Comment by hjoliver** [comment]
No longer relevant
