### ISSUE TITLE
check use and documentation of --host options

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#1754]
Some commands may not have appropriate use and/or help info for the `--host` option, e.g. `cylc scan`:  

`--host` normally tells cylc clients which host a target suite is on, but `cylc scan` is different in that it connects to multiple suites on multiple hosts that are specified as command line arguments or listed in global config.   So `--host` is not used by scan unless `--use-ssh` is specified as well, which results in the scan command being invoked on the remote host instead of locally.

**Comment by matthewrmshin** [comment]
I don't think we have this problem any more.
