### ISSUE TITLE
Migrate "rose suite-run" functionality into cylc.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#1885]
Cylc still uses its original simplistic run-in-place model: the user registers a suite source location and cylc loads it from that location (repeatedly, for reruns, restarts, reloads),  This can be a problem if changes need to be made while the suite is running: users have to manage the distinction between source and live/running suite definitions manually, or else be very careful about working in-place.

`rose suite-run` was created largely to get around the limitations of this model by automatically separating source and installed suites, and we agreed some time ago to move its main funcitionality over to cylc in due course.

Accordingly, the new cylc suite-run command (see #1030) should:
- [x] install the suite source directory into the suite run directory, register it there, validate it, run it, etc.
- [ ] allow updating an existing installed suite with changes from the source directory.
- [x] create suite directory structure and install essential files on remote task platforms - #3687 
- [x] have the option to run remotely on e.g. the least loaded server of a pool - done #2693.

Ideally the new cylc suite-run command should also have the ability to install files from external locations, because almost any suite needs that, but this may need some discussion because it is somewhat tied to rose suite and app configuration functionality, which cylc won't be taking.

**Comment by hjoliver** [comment]
Agreed:
 * source dir installation
 * start suite on a pool server
 * update changes from source

Not clear yet, possibly later:
 * installation of external files

**Comment by arjclark** [comment]
See https://github.com/metomi/rose/issues/1536

**Comment by wxtim** [comment]
I have started to discuss plans for this meta-ticket in cylc-admin...

**Comment by oliver-sanders** [comment]
superseeded by:

* #3819 
* #3889 
* #3890 
* #3887
