### ISSUE TITLE
job.sh: SIGTERM issues; sub-shells

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#2043]
### Background

The behaviour of bash in response to the TERM signal is as follows (see http://unix.stackexchange.com/a/282631):
- If TERM is not trapped then the script exits immediately (and executes any EXIT trap).
- If TERM is trapped then the trap is not executed until any child process completes.

In most cases TERM is trapped within the cylc job script. The exception is slurm - see https://github.com/cylc/cylc/pull/1287.
### Problems

When a job is cancelled (via scancel or due to exceeding the time limit) slurm only sends the TERM signal to the main process. The job script exits immediately (because TERM is not trapped) and triggers the EXIT trap so the failure message is sent to cylc. However, child processes are not signalled so do not get a chance to terminate gracefully before they receive SIGKILL.

With other job submission methods the TERM trap will not run until any child process has completed. If that process does not exit (due to being in uninterruptible sleep or because it does not receive the TERM signal) the trap is not executed so cylc does not send the failure message.
Note that:
- PBS does not signal child processes by default (we have a site configuration to enable this). This means that cylc job scripts will not normally work correctly with PBS.
- The timeout command is not currently configured to send SIGKILL if the command doesn't exit (this feature is available in GNU coreutils v8.5 but RHEL 6 uses v8.4). The timeout command does signal the child process but if that process does not exit then the job will never complete.
### Solution

The best solution would appear to be to run the job script in 2 parts - the main part (including init-script) would set up the traps, etc and then run the second part (including env-script, pre-script, script & post-script) in the background (see http://veithen.github.io/2014/11/16/sigterm-propagation.html). The main script would trap TERM and signal any child processes as part of the trap script. @matthewrmshin  has suggested we could still use a single job script which calls itself with an argument to trigger the second part. In this way we would avoid creating an additional file and would allow edit-run to continue working as currently.

**Comment by matthewrmshin** [comment]
Note: Using a sub-shell to run user logic can also protect the main job script from getting its environment and shell settings modified by user logic.

**Comment by hjoliver** [comment]
This issue now encompasses the subshell discussion of aborted PR #2885

**Comment by hjoliver** [comment]
Moved to the beyond-cylc-8 milestone (due to current priorities) ... unless @TomekTrzeciak is able to take this on sooner.

**Comment by TomekTrzeciak** [comment]
> Moved to the beyond-cylc-8 milestone (due to current priorities) ... unless @TomekTrzeciak is able to take this on sooner.

I've recently come across another case, where setting up python environment within a job script would mess up cylc message. I think it would be good to get this sorted for cylc 8 rather than 9. I've opened #3440 to make progress on this.
