### ISSUE TITLE
forced site config (or batch system)

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#2294]
We need a way to enforce use of the proper batch scheduler on job hosts, so that users can't subvert the resource management system by submitting background jobs etc.

**Comment by matthewrmshin** [comment]
Not sure how this is going to work...
* Users can override settings with `~/.cylc/global.rc` or via `CYLC_CONF_PATH=/path/to/any/dir`.
* Users can also bypass the system by installing their own version of cylc.
* A background job can make sense sometimes, if all you are doing is a sleep-ish task that waits for something to happen on a login node, or a quick set up task for creating a directory structure.

Some sites reinforce this by restricting the amount of CPU time (and/or other resource) a process can use on the login node before it gets terminated.

Related to #1413.

**Comment by hjoliver** [comment]
@matthewrmshin - my initial post was rushed and thus glossed over a few subtleties and caveats, which you've done!

Your points, in order:
 * *users can override ...* - true at the moment, but we could make it so that (some) site global settings can't be overridden by user global settings
 * *users can bypass the system by installing their own version of Cylc* - true in principle, although I doubt anyone would bother to do this do this just to allow background jobs vs PBS.  Also in high security environments I think it is possible to prevent this: BoM will run Cylc daemons in SELinux.
 * *a background job can make sense sometimes* - I agree, but users can abuse the system and submit bigger jobs this way (I've seen it happen!). It would be better to have a special PBS (etc.) queue for these kinds of jobs, no?,

**Comment by matthewrmshin** [comment]
One way to do this is to remove all the undesirable batch system handlers from the site installation of cylc on the job host. This will cause job submission to incorrect batch systems to fail as inspired by #2301. I'll have a test to see if this will work or not (and to see if there are any holes that can be bypassed or not).

**Comment by matthewrmshin** [comment]
Actually an easier way is to modify the `.submit` method of the background handler to always return a failure.

**Comment by hjoliver** [comment]
@matthewrmshin - the trouble with your suggestion is, I think, users could get around it by providing their own `background` handler in `<suite-dir>/lib/python/`.  Hence my suggestion, maybe we need to modify `cylc jobs-submit` on the job host - it could inspect the job script and/or submit command regardless of which handler was used to generate the job.

**Comment by matthewrmshin** [comment]
OK. In which case the only foolproof way for a determined site is to modify the logic so batch system manager does not load user defined handlers. (This should also stop users from overriding the handler for PBS, for example.) I'll see if we can make it easier or not.

**Comment by matthewrmshin** [comment]
@hjoliver I have just had an inspection of `cylc jobs-submit` and `cylc.batch_sys_manager`, it looks like we are fine:
* Logic to prepend per-suite `python/` directory in `lib/cylc/__init__.py` will not work, because `CYLC_SUITE_DEF_PATH` will not be defined at this point.
* Logic in [cylc.batch_sys_manager](https://github.com/cylc/cylc/blob/7.4.0/lib/cylc/batch_sys_manager.py#L199) only *appends* per-suite `python/` and `lib/python/` sub-directories to `sys.path` so suites should be *unable* to override library under `CYLC_DIR`.

However, users will still be able to provide their own custom named handler to submit a background job. So my question: is there any reason why we need to support per-suite custom batch system handler?
* If a site or user needs a custom batch system handler, surely they would have put it under their local installation of cylc already?

**Comment by matthewrmshin** [comment]
We also need to disable this somehow.

```cfg
[runtime]
    [[task1]]
        [[[job]]]
            batch system = pbs
            batch submit command template = whatever %s  # <----!
```

**Comment by hjoliver** [comment]
>  is there any reason why we need to support per-suite custom batch system handler?

Maybe not.  The original intention was to allow Cylc users to run jobs on batch systems not yet supported centrally, without having to install their own version of Cylc.  I believe this pre-dates our global config support.

**Comment by hjoliver** [comment]
I'm not sure there is any point in doing this unless it is possible for a site to prevent users from:
 * installing and using their own Cylc on the job host, and
 * installing their own modified Cylc Python modules in PYTHONPATH on the job host

This might be feasible if users cannot log in to the job host and ssh whitelisting is used to restrict access to known cylc and rose commands, and the user environment is strictly controlled on the job host (because rsync and scp are allowed).

**Comment by oliver-sanders** [comment]
What do we want to do with this issue?

As it stands the platforms approach doesn't prevent users from "subverting the resource management system" but it does make it a lot harder to do this accidentally.

SSH whitelisting is possible but even if we make all internal cylc ssh calls using absolute paths to the cylc executable on the remote platform one could still, conceivably have a controller and worker suite on the HPC to get around this. I'm not convinced that preventing subversion of resource management systems is really within Cylc's remit. It's really more the responsibility of HPC/batch-system configuration, if nothing else there are just too many ways to get around whatever we could put in place.

**Comment by hjoliver** [comment]
Yeah I agree, closing this for now.
