### ISSUE TITLE
Improve cylc validate error output for file parse error

### ISSUE THREAD

**Issue by dvalters** [cylc/cylc-flow#2425]
To assist users in debugging cylc validation failures, we could improve the error message that is printed when validation fails. 

E.g. a user recently asked the following based on this output (via a `rose suite-run` I believe):

```
[FAIL] cylc validate -v -o /var/tmp/tmppL1UKz --strict u-foobarsuite # return-code=1, stderr=
[FAIL] FileParseError:
[FAIL] Invalid line 3813: 600
```
> Is there a way of telling which file I should be looking at to find the offending 3813 or 600 ?

The issue is that the line number here refers to the expanded processed tmp file, but it would be handy if it could somehow trace back to the original suite.rc files, if possible? (or at least just say the name of the tmp file in the "Invalid line" section.)

**Comment by matthewrmshin** [comment]
Debug mode gives this traceback:

```
Traceback (most recent call last):
  File "/home/matt/cylc.git/bin/cylc-validate", line 123, in <module>
    main()
  File "/home/matt/cylc.git/bin/cylc-validate", line 83, in main
    mem_log_func=profiler.log_memory)
  File "/home/matt/cylc.git/lib/cylc/config.py", line 153, in __init__
    self.pcfg = RawSuiteConfig(fpath, output_fname, template_vars)
  File "/home/matt/cylc.git/lib/cylc/cfgspec/suite.py", line 560, in __init__
    self.loadcfg(fpath, "suite definition")
  File "/home/matt/cylc.git/lib/parsec/config.py", line 68, in loadcfg
    sparse = parse(rcfile, self.output_fname, self.tvars)
  File "/home/matt/cylc.git/lib/parsec/fileparse.py", line 376, in parse
    'Invalid line ' + str(index + 1) + ': ' + line)
```

**Comment by hjoliver** [comment]
I guess the bad line contains the string "600"?

**Comment by matthewrmshin** [comment]
Yes, the error was in line 3813 (in the expanded file), and it contained the string `600`.

**Comment by hjoliver** [comment]
In that case I think the error message is not too bad.  Normally an erroneous line will be a string that does not happen to look like another line number, and can be found easily by grepping in the suite.rc and its include-files (if any).

**Comment by matthewrmshin** [comment]
Yes. In this case, however, the `600` was generated by Jinja2, so it was not straightforward to get to it by `grep`.

**Comment by oliver-sanders** [comment]
Closing this with #3374 as due to the nature of Jinja2 and implementation of Parsec it is pretty much impossible to tell which file the error actually came from anyway.

Instead the error informs the user that "line numbers match `cylc view -p`".
