### ISSUE TITLE
external triggers with persistent connections

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#2477]
External triggering via periodic asynchronous calls to arbitrary functions is provided by #2423. 

Some external triggering events may not be easy to detect with periodic checking, however: the event might occur between checks and leave no convenient trace.  These might be better handled by a persistent "consumer" process that watches continuously for events of interest to the suite.

One example of this kind might be filesystem events (inotify) - although we decided to avoid that for other reasons: https://github.com/cylc/cylc/issues/1469#issuecomment-334420339

Another is triggering off of messages in Apache Kafka - we can use #2423 for this, but with very high message volumes a persistent consumer would be more efficient - with no need to re-consume messages that were already processed by another trigger.

**Comment by hjoliver** [comment]
It's a little harder to see how to support persistent event consumers in a generic way.  On the other hand, it would be easier than #2423 in this sense that asynchronously call-backs would not be needed.  The consumer could just put detected events into a queue for access by the main process.

**Comment by oliver-sanders** [comment]
superseded by #3497 which would allow long lived async python functions.
