### ISSUE TITLE
parameter graph incorrect on mixing offset and conditional

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc-flow#2608]
From #2525 (documented quirk #2547).

`graph = foo<m-1> & baz => foo<m>` generates `foo_cat & baz => foo_dog`, whereas it should generate `foo_cat => foo_dog` and `baz => foo_cat & foo_dog`.

**Comment by kinow** [comment]
Hmm, I re-read the docs, and also had a quick look at unit tests and code, but I couldn't understand the issue. For me `foo<m-1> & baz => foo<m>` is correctly in generating `foo_cat & baz => foo_dog`.

`foo<m-1>` being previous-foo, or in `[cat, dog]`, `foo_cat` before `foo_dog`. So for me it would make sense "execute the next foo, only if the previous foo AND baz succeeded".

Whereas the result `foo_cat => foo_dog` and `baz => foo_cat & foo_dog` looks more like "execute the next foo, after the previous foo; execute all the foo tasks after the baz task".

I may be missing something, but maybe a new user would be confused as well?

**Comment by matthewrmshin** [comment]
Hi @kinow I think @hjoliver is the best person to explain this one. Good luck.

**Comment by hjoliver** [comment]
I think the original description isn’t very clear, sorry.   When m is cat, the expression gives “baz => foo_cat” (m-1 evaluates to nothing on the left). And when m is dog it gives “foo_cat & baz => foo_dog”.  And those two results can be rearranged to give the results described above.

**Comment by kinow** [comment]
>I think the original description isn’t very clear, sorry. When m is cat, the expression gives “baz => foo_cat” (m-1 evaluates to nothing on the left). And when m is dog it gives “foo_cat & baz => foo_dog”.

Using pen & paper, replacing the values when m=cat and m=dog, I arrived at `baz => foo_cat` and `foo_cat & baz => foo_dog`.  Thanks!

>And those two results can be rearranged to give the results described above.

Hmmm, this part didn't click for me. But I think I need to experiment and/or read the CUG to understand how those values are re-arranged into:

>>whereas it should generate foo_cat => foo_dog and baz => foo_cat & foo_dog.

**Comment by hjoliver** [comment]
> Hmmm, this part didn't click for me.

It's probably easy than you think, just a matter of rearranging what is grouped with the `&`.

```
baz => foo_cat
foo_cat & baz => foo_dog
```
is equivalent to (individual dependencies written out):
```
baz => foo_cat
foo_cat => foo_dog
baz => foo_dog
```
and that is equivalent to (by combining the two lines with `baz` on the left side):
```
baz => foo_cat & foo_dog
foo_cat => foo_dog
```
Hopefully that makes sense now!

**Comment by kinow** [comment]
Ah! Rearranging like that it makes sense!

But I have always read this `a & b => c` as "run tasks `a` and `b`; and iff both succeed then run `c`".

i.e. `c` would be executed if, and only if, both `a` and `b` succeeded, and `a` and `b` could run be initialized in parallel. So for me `foo_cat & baz => foo_dog` would mean run `foo_dog` only if both `foo_cat` and `baz` succeeded.

And `baz => foo_cat & foo_dog` would be as "if `baz` succeeds, then run both `foo_cat` and `foo_dog` (i.e. `foo_dog` will run regardless of `foo_cat`).

Is that wrong? Or is `foo_cat & baz => foo_dog` equivalent to `baz => foo_cat & foo_dog`?

**Comment by hjoliver** [comment]
> But I have always read this `a & b => c` as "run tasks `a` and `b`; and iff both succeed then run `c`".  i.e. `c` would be executed if, and only if, both `a` and `b` succeeded, and `a` and `b` could run be initialized in parallel. So for me `foo_cat & baz => foo_dog` would mean run `foo_dog` only if both `foo_cat` and `baz` succeeded.


That's right. (Well, to be pedantic, `a & b => c` does mean "run `c` only if both `a` and `b` succeed, but it doesn't necessarily mean "run `a` and `b`" first - as `a` and `b` might depend on other tasks  defined in other graph lines). 

> 
> And `baz => foo_cat & foo_dog` would be as "if `baz` succeeds, then run both `foo_cat` and `foo_dog` (i.e. `foo_dog` will run regardless of `foo_cat`).
> Is that wrong? 

No, that's right.

>  Or is `foo_cat & baz => foo_dog` equivalent to `baz => foo_cat & foo_dog`?

No, they are definitely not equivalent  But what you're missing is the other dependencies defined by the `m=cat` case, which provide additional information that leads to that result. Here's the full set of dependencies:

```
# m = cat:
baz => foo_cat
# m = dog:
foo_cat & baz => foo_dog
```

Now let's drop the comments and write all the dependencies separately (if a task has multiple dependencies they can all be defined separately, you don't have to combine them in one line with `&`):
```
baz => foo_cat  # 1
foo_cat => foo_dog  # 2
baz => foo_dog  # 3
```

Now, reorder the lines:
```
baz => foo_cat  # 1
baz => foo_dog  # 3
foo_cat => foo_dog  # 2
```

And finally, combine lines 1 and 3, which both define two tasks that depend on `baz`:
```
baz => foo_cat & foo_dog  # 1 and 3
foo_cat => foo_dog  # 2
```

So as you can see, `baz => foo_cat & foo_dog` comes from both the `m=cat` and `m=dog` cases.

**Comment by hjoliver** [comment]
> And baz => foo_cat & foo_dog would be as "if baz succeeds, then run both foo_cat and foo_dog (i.e. foo_dog will run regardless of foo_cat).
Is that wrong?

Another way to think of this:

```
a => b & c
```
means both `b` and `c` depend on `a`, BUT it only means `c` will run regardless of `b` so long as there are no other graph lines that connect `c` to `b`.  

Example:
```
a => b & c
b => c
```
The first line says both c and b depend on a; and the second line says c depends on b.  Together they say c depends on both a and b.  We could write the same set of dependencies in various ways, using `&` or not.  All of the following are equivalent:
```
# 1
a = > b & c
b => c

# 2
a => b
a => c
b => c

# 3
a => b
a & b => c

# 4
a => b => c
a => c
```
(Case 4 shows the `a => c` dependency is redundant, but Cylc doesn't automatically remove those).

**Comment by kinow** [comment]
(going to read this tomorrow morning after some coffee :coffee: , but it's starting to get clearer! thanks a million @hjoliver !!!)
