### ISSUE TITLE
cylc scan and LDAP users

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#2663]
This needs to be understood and either resolved or documented prior to the new release, as it may affect many sites.

The new `cylc scan` looks for running suites via the filesystem first, instead of port scanning.  To do this, it asks the system password database for all user names and home directories.
 
On our new HPC systems Python `pwd.getpwall()` and command line `getent passwd` list only local users (i.e. those in `/etc/passwd`) even though specific LDAP users can be queried, e.g. `getent passwd bob`.

So, by default, `cylc scan` won't show any running suites.

(Evidently I did not test scan in this way on the new system - which is not my primary development platform ... I might change that).

**Comment by hjoliver** [comment]
News in from sys admins: 

We use SSSD https://en.wikipedia.org/wiki/System_Security_Services_Daemon to cache LDAP credentials to the local password database (which evidently is not `etc/passwd`).

Evidently `/etc/sssd/sssd.conf` must contain `enumerate=true` in order for `getent passwd` to list all users, not just local ones.

**Comment by hjoliver** [comment]
I guess I should document this, and add a cylc global config option to force port scanning for sites that haven't or won't configure their systems the way we need it.

**Comment by matthewrmshin** [comment]
It looks like an inconsistent behaviour between `cylc scan` and `cylc gscan` for the default behaviour. It should only look for contact files of suites under `~/cylc-run/` instead of calling `pwd.getpwall`. `cylc gscan` is correct, as it passes `None` to `get_scan_items_from_fs`. `cylc scan` is incorrect, as it passes `[get_user()]` to `get_scan_items_from_fs`, which triggers the branch that calls `pwd.getpwall`.

I am preparing a fix the default behaviour right now.

Otherwise, we don't have the same issue as `pwd.getpwall` does the correct thing, and I don't think I have an easy fix for this if `pwd.getpwall` cannot be trusted.

**Comment by hjoliver** [comment]
How about this: test that `pwd.getpwall` returns current user name; if it does, assume we can use the filesystem to discover running suites; if not, resort to port scanning (and maybe print a warning).

**Comment by hjoliver** [comment]
(presumably normal users will be all LDAP or all local, not a mix, so that should be a safe bet)

**Comment by matthewrmshin** [comment]
(Do `pwd.getpwnam` and `pwd.getpwuid` work in your LDAP-only environment?)

**Comment by matthewrmshin** [comment]
(They are used by the `cylc.hostuserutil` module.)

**Comment by hjoliver** [comment]
Yes.  I don't really know what's happening under the hood, but *I think* SSSD caches LDAP user entries and makes them available locally via `getent` etc.  The only issue is, SSSD requires special config to list *all* users rather than retrieve info about specific users. 

I don't know sites exist with LDAP users that are not available locally via `getent` (etc.).  Maybe not, because that would presumably break some things that people expect to have available - such as `pwd.getpwnam(name)`?

**Comment by matthewrmshin** [comment]
OK. However, I hope that this issue is no longer a release blocker - given that:
* Users can use `cylc scan -a [-o OWNER1 ...]` or `cylc scan [-o OWNER1 ...] [HOST ...]`.
* This only affects scanning other users' suites (after #2666) on (some? all?) sites using SSSD+LDAP.

**Comment by hjoliver** [comment]
Yes, that's fine. Release tomorrow, come hell or high water.

**Comment by matthewrmshin** [comment]
Re-targeting this for 7.8.x. (But do we still care?)

**Comment by hjoliver** [comment]
> (But do we still care?)

We still care if this still affects what users see when they do a scan.  But perhaps documenting it would suffice.  (And it will presumably affect Cylc 8 too).

**Comment by matthewrmshin** [comment]
On Cylc 8, we can have scan going through the hub and the UI servers, so we should be able to avoid this issue.

**Comment by oliver-sanders** [comment]
Do we still want a fix for this in Cylc7, otherwise I will close this against 8.0a3 with https://github.com/cylc/cylc-flow/issues/3615.

**Comment by hjoliver** [comment]
I haven't had any complaints from users, and we have more than enough to do.  I'll amend the description of #3615 to close this...

**Comment by oliver-sanders** [comment]
Closed in Cylc8 by #3615
