### ISSUE TITLE
Examples not running under OSX

### ISSUE THREAD

**Issue by Chilipp** [cylc/cylc-flow#2689]
Refering to https://github.com/openjournals/joss-reviews/issues/737#issuecomment-394786322, I create an issue here because I could not get the software to run on OSX.

After installation and running `cylc check-software`

```
Checking your software...

Individual results:
==========================================================================================
Package (version requirements)                                     Outcome (version found)
==========================================================================================
                                   *REQUIRED SOFTWARE*                                   
Python (2.6+, <3)................................FOUND & min. version MET (2.7.12.final.0)

             *OPTIONAL SOFTWARE for the GUI & dependency graph visualisation*             
Python:pygtk (2.0+)......................................FOUND & min. version MET (2.24.0)
graphviz (any)..............................................................FOUND (2.38.0)
Python:pygraphviz (any)......................................................FOUND (1.3.1)

                       *OPTIONAL SOFTWARE for the HTML User Guide*                       
ImageMagick (any)..........................................................FOUND (6.9.5-0)

                  *OPTIONAL SOFTWARE for the HTTPS communications layer*                  
Python:urllib3 (any)..........................................................FOUND (1.22)
Python:OpenSSL (any)........................................................FOUND (18.0.0)
Python:requests (2.4.2+).................................FOUND & min. version MET (2.18.4)

                       *OPTIONAL SOFTWARE for the LaTeX User Guide*                       
TeX:framed (any)...............................................................FOUND (n/a)
TeX (3.0+)...........................................FOUND & min. version MET (3.14159265)
TeX:preprint (any).............................................................FOUND (n/a)
TeX:tex4ht (any)...............................................................FOUND (n/a)
TeX:tocloft (any)..............................................................FOUND (n/a)
TeX:texlive (any)..............................................................FOUND (n/a)
==========================================================================================

Summary:
                               ****************************                               
                                  Core requirements: ok                                  
                                  Full-functionality: ok                                  
                               ****************************
```
the software is not able to `cylc run examples/7.7.0/tutorial/oneoff/basic`. It stops after having submitted the task

![Screenshot](https://user-images.githubusercontent.com/9960249/40990821-45adf0a4-68f2-11e8-9c3b-8a3e60bb86a0.png)

All the necessary dependencies (besides cylc) have been installed via homebrew.

If I test it on Linux, it runs without problems. Can you reproduce the problem?

**Comment by hjoliver** [comment]
@Chilipp - thanks for your reviewing efforts so far!

Firstly, good to hear that it runs without problems for you on Linux.

Secondly, the symptom you describe (task job stuck in the "submitted" state) means that the HTTPS job status messages are not getting through to the server program (which is listening on port 43063 according to your screenshot above).

If you look in the `job.err` file for the task you should see some evidence of this.  See `~/cylc-run/my.suite/log/job/2021/prep/01/job.err` 

This could mean the port is blocked, or that you don't have ssl libraries installed - unlikely as you're just running on localhost, and your `cylc check-software` results looked good.

More likely (bad news for OSX):  we have been told that it is **possible** to run Cylc on OSX, particularly if your computer has been configured as part of a wider network, **but** something about the default network configuration and/or SSL setup on OSX causes a problem for us.  And this may be difficult to solve, unless you're quite expert on OSX networking.  I believe we have a note about this in the installation section of the user guide.

Unfortunately we on the small development team do not have OSX, we all work on Linux.  So for the moment I'd prefer just to warn users of the potential for problems on OSX.  Hopefully this is not a show-stopper for the review?

**Comment by hjoliver** [comment]
(We should leave this new issue open until the problem is solved, however).

**Comment by matthewrmshin** [comment]
(I have modified the user guide as part of #2688.)

**Comment by hjoliver** [comment]
Thanks @matthewrmshin. (I guess we removed the OSX info that used to be in the User Guide; I vaguely recall now, the specific advice was outdated).

**Comment by Chilipp** [comment]
Hi @hjoliver and @matthewrmshin! Thanks for your quick response to that. 

I think that is a good solution, I would just phrase it a bit differently to be more transparent (see [the code comment](https://github.com/cylc/cylc/pull/2688/files/8c799c33353a02617dfc8f044b61702ba41b15f5#r194048585) in PR https://github.com/cylc/cylc/pull/2688)

**Comment by kinow** [comment]
@oliver-sanders didn't you get Cylc master build passing on OSX? Is it still a problem?

**Comment by oliver-sanders** [comment]
Yep, I've been developing on Mac OS since March, after a few small portability changes everything is working well.

However, we still have the DNS issue (#3595) to solve. Currently I'm using this patch:

```diff
--- a/cylc/flow/hostuserutil.py
+++ b/cylc/flow/hostuserutil.py
@@ -113,7 +113,7 @@ class HostUtil:
         """Return the extended info of the current host."""
         if target not in self._host_exs:
             if target is None:
-                target = socket.getfqdn()
+                target = socket.gethostname()
             try:
                 self._host_exs[target] = socket.gethostbyname_ex(target)
             except IOError as exc:
```

This works fine for a standalone machine, however, using the hostname rather than FQDN may not be ideal for a larger network.

The irritating part is that by default Macs get the same hostname as FQDN, I think the issue is actually to do with the Python socket bindings which return an "arpa" address which bears no relation to the value of `hostname -f`:

```python
>>> import socket
>>> socket.getfqdn()
'1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa'
```

I think as it stands the plan is to wait until the platforms work is finalised then re-evaluate the use of host identification as I think we should probably be able to cut it back pretty hard now.

**Comment by oliver-sanders** [comment]
With this issue closed we are set to provide Mac OS support with Cylc 8.0b2 to be release shortly, Conda images for Mac OS should follow the release.

Note, Cylc still requires Bash, GNU coreutils (as opposed to BSD) and GNU sed (as opposed to BSD) as system dependencies.

Details can be found on the installation page:

https://cylc.github.io/cylc-doc/latest/html/installation.html#installing-on-mac-os
