### ISSUE TITLE
Log transition to ready state

### ISSUE THREAD

**Issue by trwhitcomb** [cylc/cylc-flow#2699]
Currently the status log in the suite run database begins once a job is submitted.  However, logging the time that a task entered the `ready` state in the run database would permit additional analytics to monitor suite performance.

Just like `submitted` and `started` times allow us to track how the queue wait times are distributed, `ready` to `submitted` would allow us to track how well the suite control processes are coping under load and (for example) permit decisions about distributions across suite host VMs (or allocations of additional VMs), or alterations to the size of the Cylc process pool.

**Comment by trwhitcomb** [comment]
Earlier discussion at https://groups.google.com/forum/#!topic/cylc/vcM58GtxBMo

**Comment by matthewrmshin** [comment]
I'll have a think to see how this can be done properly. The *submitted* time and *started* time are times associated with a *job*, whereas *ready* is a state of a *task*. Perhaps we need to record task state change in a separate table to have timing and the nature (e.g. dependency done or manual reset) of the state change.

**Comment by trwhitcomb** [comment]
@matthewrmshin That's why I stopped when trying to do a "quick fix" - it wasn't clear the best location for this.  My best guess at this time is that there's a `task_events` table that could be co-opted for this task, but "event" isn't the same as "state change".

**Comment by oliver-sanders** [comment]
> additional analytics to monitor suite performance.

I'm not too sure how good a metric the "ready" time is for suite performance, especially as we bravely move forward into an async world. We may even have async job submission at some point in the not-so-distant future.

We do currently have a measure of the "main loop time" (though I don't think it is exposed) which is probably a better measure of suite "load", though again, the meaning of this measurement will get broken with future async changes.

> decisions about distributions across suite host VMs (or allocations of additional VMs)

We now have load-balancing capability for suite servers built into Cylc. Balancing based on available CPU should deliver much the same effect (note we actually balance by memory usage at the Met Office).

> or alterations to the size of the Cylc process pool.

Perhaps a metric based on queue size would be better for judging this?

**Comment by hjoliver** [comment]
(Note also the "ready" state is changing in Cylc 8 to "preparing" https://cylc.github.io/cylc-admin/proposal-state-names.html )

**Comment by oliver-sanders** [comment]
The "ready" state has now changed name to "preparing", it covers:

* remote-init
* remote-fileinstall
* submission

All state transitions are now logged:

* waiting(runahead) -> waiting
* waiting -> waiting(queued)
* waiting(queued) -> preparing
* preparing -> submitted
* submitted -> running
* running -> succeeded
