### ISSUE TITLE
Jinja2 errors - line context failure

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#2708]
Report from user.  A `suite.rc` file contains a Jinja2 include-file:
```
{% include 'splat-template.rc' %}
```

There's a clash between Jinja2 and bash syntax in line 94 of the included `splat-template.rc`:

```
​   if [[ ${#ALT_DIR} -lt ${#MAIN_DIR} ]]; then
```

but validation incorrectly points to line 94 of the main file:
```
$ cylc validate suite.rc
Jinja2Error:
  File "<unknown>", line 94, in template
TemplateSyntaxError: Missing end of comment tag
Context lines:
{% set NWP_SLS_STASHLIST="" %}
{% set NWP_SLS_VARLIST="" %}
{% set NWP_STASH2CF_FILE="stash2cf.xml" %}
{% set NWP_UM_EXTN="" %}        <-- Jinja2Error  [this is suite.rc line 94]
```

**Comment by hjoliver** [comment]
See also #2572

**Comment by hjoliver** [comment]
Closing as (almost certainly?) duplicate of #2572

**Comment by oliver-sanders** [comment]
Note: closed by:

* https://github.com/cylc/cylc-flow/pull/3502 - Cylc 7
* https://github.com/cylc/cylc-flow/pull/3493 - Cylc 8
