### ISSUE TITLE
Future Cylc Authorisation / GUI Architecture

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#2729]
#### To achieve the futuristic vision of #1873 we may require an overhaul of our existing architecture and authentication model.

Most of this discussion has been off-line. This issue is to provide the key details and to keep the broader architecture and GUI specifics separate.

#### Barriers To Overcome

* Meet the browser authentication requirements of the next Cylc GUI.
* Integration (by plugin) with site identity management (LDAP, AD, RedHat IPA...)
* Enable interaction with suites on other platforms from the GUI (potentially platforms in other trust zones without SSH access).
* Remove users from the implementation of Cylc infrastructure (i.e. move Cylc servers behind some form of proxy so they can be treated as a single service).
* Maintain simple "out of the box" set-up for running suites locally.

#### Benefits To A New Architecture

*[From the June meeting]* Here's the list of characteristics we would like to achieve from a new architecture:

* Ability to interact with suites from the GUI without a local Cylc installation.
* Ability to run / restart suites from the GUI without a local Cylc installation (more difficult).
* No more port scanning (by the GUI, will still be done by a service under the proxy)
* No more self signed certificates.
* Single point of access for Cylc suites.

#### Possible Architecture

An indication of current thinking:

*Client - Suite Interaction*

![cylc-client-proxy-suite](https://user-images.githubusercontent.com/16705946/42768105-8dd424c2-8916-11e8-84ec-7fcb1afadae8.png)

*Suite - Job Interaction*

![cylc-suite-job](https://user-images.githubusercontent.com/16705946/42768025-53d3e6cc-8916-11e8-9ab5-736f47941dd6.png)

**Comment by hjoliver** [comment]
@oliver-sanders - a couple of additional comments added above.  Feel free to remove the associated "[HJO]" markup if you agree with them.

**Comment by hjoliver** [comment]
Nice diagrams :+1:

**Comment by matthewrmshin** [comment]
Diagrams lost their arrow heads? (Or is it just my browser?)

See also #1901 #2563.

**Comment by hjoliver** [comment]
(I don't see arrow heads either)

**Comment by oliver-sanders** [comment]
> Feel free to remove the associated "[HJO]" markup if you agree with them.

No, no, please add to this.

> Nice diagrams

They're Matts

> Diagrams lost their arrow heads?

Yes apparently, I did a SVG to PNG conversion to upload them, must have disappeared then.

**Comment by hjoliver** [comment]
(I meant, literally, just remove the "[HJO]" bit if you agree with my additions - they highlight the new bits, but no need to continue marking who added what if we agree on the additions).

**Comment by hjoliver** [comment]
The diagram logic looks pretty good to me.  I don't think the WebSocket and API discussions affect it (unless a persistent WebSocket connection removes the need for session management, for the GUI, which seems unlikely - we might need to re-establish the connection sometimes).

**Comment by hjoliver** [comment]
Closing as superseded by https://github.com/cylc/cylc-uiserver/issues/10
