### ISSUE TITLE
"run directory housekeeping" broken - remove it?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#2732]
Ref: https://groups.google.com/forum/#!topic/cylc/U9gzUX5LdA0

If I turn this setting on in global config, suite fails at start-up:
```
Suite shutting down - ERROR: Couldn't get passphrase
```

This is probably very easy to fix, and support with a test.  But, evidently no one uses it (because Rose does it better) so we could just remove it.  Or, is this really something that Cylc should have built-in in principle?

**Comment by matthewrmshin** [comment]
Functionality is supposed to be moved from Rose to Cylc soon.

**Comment by hjoliver** [comment]
Ah yes, of course.  (It is cycle point based in-suite housekeeping - i.e. rose_prune - which we haven't really decided on yet, in terms of transfer to Cylc, I think).

**Comment by matthewrmshin** [comment]
That's a discussion point for #1159.

**Comment by matthewrmshin** [comment]
Hopefully this will be done as part of #1885?

**Comment by hjoliver** [comment]
I'll put up a PR to remove the existing config and close this issue. The setting is broken (confirmed) so no one can be relying on it.
