### ISSUE TITLE
Task event handler string template documentation

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#2757]
New items added in #2458 were not documented.

**Comment by hjoliver** [comment]
Relatedly - I need to check when these items get defined: `%(started_time)s` seems not be be available at to `started` event handlers.

**Comment by matthewrmshin** [comment]
Looks like the ordering here is a bit wrong. https://github.com/cylc/cylc/blob/6ba43fdf58b0c2fc53232bf150e78e994cdbde5c/lib/cylc/task_events_mgr.py#L641-L643

**Comment by matthewrmshin** [comment]
Is the documentation part still true? If so, we should move the issue to live under *cylc/cylc-doc*. I'll see if the other part can be repeated or not.
