### ISSUE TITLE
Deprecate the `group` setting

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#2776]
Now that we can register suites in a hierarchy the `group` setting seems somewhat redundant.

The `group` setting is hard-coded in the suite, the suite registration can be decided on by the user allowing them to group suites as they like.

Registration hierarchies can also have multiple levels and are generally more intuitive as they are included in the suite name.

![generic](https://user-images.githubusercontent.com/16705946/42779578-c1810462-8938-11e8-90a8-8d2c03d71289.png)

This could be done with #1873, creating as a separate issue in-case there is discussion to be had here.

**Comment by arjclark** [comment]
The group setting only really came into play as a way to help operations to separate out PP suites from model suites (+ some other sub-groups within that) in gscan so if there's a sensible alternative then that's fine - its not really a setting the average user's going to use anyway, more for those running 20+ suites with critical timescales and varying priorities for order in which they need to deal with them (PSAs).

Not being privy to current discussions on #1873 - is the intention that this would purely be a rendering of the registration hierarchy or is there something else that could be done on top here? If its purely a hierarchy rendering I guess it's worth noting that, while hard-coded in the suite.rc, the group value can still be altered for a running suite via a reload whereas the registration hierarchy cannot trivially I think.

**Comment by oliver-sanders** [comment]
> the registration hierarchy cannot trivially I think

We can now change registration by shutting down the suite, moving its directory and restarting. Not perfect, is this an issue?

**Comment by arjclark** [comment]
> We can now change registration by shutting down the suite, moving its directory and restarting. Not perfect, is this an issue?

Personally, I think moving directories is worse. Worth a quick chat with Iain and co. I think to work out what they'd be happy to do - I don't think they make use of sub-directories for registration or know about it. Whether its something there's any other concerns there I don't know.

**Comment by hjoliver** [comment]
A name hierarchy doesn't work with "rose suite-run" does it (by default, i.e. without `--name=...`)?  (May be a temporary problem of course, pre migration to cylc).

**Comment by oliver-sanders** [comment]
Yes the name would have to be manually specified.

**Comment by hjoliver** [comment]
My point there was (intended to be) that most users may therefore not know about hierarchical names, and/or may be unlikely to use them, because "rose suite-run" sort-of-imposes flat names. In which case maybe it's not the best way to define grouping for gscan. (But perhaps we could make hierarchical names more favoured somehow)
