### ISSUE TITLE
local run-dir mode for sub-suites

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#2797]
Supersedes #2749 - specifically, to address this comment: https://github.com/cylc/cylc/issues/2749#issuecomment-415236320

I've figured out why `cylc run /path/to/suite.rc` unexpectedly worked, and resulted in a run directory inside the source directory, and I have a branch that intentionally supports this behaviour - which will (I think) undoubtedly be useful for sub-suites (even though we may have more complete solutions for this sort of thing longer term).

(Note this is a partial solution to old issue #171 too).

**Comment by oliver-sanders** [comment]
To add to the use cases, it looks like I was taking advantage of this feature to test a tutorial suite in Rose:

https://github.com/metomi/rose/blob/2018.06.0/etc/tutorial/cylc-forecasting-suite/.validate#L3
