### ISSUE TITLE
Move parsec to cylc package

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#2880]
This is an issue to discuss moving the `parsec` package to the `cylc` package. Currently Cylc contains two high level packages, `cylc` and `parsec`.

It means that installing Cylc as a Python module, with `python setup.py install` for instance, would allow users to not only do `import cylc`, but also `import parsec`.

Instead, moving it to the `cylc` package would make packaging simpler in `setup.py`, and reduce the namespaces added when installing Cylc.

**Comment by kinow** [comment]
These two packages are intrinsically related to `parsec` too:

- `cylc.cfgspec`
- `cylc.cfgvalidate`

But not sure if they should later be grouped together. Probably that would only complicate the task too much. Might be simple/easier to just move `parsec` in this issue, leaving any further work for another ticket(s).

**Comment by matthewrmshin** [comment]
Finally completing the discussion we had in #2609!

**Comment by matthewrmshin** [comment]
I should have done it there and then. 😜
