### ISSUE TITLE
reset state of task not in the pool

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc-flow#2903]
It should be possible for users to tell the suite to reset the state of a (historical) task not in the pool but is recorded in the suite runtime database file. (Users should not need to know about the task pool.)

See also #423 #864 #2143.

**Comment by matthewrmshin** [comment]
See also #3304.

**Comment by hjoliver** [comment]
Our proposed "hybrid mode" (display N-dependencies out from "active tasks") should solve this problem for Cylc 8 - see #3248  ... so bumping the milestone to Cylc 8 (OK?)

**Comment by oliver-sanders** [comment]
Will be closed by #3515

**Comment by oliver-sanders** [comment]
Closed by #3515
