### ISSUE TITLE
Provide metrics for monitoring tools

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#2904]
I have already bothered @hjoliver and @dwsutherland with questions regarding monitoring Cylc. During the Melbourne workshop there were some talks that involved monitoring/reporting, but done only in a push-based fashion.

This is a placeholder issue for discussion around monitoring in Cylc. I built something in Melbourne, but it is not ready to be reviewed by others yet, so will use it to explain my line of thinking, and then later ask for review to see whether it would be useful for others or not.

**Comment by kinow** [comment]
## Push based monitoring with Graphite

In the past I used Graphite (plus statsd/collectd/jolokia/jmx/etc) pushing metrics. It was done normally by adding a cron job somewhere or a daemon, or using application extension points, such as event handlers, listeners, or plugins. 

The daemon or cron job would then collect the metrics and push to the monitoring system, which normally uses - normally - a type of [round-robin time series database](https://en.wikipedia.org/wiki/RRDtool). Alternatively, the application may also send the metrics through something like an event handler that sends the metric to syslog, to a database table, a JMS queue, or another messaging system (like Kafka/RabbitMQ/etc).

But it can be a bit hard to scale. A Java cluster with 4 machines and a few hundreds users is enough to put some stress on the monitoring end.

**Comment by kinow** [comment]
## Pull based monitoring with Prometheus

A different approach, that requires less tooling, is using a pull based approach, where you have a very cheap web service end point, which in Prometheus defaults to `/metrics`.

JupyterHub comes with Prometheus, and exposes several metrics. There are built-in [metric types](https://prometheus.io/docs/concepts/metric_types/) in Prometheus such as Histogram, Gauge, and Counter.

Here's an example of how to measure the method time in Python with Prometheus, adapted from [their README](https://github.com/prometheus/client_python/blob/5aa256d8aab3b81604b855dc03f260342fc391fb/README.md):

```python
from prometheus_client import Summary
import time

# Create a metric to track time spent and requests made.
REQUEST_TIME = Summary('request_processing_seconds', 'Time spent processing request')

# Decorate function with metric.
@REQUEST_TIME.time()
def process_request(t):
    """A dummy function that takes some time."""
    time.sleep(t)
```

The decorator makes sure to track the summary of the request times (or you could have used another metric type).

Then you have a normal endpoint in Tornado, for instance, to expose all the metrics collected. Here's what [JupyterHub does](https://github.com/jupyterhub/jupyterhub/blob/0e6cf6a485b244c8b02e0da0269648c0de6370f7/jupyterhub/handlers/metrics.py):

```python
from prometheus_client import REGISTRY, CONTENT_TYPE_LATEST, generate_latest
from tornado import gen

from .base import BaseHandler
from ..utils import metrics_authentication

class MetricsHandler(BaseHandler):
    """
    Handler to serve Prometheus metrics
    """
    @metrics_authentication
    async def get(self):
        self.set_header('Content-Type', CONTENT_TYPE_LATEST)
        self.write(generate_latest(REGISTRY))

default_handlers = [
    (r'/metrics$', MetricsHandler)
]
```

The `metrics_authentication` is a decorator from JupyterHub, to protect the endpoint when a configuration is enabled. But other than that, that's all it takes to get metrics.

Here's what the metrics in JupyterHub look like, from my local notebook running `jupyterhub` in the command line with default settings, and starting one notebook.

```

```

**Comment by kinow** [comment]
## Push vs. Pull

There's no silver bullet, as in most technologies. There are even solutions to have a push based daemon sending metrics to Prometheus, creating a hybrid solution. But endpoints for metrics like the above are very cheap for Open Source tools.

It allows you to provide several metrics, without having to modify a lot of your code, and users are expected to simply plug whatever tool they prefer to retrieve the metrics.

**Comment by kinow** [comment]
I am working on `isodatetime` Python 3 support, then Cylc Python 3 support, and the new Web UI with Vue.js. But hope to have time to prepare a presentation showing how to monitor multiple metrics in Cylc with Prometheus, storing their values in the Prometheus time series DB.

Inside Prometheus there is also an alert system, that can be used to send notifications when a metric reaches a threshold. But other systems can be plugged too.

It is possible to use the time series DB and the metrics to:

- [build anomaly detection](https://prometheus.io/blog/2015/06/18/practical-anomaly-detection/) tools
- [forecast system usage/load](https://github.com/nfrumkin/forecast-prometheus), normally with some machine learning (related to what was presented in Melbourne, but we can re-use what others [especially SRE, system admins] have created for that).

**Comment by kinow** [comment]
And example of plotting the metrics with Grafana (default visualisation tool for Prometheus): https://prometheus.io/docs/visualization/grafana/

Also another example from users reporting issues with their screenshots of the metrics/monitoring (useful for maintainers familiar with the tool?): https://github.com/jupyterhub/mybinder.org-deploy/issues/350.

**Comment by hjoliver** [comment]
Good idea(s) @kinow :+1:  - definitely worth pursuing.

The metrics of most interest to Cylc users (or site admins) are job execution time, job queue time, job failures, number of jobs per day, etc.  I suppose the "pull" variant you describe above would require a back-end service that scrapes that information from individual suite DBs, in order to extract the data for these metrics.

**Comment by hjoliver** [comment]
(those grafana examples look *very* nice)

**Comment by kinow** [comment]
> I suppose the "pull" variant you describe above would require a back-end service that scrapes that information from individual suite DBs, in order to extract the data for these metrics.

That's correct. You basically avoid promising to deliver a package to some server, and instead tell users metrics will be here, so just come and fetch them.

If you download prometheus, editing the `yaml` file to have a line like the following under the `scrape_configs`:

```
scrape_configs:
  - job_name: 'cylc'
    # here users can change the scrape interval to shorter periods to investigate issues, for example
    scrape_interval: 5s
    static_configs:
      # by default will look for cylc-hub-node:9090/metrics, but that can be configured
      - targets: ['cylc-hub-node:9090']
```

Graphite's was all Python, with Twisted at its core (precursor of asyncio I believe). Prometheus was written in Go to allow for the loop to be optimized ([related talk](https://docs.google.com/presentation/d/1Zu0BdbhMRar7ycEwDi8jepGokTXTDXlKFf7C13tusuI/edit#slide=id.p))

**Comment by oliver-sanders** [comment]
A nice tool for integration with CI, helps identify when performance characteristics change and track down negative changes which lie within the "jitter" by scanning back at graphs.

https://asv.readthedocs.io/en/stable/

**Comment by hjoliver** [comment]
(Probably move UIS)

**Comment by oliver-sanders** [comment]
Going to close this cylc-flow issue and continue to track in https://github.com/cylc/cylc-admin/issues/132.
