### ISSUE TITLE
suite.rc scheduling dependencies sub-section: uniform level for cycling/non-cycling suites?

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc-flow#2905]
At the moment we have:

```
# Non cycling
[scheduling]
    [[dependencies]]
        graph = "wakeup => takephonecall"
```

```
# Cycling
[scheduling]
    initial cycle point = 20181225T00Z
    [[dependencies]]
        [[[T07]]]
            graph = "wakeup => breakfast"
```

A more uniform syntax may look like:

```
 # Non cycling
 [scheduling]
     [[dependencies]]
         1 = "wakeup => takephonecall"  # Or R1 = ...
```

```
# Cycling
 [scheduling]
     initial cycle point = 20181225T00Z
     [[dependencies]]
         T07 = "wakeup => breakfast"
```

The new syntax allows graphs (cycling or not) to be specified under the same level and removes the need to have an extra level of `dict` for each set of recurrences.

Backward compatibility upgrade should be straightforward.

@cylc/core any strong objection?

**Comment by hjoliver** [comment]
i quite like this.  

A minor niggle, perhaps - it elevates the somewhat unfortunate/mysterious "1" cycle point of a supposedly non-cycling suite to a more fundamental role.

**Comment by TomekTrzeciak** [comment]
What would be the semantics of repeated keys (concatenate?):
```
[scheduling]
     [[dependencies]]
         R1 = "foo=> bar"
         R1 = "bar=> baz"
```

Longer term, I would like to see the cycling definitions unified with parameterization (both serve as abstractions of iteration, makes sense to treat them uniformly). But that would be far more challenging than just a syntax change.

**Comment by matthewrmshin** [comment]
Similar as now. Concatenate.

**Comment by oliver-sanders** [comment]
Agreed, the current syntax bugs me. Quick thoughts:

* It would probably be best if we don't deprecate the old syntax as this would cause a lot of bother to users.
* We should fail suites with mixed syntax.
* Concatenate behaviour would be different from the default so we would need to communicate this to avoid the inevitable confusion.
* It would be nice if we could think of a path by which we could bring parameters (and subgraphs) into this now just to make sure we leave room for it later. *For example something like `<param> = bar => baz`, `[subgraph] = foo => [other-subgraph] => baz`.*
