### ISSUE TITLE
scan: excessive scanning of invalid hosts

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-flow#2927]
#### Issue

After a host server is not recognised, ``cylc scan`` will needlessly go on to across all ports, instead of terminating with a single error message to that effect. Not only is this inefficient, it spams users with the same repeated error line.

This is not entirely trivial to fix since ``multiprocessing.Process`` is used for concurrent scanning, so even with a basic shift of the ``except socket.error`` catch, there will be a message for each process in the pool, assuming it has non-singular size.

#### Minimal example

Run ``scan`` with any argument that is not a known host, e.g. ``invalidhost``:

```bash
$ cylc scan invalidhost
ERROR: [Errno -2] Name or service not known: invalidhost
...
...
...
ERROR: [Errno -2] Name or service not known: invalidhost
```
where the error line is printed *once for each port configured in the ``global.rc`` which is by default totals 50*.

**Comment by matthewrmshin** [comment]
Note this is no longer the recommended usage of `cylc scan`. The normal usage (no argument) should no longer involve full range port scan.

If I remember correctly, we have also discussed removing this usage in Cylc 8.

The other problem is that you do not know if a host:port is available or not until you try connecting to it. Service not available on one port does not mean that it will not be available on the other.

**Comment by sadielbartholomew** [comment]
I see, thanks for clarifying. Please close this if you think it appropriate.

**Comment by matthewrmshin** [comment]
If we are keeping full range port scanning functionality, we can gather up all the exceptions and group them together by hosts, so we can then just report what ports are not available on what hosts.
