### ISSUE TITLE
cylc review: improve CLI

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-flow#2928]
As outlined in https://github.com/cylc/cylc/pull/2924#discussion_r248205785. For useful feedback we should notify users when any arguments passed have no influence on the code logic, particularly as I anticipate it could often be assumed a suite argument can be passed to this utility to open directly onto that suite's listing page, e.g:

```
$ cylc review mysuite
host=0.0.0.0
pid=7395
port=8080
``

**Comment by hjoliver** [comment]
IMO we should require an explicit argument to get server status, as I had assumed was the case: `cylc review status`. I think (although not 100% sure) that's standard for daemons, both standalone and those managed by `systemctl` on Linux, for instance.  Then perhaps `cylc review` (no args) could either fail or try to open Cylc Review on the current suite?

**Comment by matthewrmshin** [comment]
We can do this now with our own logic, or we can wait until we move away from `optparse` to `argparse` when we drop support for Python 2.6. Use of `argparse` should allow us to define better options or argument choices.

**Comment by sadielbartholomew** [comment]
(I've renamed this Issue to be more accurate given the previous comments.)

I think it is best to wait until the Python 3 port is done, hence I will not assign myself & tackle it, but someone could always do so pre-migration if they wish.

**Comment by hjoliver** [comment]
closing as wontfix.  `cylc review` won't be developed further, pending integration with cylc-ui.
