### ISSUE TITLE
Minor check-software tweaks needed

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#2957]
Just discovered two problems using a Centos-based Docker container for Cylc

 - `cylc check-software` has an implicit dependence on the `which` command, which may not be installed by default (`yum install which` on RHEL systems).

We can't use `shutil.which()` till Python 3, but maybe `distutils.spawn.find_executable()`?

 - `cylc check-software` does an `import gtk` which evidently aborts with RuntimeError if no display is available - which it typically isn't in a container.

Is it possible to determine the right module version without needing a display?

**Comment by sadielbartholomew** [comment]
Thanks for providing the context, @hjoliver. I am quite tied up with Python 3 porting, so I doubt I can tackle this until next week, but that is assuming it is not urgent; I can reprioritise if necessary?

Of course if anyone else wanted to work towards closing this before that point, feel free to un-assign me!

**Comment by TomekTrzeciak** [comment]
> * `cylc check-software` has an implicit dependence on the `which` command, which may not be installed by default (`yum install which` on RHEL systems).
> 
> We can't use `shutil.which()` till Python 3, but maybe `distutils.spawn.find_executable()`?

The POSIX way of doing this (guaranteed to work on any POSIX compatible shell):
```
command -v cmd_name >/dev/null || echo command not found
```

**Comment by kinow** [comment]
I had trouble with `which` before while creating a container for Cylc (can't recall if it was with the ubuntu docker image).

But another dependency that I remember that appeared as a dependency of cylc is `less` (I had to install it in the [singularity container](https://github.com/kinow/cylc-singularity/blob/master/Singularity-cylc-7.8.1#L26)).

It is used when you execute `cylc`, to display all help options. And of course `git` too. If they install Cylc from Git, and it finds a `.git` folder, I believe it will fork a process to get the version based on commits.

**Comment by hjoliver** [comment]
@sadielbartholomew - no problem, no massive hurry on this.

@kinow - hmm, yeah it looks like `less` is a separate system package too.  We should address that in this issue too (maybe just be documenting as a dependency in this case).

@TomekTrzeciak - good suggestion, thanks!

**Comment by kinow** [comment]
Looking at some tests failing in Travis, and noticed a warning that appears but without failing the test from what I could tell.

```
===(     197;600  1/2  1/2  2/6  1/8  0/2 )=============================python3: can't open file '/home/travis/virtualenv/python3.7.1/tests/lib/python/diffr.py': [Errno 2] No such file or directory
===(     202;633  1/2  1/2  5/6  2/8  1/2 )=============================python3: can't open file '/home/travis/virtualenv/python3.7.1/tests/lib/python/diffr.py': [Errno 2] No such file or directory
===(     203;634  1/2  1/2  6/6  2/8  1/2 )=============================
```

I could not find any reference to `diffr` in `lib/cylc`, so it looks like this one is a requirement for running the tests in Cylc, and the library is [this one from PYPI](https://pypi.org/project/diffr/). I'll update #2990 to include it.

**Comment by kinow** [comment]
Related #3208

**Comment by matthewrmshin** [comment]
We should not need a hard dependency on `less`. We can either `export PAGER=cat` (or `more`) or modify the logic in `cylc` to pipe to `${PAGER:-less}` only if `${PAGER}` is set or if `less` is available.

**Comment by hjoliver** [comment]
I think we're likely to get rid of `cylc check-software` now; it was a useful helper in the days of manual package installation.  #3208
