### ISSUE TITLE
validate: implement task-name rules for xtriggers

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#2987]
At present it is possible to create xtriggers with "invalid" names which pass validation but result in runtime errors e.g:

```ini
    foo-bar = baz(pub=42)
```

For consistency we should probably enforce the same name check as for tasks?

See related #2979

**Comment by hjoliver** [comment]
Sorry - I seem to have a history of causing this sort of problem 😬 

(Yes, we should do that)

**Comment by oliver-sanders** [comment]
Easily done!

**Comment by oliver-sanders** [comment]
Add to the rules in `cylc/flow/unicode_rules.py`.

**Comment by oliver-sanders** [comment]
Closing as this is a duplicate of #3703
