### ISSUE TITLE
Protobuf & GraphQL? - Workflow Service API Data Elements

### ISSUE THREAD

**Issue by dwsutherland** [cylc/cylc-flow#3023]
There is a need to test and decide on the format of data elements, passed over ZeroMQ between the Workflow Service and the UI Server, that graphql will resolve it's queries from..

I choose to investigate protobuf, for a number of reasons including:
- It's strong type system is a direct match for the graphql schema
- It's an efficient data format.

The hope was that I could resolve GraphQL directly off the protobuf message objects...

It worked! However there may be a show stopper:
[Example Code](https://github.com/dwsutherland/graphene-protobuf)

We have fields of unknown key/value pairs `\[[[environment]]]` and outputs\.\.\. and Although protobuf can handle this;

```
message Person {
    string name = 1;
    int32 age = 2;
    map<string, string> details = 3;
}
```
it doesn't appear to preserve the order... And sections like the environment have items that rely on assignment order, so it would make sense to present them with this order in the client.

So on populating and returning a message;
```
class CreatePerson(graphene.Mutation):
    class Arguments:
        name = graphene.String()

    ok = graphene.Boolean()
    person = graphene.Field(lambda: Person)

    def mutate(self, info, name):
        person = hello_pb2.Person()
        person.name = name
        person.details['item1'] = "some string1"
        person.details['item2'] = "some string2"
        person.details['item3'] = "some string3"
        print(dict(person.details))
        ok = True
        return CreatePerson(person=MessageToDict(person,
                including_default_value_fields=True), ok=ok)
```
So
```
    result3 =  schema.execute("""mutation myFirstMutation{
        createPerson(name:"Peter") {
            person{
                name
                details
            }
            ok
        }
    }
""")

    print(json.dumps(result3.data))
```
Could return
```
{'item1': 'some string1', 'item2': 'some string2', 'item3': 'some string3'}
{"createPerson": {"person": {"name": "Peter", "details": {"item1": "some string1", "item2": "some string2", "item3": "some string3"}}, "ok": true}}
```
or
```
{'item3': 'some string3', 'item1': 'some string1', 'item2': 'some string2'}
{"createPerson": {"person": {"name": "Peter", "details": {"item3": "some string3", "item1": "some string1", "item2": "some string2"}}, "ok": true}}
```
This appears to be an attribute of the protobuf `map` message type, as iterating directly over the message is the same:
```
OrderedDict([('item3', 'some string3'), ('item1', 'some string1'), ('item2', 'some string2')])
item3 some string3
item1 some string1
item2 some string2
```
There may be ways around this like, the clunky, a listing of key & value explicitly as keys:
```
[{key: <key>, value: <val>}, {key: <key2>, value: <val2>}, . . .]
```

We need to decide from this whether protobuf meets cylc WS & UIS requirements.

**Comment by matthewrmshin** [comment]
As discussed on Riot.im... I recommend that we use a simple list of `key=value` strings for environment variables and directives.

If we need to manipulate the data, it should be easy enough to convert the list back to a Python dict (order preserved since CPython 3.6) or to a JavaScript Map (order preserved) and then apply a `key, value = item.split('=', 1)` to each item.

**Comment by kinow** [comment]
>As discussed on Riot.im... I recommend that we use a simple list of key=value strings for environment variables and directives.
>
>If we need to manipulate the data, it should be easy enough to convert the list back to a Python dict (order preserved since CPython 3.6) or to a JavaScript Map (order preserved) and then apply a key, value = item.split('=', 1) to each item.

That sounds simpler for now. So +1.

Looks like protobuf works that way by design. From their documentation for Protobuf 3 on [Maps](https://developers.google.com/protocol-buffers/docs/proto3#maps):

>Wire format ordering and map iteration ordering of map values is undefined, so you cannot rely on your map items being in a particular order. 

And it also looks like we are not alone in needing some sort of order. There was an issue from someone doing some cryptography that needed it. But this one is still open and is much simpler: https://github.com/protocolbuffers/protobuf/issues/3848

There is a workaround in that issue. But I spent some 10 minutes playing with that on the current code from `graphene-protobuf`, and it did not appear to be super simple to use that workaround.

**Comment by oliver-sanders** [comment]
A quick note on the current ZMQ implementation (open to change):

* The data interface is JSON at either end.
* JSON is encrypted using JWT for transmission.

**Comment by hjoliver** [comment]
> A quick note on the current ZMQ implementation (open to change):

Are we all agreed on going to Protobuf instead of JSON?  I think I recall that @matthewrmshin agrees. It seems sensible to me, since some discussion and investigation some time back. Slight(?) disadvantage of introducing a real compile step to the build.

**Comment by matthewrmshin** [comment]
It makes sense to me as well with the advantage of type checking etc. (Noting that GraphQL used in the frontend is also strongly typed.) The additional compilation step may or may not be bad. I guess it depends on the deployment method?

**Comment by dwsutherland** [comment]
> Are we all agreed on going to Protobuf instead of JSON? I think I recall that @matthewrmshin agrees. It seems sensible to me, since some discussion and investigation some time back. Slight(?) disadvantage of introducing a real compile step to the build.

> It makes sense to me as well with the advantage of type checking etc. (Noting that GraphQL used in the frontend is also strongly typed.) The additional compilation step may or may not be bad. I guess it depends on the deployment method?

Pretty sure the only time you compile is on change of the `.proto`  message-definition/`protobuf-schema`, as that's when the corresponding python module is generated... Once it's generated the only other thing you need is the python library `pip install protobuf`... 

So we'll have two extra files; the protobuf definition (say `ui_data.proto` or something) and the corresponding generated module `ui_data_pb2.py` ...  And it only needs to be a developer that "compiles" on change of the `.proto`..

Yes, that type checking will help ensure that the WS and UIS data are in sync.. (also declaring fields as required and/or setting defaults)..

**Comment by hjoliver** [comment]
Well, compiled code is platform-specific so in general the compilation has to be done at **install time** ... unless we provide platform-specific binary packages for installation (which we might do for some target systems, but probably not all of them).

**Comment by kinow** [comment]
I am still going through the Python documentation for Protobuf (luckily it's similar to Java in some parts), so others can correct me if I am wrong. But I think we will have `proto` -- compiling to --> `*.py` files committed to our repository.

@dwsutherland 's [example repository](https://github.com/dwsutherland/graphene-protobuf) contains the `hello.proto`, which he compiled to `hello_pb2.py`. `hello.py` could actually be `main.py`, as that is not related to `hello.proto` directly. It merely imports the `hello_pb2` module.

So in theory, if we release 8.0.0 with a version of the messaging layer compiled with protobuf, and did not change anything for 8.1.0, then there would be no need to re-compile it (except maybe improvements with new compiler? bug fixes, performance, etc), and it would still work. 

As a test, I just uninstalled `protobuf-compiler` from Ubuntu, so I don't have `protoc` (protobuf compiler) anymore. But I still have the python module for protobuf, so `import google.protobuf` works in Python.

The example from @dwsutherland 's repository worked without re-compiling in my environment. And I suspect he compiled it on Windows (the first README I read there mentioned an EXE file...)

**Comment by hjoliver** [comment]
OK, I think we're both right!   It seems there is a pure Python implementation of protobuf, but it is much(?) slower than using a Python interface to the "real" compiled C++ implementation.  I'll post my reference to Riot.im later.  In that case the right way to go is Python, with the option to go hard core if it provides a significant advantage in our context.  (@kinow - can we can make `setup.py` fetch non-PyPi sources and invoke a C++ compiler during `pip install`? - I'm pretty sure this happens when installing pygraphviz).

**Comment by kinow** [comment]
>OK, I think we're both right! It seems there is a pure Python implementation of protobuf, but it is much(?) slower than using a Python interface to the "real" compiled C++ implementation.

Interesting! 

>  I'll post my reference to Riot.im later.

Please do. Comparing the Java and the Python docs, I think the C++ alternative is not mentioned in Java. Either the performance is OK in Java, or using native code would cause more issues (so using protobuf with python would be advantegeous). 

>  (@kinow - can we can make setup.py fetch non-PyPi sources and invoke a C++ compiler during pip install? - I'm pretty sure this happens when installing pygraphviz).

That's doable, but would be more a hack and platform specific. That's one of the selling points of anaconda, including system packages.

**Comment by hjoliver** [comment]
> That's doable, but would be more a hack and platform specific

Well the compilation (of C++) bit is necessarily platform-specific anyway, so maybe no worse than that.

**Comment by dwsutherland** [comment]
That article you sited on riot.im is old.. CPP is the default implementation
```
(protographene) sutherlander@cortex-vbox:learn_protobuf$ pip freeze
aniso8601==3.0.2
graphene==2.1.3
graphql-core==2.1
graphql-relay==0.4.5
promise==2.2.1
protobuf==3.7.0
Rx==1.6.1
six==1.12.0
(protographene) sutherlander@cortex-vbox:learn_protobuf$ python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
cpp
```
So we only need `pip install protobuf` on any platform... see this issue:
https://github.com/protocolbuffers/protobuf/issues/1332

**Comment by dwsutherland** [comment]
Hence it should be fast.. and I don't think we would want to slow it down by forcing a pure python implementation (if possible).

**Comment by dwsutherland** [comment]
I also think the terms are confusing ... Because we usually associate compiling to platform and language specific invocation to machine binary.. But I think the `.proto => "compile" => python module` is really generating from definition via the protoc, but doesn't compile any machine binary...  (excuse any newb terminology misuse)

**Comment by hjoliver** [comment]
If it's a C++ runtime someone has to have compiled it to binary machine code *for our specific platforms*, and made it available. (Luckily "our specific platforms" are just Linux flavours and OSX at the moment ... nothing weird like Cray Unicos :-)

**Comment by dwsutherland** [comment]
closed by https://github.com/cylc/cylc-flow/pull/3122
