### ISSUE TITLE
Link to GitHub sources instead of pointing to local <cylc-dir>/folder/examples/etc

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3038]
More reading documentation time for me :grimacing: In _11.2. Built-in Suite State Triggers_, we point to users that they are able to read examples in a folder like `<cylc-dir>/etc/examples/...`.

However, once #2989 is done, some users simply won't have a local Cylc directory. The directory will be somewhere in either within the user directory, or in the system Python libraries folder. And the binary files will also move around. (or they may even be in an Anaconda folder, or installed somewhere via RPM) (or they may not even be included in the PYPI package!).

So I think we can perhaps do as some other projects do, and instead of saying:

As a simple example, consider the suites in `<cylc-dir>/etc/examples/xtrigger/suite_state/`. The “upstream” suite (which we want to trigger off of) looks like this

We could link to the GitHub repository (maybe with a tag instead of `master`) and say:

As a simple example, consider the [example xtrigger suites](https://github.com/cylc/cylc/tree/master/etc/examples/xtrigger). The “upstream” suite (which we want to trigger off of) looks like this

Thoughts? If not, we may need another solution for the examples directories that will be harder for some users to locate.

**Comment by hjoliver** [comment]
Closed by #3162 (I think).
