### ISSUE TITLE
Remove unnecessary shebang in Python files

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3041]
Hi,

While preparing a simple pull request for #3040 , I gave a step back to look at `xrandom.py` and see what else that file had. And noticed the `#/usr/bin/env python3` shebang, present in most (all?) of Cylc files.

As far as I know, that shebang is useful only for the scripts that may be executed directly (e.g. `./myscript.py`). So in the case of `xrandom.py` it implies that that script could be executed with `python3`, but actually that file is not supposed to be used that way, but instead only via Python import module.

I think the shebangs could be removed, which would save some commits when Python 4 is released too. And maybe we should include `# -*- coding: utf-8 -*-`? I believe `isodatetime` does that already.

Thoughts?

**Comment by hjoliver** [comment]
Haha, you're right ... I've vaguely intended to do something about this for ever (approximately).  The original reason (at least in my mind) was to support manual command line driven unit tests (`if __name__ == __main__: ...`).  But in reality we never did that much, and we've since moved on to much better things anyway.

So my thoughts are: yes (remove the shebangs); and yes (add the utf-8 coding lines).

**Comment by hjoliver** [comment]
Python 4 ... argh!!!  I imagine we'll have to completely replace the "old" web UI with a new cybernetic direct-brain-link at the same time. 😬

**Comment by kinow** [comment]
Haha, for me Python 3.8 it already quite a jump from Python 3.3. Can't imagine what a Python 4 would look like.

Will wait to see what others think. This might be a spam-commit, so might push it till 7.8.x is stable, and there's some quiet period for everybody in git, to make `diff`ing less painful.

**Comment by matthewrmshin** [comment]
Yes, that's what we do under Rose and Isodatetime. So :+1: to the proposal.

**Comment by oliver-sanders** [comment]
In Python3 UTF8 is assumed so `# -*- coding: utf-8 -*-` lines are obsolete, we should remove them from Rose and Isodatetime.

[PEP3120](https://www.python.org/dev/peps/pep-3120/)

**Comment by sgaist** [comment]
Hi,

I can take care of this one :-)

**Comment by kinow** [comment]
Hi @sgaist 

That would be great! Have a look at the CONTRIBUTING.md too as it contains useful information for your first PR to Cylc Flow :-)

Thanks
Bruno

**Comment by sgaist** [comment]
Sure thing, I'll read the file :-)

Should the utf-8 lines also be removed at the same time or should it rather be part of another cleanup pr ?

**Comment by kinow** [comment]
I think both can be done in the same PR. I think we probably have only a few files with the ut8 line.

**Comment by sgaist** [comment]
Indeed, there are not so many files.

However some of them looks like not "part of the Cylc Suite Engine", should they be left as is ?

**Comment by kinow** [comment]
>However some of them looks like not "part of the Cylc Suite Engine", should they be left as is ?

Oh, interesting. Which files?

**Comment by sgaist** [comment]
There's the protobuf generated file: ws_messages_pb2.py

Then the resolvers.py and schema.py files in network that are copyrighted to "NIWA and British Crown (Met Office) & contributors"

**Comment by kinow** [comment]
>There's the protobuf generated file: ws_messages_pb2.py

Oh, that's right. That file can be left as-is as it's compiled by `protoc` whenever there's a change to the Protobuf schema.

>Then the resolvers.py and schema.py files in network that are copyrighted to "NIWA and British Crown (Met Office) & contributors"

That copyright part is correct. But looks like some files are missing the part "THIS FILE IS PART OF THE CYLC SUITE ENGINE.". This can be left for later (but if you are interested, you can send a separate PR to update the files that are missing it).

I think we can work on just removing the shebang and the few utf8 lines. What do you think?

**Comment by sgaist** [comment]
Ok, it's good for me.

I'll cleanup these files and prepare an additional PR that adds the missing line to the header of the few files missing them.

**Comment by kinow** [comment]
Thanks @sgaist !

**Comment by sgaist** [comment]
One additional question, should the bin folder also be cleaned up with regards to the shebang line ?

**Comment by kinow** [comment]
@sgaist 

>One additional question, should the bin folder also be cleaned up with regards to the shebang line ?

No. That file contains scripts that are actually executed, so the shebang lines may be used (i.e. if not executed via `python cylc-message`, then the shebang is helpful/necessary).

If curious, when you install `cylc-flow` with `pip` or `conda`, the scripts in that folder are put in your `$PATH` because of [this line](https://github.com/cylc/cylc-flow/blob/9ff5b7719fe924a9a2c8c1b3446faaaf47a4c5b2/setup.py#L75). Which magically copies those files to a folder in your `$PATH` (varies if using Conda or Setuptools).

**Comment by sgaist** [comment]
In that case, may I suggest using [entry_points](https://packaging.python.org/specifications/entry-points/) ?

**Comment by kinow** [comment]
> In that case, may I suggest using [entry_points](https://packaging.python.org/specifications/entry-points/) ?

That's a good suggestion! You'll soon find out I have a very bad memory. But from what I recall; we tried it first with entry_points, but then realized it wouldn't work because... I think... we have some Shell scripts that are either executing pure shell (e.g. `cycl` typo alias helper) or invoking Python code (e.g. `cylc-grep`)?

Probably related to your suggestion:

- https://github.com/cylc/cylc-flow/issues/2802
- https://github.com/cylc/cylc-flow/issues/2959

I think if we move the commands to pure Python we will a) be able to write tests, b) re-use the code in other parts and even in external code, c) use entry_points and allow users to extend the functionality... but we are probably digressing here 🙂 

I haven't looked at those issues in quite some time (currently working on cylc-ui JS, so my memory may be wrong), but would be nice to get the ball rolling soon. Feel free to have a look at these two issues above, though they may take a bit longer to code.

**Comment by oliver-sanders** [comment]
> I think... we have some Shell scripts

Yep. I think moving to `entry_points` will need to be saved for future work if we want to do it as it's a little more involved. Quick summary:

* Most of these Bash scripts are just fancy aliases (they run `exec` which means the command gets corrected in process listings which is useful).
* The really big problem is `bin/cylc`, this actually used to be implemented in Python, it's knida my fault it got converted to Bash, we thought there would be a performance boost.
* There are only three other Bash scripts in the `bin/` dir. They kinda make sense as Bash scripts but are all pretty simple so could be converted to Python if desired for consistency:
   * `graph-diff`
   * `jobscript`
   * `scp-transfer`

**Comment by sgaist** [comment]
In that case, we could move everything that is python to use entry_points and keep the aliases.

On the subject of process listing, I have found https://github.com/dvarrazzo/py-setproctitle which could be of interest for an "all python" solution.

**Comment by kinow** [comment]
>In that case, we could move everything that is python to use entry_points and keep the aliases.

I am not sure if that's that simple. But this would be an immense contribution to the project. I remember seeing other projects with a central command that would invoke subcommands, and it was all Python. Will try to find it later.

Let's move the discussion to the actual issue #2802 as this issue has been closed @sgaist :+1:
