### ISSUE TITLE
Kill not holding task in pbs

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#3052]
Hi cylc team,

I don't know if this is something on our end, or a repeatable bug for you guys as well, but when I kill a PBS task, it doesn't hold it like is expected. Well, it does for a second or two, but then it moves into the retry phase.

When I do the same for localhost + background task combination, it works correctly, and the task stays held.

I have run this with `CYLC_VERSION 7.7.2 and 7.8.0`

Example suite (comment out relevant parts to make it run as a background/localhost task):

```
[scheduling]
    [[dependencies]]
        graph = "foo"
[runtime]
    [[foo]]
        script = """
sleep 20
if (( CYLC_TASK_TRY_NUMBER < 25 )); then
    bin/false
fi
"""
        [[[remote]]]
            host = MY_REMOTE_HOST
        [[[job]]]
            execution retry delays = 30*PT15S
            batch system = pbs
            execution time limit = PT55M
        [[[directives]]]
            -l select=1:ncpus=1:mem=1G
            -q = MY_QUEUE
            -P = MY_PROJECT
```

I've attached videos below (zipped because GitHub doesn't like mp4 files but does accept zip files).

Expected behavour (local/background):
[local.zip](https://github.com/cylc/cylc/files/3020833/local.zip)

Actual behaviour (remote/pbs):
[pbs.zip](https://github.com/cylc/cylc/files/3020836/pbs.zip)

**Comment by matthewrmshin** [comment]
OK. I'll take a look to see if the problem is still there under the 7.8.x branch.

**Comment by matthewrmshin** [comment]
Problem repeated. The sequence of event is roughly as follow:

0. Workflow server (WFS, previously known as *suite server program*) receives kill command.
1. WFS holds the tasks.
   * Task state: *running* -> *running (held)*.
2. WFS invokes `cylc jobs-kill ...`.
3. `cylc jobs-kill ...` successfully invokes `qdel ...`.
4. `cylc jobs-kill ...` returns 0. WFS processes its output.
   * Task state: *running (held)* -> *held (retrying)*.
5. Job script gets signal from PBS. Invokes `cylc message` to tell WFS it has received a signal.
6. WFS processes the message.
   * Task state: *held (retrying)* -> *retrying*. <- **problem here**

**Comment by matthewrmshin** [comment]
Move milestone. #3053 will address 7.8.x. I'll forward port that to master soon.
