### ISSUE TITLE
A few improvements for xtrigger_mgr.py

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3057]
Hi!

`cylc.xtrigger_mgr.py` contains the `XtriggerManager` class, and is used by the `Config` (to validate) and `Scheduler`. The `Scheduler` also has a `TaskPool`.

At the moment, the method `check_xtriggers` is in `TaskPool`, but this is mainly about checking for the status of xtriggers. We are calling `xtriggers` in `TaskPool`, and giving it a `proc_pool` (subprocess pool), but this has little to do with the `TaskPool` - it only needs the list of tasks.

I did a quick experiment moving `check_xtriggers` to `XtriggerManager`. Then removed an unused parameter in its constructor, and added a new parameter to pass the `proc_pool` to the `XtriggerManager`.

https://github.com/cylc/cylc/compare/master...kinow:xtrigger-minor-improvements

If others agree with the change, I will write some unit tests later and prepare a pull request for the later milestone (or cylc8 if it's better?).

My motivation for this is from trying to use the `TaskPool` in Jupyter Notebooks to learn about its API. Then I realized I needed the `XtriggerManager`, even though I only wanted to try to populate the pool and play with its API. After this change, I wouldn't need the `XtriggerManager` at all to interact with the `TaskPool` :)

Which means we are reducing dependency between objects, and isolating responsibilities.

Cheers
Bruno

ps: also [forcing named parameters](https://www.python.org/dev/peps/pep-3102/) to prevent accidentally passing wrong objects (as I did a few times while writing this change).

**Comment by kinow** [comment]
And Travis is happy with the changes in my branch :+1:

**Comment by hjoliver** [comment]
Sounds sensible to me @kinow

**Comment by matthewrmshin** [comment]
Reducing dependency between modules and classes is good for me.

**Comment by kinow** [comment]
Roger that :tada: 

FWIW, here's what Cylc's internal dependency looks like in `master` now.

![cylc-master](https://user-images.githubusercontent.com/304786/55518375-43ab5900-56d0-11e9-9cdc-5a23728bb51a.png)

The only difference after this change is the dependency in `cylc.task_pool.py` reducing from 7 to 6 :+1: PR on its way.

**Comment by hjoliver** [comment]
Ouch, that ain't too pretty!

**Comment by matthewrmshin** [comment]
Is it just Graphviz or does it really look that bad?

**Comment by kinow** [comment]
I think it's Graphviz, probably the graph could be better organized.

There is no cyclic dependency (there's one in `isodatetime` however, will write an issue explaining later), it's just the number of dependencies for each class/module that is causing the confusion.

But from using Notebooks trying to use Cylc API as a user (i.e. `import cylc... ` then instantiate objects in the notebook and play with them), and from writing unit tests, I can tell that in a few parts I wish I didn't need to create so many objects just to validate a cycle point, or to see what would happen in the scheduler loop.

**Comment by kinow** [comment]
FWIW, my `.pydeps` used for Cylc: https://gist.github.com/kinow/0735b5c07ee564c7a991cb09e080f9be

**Comment by oliver-sanders** [comment]
Closed by #3072
