### ISSUE TITLE
03-clock-triggered-non-utc-mode.t failing in NZ time

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3073]
Running `cylc test-battery` in my computer (rarely run locally the complete battery) for #2990 , noticed one error that could be related to my NZ time zone, or to something with `isodatetime`. The test failing is [`03-clock-triggered-non-utc-mode.t`](https://github.com/cylc/cylc/blob/41023f395d101aa4ecc0a178279303be3a271ea4/tests/cylc-show/03-clock-triggered-non-utc-mode.t).

In one of the tests, it compares line by line a file with [`comm`](https://linux.die.net/man/1/comm) and checks that the file contains certain lines we expect to be present.

e.g.

We expect it to have `  o  Triggers at ... 2014-08-08T09:05:00+13` in a file such as

```
Test File:
title: (not given)
description: (not given)
URL: (not given)

prerequisites (- => not satisfied):
  - show.20140808T0900+13 succeeded

outputs (- => not completed):
  - foo.20140808T0900+13 expired
  - foo.20140808T0900+13 submitted
  - foo.20140808T0900+13 submit-failed
  - foo.20140808T0900+13 started
  - foo.20140808T0900+13 succeeded
  - foo.20140808T0900+13 failed

other:
  o  Clock trigger time reached ... True
  o  Triggers at ... 2014-08-08T09:05:00+13:00
```

Notice that the line line in the file is `  o  Triggers at ... 2014-08-08T09:05:00+13:00`, not `  o  Triggers at ... 2014-08-08T09:05:00+13`.

So that line does not match the expected, and the test fails.

**Comment by kinow** [comment]
Yup, doing `export export TZ=UTC` before `cylc test-battery ./tests/cylc-show/03-clock-triggered-non-utc-mode.t` fixed in my environment.

I am not on `master`, but on a new branch with `setup.py`, using version 2.0.0 of `isodatetime`.

**Comment by matthewrmshin** [comment]
The test is totally flawed. I notice that while working on my branch last night.

**Comment by matthewrmshin** [comment]
I'll forward port this change to master (#3053 for 7.8.x) soon:
https://github.com/cylc/cylc/pull/3053/files#diff-347246bfb541d9e1b39b1a54b4773626

**Comment by matthewrmshin** [comment]
Close by #3137.
