### ISSUE TITLE
Revisit CYLC_DIR use

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3080]
We had a few hiccups with `CYLC_DIR` when adding `setup.py` to the project (#2989). That's due to how setuptools installs python projects, where files may use multiple folders, so there's no more concept of `CYLC_DIR` after this.

Using Anaconda and virtual environments, it's not necessary to have `CYLC_DIR` any longer. A few fixes were done for #2989, but there might be still some commands using it (and perhaps working or not).

**Comment by hjoliver** [comment]
@kinow - I guess the point of this issue is just to check for any remaining use of CYLC_DIR and remove it, after #2989 is merged?

**Comment by kinow** [comment]
That's right @hjoliver. A just-in-case issue

**Comment by hjoliver** [comment]
I'm working on getting rid of CYLC_DIR, will post a PR soon.  Some details:
