### ISSUE TITLE
Revisit the CYLC_VERSION use prior to setup.py

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3081]
Prior to setuptools and `setup.py`, we used `CYLC_VERSION` to allow users to switch between versions of Cylc (as far as I understand it). After setuptools, it will be harder to maintain this feature.

But users might be able to have the same feature through virtual environments anaconda, etc.

This issue is a left over of #2989, to revisit its use, and document what must be done with it now.

Quoting @hjoliver comment from another issue:

> ATM users can run different suites at different versions if necessary (e.g. long-running suite that's not upgraded yet, and a new suite written for new cylc) and every suite job invokes the right cylc version thanks to $CYLC_VERSION in the job environment, with cylc versions installed in (e.g.) in /opt/cylc/[VERSION].

**Comment by matthewrmshin** [comment]
Yes. The variable is used in remote commands such as when submitting jobs on remote hosts. The variable allows the correct version of Cylc to be chosen with login profiles, e.g. by loading the correct module or Python environment. If not Cylc version, we'll need a similar mechanism for a remote job host to recognise that it needs to load a matching Python environment before doing anything.

**Comment by kinow** [comment]
Hummmm, so looks like virtualenv/conda/etc are not a drop-in replacement for Cylc version :worried:

**Comment by hjoliver** [comment]
I'm absorbing this into #3150
