### ISSUE TITLE
Avoid creating empty suite directories when running suites that do not exist

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3097]
Hi,

I executed `cylc --debug --verbose --no-detach five`, without registering the suite `five`. And I was expecting `cylc` to fail and nothing to be touched on my file system. However, looks like the `~/cylc-run/five` (or wherever is cylc run/work directories specified) was still created, but empty.

This is a bit misleading. I noticed this happened after I moved my cylc run/work directories to `/tmp`, ran my suite `five`, minimized the terminal. Then from another terminal went to check the logs, and the directory was empty.

Took me a few seconds to understand why that happened. The issue happens with `7.8.x` line too, and that's because before checking if the suite exists, we try to create auth files (`create_auth_files` call). I think this logic should be changed, and instead the auth files should be created only if the suite exists.

https://github.com/cylc/cylc/blob/d2e649bfcdaf655a0ae56bf128f213a57e4e612c/lib/cylc/scheduler_cli.py#L94-L104

Cheers
Bruno

**Comment by kinow** [comment]
Not sure if we need to worry about 7.8.x for this small one.

**Comment by hjoliver** [comment]
I can't look at the code right now, but this might be complicated slightly by auto-registration of a suite in $PWD by `cylc run`.  (Should still be able to check if there is a suite in $PWD though, before creating auth files).

**Comment by hjoliver** [comment]
> Not sure if we need to worry about 7.8.x for this small one. Probably?

Yes, better do both branches.
