### ISSUE TITLE
Test battery and configured run/work locations.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3106]
Some functional tests may fail if non-standard run or work locations are configured in `global-tests.rc`, as described here: https://github.com/cylc/cylc/pull/3104#issue-269117613

Not urgent (such non-standard locations are unlikely to be needed for running the test battery).

**Comment by oliver-sanders** [comment]
@hjoliver I think this can be closed by #3808 as we are now free to configure test platforms in full.
