### ISSUE TITLE
Pre-pend Jinja2 filters (etc.) path

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3109]
Currently in `lib/parsec/Jinja2Support.py` we pre-pend the custom filter path to the Python module search path.  This will cause problems if another module with the same name is already in the search path.  https://groups.google.com/forum/#!topic/cylc/k2rnaMBFYuw

**Comment by liu-jianyu** [comment]
I think currently it appends the custom filter path at the end of Python module search path instead pre-pending at the front of search path.  If another module with the same name is already in the search path,  Cylc will pick up module from an unexpected location other than custom filter path. 

Here are the fix 

orig_sys_path = sys.path
sys.path = [os.path.abspath(fdir)] + orig_sys_path

**Comment by hjoliver** [comment]
(GitHub automatic closing of issues via PR keywords ("close", "fix" etc., seems to have stopped working...)

**Comment by kinow** [comment]
@hjoliver I wonder if that's because there are two PR's open with Close referencing this issue? Kind like Cylc task prerequisites? 🤣

**Comment by hjoliver** [comment]
Yeah, let's see when 3112 is merged...
