### ISSUE TITLE
cylc review: Links broken when suites names contain URL encoded names

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3121]
Register two suites, `cylc1`, and `ylc1` (the first 'c' was url-encoded):

```bash
$ cylc register cylc1 .
$ cylc register "%63ylc1" .
```

Now execute `cylc1`:

```bash
$ cylc run cylc1
```

Now you have the logs, files, etc, under `~/cylc-run/cylc1` for the cylc1 suite. And the other directory should be empty:

```bash
$ ls ~/cylc-run/%63ylc1/
$ ls ~/cylc-run/cylc1
cylc-suite.db  log  share  suite.rc.processed  work
```

Now access Cylc Review, and you should be able to see both for your local user:

![image](https://user-images.githubusercontent.com/304786/56549542-1a972d80-65d7-11e9-8b3e-99eea36072c9.png)

Notice that the last active time is correctly displayed, as only `cylc1` was active before. Now click on the link for `%63ylc1`, **and you should be redirected to the output of `cylc1`**.

![image](https://user-images.githubusercontent.com/304786/56549591-40bccd80-65d7-11e9-95d2-8cef0fd0ced3.png)

It does work if you url-encode the `%` character (which is `%25`)... i.e. instead of `%63ylc1`, you use `%2563ylc1`.

**Comment by hjoliver** [comment]
Closed by #3125 (didn't auto-close?)
