### ISSUE TITLE
Fix PYPI long description

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3142]
It looks like the long description is not being correctly displayed (found while working on cylc-xtriggers, so not fixing right now).

Good first issue for anyone interested in experimenting with setuptools, pip, etc.

Link: https://pypi.org/project/cylc/

Current screenshot:

![Screen Shot 2019-05-01 at 18 14 25-fullpage](https://user-images.githubusercontent.com/304786/57007471-fc67a800-6c3c-11e9-942d-2d58d516f176.png)

**Comment by matthewrmshin** [comment]
The one under https://pypi.org/project/cylc-flow/ is correct. Fixed by #3131. Once we have tagged 8.0a1, we can blast away the one under https://pypi.org/project/cylc/.

**Comment by kinow** [comment]
Got it, thanks @matthewrmshin !
