### ISSUE TITLE
cylc review: pager/pagination broken for suite %63cylc

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3145]
I am using a suite called %63ylc for tests, using the latest examples from #3117 with an extensive list of special task names.

I've augmented it with cyl%63 which passes validation and also works in runtime (this task name is not relevant to this issue I think).

After running the suite, everything appears to OK fine in Cylc Review. However, as @sadielbartholomew prepared such an amazing and extensive list, this was my first test with a paginated list of tasks.

Clicking on the `>>` next link, it leads to a 404 page. Looks like the suite name is being encoded twice.

**Comment by hjoliver** [comment]
Closed by #3146. (Not sure why it didn't auto-close this).
