### ISSUE TITLE
Could we use functools.lru_cache for xtrigger functions?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3149]
Something I noticed while working on the [pull request for `cylc-xtriggers`](https://github.com/cylc/cylc-xtriggers/pull/2), I think the dictionary `_XTRIG_FUNC` perhaps could be replaced by [`functools.lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache).

It would simplify a bit the code I think, but also remove the chance of that dictionary ever growing to a very large size (which is hardly possible I think, as it would require a very long running suite, that perhaps dynamically created xtriggers over that time, and even then I think they would eventually be garbage collected... but anywhoo).

Low priority I believe, just in case this chance is worth a try :+1:

**Comment by hjoliver** [comment]
Not sure I understand!  I think `_XTRIG_FUNCS` just stores functions, not function results, whereas `functools.lru_cache` is for memoizing function call results (so maybe it could replace our home-built memoize decorator in `lib/cylc/cycling/iso8601.py`).

**Comment by hjoliver** [comment]
Also, external trigger functions are called repeatedly with the same args until they return True (which signifies that external conditions have changed appropriately) and so they aren't memoizable (i.e. same args don't necessarily produce the same result).

**Comment by kinow** [comment]
I may be mistaken. I thought [`_XTRIG_FUNCS`](https://github.com/cylc/cylc-flow/blob/master/lib/cylc/subprocpool.py#L35) was acting as a cache for the loaded modules. Using `lru_cache`, wouldn't we avoid the need of `_XTRIG_FUNCS` and also be able to define its maximum size?

It would not store the external trigger function's result... it would store the result of `subprocpool.get_func`... I think. Though my mind is now more on Cylc packaging and cylc-xtriggers & jinja2filters & CYLC_DIR, so I might be a little confused here.

>so maybe it could replace our home-built memoize decorator in lib/cylc/cycling/iso8601.py

+1 I believe we have an issue for that somewhere... or at least it was discussed in the past, before Py3 migration I think...

**Comment by hjoliver** [comment]
The way I think of it, `_XTRIG_FUNCS` is just a dictionary that associates a function name (a string parsed from the suite.rc file) with an actual callable function, which we have to attempt to import from a module of the same name to see if the referenced function actually exists.

It is a cache in the sense that we don't attempt the import again if the name already has an associated callable.  So I think was over-interpreting what you were saying above, sorry ... but still: a) xtrigger functions are not created dynamically (the cache is keyed only by function name only, not args such as cycle point that change as the suite runs) so I can't imagine this cache ever getting very big; and b) `lru_cache` documentation does seem to be about function call memoization (i.e. return cached results if the same argument values are passed again).

**Comment by hjoliver** [comment]
@kinow - I just re-read our discussion above.  I guess we do agree on what `lru_cache` is for, but you were talking about storing the result of *the function call that locates the xtrigger module and function* (not the result of the xtrigger function call as I had assumed you meant).  If so, then this issue is not invalid as such, but I still think no point in using `lru_cache` because I can't imagine there will ever be a large number of different xtrigger functions used in a single suite (so the existing dict will never be very big).  If you agree we can close this ...

**Comment by kinow** [comment]
>I can't imagine there will ever be a large number of different xtrigger functions used in a single suite (so the existing dict will never be very big). If you agree we can close this ...

+1 I suggested a contrived case where it would be possible, but very unlikely. Let's close it and worry about it if we ever modify how the xtriggers functions are loaded 👍 

Thanks!
