### ISSUE TITLE
Cylc and virtual environments

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3150]
We need to be able to install Cylc into virtual environments.  In the future we may even need to be able to do system-level installs into virtual environments (i.e. each Cylc release into its own venv) ... to avoid any risk of different Cylc versions with incompatible dependencies.

So for cylc-8, possibly in a venv (check off as solved in comments below):

- [x] how can we ensure that jobs execute CLI from the right venv? (same or remote host)
  - *no need to "activate" environments, just need the right bin path*
  - done https://github.com/cylc/cylc-flow/pull/3162#issuecomment-493277605

- [x] access to multiple cylc releases (potentically in their own venvs)
  - *the currently central wrapper and `$CYLC_VERSION` should still work*

- [x] where should "site" global config files go?
  - a generic central location such as `/etc/cylc-flow/global.rc`? (nope/sort-of)
    - but version-specialized?  `etc/cylc-flow/8.0.0/global.rc`? (nope/sort-of)
  - inside every cylc-flow installation (may be in a venv)? (nope)
  - https://github.com/cylc/cylc-flow/issues/3150#issuecomment-493029217:
    `etc/cylc/<pkg-name>/<version>/<conf-file>`
- [x] how can users access "package resources" such as editor syntax files and bash command completion?
  - *as of #3162 : retrieve with `cylc get-pkg-resources` and install maually*
  - but see https://github.com/cylc/cylc-flow/pull/3162/files#r283254198

See also: #3081 #3080 #3133 #3134 

UPDATE: pretty much done; will close the issue once global config file locations are implemented.

**Comment by hjoliver** [comment]
For a single-install use case (one user on h/is/er own VM) and maybe no central cylc wrapper - it seems to me that the user should not have to explicitly define job scripting to make every job load the venv that its host suite is running in.

Options?
- require a central wrapper, and have it automatically detect if the cylc executable that it wants to invoke is in a venv or not; and if it is, activate the venv
- or just have `bin/cylc` (which is a bash script) do that?
- or have the suite server know if it is running in a venv, and export `CYLC_VIRTUAL_ENV` to be detected by the cylc wrapper or bin script?
- (or expect users to explicitly activate the venv in every job?)

**Comment by hjoliver** [comment]
For multiple Cylc releases installed on the system in their own venvs (or same under a user account):
In this case we really need it to work without the user having to even know that the cylc they are running is in a virtual environment.  i.e. the executable (as far as the user is concerned) should really be the actually executable wrapped up in its own virtual environment (and the server program needs its jobs to invoke the same wrapped cylc).

Options:
- same as above?

**Comment by oliver-sanders** [comment]
With the execption of `cylc get-pkg-resources` I think this will all hold true for Conda as well as virtualenv.

> where should "site" global config files go?

a generic central location: `etc/cylc/flow/8.0.0/global.rc`

**Comment by kinow** [comment]
`etc/cylc/flow/8.0.0/global.rc` or `/etc/cylc/flow/8.0.0/global.rc` @oliver-sanders ? (just checking if the first would be a package in `cylc-flow`?)

**Comment by oliver-sanders** [comment]
Whoops updated. `/etc`.

**Comment by kinow** [comment]
>A generic central location: /etc/cylc/flow/8.0.0/global.rc

Sounds good to me too :+1:

**Comment by oliver-sanders** [comment]
We may well amass a few configurations here, because Cylc components don't all have the same release cycle I imagine we may need something along the lines of:

* `/etc/cylc/flow/8.0.0/global.rc`
* `/etc/cylc/flow/8.1.0/global.rc`
* `/etc/cylc/ui-server/1.0.0/global.rc`
* `/etc/cylc/ui-server/1.0.0/proxy.conf`
* ...

**Comment by hjoliver** [comment]
I like.

**Comment by hjoliver** [comment]
In #3162 I've implemented a variation on @oliver-sanders suggestion:

- `/etc/cylc/flow/8.0a0/flow.rc`

(This anticipates planned unification of `suite.rc` and `global.rc`; name not final as this might require some discussion)

**Comment by oliver-sanders** [comment]
> might require some discussion

As flow is the name of a cylc module it doesn't quite make sense e.g:

* `/etc/cylc/flow/8.0a0/flow.rc`
* `/etc/cylc/ui-server/1.0/flow.rc`?
* `/etc/cylc/ui-server/1.0/ui-server.rc`?

Suggestions:

* `cylc.rc`
* `conf.rc`
* `config.rc`
* `settings.rc`
