### ISSUE TITLE
Separation of library and application?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3154]
[Python packaging documentation](https://packaging.python.org/overview/#packaging-python-applications) recommends that `pip`/`setup.py` based installation be used for installing re-usable library code, and small developer tools associated with libraries - not full-blown Python applications.  Otherwise all the additional "package data" that comes with applications (user documentation, config files, etc.) has to be installed (via pip) into the Python library path, which is not a natural place for it. (Plus other disadvantages - see the aforementioned documentation).

Ideally we should split this repository into a pure library package, and a separate application package that just imports the library. This would also allow other applications to use the library without getting all the additional baggage of the original application; and it might make use of other more application-appropriate packaging methods easier, for the application. 

We can't make this split cleanly yet, however, because the current library depends to some extent on the application scripts (esp. job management related commands). So as a prerequisite we need to:
- finish moving all appropriate logic from the command scripts into the library
- figure out "how to separate out the job management sub-system, including the task message interface and handlers, as well as the job script generation logic" (quoting @matthewrmshin)

**Comment by hjoliver** [comment]
> Other logical components may be the cycling schemes, the event handlers, the database dumper and loader. We can, in theory, also separate the central workflow management logic from the network API. Configuration parser and validation service as well.

**Comment by hjoliver** [comment]
If we are in danger of getting too many repositories, @kinow commented (on Riot):
> Maybe we could keep [them] separately logically, but under the same project, with the idea that we will split it if we have other cylc/??? projects, or external projects that need [them]?

**Comment by hjoliver** [comment]
Related advice on virtual environments and application packaging, from the Python packaging documentation:

> Virtualenvs have been an indispensible tool for multiple generations of Python developer, but are slowly fading from view, as they are being wrapped by higher-level tools.

and:

> For production deployments, do not rely on running pip install from the Internet into a virtualenv, as one might do in a development environment. The overview above is full of much better solutions.

**Comment by jarich** [comment]
Related to this, and perhaps also relevant to #1962, it would be really great if - once the appropriate functionality is moved out of the command scripts and into the library - cylc-flow functionality could be accessed through python without subprocess.

For example if we have a graph:

```
graph = "foo"
```

which exclusively calls a python script:

```
[[runtime]]
    [[[foo]]]
        script=foo.py
```

then it would be so much nicer if foo.py could access cylc functionality such as `cylc__job_abort` or equivalent without having to try to get into a cylc-aware shell environment to achieve the same.

```
#!/usr/bin/env python
from cylc.runtime import job_abort

...
if happy == 0:
    job_abort('Not the path to happiness')
```

in the same way that we could have:

```
#!/bin/bash

...
if [happy -eq 0]; then
   cylc__ job_abort 'Not the path to happiness'
```

**Comment by hjoliver** [comment]
@jarich - the initial focus of a stable API to Cylc internals will be workflow configuration (instead of the current config file with Jinja2 code) but we will probably go beyond that. Your particular example, however, `cylc__job_abort`, is a shell function in order to abort the main job shell rather than a subshell.  Not sure that can be done from within a Python script executing in a job subshell (?) unless the Python script **is** the job script.  Mind you, we'll probably support Python job scripts as option eventually (@oliver-sanders reminded me of some good reasons yesterday).

**Comment by hjoliver** [comment]
> `cylc__job_abort`, is a shell function in order to abort the main job shell rather than a subshell.

Reminding myself of the reason for that: 
https://github.com/cylc/cylc-flow/pull/2298#issuecomment-303627855

**Comment by oliver-sanders** [comment]
> Ideally we should split this repository into a pure library package, and a separate application package

As it stands (2023) Cylc is an application with very little library code, we use generic libraries for the generic bits, the Cylc code is bespoke business logic and not especially reusable. The Cylc internals are not intended to be exposed to users and are not of interest to application developers so at present there really isn't any benefit to splitting the repo.

Comments above about job script and calling Cylc commands via Python are related to #3613 not this issue.

Suggest closing this.

**Comment by hjoliver** [comment]
The reason for the suggested split went beyond actual likelihood of library reuse in other contexts - it was also do with having to store other non-Python files inside what's essentially a Python library. However, much of that has been mitigated by moving stuff out to other repositories, and yes I can't see much point in this now.
