### ISSUE TITLE
non-system site config location?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3167]
For cylc-7 (and earlier) we expected site global config files to be stored in the self-contained installed application+library tree (a.k.a. CYLC_DIR)

For cylc-8, CYLC_DIR no longer exists, because cylc now gets `pip install`ed as a Python package into the standard Python library path (or venv). 

So, as of #3162, we have the following global config locations:
- `/etc/cylc/flow/VERSION/flow.rc`
- `$HOME/.cylc/flow/VERSION/flow.rc`

@matthewrmshin has raised concerns about site config files at multi-user sites where Cylc is not installed at system level (e.g. into some "role account" home directory) where the admin user does not have access to `/etc/`.  (Presumably in this case cylc would be installed into a local venv).

#### Questions:

- do we really need to worry about this? (many other systems expect either single-user install, or system level for multiple users with config files under /etc).

- if we do need to worry about this, how to do it, give that the site config file is the only obvious place to store non-hardwired parameters (and that obviously won't work for a parameter that determines the location of the file itself).
  - could we store the config location prefix (default `/etc`) as a package resource, and extend `pip install` with a command line option (e.g. `pip install --conf-dir=/home/cylc-admin/etc`) to modify the config prefix at install time?

See also #3170.

**Comment by hjoliver** [comment]
Another option:

The person who installs cylc-flow has (by definition) write access to the installed library location - whether for a system install or local virtual environment.  So, can we store the site config location (default `/etc`) as a package resource, and expect the "cylc administrator" to manually edit that file in the installed library if `/etc` can't be used?

Example: user `cylc-admin` installs cylc-flow into a virtual env in h(is/er) home directory at `/home/cylc-admin/cylc-flow/venv`, then a) edits installed package resoures to set the site config path to `/home/cylc-admin/etc/` and instructs all cylc users to put the venv  bin directory in their `$PATH`.

**Comment by kinow** [comment]
Sounds good to me. We won't be touching files within the virtual environment, and the user should have access to his own home directory.

Q: we have ~/cylc-run, now we could have ~/etc too if I understand it correctly. Besides that, I also have ~/cylc-suites where I keep my suites (that get symlinked to ~/cylc-run). Should we perhaps move everything under one directory, maybe something like ~/.config/cylc, ~/.cylc?

**Comment by hjoliver** [comment]
> Q: we have ~/cylc-run, now we could have ~/etc too ...

We also already have `~/.cylc` for user global config files etc.

I was thinking non-system site config dir would have to be entirely up to the installer/admin-user, just gave `~cylc-admin/etc` as an example.  On our HPC certain non-root expert users get access to `/opt` sub-dirs for installing (e.g.) Rose and cylc, but not `/etc`.  I would expect in future we could request/demand access to `/etc/cylc` too, but if not we might want site config under `/opt/cylc/etc` (say)... probably can't assume any sensible default outside of `/etc` though, as it could be anywhere.

On combining the various directories, IMO `cylc-run` needs to be kept exposed (not a hidden dot-directory), whereas user config directories are conventionally hidden.

We could consider putting user config files under `$HOME/cylc-run` run though.  Hadn't thought of that. On second thoughts, that may be dangerous. At the moment we can clean out cylc run directories by deleting `$HOME/cylc-run` entirely ... which I wouldn't want to nuke my important config files.

**Comment by TomekTrzeciak** [comment]
> "cylc administrator" to manually edit that file in the installed library if `/etc` can't be used?

My instinct would be against editing installed files, because you loose your edits if you reinstall for some reason (easy to do in an automated environment). In fact, I would keep user files out of installed package entirely. Why not rely on some environment variable, say, CYLC_CONFIG_PATH? This is a fairly standard practice and provides a lot of flexibility.

**Comment by hjoliver** [comment]
Excellent suggestion @TomekTrzeciak - if no one raises any objection, I suggest we go with that, defaulting to `/etc`.

**Comment by matthewrmshin** [comment]
Please hold while I'm on leave. I'd like comment on this properly when I have time to think about this when I'm back at work next week. But let's spell out the problem. I currently deploy Cylc to about 6 different platforms in and out of the MO. I have no access to modify /etc in any of these platforms. Most of these also have /etc being in a local filesystem, so you cannot easily update all of them for all the nodes in a cluster. And I'd like avoid environment variables where possible, as they can be messed up by users and difficult to carry forward to remote jobs.

**Comment by hjoliver** [comment]
Roger that @matthewrmshin - happy to hold off for your input.

Local disk `/etc` on a cluster of suite hosts is a good point.  

(Hopefully remote job cylc CLI should not need the workflow service config file, but I suppose it is conceivable).

**Comment by oliver-sanders** [comment]
Superseded by #3689.
