### ISSUE TITLE
Name of global config file?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3170]
Ref: https://github.com/cylc/cylc-flow/issues/3150#issuecomment-493898123

Ping @oliver-sanders

**Comment by hjoliver** [comment]
> As flow is the name of a cylc module it doesn't quite make sense e.g:

I had imagined that each distinct component will have its own config file now.   In which case, `flow.rc` seemed appropriate for cylc-flow global config and (future) workflow definition file (formerly known as `suite.rc`).

We could combine them all into one, but that might create problems or confusion if not all components are used?

**Comment by kinow** [comment]
Maybe keep it as `global.rc`? Residing within a directory of cylc-flow like `~/etc/cylc/flow/8.0.0/global.rc`?

**Comment by matthewrmshin** [comment]
Global should be `flow. rc` whereas suite should be `cylc-flow.rc`. Reason being that global always lives under a directory in the cylc/flow namespace whereas a suite file can live anywhere.

**Comment by hjoliver** [comment]
> Maybe keep it as global.rc?

We are planning (I think) to unify `global.rc` and `suite.rc` - because both of these are concerned with configuring the workflow engine (current `global.rc` includes a few unnecessary extras)... and `global.rc` essentially gives default values that apply to all suites.

So, once unified, `global.rc` doesn't make sense as a workflow definition config file.

**Comment by hjoliver** [comment]
>Reason being that global always lives under a directory in the cylc/flow namespace whereas a suite file can live anywhere.

Not sure I understand this - what if global config is under `/etc`.  We weren't considering (so far) actually keeping the config file in the library, just a package resource that specifies the prefix for the config file location.

**Comment by hjoliver** [comment]
So I think either `flow.rc` or `cylc-flow.rc` would be fine for both global and specific workflow config.  It is just the location that determines its use.

**Comment by matthewrmshin** [comment]
Another suggestion is to call global `config` like Git.

**Comment by hjoliver** [comment]
I kind of like have the filename make the purpose obvious (`config` is maximally generic) especially if the user gets to choose the location.  (We can't guarantee that it will end up under `/etc/cylc/cylc-flow/...`)

**Comment by oliver-sanders** [comment]
> **I kind of like have the filename make the purpose obvious (config is maximally generic)**

:+1: 

If we do go for a configuration tree structure something like:

* `<configuration_root_dir>`
  * `\cylc`
    * `\flow`
       * `\8.0.0`
           * `flow.rc`
       * `\8.0.1`
           * `flow.rc`
    * `\ui-server`
       * `\1.0.0`
           * `ui-server.rc`
    * `/hub`
       * `\1.0.0`
            * `hub.rc`

It would be quite annoying that the configuration files are called something different in each case. Something generic like `config.rc` which makes it's purpose clear and permits consistency would be preferable.

**Comment by hjoliver** [comment]
@oliver-sanders your :+1: seems inconsistent with the subsequent verbiage :grin:  (maybe you thought I was arguing **for** a generic filename?)

**Comment by sadielbartholomew** [comment]
> I kind of like have the filename make the purpose obvious (config is maximally generic)

I do (also?) agree a specific name is better, & like the idea of naming equivalent config after the relevant repo e.g. ``flow``, ``ui-server`` & ``hub`` (``.rc``), etc.

**Comment by oliver-sanders** [comment]
Closing as superseded by https://github.com/cylc/cylc-flow/issues/3689
