### ISSUE TITLE
Cannot suicide root

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3206]
This suite should run 3 cycles concurrently (by default max active cycle points).  In each cycle point, foo should fail, and all tasks in the cycle should suicide out:
```
[scheduling]
   cycling mode = integer
   initial cycle point = 1
   spawn to max active cycle points = True
   [[dependencies]]
      [[[P1]]]
          graph = """
              foo => bar & baz
              foo:fail => !root
                  """
[runtime]
   [[root]]
      script = sleep 5

   [[foo]]
      script = sleep 5; exit 1
```

BUT what happens is foo fails and suicides out (expected) leaving the suite stalled with tasks bar and baz still there waiting (not expected).

HOWEVER, if I leave the graph exactly the same but add this intermediate family between root and the three tasks, it runs correctly!!!
```
   [[ALL]]
   [[foo, bar, baz]]
       inherit = ALL
```

**Comment by hjoliver** [comment]
BTW this is 7.8.x - I have not test on master (I'm using the old GUI to observe the results) ... I should have used the new bug report template :grimacing: )

**Comment by matthewrmshin** [comment]
Bug repeated on master.

**Comment by hjoliver** [comment]
Another example:
```
[cylc]
   cycle point format = %Y
[scheduling]
   initial cycle point = 2020
   spawn to max active cycle points = True
   [[dependencies]]
      [[[P1Y]]]
          graph = """
          a => b => c => d => e => f
          a => !a_x
          a:fail => a_x => !ALL
                  """
[runtime]
   [[root]]
      script = sleep $((5 + RANDOM %10))
   [[ALL]]
   [[a, b, c, d, e, f]]
      inherit = ALL
   [[a]]
      script = """
sleep 5
if [[ $CYLC_TASK_CYCLE_POINT == 2021 ]]; then
   exit 1
fi
sleep 5
"""
```

This works as expected: in the second cycle a fails, and a through f suicide; and in all other cycles a succeeds and a_x suicides.

BUT if I change this:
```
   [[a, b, c, d, e, f]]
      inherit = ALL
```
to this:
```
   [[a, b, c, d, e, f, a_x]]
      inherit = ALL
```
leaving all else the same, a_x no longer suicides in the normal cycles (or in the second cycle).

Also, I delete family ALL under runtime, and do this instead ```a:fail => a_x => !root```, then a_x gets removed as expected in the normal cycles, but only a gets removed in the second cycle.

AND like the original example above, suiciding root works correctly if I simply restore the ALL family under runtime (but do not use it at all in the graph!!).

**Comment by hjoliver** [comment]
So we have sufficient evidence that something bizarre is going on that's unfortunately not covered by our tests.  Next step is to look at the code.  (But not now, it's 1:20 a.m. here :grimacing: )

**Comment by matthewrmshin** [comment]
You don't even need the intermediate ALL family, you can do just this.

```
   [[foo, bar, baz]]
       inherit = root
```

For some reason, an explicit inheritance of `root` changes the behaviour of the graph parser.

**Comment by hjoliver** [comment]
Huh, interesting.

**Comment by matthewrmshin** [comment]
In the case without explicit inheritance, this dict does not get populated fully before we parse the graph.

https://github.com/cylc/cylc-flow/blob/d774fe0c07fe7b448065f9d12e0bf9a204ce9c84/cylc/flow/config.py#L2106-L2110

**Comment by matthewrmshin** [comment]
Note the comment here:

https://github.com/cylc/cylc-flow/blob/60031ddbaf64cd273dd4e4768c87dbf2eaca86cb/cylc/flow/config.py#L2103-L2110

So, I guess `root` cannot currently be used safely in the graph?

**Comment by oliver-sanders** [comment]
@hjoliver happy to close this post-SoD?

**Comment by hjoliver** [comment]
Yes a quick test shows the cases above run correctly on master.
