### ISSUE TITLE
Bug in mutation if there is no owner

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3212]
**Describe the bug**

@dwsutherland syncing code and looking at IDE issues, looks like there is one branch of the code for mutations that is missing an `append` function? Looks like if there is a workflow with no owner associated it would result in a runtime error.

**Release version(s) and/or repository branch(es) affected?**

`master` on cylc-flow

**Steps to reproduce the bug**

Sorry, haven't actually tried, as I haven't learned how to use mutations yet. And furthermore, it would have to be one that owner is not present. I'm hoping this information is enough for @dwsutherland to spot what's missing :crossed_fingers: 

**Expected behavior**
An imported function is used.

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/61102839-b5f7ba80-a4c3-11e9-95d3-915eb5984969.png)

**Additional context**
NA

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by dwsutherland** [comment]
Added it as a fix to #3202  (as it's related)
