### ISSUE TITLE
graph: optional branching

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc-flow#3226]
Suicide triggers are sometimes very clunky - maybe we could have syntax to denote a part of the graphing that _only_ runs under certain conditions (e.g. a task succeeds) and otherwise removes itself (or is never inserted).

We use round brackets for optional source inclusion in Rose, and they can't be used on the RHS of a graph in cylc, so maybe we can use them here?

``` ini
[[[P1D]]]
    graph = """
        foo => bar => baz
        bar[-P1D] => foo
        baz => (qux => wibble => wobble)
    """
```

This could be presented nicely in the graph view with a subgraph.

**Comment by matthewrmshin** [comment]
Issue back to cylc/cylc-flow!

**Comment by kinow** [comment]
Ops, sorry. Thanks for transferring it back :)
