### ISSUE TITLE
Run unit tests against master

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#3235]
In PR #3222 the following suggestion:

>>    Other alternative is to run against the pinned version then have another travis build just run the unittests against isodatetime:master.

>I swear I just came back here to comment exactly that.

>Exactly same idea, to build in Travis (either with each commit/PR or nightly) that runs some Shell-Fu that magically replaces the versions prior to running the tests.

Create a second run of the unit tests using the master version of metomi.isodatetime rather than the last release.

**Comment by oliver-sanders** [comment]
I think the approach we are leaning towards is nightly builds running on development versions. So closing this a superseded by https://github.com/cylc/cylc-admin/issues/33.
