### ISSUE TITLE
Active Node-Edge N-Distance GraphQL Query

### ISSUE THREAD

**Issue by dwsutherland** [cylc/cylc-flow#3248]
This is in reference to the desired HYBRID mode noted in the Exeter-June-2019 meeting, and as a solution could present a way of masking the Cylc 8 to 9 backend transition.

To create a query to return that active task/job-edge view:
- Define a type (or query with fields) whose fields are a node/task-proxy list and list of edges
- Define query arguments with one filtering on node atts (i.e. active states for current data provision), and another `level` or `distance` (i.e. geodesic distance, because level implies a tree?).
- Create a resolver to collect the selected  `D0` (`distance`=0) nodes, then loop on all edges to collect edges and nodes (`D1`) who are the source or target of `D0`... Repeat for `D1..N`

If we think that resolver would be too computationally expensive, then for every node we could store edges that connect to it, as either source or target, in a list field of that node.
(by store I mean the edge IDs of course)

**Comment by oliver-sanders** [comment]
Something which is kinda tricky with this approach is dealing with graph isolates e.g:

```ini
[scheduling]
    cycling mode = integer
    initial cycle point = 1
    [[dependencies]]
        [[[P1]]]
            graph = """
                foo[-P1] => foo => bar => baz
                pub  # graph isolate
            """
```

**Comment by dwsutherland** [comment]
> Just to flag something which is kinda tricky with this approach is dealing with graph isolates e.g:
> 
> ```ini
> [scheduling]
>     cycling mode = integer
>     initial cycle point = 1
>     [[dependencies]]
>         [[[P1]]]
>             graph = """
>                 foo[-P1] => foo => bar => baz
>                 pub  # graph isolate
>             """
> ```

Yes, could be tricky.  Although, if the isolates are active (`D0`) then they will show up.
Otherwise, they would be identified via the edges, as sources with no target (I think).

**Comment by hjoliver** [comment]
Note this mode, if we can do it, hides the back-end "task pool" from users (which is highly desirable). Some of the the nodes displayed will be ghost nodes (no task proxy in the pool) so this requires automatic insertion and should solve/close #2903 and #2143

**Comment by hjoliver** [comment]
I believe we are aiming for Cylc 8 here @matthewrmshin!
