### ISSUE TITLE
Allow proper escaping in xtrigger format statements

### ISSUE THREAD

**Issue by trwhitcomb** [cylc/cylc-flow#3256]
I had a format string that I wanted to pass through the xtrigger formatting, but the regular expression used to match format strings and check their validity did not honor the Python escape sequence, i.e.
"%%(asdf)s" after running through string format is "%(asdf)s", but the current xtrigger format check in the suite validation complains that "asdf" isn't one of the approved variables for string substitution.

Use case here is to allow for parameterized filenames in the xtrigger, but I can't directly use cycle points as the files have 10-digit YYYYMMDDHH in the name so I resorted to passing in a format-string filename and a date-time-group format.

**Comment by hjoliver** [comment]
But reproduced.
