### ISSUE TITLE
ResourceWarnings when running with a development version of Python

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3264]
**Describe the bug**

Python raises several [`ResourceWarning`s](https://docs.python.org/3/library/exceptions.html#ResourceWarning) when running a simple suite in Cylc 8 (not tested on Cylc 7).

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

1. Clone cpython from github.com/python/cpython
2. Configure with pydebug flag (`./configure --with-pydebug`) then `make`
3. Create a venv with the newly created `python` command
4. Update `pip`
5. Install `metomi-isodatetime` (`pip` won't be able to install, I guess because the version is `3.8.0b3`, which appears to fail `<=3.8` I think?)
6. Install `pyzmq` from `v18.0.2` tag (`pip` fails due https://github.com/zeromq/pyzmq/issues/1315)
7. Install `cylc-flow` with `pip install -e .`
8. Run `cylc run --no-detach five` (or some other simple local suite)

**Expected behavior**

Normal output of the suite.

**Screenshots**

**Additional context**

The `ResourceWarning` errors will include a note that you should enable [`tracemalloc`](https://docs.python.org/3/library/tracemalloc.html) to get allocation traceback. You can enable it with `export PYTHONTRACEMALLOC=1`, or even `export PYTHONTRACEMALLOC=10` to get 10 frames from the stack instead of just 1 in the traceback.

I found three warnings, but I think the number can be different if you execute suites that go through different parts of the code (e.g. `BatchSysManager` would raise one too I think, when it executes the remote command with `Popen`).

1. `/home/user1/Development/python/workspace/cylc-flow/cylc/flow/job_file.py:87: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>
  proc = Popen(`

Code: https://github.com/cylc/cylc-flow/blob/39edc6fa21f366e3094e2e3063a76a3fdbba9cc3/cylc/flow/job_file.py#L87

2. `/home/user1/Development/python/workspace/cylc-flow/cylc/flow/task_job_mgr.py:790: ResourceWarning: unclosed file <_io.BufferedReader name=16>
  self.job_file_writer.write(local_job_file_path, job_conf,`

Code: https://github.com/cylc/cylc-flow/blob/39edc6fa21f366e3094e2e3063a76a3fdbba9cc3/cylc/flow/task_job_mgr.py#L790

3. `/home/user1/Development/python/workspace/cylc-flow/cylc/flow/suite_srv_files_mgr.py:573: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/user1/cylc-run/five/.service/contact' mode='r' encoding='UTF-8'>
  return open(os.path.join(path, item)).read()`

Code: https://github.com/cylc/cylc-flow/blob/39edc6fa21f366e3094e2e3063a76a3fdbba9cc3/cylc/flow/suite_srv_files_mgr.py#L573

4. `/home/user1/Development/python/workspace/cylc-flow/cylc/flow/subprocpool.py:210: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>
  proc = self._run_command_init(ctx, callback, callback_args)`

Code: https://github.com/cylc/cylc-flow/blob/39edc6fa21f366e3094e2e3063a76a3fdbba9cc3/cylc/flow/subprocpool.py#L210

The issue is mainly with file handlers open to `os.devnull` being left open. While it is harmless, as Python handles (or should in theory) the removal of dangling files left open... though it's hard for me to visualize where it is happening as we are running some of the processes as daemons or forking new processes.

Prepared an example pull request showing a possible way to solve these issues. One was easy (the third in the list), as just needed to use a context manager (`with ...`). The other cases with `os.devnull`, instead of always opening a new file, I used Python 3.3+ `subprocess.DEVNULL`: https://docs.python.org/3/library/subprocess.html#subprocess.DEVNULL

What is more interesting about this approach, is that not only the warnings are gone, but looks like Python reuses the same file handler for all the calls (see https://github.com/python/cpython/blob/2491134029b195d3159a489e1803ee22a7839b41/Lib/subprocess.py#L941).

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
I collected these logs yesterday while checking if Cylc 8 would work with Python 3.8: https://gist.github.com/kinow/0a282fdca776397ba2b62874f68743a7.

On the bright side, it does work with no issues - at least for my simple suite :+1:

**Comment by hjoliver** [comment]
Interesting!
