### ISSUE TITLE
add is_held field into the network schema

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3278]
**Describe exactly what you would like to see in an upcoming release**
Follow on to #3230

Make the new `is_held` task state attribute available in the workflow schemas:

* GraphQL
* Protobuff

**Pull requests welcome!**

**Comment by dwsutherland** [comment]
Will `is_held` remain in the state_totals?, i.e.:
```
message PbStateTotals {
    int32 runahead = 1;
    int32 waiting = 2;
    int32 held = 3;
    int32 queued = 4;
    int32 expired = 5;
    int32 ready = 6;
    int32 submit_failed = 7;
    int32 submit_retrying = 8;
    int32 submitted = 9;
    int32 retrying = 10;
    int32 running = 11;
    int32 failed = 12;
    int32 succeeded = 13;
}
```
I think it should have it's own total... (as a task will have a state and be held)

So the change will require:
- `ws_messages.proto` - Remove `held` from `state_totals`, creation of held_total field in `workflow` and `is_held` boolean field in task_proxy and family_proxy.
- `ws_data_mgr.py` - Field calculation and updates to these object fields.
- `network/schema.py` - Respective fields created, and query argument addition for `is_held` (`isHeld`)
- `network/resolvers.py` - Adjust for new filter arg.

This change should go in after #3202 if it doesn't break it.
Both this respective PR and #3202 will require and accompanying PR to the UI Server (to fix the resolvers)..

**Comment by hjoliver** [comment]
(Agreed, presumably will not remain in the state totals).

**Comment by oliver-sanders** [comment]
Should be removed from state totals I think.

**Comment by matthewrmshin** [comment]
This used to provide a quick way to query the number of *held* tasks? I guess it is easy enough to filter the number of tasks with the `is_held` flag?

**Comment by dwsutherland** [comment]
> This used to provide a quick way to query the number of _held_ tasks? I guess it is easy enough to filter the number of tasks with the `is_held` flag?

I think we may still need an isHeldTotal in the workflow summary I suppose.. As it  would be useful on the workflows `gscan` page, and that data/query may have a different privilege/authorisation level.

**Comment by hjoliver** [comment]
Yes I think we do need that. Maybe for the Dashboard page as well (the design currently only has number of held workflows, under Workflows.  But we might want a Tasks column too, to give a collective summary of all the tasks being managed by the user.
