### ISSUE TITLE
Expanding 1 suite in `cylc gscan` causes all suites to expand.

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc-flow#3281]
**Describe the bug**
When I expand the view of one suite in the `cylc gscan` GUI, after a few seconds all running suites are also expanded without any further mouse input.

**Release version(s) and/or repository branch(es) affected?**
Cylc 7.8.3 but have noticed similar behaviour on several older versions

**Steps to reproduce the bug**
See above.

**Expected behavior**
Clicking one one suite to expand it should do just that. There is a 'expand all' button for expanding all suites.

**Screenshots**

I can't seem to get them the right way up 🤣 ...

![1](https://user-images.githubusercontent.com/12940715/62750693-23900a00-bab5-11e9-9fff-085c0edfd5ea.JPG)
![2](https://user-images.githubusercontent.com/12940715/62750694-2428a080-bab5-11e9-908c-dca13e1c83dc.JPG)

**Additional context**
Running through MobaXterm on Windows 10.

**Pull requests welcome!**
I wouldn't know where to start I'm afraid...

**Comment by hjoliver** [comment]
@jonnyhtw - I think this is a long-standing known issue that we keep forgetting about: #2576   ... however, we marked that as superseded by #2956 ... then closed that one as obsolete/wont-fix by the upcoming new UI - which probably wasn't the right thing to do given that Cylc 8 won't be ready quite some time yet.  @cylc/core - worth a look to see if this is an easy fix for cylc-7?

**Comment by jonnyhtw** [comment]
Thanks HIlary

This certainly isn't anywhere near a priority as far as I am concerned and there is clearly way more pressing things to do. Happy to close this issue in light of the upcoming change to the UI.

Cheers

Jonny

**Comment by sadielbartholomew** [comment]
> worth a look to see if this is an easy fix for cylc-7?

I'm happy to pick up on this, though it may be towards the end of the week earliest I can put in a fix (given priorities). That should be well in time for 7.8.4, though.

If it takes more than a few hours I will have to leave it, but it shouldn't do (on the face of it, at least)!

**Comment by jonnyhtw** [comment]
Thanks Sadie!

This certainly isn't at all urgent so please don't spend too much time on it, if any! 😃 

Ngā mihi

Jonny

**Comment by kinow** [comment]
Closing manually (only pull requests against `master` close automatically). Merged, to be included in the next 7.8.x release @jonnyhtw 👍

**Comment by jonnyhtw** [comment]
Thanks @kinow
