### ISSUE TITLE
"cylc insert --help": no cycle point globbing

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3284]
**Describe the bug**

Cycle point ~~and task name~~ globs do not (and probably should not) work with `cylc insert`, but command help suggests they do.

REF: https://cylc.discourse.group/t/square-bracket-wildcards-in-cylc-insert-cycle-points/123/2

**Release version(s) and/or repository branch(es) affected?**

All versions to date.

**Steps to reproduce the bug**

`cylc insert --help`

**Expected behavior**

Don't mention globbing, and/or explain why `cylc insert` is different to other task-targeting commands in this respect.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by matthewrmshin** [comment]
(I thought task names should glob correctly with task definition?)

**Comment by dwsutherland** [comment]
They do work with globing  (>.>) ... When I was working with the API, I found it strange that the ZeroMQ endpoint treated it differently (as if it couldn't glob), however it worked with globs.. So I treated it the same as any other task action in the GraphQL setup:
https://github.com/cylc/cylc-flow/blob/bb5a1270e5a695e4a69c4f0d476d1c00d17ae81f/cylc/flow/network/schema.py#L913

**Comment by dwsutherland** [comment]
> (I thought task names should glob correctly with task definition?)

Yeah, maybe it just works on task name not point.

**Comment by hjoliver** [comment]
Sorry, yes - globbing on insert works with task name, but not cycle point.  That makes sense because a task name glob can be matched against "known stuff" - the list of all task names in the suite.

Globbing on cycle point (for insert) doesn't work - we'd have to generate all possible cycle points for matching tasks, and then match against those (possible, but not very easy, and not really in the spirit of "matching existing stuff against a pattern).

Amending description...
