### ISSUE TITLE
Held tasks should not suicide.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3293]
https://github.com/cylc/cylc-flow/issues/3282#issuecomment-521421980

**Pull requests welcome!**

**Comment by dpmatthews** [comment]
@hjoliver I'm not convinced this makes sense - I don' see why a held task should not suicide.
The main reason this got raised is no longer applicable at Cylc 8.

**Comment by hjoliver** [comment]
Agreed.
