### ISSUE TITLE
Sorting of integer cycle points in gcylc uses incorrect order

### ISSUE THREAD

**Issue by trwhitcomb** [cylc/cylc-flow#3299]
(cylc 7.8.3)

When multiple digit count cycle points are displayed (e.g. both 1-digit and 2-digit cycle points) for integer cycles, they are sorted incorrectly.

Steps to reproduce:
1. Create an single-task, integer-cycling suite with the single task externally triggered.
2. Configure a script for the externally-triggered task so that it will exit abnormally.
3. Submit a large number (e.g. if cold-starting, at least 10, but potentially more: 40 or 50) of external triggers all at once

Expected behavior:
1. Cycle points are listed in the GUI in numerical order (e.g. 1, 2, 3, 4, etc.)

Observed behavior:
1. Cycle points are listed in the GUI in lexical order (e.g. 1, 10, 11, ... 19, 2, 20, 21, 22, etc.)

**Comment by hjoliver** [comment]
Ha, oops :rofl: ... yes we should fix that!

**Comment by hjoliver** [comment]
Closed by #3526 and #3537
