### ISSUE TITLE
Prevent logging pyzmq messages to console output

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3300]
**Describe the bug**

While running a workflow with `cylc run --no-detach --verbose --debug five`, I see several messages that appear to be pyzmq / protobuf in the console.

These messages are really long, and with content that is not human readable. Furthermore, even if investigating communication issues, it is hard to use that output and try to reconstruct it to something readable or that could be used for troubleshooting.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

`cylc run --no-detach --verbose --debug $WORKFLOW` for any $WORKFLOW, and after a while you should see the messages logged.

**Expected behavior**

Only information that is useful for users/site admins for troubleshooting workflows is logged.

**Screenshots**

![Screenshot_2019-08-19_15-04-02](https://user-images.githubusercontent.com/304786/63236613-986ffa80-c292-11e9-9bae-c70851ae90c6.png)

It also uses a lot of the buffer available in my terminal, so it is hard to look at previous log messages (have already increased the buffer size).

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
Yes that is annoying!
