### ISSUE TITLE
zmq: (don't) re-implement task message retries?

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3331]
See also #2978

Simple feature removed in the initial Python3 port. For more information see:

```console
$ git grep TASK_MSG_MAX_TRIES
$ git grep 3331
```

**Comment by oliver-sanders** [comment]
Result of offline discussion with @matthewrmshin: maybe we shouldn't do this? The retry will almost always fail anyway.

**Comment by hjoliver** [comment]
Yeah I recall a discussion (with @matthewrmshin) of this somewhere else recently (but I don't recall where). I tend to agree - message retries are almost always a waste of time, so we shouldn't bother. Polling (job query) is the only effective way to catch/recover-from status messaging failures.

**Comment by hjoliver** [comment]
@oliver-sanders - can you check that I've got everything (in PR #3402)   ... your `grep 3331` instruction above doesn't make sense as *this issue* IS 3331 :grimacing:

**Comment by matthewrmshin** [comment]
Re: the conversation on removing task message retries was this comment:
https://github.com/cylc/cylc-flow/pull/3348#discussion_r324178851

**Comment by oliver-sanders** [comment]
> @oliver-sanders - can you check that I've got everything (in PR #3402) ... your grep 3331 instruction above doesn't make sense as this issue IS 3331 grimacing

I think I added a TODO in the code with "see #3331", seems to have been removed by another change.
