### ISSUE TITLE
Add more GraphQL documentation for the fields (for GraphiQL & clients)

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3340]
**Describe exactly what you would like to see in an upcoming release**

Document GraphQL returned fields (e.g. Edge attributes).

**Additional context**

In GraphiQL, it is possible to read the documentation of the returned fields. We have the documentation for some fields already, but others are missing.

From: https://github.com/cylc/cylc-flow/pull/3337#issuecomment-526976462

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Superseded by #4091
