### ISSUE TITLE
Tidy up command categories of cylc command

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3341]
**Describe the bug**

Running `cylc license` with `master`:

```
$ cylc license
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/bin/cylc-help", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-help", line 487, in <module>
    main()
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/terminal.py", line 126, in wrapper
    wrapped_args = (parser, opts, *args)
TypeError: 'NoneType' object is not iterable
```

Instead of fixing this bug, I guess we could remove `license` and `GPL` subcommands in Cylc 8? Before Cylc had a very limited set of dependencies. But now, thanks to Setuptools, anybody can quickly inspect the licenses (and there are multiple ways, via `pkg_resources`, PYPI, manual inspection, Conda, etc).

Here's an easy one with [`pip-licenses`](https://pypi.org/project/pip-licenses/):

```bash
$ pip-licenses --with-system | grep -v pip-licenses
 Name                Version  License              
 Jinja2              2.10.1   BSD                  
 MarkupSafe          1.1.1    BSD-3-Clause         
 PTable              0.9.2    BSD (3 clause)       
 Rx                  1.6.1    Apache License       
 aniso8601           7.0.0    UNKNOWN              
 ansimarkup          1.4.0    Revised BSD License  
 colorama            0.4.1    BSD                  
 cylc-flow           8.0a0    GPL                  
 ecdsa               0.13.2   MIT                  
 future              0.17.1   MIT                  
 graphene            2.1.8    MIT                  
 graphql-core        2.2.1    MIT                  
 graphql-relay       2.0.0    MIT                  
 metomi-isodatetime  1!2.0.1  LGPLv3               
 pip                 19.2.3   MIT                  
 promise             2.2.1    MIT                  
 protobuf            3.9.1    3-Clause BSD License 
 pyasn1              0.4.7    BSD                  
 python-jose         3.0.1    MIT                  
 pyzmq               18.0.2   LGPL+BSD             
 rsa                 4.0      ASL 2                
 setuptools          41.2.0   UNKNOWN              
 six                 1.12.0   MIT                  
 wheel               0.33.6   MIT
```

These are our dependencies and licenses, minus `pip-licenses` itself. When I create a virtual environment and install `pip-licenses`, I get `PTable`, `pip`, `setuptools`, and `wheel`. So here's the final set of dependencies:

```bash
 Name                Version  License              
 Jinja2              2.10.1   BSD                  
 MarkupSafe          1.1.1    BSD-3-Clause             
 Rx                  1.6.1    Apache License       
 aniso8601           7.0.0    UNKNOWN              
 ansimarkup          1.4.0    Revised BSD License  
 colorama            0.4.1    BSD                  
 cylc-flow           8.0a0    GPL                  
 ecdsa               0.13.2   MIT                  
 future              0.17.1   MIT                  
 graphene            2.1.8    MIT                  
 graphql-core        2.2.1    MIT                  
 graphql-relay       2.0.0    MIT                  
 metomi-isodatetime  1!2.0.1  LGPLv3                            
 promise             2.2.1    MIT                  
 protobuf            3.9.1    3-Clause BSD License 
 pyasn1              0.4.7    BSD                  
 python-jose         3.0.1    MIT                  
 pyzmq               18.0.2   LGPL+BSD             
 rsa                 4.0      ASL 2                    
 six                 1.12.0   MIT                  
```

`aniso8601` is BSD but they messed up their license. There are more dependencies if installed via `pip install .[all]` too. (perhaps we could automatically list the dependencies somewhere in the site or doc someday).

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Run `cylc license` with the latest code.

**Expected behavior**

I think it would print the license information before.

**Screenshots**

NA

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
I actually thought we had removed those commands already - it was definitely the intention!

**Comment by hjoliver** [comment]
Ah yes, we have removed them.  The bug just results from not removing the associated command categories:

https://github.com/cylc/cylc-flow/blob/master/bin/cylc#L18-L19

https://github.com/cylc/cylc-flow/blob/master/bin/cylc#L184-L185

**Comment by kinow** [comment]
Changed the title then. Not too sure which categories need to go, but sounds like an easier job than removing the actual commands :tada:
