### ISSUE TITLE
cylc report-timings broken unless extra dependencies are manually installed

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3364]
**Describe the bug**

`cylc-report-timings` has a dependency on `pandas` and `matplotlib`. Running this command, even after installing cylc with the extra `[all]` dependency group still results in an `ImportError` as these two dependencies are not included.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

1. `pip install .[all]`
2. `cylc report-timings five`
3. `CylcError: Cannot import pandas - summary unavailable.`

**Expected behavior**

Not having to install modules manually.

**Screenshots**

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by matthewrmshin** [comment]
Should `cylc report timings` become a component of the new UI?

**Comment by hjoliver** [comment]
It should eventually, but we might need the simpler solution in the interim.

**Comment by kinow** [comment]
>It should eventually, but we might need the simpler solution in the interim.

In that case, I think we can simply copy what was done for [`empy`](https://github.com/cylc/cylc-flow/blob/7442f9c6364c4a04c6879edbc83f4f7881fb14b0/setup.py#L65)?

Creating a group like `report-timings` with a version of `pandas` and `matplotlib` that, when installed, allows `cylc report-timings` runs OK.

**Comment by oliver-sanders** [comment]
For the interim we should probably put the `cylc report timings` in the `extras_require` section.

**Comment by irvslyy** [comment]
sendi sehat semangat gowes,mister

**Comment by irvslyy** [comment]
sepeda terus,sampe betis keluar otot

**Comment by kinow** [comment]
@irvslyy I've deleted your previous two comments. Google Translate gives me some strange text in Indonesian. Sorry, but none of us - as far as I know - know much Indonesian (I could probably recognize the words with origin in Portuguese, but that's all). But if you could post in English it would be easier :+1:

**Comment by datamel** [comment]
I'll have a go at this :)
