### ISSUE TITLE
Remove executable bit of Python source code

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3382]
**Describe the bug**

If you look at the Python source code under `cylc`, you will find some files that have the executable bit turned on. e.g. `cylc.flow.scheduler_cli`, `cylc.flow.prerequisite`, etc

![image](https://user-images.githubusercontent.com/304786/65639113-950f2200-e03b-11e9-87e3-0ccda8d58f31.png)

I see no reason for having the files under `cylc` with `+x`.

**Release version(s) and/or repository branch(es) affected?**

`master`, 8.0a1

**Steps to reproduce the bug**

NA

**Expected behavior**

Source code simply with `rw` permissions.

**Screenshots**

Added in previous section.

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
I never submitted a PR like this, but I think it should work. Something like `chmod -x $file...`, then commit the file, and prepare the PR.

**Comment by matthewrmshin** [comment]
Doh!

**Comment by hjoliver** [comment]
(It probably results from running primitive built-in unit tests during development, before we had proper unit tests).

**Comment by matthewrmshin** [comment]
Closed by #3385.
