### ISSUE TITLE
Remove ParsecConfig#checkspec (or remove its parents parameter)

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3383]
**Describe exactly what you would like to see in an upcoming release**

This was on a post-it for someday, but might be an easy one for someone else with more time.

`cylc.flow.parsec.config.ParsecConfig` has a static method `checkspec`. I couldn't find any user of this method in cylc-flow, and am not aware of any external module using cylc's parsec module.

So I think this method, and associated unit tests, can be removed?

If not, at least its `parents` parameter can be removed. It is never used and discarded when a new `parents` variable is declared within the method.

**Additional context**

![image](https://user-images.githubusercontent.com/304786/65649412-926ff500-e05a-11e9-8837-e839f5e7f9f5.png)

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Yeah, `check_spec` evidently isn't needed any more, it can just be removed.
