### ISSUE TITLE
Include LICENSE file in sdist

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3387]
**Describe exactly what you would like to see in an upcoming release**

For the conda recipe, we will need to include the LICENSE file for now (cc @sadielbartholomew). Ideally that should come from the PYPI package, but for that we need to do as in metomi-isodatetime and include the LICENSE in the sdist (source distribution, used by conda to build the recipe...)

**Additional context**

See this metomi-isodatetime PR for reference: https://github.com/metomi/isodatetime/pull/144

**Pull requests welcome!**

**Comment by sgaist** [comment]
Hi,

I can take on this one :-)

**Comment by sgaist** [comment]
From a quick test on master, if calling `python setup.py sdist`, the COPYING file is already being copied in the tar.gz archive.

So it looks like this issue can be closed.

**Comment by kinow** [comment]
Oh, thanks for testing it, I believe you are correct @sgaist !

Tested locally, and the `COPYING` file was included indeed.

![image](https://user-images.githubusercontent.com/304786/70482389-3d685900-1b4a-11ea-98b9-f57162fdc1bd.png)

I think it might be due to our `license_files` entry in [`setup.cfg`](https://github.com/cylc/cylc-flow/blob/6bb76625903ff3c9f326e66628b5abf7d81f0159/setup.cfg#L33).

That should be enough for Conda, so closing.
