### ISSUE TITLE
[New Config 1] Combine Global and Suite Config Spec

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#3419]
PR #3348 Sets out how an end point for unifying global and local configs, but contains many very complex changes.

An alternative first step to making this change in a way that produces working code is to combine global and local changes whilst making the bare minimum of changes to the code-base.

This issue should cover:
- [x] Move `cylc/flow/cfgspec/suite.py` -> `cylc/floc/config_schema.py`
- [x] Add items from `cylc/flow/cfgspec/global.py` to the new `config_schema.py`
- [x] Move the global config lazy loader (`cylc/flow/cfgspec/glbl_cfg.py`) to `cylc/flow/glbl_cfg_lazy.py`
- [x] Grep the rest of the repo for `cylc.flow.cfgspec` and ensure that the new spec is being imported in all cases.
- [x] Delete the `cfgspec` folder.
- [ ] :tada: Celebrate a small victory on the road to the replacing Rose Suite Run with a new Cylc command.

**Comment by dpmatthews** [comment]
No longer planning to do this
