### ISSUE TITLE
[New Config 2] Introduce `[job platforms]`

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#3421]
PR #3348 Sets out how an end point for unifying global and local configs, but contains many very complex changes.

An alternative step to making this change in a way that produces working code is to combine global and local changes whilst making the bare minimum of changes to the code-base.

#### This issue should cover:
- [ ] Moving settings from `[runtime][job]` & `[runtime][remote]` to a new `[job platform]` section.
- [ ] Adding a specialist section to the upgrader function to deal with deprecation. This is potentially controversial. 

#### This issue should __not__ cover:
Any changes unrelated to creation of job platforms.

**Comment by oliver-sanders** [comment]
@wxtim, @datamel closed by #3453?

**Comment by oliver-sanders** [comment]
Closed by #3453, #3772
