### ISSUE TITLE
Review names of all settings and in the global and suite configs

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#3422]
As part of the rose suite-run migration work, lots of changes to the global and suite config's were discussed. We've decided to focus on the functionality first and will review all the config settings later (prior to the Cylc 8 release).

We need to look through the discussions in the following issues/PRs:
#3404
#3348

**Comment by dpmatthews** [comment]
Changes now agreed: https://cylc.github.io/cylc-admin/proposal-config-changes.html

**Comment by hjoliver** [comment]
Can we close this now?

**Comment by dpmatthews** [comment]
I was assuming we'd leave this issue open until the agreed changes have been implemented.

**Comment by hjoliver** [comment]
(The issue title says "review", which is done ... but I'm being pedantic :grimacing: )

**Comment by dpmatthews** [comment]
Superceded by:
#3690 
#3691 
#3692 
#3693
#3694 
#3695 
#3696
