### ISSUE TITLE
parameters: undefined variables in environment templates

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3446]
#### What

Parameter environment templates, although user defined, belong to `cylc__job__inst__cylc_env` rather than `cylc__job__inst__user_env`.

#### Why

In the job script the `set -euo pipefail` happens after `cylc__job__inst__cylc_env` but before `cylc__job__inst__user_env` meaning that undefined variables in parameter environment templates do not halt execution.

#### Example

```ini
[cylc]
    [[parameters]]
        foo = 1..2

[scheduling]
    [[dependencies]]
        graph = <foo>

[runtime]
    [[<foo>]]
        script = echo "${FOO}"
        [[[parameter environment templates]]]
            FOO = ${HELLO}_%(foo)d
            # $HELLO is undefined so this is really just "_%(foo)d"
        [[[environment]]]
            HELLO = greetings
            # note: user_env gets evaluated *after* environment templates
```

#### Solutions

1. Export parameter environment templates at the top of `cylc__job__inst__user_env` rather than at the end of `cylc__job__inst__cylc_env`.
2. Move the `set -euo pipefail` further up in the job script, there is probably a good reason why this isn't done earlier.
3. Wrap `cylc__job__inst__cylc_env` with `set -euo pipefail`.

#### When

Should this go up against 7.8.5 and or 8.0.0?

**Comment by hjoliver** [comment]
I guess this should go to 7.8.5, if you have evidence that this has caused users real problems?

**Comment by oliver-sanders** [comment]
This has caused hard-to-debug issues but not functional problems...

**Comment by hjoliver** [comment]
OK, I've put this to 7.8.5 as it's an easy fix.

**Comment by oliver-sanders** [comment]
Were we happy with option (2)?

**Comment by hjoliver** [comment]
All the suggested solutions are better than the status quo, but none of them make the example above work (as opposed to error out). It seems conceivable to me that users might want to their other environment variables in parameter environment variables (like `$HELLO` above).  So perhaps we should do:

4. export parameter environment templates at the **end** of  `cylc__job__inst__user_env`

Is there any reason not to do this?  It would solve the undefined-var problem and allow use of user-defined vars in the template.

**Comment by oliver-sanders** [comment]
We have `[environment]` and `[parameter environment templates]`, one must be exported before the other so we can only support the use of one in the other and not both ways unless we delay evaluation?

**Comment by hjoliver** [comment]
My feeling is, I'd be much more likely to want to use a general variable from the `[environment]` section in one from `[parameter environment templates]`, than the other way around.

**Comment by MetRonnie** [comment]
> My feeling is, I'd be much more likely to want to use a general variable from the `[environment]` section in one from `[parameter environment templates]`, than the other way around.

That was my initial expectation of the behaviour

**Comment by oliver-sanders** [comment]
> My feeling is, I'd be much more likely to want to use a general variable from the [environment] section in one from [parameter environment templates], than the other way around.

I think it could play either way, there will definitely be existing suites which do it this way around:

```ini
[runtime]
    [[foo<x>]]
        [[[parameter environment templates]]]
            FILENAME = 'my_%(03x)d.xyz'
        [[[environment]]]
            IN = "$LOC/a/b/c/$FILENAME"
            OUT = "$ARCH/b/e/$FILENAME"
```

I wouldn't want this to be a barrier to Cylc8 adoption.

The user is so far removed from the jobscript implementation that they have no idea why it would work one way and not the other.

Perhaps the nicest solution is to merge `[parameter environment templates]` in with `[environment]` (seems kinda odd doing it in two sections) then it's down to the user to order variables appropriately. Sadly for safety we would need some syntax for marking the things we want to expand parameters in which may cause as much confusion as the original issue...

**Comment by hjoliver** [comment]
> Perhaps the nicest solution is to merge [parameter environment templates] in with [environment] ...

Sounds good if we can avoid the special syntax.  I think it is reasonable to expand any parameter syntax (e.g.`%(name)s`) detected in an environment variable IF the parameter name matches a task parameter defined in the suite.

**Comment by oliver-sanders** [comment]
At least it's nice simple upgrade logic. If we find a template var which doesn't match, log a warning.
