### ISSUE TITLE
authentication: wash up

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3449]
Wash up from #3359 

- [x] Remove old passphrase generation logic and flush out any old code related to this (e.g. remote host installation?).  (Addressed by #3509)
- [x] Allow `cylc scan` to skip running suites which use previous authentication schemes rather than failing with traceback.  (Addressed by #3509)

Document how authentication works, in the user guide: cylc-doc issue created: cylc/cylc-doc#123

**Comment by oliver-sanders** [comment]
Assigning @wxtim and @datamel to help us prioritise #3444.

**Comment by dwsutherland** [comment]
Please put this on hold until #3389 is merged, because the network code has been refactored (due to the new PUB/SUB pattern using the same security).

**Comment by hjoliver** [comment]
Added a list item above for documentation.

**Comment by oliver-sanders** [comment]
(#3389 will definitely get merged first)
