### ISSUE TITLE
cylc run: parsable output

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3451]
To facilitate the job of the UI server it would be good if `cylc run` had an option to output contact information in a parseable format (say JSON) and send the other gunk to stderr.

When `cylc run` returns `0` the contact file should be there (filesystem issues aside) so this is a "nice to have" rather than a critical feature but it seems sensible and simple to me. Thoughts?

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Good idea :+1:
