### ISSUE TITLE
Remove spurious queue add warning

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3470]
**Describe the bug**

If a task `foo` inherits from two families `A` and `B`, assigning members of both `A` and `B` to a queue will result (on adding the second family) in a warning that `foo` has already been added to a queue. This is fine if `A` and `B` are separately added to different queues, but pointless at best if they are both added to the same queue.

https://cylc.discourse.group/t/suggestion-for-queue-warnings/190

**Release version(s) and/or repository branch(es) affected?**

7.8.x and current master

**Steps to reproduce the bug**

(Just reproduce the above scenario in a small workflow definition, then validate it).

Assigning myself as I already put in a quick fix while looking at the problem.

(PR should go to both 7.8.5 and 8.0a2)

**Comment by wxtim** [comment]
@hjoliver  Can we get a PR or push this beyond 7.8.5?

**Comment by hjoliver** [comment]
I'll take a quick look now...

**Comment by hjoliver** [comment]
Closed by #3539 #3540 #3541
