### ISSUE TITLE
Check and remove refs to legacy suite database item `user@host`

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#3476]
Spun off #3473 

@oliver-sanders said
> The upgrader looks good and well tested. It adds the new user and platform columns but doesn't remove the old user@host column. I think old column should be harmless, removing columns with sqlite is difficult and would involve deleting and re-writing the whole table from scratch so this approach seems sensible to me.

So @wxtim left this database item in place.

[Oliver]
> We should be [able] to catch this with a quick git grep, shouldn't be too big a risk as the test battery should catch this too but good point. Perhaps add a TODO to the ticket to check for this before signing off on the job platforms work.

This is that TODO ticket

**Comment by oliver-sanders** [comment]
This might have been done now?

**Comment by wxtim** [comment]
After a quick check of master...
