### ISSUE TITLE
Fix `tests/jobscript/05-global-config.t` for use with platforms

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#3481]
Earlier work on platforms has broken this test: 

We are not intending to have this globalconfig work in Cylc 8. The best this test should give is a helpful warning, but that warning should already have been given elsewhere. More likely we need to re-write this in a platformsy way.

**Comment by oliver-sanders** [comment]
@datamel you get to close this one the easy way!

**Comment by wxtim** [comment]
This issue can be closed at the test in question has been replaced by tests/unit/test_job_file.py
