### ISSUE TITLE
cli: change how we re-invoke commands?

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3488]
The `cylc` command currently re-invokes its sub-commands, e.g. `cylc run suite` becomes `cylc-run suite`.

https://github.com/cylc/cylc-flow/blob/8af55bc494d8b9904898262212f96b6806eea921/cylc/flow/scripts/cylc.py#L53

Now that the veil of the bash script has been stripped I'm not quite sure what the reason for this is.

* We can still easily grep for `cylc` processes.
* `cylc` can be easily white-listed.

Turns out `os.exec*` operations do not play with Code coverage (see #3486).

Questions:

* [x] Any objections to invoking `cylc` sub-commands via a Python interface without system re-invocation as `cylc-<sumcmd>`? **No**

**Pull requests welcome!**

**Comment by hjoliver** [comment]
No objections :+1:
