### ISSUE TITLE
Tidy Up Task Communications Methods

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-flow#3511]
In Cylc 7, Contact2 file is generated for the remote platform, when indirect communication (eg. ssh) is set. It contains one field name: CYLC_COMMS_PROTOCOL_2. 
This is currently redundant for Cylc 8, some code remains. 

Do we still want a Contact2 file for Cylc8? If not this needs clearing out.
Indirect communication needs investigating - possibly ZMQ but alternatively maybe ssh.
Documentation: needs updating.  
Test: cylc-poll/14-intervals references CYLC_TASK_COMMS_METHOD.

**Comment by hjoliver** [comment]
>  This is currently redundant for Cylc 8, some code remains.

Redundant because we've removed ssh task comms on master?

> Do we still want a Contact2 file for Cylc8? If not this needs clearing out.

Presumably we do (once ssh comms is re implemented on master) but I'm not sure; we'll have to figure it out. I think the contact2 logic was added in #2582 and #2637

**Comment by hjoliver** [comment]
Ref: #3327 (re-implement ssh comms)

**Comment by oliver-sanders** [comment]
> Do we still want a Contact2 file for Cylc8? If not this needs clearing out.

*Update: 2020-06-15*

As of #3509 the CONTACT2 file has been removed. Instead we now install the contact file only if using TCP task comms.

You can still tell apart a remote installation from a suite run dir by the presence of `.service/source`.

For #3327 we can probably install the contact file with a task comms field.

> Test: cylc-poll/14-intervals references CYLC_TASK_COMMS_METHOD.

`tests/cylc-poll/14-intervals` uses `CYLC_TASK_COMMS_METHOD` to break TCP comms, there are other ways of achieving that.

 
Is #3509 enough to close this issue?

**Comment by dpmatthews** [comment]
I think we can close this (I'm sure we'll pick up any documentation issues as part of general doc review)
