### ISSUE TITLE
[protobuf] Warning logged as batch_sys_job_id cannot be None when job submission fails

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3517]
**Describe the bug**

Today I spent some time building Docker containers for Slurm, and reading the CUG to experiment with Cylc + Slurm.

When submitting my first job, `sbatch` was not installed yet, so the suite failed. However, there was this line in the logs:

```
...
2020-03-13T10:23:21+13:00 ERROR - [hello.1] -submission failed
2020-03-13T10:23:21+13:00 ERROR - Unable to set kinow|slurm1|1|hello|1 data field: None has type NoneType, but expected one of: bytes, unicode
```

That `None has NoneType` happens because - as far as I understand it - our Protobuf schema [defines](https://github.com/cylc/cylc-flow/blob/b68e7d03a34362bf3ebc4552e05daad51306c846/cylc/flow/data_messages.proto#L98) the `batch_sys_job_id` to be a `string`.

But when a job submission fails (probably happens when using default batch, `at`, etc) the code sets that field to `None`:

https://github.com/cylc/cylc-flow/blob/b68e7d03a34362bf3ebc4552e05daad51306c846/cylc/flow/task_events_mgr.py#L771

The call above results in this try/catch:

https://github.com/cylc/cylc-flow/blob/b68e7d03a34362bf3ebc4552e05daad51306c846/cylc/flow/job_pool.py#L162-L168

Which will always print that error message as in protobuf that seems to be invalid (paging @dwsutherland as he knows protobuf much better than I).

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Submit a job that will fail to be submitted, and look at the log files for the warning.

**Expected behavior**

I think we should set that value to `''` (empty string) instead of `None`, but not quite confident to send a PR for that, as I don't know if there was some reason for using `None` there in the first place.

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/76574784-27d84600-6522-11ea-95c0-c72989a8904f.png)

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by dwsutherland** [comment]
@kinow - Well done, haven't seen this one.

Yes it expects a string assignment, it could easily just do
```
if attr_val is None:
    return
```
Because the field will have a default empty type... (although it looks like it is handled already)..

Also it can't just be `''` because string is not the only type that could be assigned with that function.

**Comment by dwsutherland** [comment]
@kinow - Couple of additional points:
- Perhaps we shouldn't be calling the attribute assignment function with None/invalid job field value (?)
- We could remove the `try: . . . except:` if we'd rather errors on internal code crash the workflow (and are then brought to our attention)..

**Comment by kinow** [comment]
> 
> 
> @kinow - Couple of additional points:
> 
>     * Perhaps we shouldn't be calling the attribute assignment function with None/invalid job field value (?)

That was the first think I thought (see my comment under Expected Behavior above). 

>     * We could remove the `try: . . . except:` if we'd rather errors on internal code crash the workflow (and are then brought to our attention)..

Oh, didn't think about that. Sounds good to me, but probably @hjoliver or @oliver-sanders would be better to answer if that's a good option or not I think.

**Comment by hjoliver** [comment]
@dwsutherland - 

> We could remove the try: . . . except: if we'd rather errors on internal code crash the workflow (and are then brought to our attention).

We should only catch and ignore exceptions that can be legitimately handled, or that don't matter (e.g. `try` to remove a list item that might not exist), everything else is presumably a bug that needs fixing 

In those terms, what's the deal with the try block above?  (i.e. what would it mean if a job "data field" could not be set?).

**Comment by dwsutherland** [comment]
> In those terms, what's the deal with the try block above? (i.e. what would it mean if a job "data field" could not be set?).

Yeah, can't remember if it was scaffolding for development or some fields being set to multiple types... There's a few of these in there, but they can go, we need to just make sure whatever's calling the field setter method(s) feed them the right type.
