### ISSUE TITLE
tui: improve performance

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3527]
* Use a subscription to GraphQL deltas to update the tree.
* Perform the updates asynchronously so that the app doesn't freeze during the update.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
What the change to GraphQL deltas means for communications and how it fits into the [plan](https://github.com/cylc/cylc-admin/blob/master/docs/img/interfaces-and-protocols.png):

![rect4117](https://user-images.githubusercontent.com/16705946/89285829-fd119a00-d648-11ea-83e4-b22187acd3a4.png)

**Comment by hjoliver** [comment]
Blocked by #3731

**Comment by hjoliver** [comment]
Good idea.
