### ISSUE TITLE
job pool pruning problem with absolute trigger

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3553]
Finished `foo`'s never get pruned here:
```
[scheduling]
   cycling mode = integer
   initial cycle point = 1
   final cycle point = 10
   [[graph]]
         R1 = start
         P1 = "start[^] => foo"
[runtime]
   [[root]]
       script = sleep 2
```
![shot1](https://user-images.githubusercontent.com/2362137/78466879-b6736800-775a-11ea-9b87-01460f06089a.png)

Strangely, adding another task downstream of `foo` fixes the problem (`start[^] => foo => bar`):
![shot2](https://user-images.githubusercontent.com/2362137/78466893-ec185100-775a-11ea-9254-d8587a66031e.png)

**Comment by oliver-sanders** [comment]
Have we confirmed whether this housekeeping bug is in:

* Tui;
* The data store;
* The task pool?

**Comment by hjoliver** [comment]
Data store. Monitoring with ‘watch -n 1 “cylc dump -t”’ shows the task pool is OK.

**Comment by hjoliver** [comment]
(And I think?? I tried cylc-ui too, so not Tui)
