### ISSUE TITLE
bash: allow user installation

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3554]
The remaining bash scripts in Cylc Flow are all called as `/bin/bash`

By contrast we run python scripts as `/usr/bin/env python3`.

Is there any reason not to change to `/usr/bin/env bash` to allow for user installation?

This would enable us to support local installations providing better version decoupling (you can even install bash via conda). We could potentially run the test battery against different bash versions.

(note this is a big deal for mac OS users who get a bash3 system installation as zsh is the default shell, mac package managers install locally to `/usr/local/bin/bash`)

**Pull requests welcome!**

**Comment by kinow** [comment]
When I was testing with FreeBSD some days ago, my last problem was `bash`. I did a `pkg add bash` (I think that's the command in FreeBSD), and that downloaded `bash` into `/usr/local/bin/bash`.

Had to add a link (`ln`) to fix that. After that `cylc` command was working fine on FreeBSD, and then I could test the issue we were working.

So +1 from me for using `env` from me :+1:

**Comment by oliver-sanders** [comment]
That's interesting, what version was the FreeBSD system bash? Was it less than 3?

**Comment by hjoliver** [comment]
(The last one there is `csh` @kinow, did you post the wrong screenshot?)

**Comment by kinow** [comment]
> (The last one there is `csh` @kinow, did you post the wrong screenshot?)

No, sorry, but I should have been clearer, so instead of 

>And this is the one that my user had by default in the virtual machine.

maybe should have said

>And this is the **shell** that my user had by default in the virtual machine.

Not sure if helpful, but just in case.

**Comment by hjoliver** [comment]
Wow, defaulting to `csh` is insane.  

> Csh was the most popular interactive shell in the late 1980s

https://www.grymoire.com/Unix/CshTop10.txt

**Comment by oliver-sanders** [comment]
FYI https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features

**Comment by oliver-sanders** [comment]
@dpmatthews any concerns.

**Comment by dpmatthews** [comment]
I'm OK with this
