### ISSUE TITLE
cylc-7 bundled Jinja2 clash

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3575]
From NIWA today:

If a Cylc 7.8 task job runs (via Slurm) *a user script that uses Jinja2 and requires the latest Jinja2 version*, it will fail because `$PYTHONPATH` in the job environment points at the older Jinja2 version bundled with Cylc. 

The reason for this is, the Cylc scheduler program sets PYTHONPATH in its own environment, and Slurm by default copies the job submission environment into jobs.

Possible workarounds for users:
- Tell Slurm not to copy the job submission environment to the job:
```
    [[[directives]]]
       --export=NONE
```
- explicitly remove the Cylc library from PYTHONPATH, inside the task job:
```
    script = """
export PYTHONPATH=$(echo $PYTHONPATH | perl -pi -e 's/:.*cylc.*?:/:/g;')
run-my-script-that-uses-jinja2.py"""
```
- Run the script inside a Python virtual env, so it doesn't see the Cylc 7 Python library?

Perhaps we should deliberately strip PYTHONPATH in `etc/job.sh` (I don't think anyone is trying to use the Cylc library inside the job scripts at this point).??

I guess this is an unfortunate side-effect of bundling third-party libraries (which, for the record, we do not do in Cylc 8!).  Users are very unlikely to hit the problem, but this shows it can happen (who knew Jinja2 would be used in some Python climate data analysis script!!)

**Comment by oliver-sanders** [comment]
With option 2 job scripts loose access to the Cylc library.

With option 3 job scripts loose access to the Cylc CLI including `cylc message`?

**Comment by hjoliver** [comment]
> With option 2 job scripts loose access to the Cylc library.

Yes, which is why I added this: *(I don't think anyone is trying to use the Cylc library inside the job scripts at this point).??*  (This is only a Cylc 7 problem, and we don't have a stable supported API in Cylc 7).

> With option 3 job scripts loose access to the Cylc CLI including cylc message?

No, because `cylc message` is found via the shell `$PATH`, and `cylc` commands configure their own library path.

**Comment by dpmatthews** [comment]
Duplicate of #3487

**Comment by hjoliver** [comment]
Closing as a duplicate...

**Comment by TomekTrzeciak** [comment]
> The reason for this is, the Cylc scheduler program sets PYTHONPATH in its own environment, and Slurm by default copies the job submission environment into jobs.

Did anyone pursue this with upstream Slurm devs? Exporting user environment to the submitted job (including shell functions like `module`!) just doesn't seem to be sensible as a default behaviour.

**Comment by dpmatthews** [comment]
I suspect it would be hard to change existing behaviour which some users would be relying on.

**Comment by hjoliver** [comment]
>  Did anyone pursue this with upstream Slurm devs? Exporting user environment to the submitted job (including shell functions like module!) just doesn't seem to be sensible as a default behaviour.

I agree @TomekTrzeciak, as I said in my response to the local users who ran into this problem, *this is arguably Slurm's fault for copying the job-submission environment into the job by default. That's dangerous, best not to rely on hidden implicit inputs!*  But I can't imagine the Slurm team would change this because (as per @dpmatthews response) loads of users are almost certainly relying on this even if they don't know it.
