### ISSUE TITLE
Proposed change to host name and IP address handling

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#358]
Determining whether a specified host is a remote host or not turns out to be non-trivial: 

Currently cylc always attempts to determine the "local" hostname and IP address of the suite host with `hostname=socket.getfqdn()` and `socket.gethostbyname(hostname)`. Then to decide whether or not a specified task host is a remote host, it gets the IP address of the task host with `socket.gethostbyname()` and compares that to the aforementioned IP address of the suite host. 

**Problems:**
- If you attempt to run cylc on a box that is disconnected from the network, `socket.getfqdn()` may take a long time to time out (20 seconds: #289).
- even when the suite host is online, this is the major source of delayed start-up for cylc commands.
- the  "local" hostname and IP address of the suite host may turn out to be "localhost" and "127.0.0.1". This is sufficient for checking that a specified task host is remote or not, but it is not sufficient for identifying the suite host externally to remote tasks - hence the extra machinery in `suite_host.py` to determine the external IP address of the suite host. 

**proposed simpler method:**
-  If a task specifies a host, submit it as a remote task with ssh; otherwise submit it to run on the suite host. 
- ~~If no tasks specify `[remote]host` there is no reason to do any host lookups.~~
- If any tasks do specify `[remote]host` we still need to do _one_ lookup (name or IP address) for suite-host self-identification in the remote task environments, but this could be punted to the task `submit()` method (and just execute once, for the first remote task) so any associated delay occurs in the job submission thread and won't affect start-up times at all.  
- We will be able to test remote task hosting functionality easily and portably (e.g. in the test battery) without having to have an actual remote host configured - just specify the task host explicitly as "localhost" and the task will run as a remote task on the suite host.

@dpmatthews and @matthewrmshin - please let me know if you agree to this change, which will be quite easy to implement.  It does reverse, in a way, recent small change #356.

**Comment by hjoliver** [comment]
(I need to review this issue)

**Comment by matthewrmshin** [comment]
(Is this issue still important?)

**Comment by hjoliver** [comment]
(I don't think so)
