### ISSUE TITLE
DB task_action_timers housekeeping

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3590]
REF: https://github.com/cylc/cylc-flow/pull/3515#issuecomment-623734136

At restart, we load the entire `task_action_timers` DB table, which records all timers back to the initial cycle point. Then we discard them if they don't apply to an existing task proxy in the pool, with this warning:

> 2020-05-05T10:07:36+12:00 WARNING - foo.34: task not found, skip

Restarting a large suite many cycles in from the ICP would result in gazillions of these warnings. I'm not sure how much time could be wasted doing this, but it seems unnecessary at best. 

This affects current master and 7.8.x; `git blame` suggests it dates back to 2016/17.

Should we:
- load the task pool first, then do a targetted request to load timers for the specific existing task proxies?
- OR housekeep the task_action_timers` table, only keeping timers for existing tasks?
- OR make a new timer snapshot table, separate from the historical record of timers?

**Comment by oliver-sanders** [comment]
The housekeep option sounds the best as we have no reason to store this historical data.

**Comment by hjoliver** [comment]
> Can we just remove timers when we remove tasks from the pool?

I would think so.  @matthewrmshin - do you recall why we were keeping all task action timers in the DB?  (I'm not sure if your comment on Riot addressed that question ... I'll look back later).

**Comment by matthewrmshin** [comment]
The reason for the serialisation in the database is for restart - so any unfinished actions can continue or retry after the restart. (Task retry delay count down may also be using the same database table for serialisation, but my memory of the system is fading without checking the source logic.)

Taking some of the things back from the Riot comment. Jogging my memory of the system, the task action timer objects may no longer be just the attributes of task proxy objects. If they are held by another data structure, then you should be able to clear out task proxy objects without affecting the task action timers. But please check the latest logic to confirm.

**Comment by hjoliver** [comment]
Thanks Matt, but I wonder if think I'm asking a different question :thinking: The problem is, at restart we are loading every every timer that ever existed right back to the ICP, whereas we presumably only need those that correspond to the tasks currently held in the task pool. I was just checking if you recall some non-obvious reason why we actually need to do that (seems unlikely, but just checking!).

**Comment by matthewrmshin** [comment]
It should only load things that are relevant. Or at least how I remember the logic. I also remember that the old task action timers are cleared out from the database when they are no longer relevant. Is that not the case?

**Comment by hjoliver** [comment]
Hmm, in that case I wonder if we accidentally broke the timer DB housekeeping somewhat more recently.  Nevermind, we'll look at the current logic and figure it out :beers:

**Comment by hjoliver** [comment]
Huh, comments below suggest housekeeping should be happening as Matt suggests:
```python
# suite_db_mgr.py
  def put_task_pool(self, pool):
        """Put statements to update the task_pool table in runtime database.

        Update the task_pool table and the task_action_timers table.
        Queue delete (everything) statements to wipe the tables, and queue the
        relevant insert statements for the current tasks in the pool.
        """
        self.db_deletes_map[self.TABLE_TASK_POOL].append({})
        # No need to do:
        # self.db_deletes_map[self.TABLE_TASK_ACTION_TIMERS].append({})
        # Should already be done by self.put_task_event_timers above.
```

**Comment by hjoliver** [comment]
OK, I think I've confirmed that housekeeping of this table is just being erroneously skipped.
