### ISSUE TITLE
Universal suite/task/cycle delimiter (universal identifier)

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3592]
specification: cylc/cylc-admin#115

For suite/task IDs, the new hierarchical ID chosen by @dwsutherland for use in the back-end has nice properties but can't be used on the command line because the delimiter is the shell pipe character. 

Supersedes #3542 - please refer to the discussion there.  The general solution to this problem should support the original use case of that issue (allow dots in task names).

**Comment by dwsutherland** [comment]
As mentioned in the superseded [ticket](https://github.com/cylc/cylc-flow/issues/3542#issuecomment-611787467); We may need to use a two character delimiter to meet 
 the constraints of shell/Cylc-Conf/datetime ...

**Comment by oliver-sanders** [comment]
Proposal:

* Use `/` as the separator (as originally intended) but use `//` to separate the flow from the cycle.
* Support `:<arg>` as a state selector (e.g. the current `cylc trigger flow *:failed`).

```bash
# regular form (e.g. element ids in GraphQL schema)
[~user[/]]flow//cycle/task/job

# expanded form with selectors (e.g. CLI querying)
[~user[/]]flow[:state]//cycle[:state]/task[:state]/job[:state]
```

Examples (equivalent GraphQL arguments under current scheme)

```bash
# flow under account user (wid="user|flow")
~user/flow

# the task foo at all cycles in flow (wid="flow|*|foo")
flow//*/foo

# all running tasks in foo (wid="flow|*|*" state="running")
flow//*/*:running

# all running workflows (wid="*" state="running")
*:running
```

cylc-admin proposal PR: https://github.com/cylc/cylc-admin/pull/115

**Comment by oliver-sanders** [comment]
Assigning myself for phase 1 i.e. permitting the new syntax on the CLI.
