### ISSUE TITLE
portability: dns

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3595]
DNS issues have long caused portability issues with Cylc.

A lot of our tests make the assumption that `socket.getfqdn` will always match `hostname -f`, sadly this assumption is not realistic. Of the six platforms I use regularly this assumption only holds for two of them.

Here are five different methods for identifying localhost:

```
hostname
hostname -f
python3 -c 'import socket; print(socket.getfqdn())'
python3 -c 'import socket; print(socket.gethostname())'
python3 -c 'from cylc.flow.hostuserutil import get_fqdn_by_host; print(get_fqdn_by_host(None))'
```

And here are the results from a few different platforms:

Ubuntu (Vanilla)
===========

No surprises, all methods return the short hostname:

```
ubuntu
ubuntu
ubuntu
ubuntu
ubuntu
```

Mac OS
======

* `socket.getfqdn` returns an IPV6 loopback.
* Hostnames are case insensitive but are configured with capitals, some socket methods reduce names to lowercase causing diffs.

```
Bobs-MacBook.local
Bobs-MacBook.local
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
Bobs-MacBook.local
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
```

GitHub Actions
==============

* `hostname -f ` disagrees with `socket.getfqdn`.

```
fv-az33
fv-az33.ukytxvjih3denlwyewf2iq3q4b.cx.internal.cloudapp.net
fv-az33.internal.cloudapp.net
fv-az33
fv-az33.internal.cloudapp.net
```

Travis CI
========

* `hostname -f ` disagrees with `socket.getfqdn`.

```
travis-job-e8a47a2f-a1eb-4e70-96e1-d884e48e24bc
travis-job-e8a47a2f-a1eb-4e70-96e1-d884e48e24bc
localhost
travis-job-e8a47a2f-a1eb-4e70-96e1-d884e48e24bc
localhost
```

Networked Linux example 1
=========

No surprises, one fqdn and one short hostname:

```
vld601
vld601.c.m.g.u
vld601.c.m.g.u
vld601
vld601.c.m.g.u
```

Networked Linux example 2
==========

* `hostname -f ` disagrees with `socket.getfqdn`.

```
exvcylcdev01
exvcylcdev01.m.g.u
exvcylcdev01.meto.g.u
exvcylcdev01
exvcylcdev01.meto.g.u
```

**Comment by oliver-sanders** [comment]
It seems to me that the only method which consistently yields meaningful results is `hostname -f`.

**Comment by hjoliver** [comment]
> DNS issues have long caused portability issues with Cylc.
...
A lot of our **tests** make the assumption that `socket.getfqdn` will always match `hostname -f`

Is this a problem for Cylc itself, as well, or just the tests??

**Comment by kinow** [comment]
Might be related to this ~10 years old bug in Python: https://bugs.python.org/issue5004

One user commented with a [similar issue](https://github.com/borgbackup/borg/issues/3471), and there's a patched version of `getfqdn` too. If that works (and that makes sense too) maybe we could just comment in the Python bug saying it worked for us, or that we have a similar problem.

https://github.com/borgbackup/borg/commit/9b0d0f3127289fc3bbe620e8adce8038ed594e9f

Just 0.02$

**Comment by dpmatthews** [comment]
Lots of systems seems to implement similar workarounds, e.g.
https://github.com/apache/airflow/blob/master/airflow/security/utils.py#L61
(uses https://github.com/apache/airflow/blob/master/airflow/utils/net.py#L31)

**Comment by oliver-sanders** [comment]
> Is this a problem for Cylc itself, as well, or just the tests??

Both. On some platforms Cylc will not be able to run out-of-the-box (even if the host is vanilla and not networked) without patching or configuration workarounds.

> Might be related to this ~10 years old bug in Python

I think this is a different problem relating to slow resolution of hostnames, though it does have a similar workaround.

> Lots of systems seems to implement similar workarounds, e.g.

Nice find.

**Comment by hjoliver** [comment]
Superseded by #3768
