### ISSUE TITLE
actions: mail tests

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3599]
Setup `mail` on GitHub Actions to allow dependent tests to run.

Follow-on from: #3548 

See previous aborted attempt: https://github.com/cylc/cylc-flow/pull/3548/commits/a0e07ab871ef014a11ca7191be2b0630a42c28ca

**Comment by MetRonnie** [comment]
I think it just needed a `sleep` to allow the mailbox to be created on receiving the email from itself: https://github.com/MetRonnie/muldoon/runs/811076277?check_suite_focus=true

Btw, how about creating a new label `gh-actions` for these sorts of issues/PRs?

**Comment by oliver-sanders** [comment]
Brilliant, I nearly went nuts trying to figure out what was wrong there.

Can create a label if you like, if so it's worth post-humorously labelling old PRs/issues.

I try to prefix issue/commit/PR names as there are quite a lot more topics than we we could ever have labels for.
