### ISSUE TITLE
default to initial cycle point = 1 for integer cycling suites

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3610]
Tiny thing which kinda bugs me:

```
[scheduling] 
    cycling mode = integer
    [[dependencies]]
        graph = foo
```

This fails because we have not set the initial cycle point.

For `cycling mode = integer` should we set default to `initial cycle point = 1`? *Seems like thats a yes.*

**Pull requests welcome!**

**Comment by kinow** [comment]
+1

**Comment by hjoliver** [comment]
Yes, that's always annoyed me too.

**Comment by oliver-sanders** [comment]
Whilst Ronnie is looking at this one, is there any reason not to infer `cycling mode = integer` if `initial cycle point` and `cycling mode` are both omitted?

```ini
[scheduling] 
    [[dependencies]]
        graph = foo
```

**Comment by kinow** [comment]
> Whilst Ronnie is looking at this one, is there any reason not to infer `cycling mode = integer` if `initial cycle point` and `cycling mode` are both omitted?
> 
> ```ini
> [scheduling] 
>     [[dependencies]]
>         graph = foo
> ```

I wouldn't mind that change too. Most times when I am—rarely—writing a workflow, I want an integer-point based to run some quick tests in the UI or to see how something works in Cylc. 

+1

**Comment by oliver-sanders** [comment]
> I want an integer-point based to run some quick tests

Yep, often you want a quick non-cycling workflow.

> is there any reason not to infer cycling mode = integer

Oh, actually this might be a pretty good reason not to do this:

```console
$ cylc run <mysuite> 2000
```

Is that `2000-01-01T00:00Z` or `2000`?

**Comment by hjoliver** [comment]
> Oh, actually this might be a pretty good reason not to do this:
> `$ cylc run <mysuite> 2000`

Yeah, 2000 is valid as date-time and integer format :grimacing: 

Actually, it would make more sense to default to integer cycling and require an explicit cycling mode declaration for date-time (but, historical reasons... date-time came first in Cylc).

We could almost do that, if date-time could also be inferred from ICP/FCP and recurrence forms?

**Comment by oliver-sanders** [comment]
Problem is in the non-cycling case there is only one recurrence `R1` which is valid in both contexts.

**Comment by MetRonnie** [comment]
> is there any reason not to infer cycling mode = integer if initial cycle point and cycling mode are both omitted?

It looks like this is supposed to do that:
https://github.com/cylc/cylc-flow/blob/c360146fe1133bf34e2e5c877f6bae966113c6f3/cylc/flow/config.py#L219-L225

however it doesn't seem to allow for any task names? I.e. for 
```ini
[scheduling] 
    [[graph]]
        R1 = foo
```
`foo` is not in `['graph', '1', 'R1']`
