### ISSUE TITLE
daemonization: consider moving to PEP3143

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3652]
When [PEP3143](https://www.python.org/dev/peps/pep-3143/) makes it to the standard library we may wish to consider replacing our custom daemonization logic.

> **Note** I've tried out the [python-daemon](https://pypi.org/project/python-daemon/) library and it does work (with a caveat regarding printing to stdout from within the context).

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Might be a while: https://www.python.org/dev/peps/pep-3143/#pep-deferral

> Further exploration of the concepts covered in this PEP has been deferred for lack of a current champion interested in promoting the goals of the PEP and collecting and incorporating feedback, and with sufficient available time to do so effectively.

**Comment by oliver-sanders** [comment]
Yeah, spotted that, however the python-daemon library is a working implementation.

**Comment by oliver-sanders** [comment]
[PEP3143](https://www.python.org/dev/peps/pep-3143/) is still deferred, probably unlikely to make it, closing.
