### ISSUE TITLE
Investigate why the web UI is getting jobs under deltas.added without getting its parent task proxy first/at the same time

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3658]
**Describe the bug**

Follow up for the deltas/incremental updates work.

For one workflow, after running it for some minutes, some times 5 minutes, some times 15 or so, the Web UI gets a job under `deltas.added`, without getting the job's parent under `deltas.added`.

The job parent does appear in the same response payload, but under `deltas.updated`.

**Release version(s) and/or repository branch(es) affected?**

`master`, but the Web UI pull request is still under review: https://github.com/cylc/cylc-ui/pull/458

**Steps to reproduce the bug**

1. check out `master` for Cylc UI Server, and install it with `pip` or `conda` in a virtual environment
2. check out the Web UI branch, and run `yarn install`, following by `yarn run build:watch`
3. install the Cylc workflow (code below)
4. start the `jupyterhub` and Cylc workflow
5. open the browser to start the Cylc UI Server
6. visit the /#/workflow/$NAME page, to see the Cylc tree component, not necessary to open any other widgets
7. press F12 (chrome/ffox) and choose the Console tab, keep an eye for warnings
8. optionally, you can choose the Debugger tab, and check the option to break on uncaught exceptions; that way you should be able to hover the variable containing the deltas payload
9. also optional, when performing step 6, choose the Network tab and filter by WS (WebService) and refresh the page, this way you should have a complete log of the messages received by the Web UI, and if you have a breakpoint, you should be able to locate your message and previous one (with some effort)

:vulcan_salute: 

**Expected behavior**

No console errors or warnings.

**Screenshots**

**Additional context**

- Previous discussion on UIS pull request starts around this comment: https://github.com/cylc/cylc-uiserver/pull/118#issuecomment-642389311
- Pull request in the Web UI to reproduce: https://github.com/cylc/cylc-ui/pull/458
- Query used: https://gist.github.com/kinow/a1f99b40d0deb3766e13b0584a84773c
- Workflow used: 

```
[scheduling]
initial cycle point = now

[[dependencies]]
[[[P1Y]]]
graph = "FAM3:succeed-all => FAM6"

[runtime]
    [[root]]
        init-script = echo "I'm first"
        env-script = echo "Hi first, I'm second"
        script = sleep 20; echo "RubyRubyRubyRuby"
        exit-script = echo 'Yay!'
        err-script = echo 'Boo!'
    [[FAM]]
    [[FAM2]]
        inherit = FAM
    [[FAM3]]
        inherit = FAM2
    [[foo]]
        inherit = FAM3
    [[bar]]
        inherit = FAM3
    [[FAM4]]
    [[FAM5]]
    [[FAM6]]
        inherit = FAM5
    [[qux]]
        inherit = FAM6
    [[qaz]]
        inherit = FAM4, FAM
    [[qar]]
        inherit = FAM, FAM4, FAM5
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Had some similar errors today, but in an easier way to reproduce it. I applied the following patch to the code.

```diff
diff --git a/src/components/cylc/tree/deltas.js b/src/components/cylc/tree/deltas.js
index 3bfe054..e4bc3c7 100644
--- a/src/components/cylc/tree/deltas.js
+++ b/src/components/cylc/tree/deltas.js
@@ -50,6 +50,9 @@ const PRUNED = {
  * @param {CylcTree} tree
  */
 function applyDeltasPruned (pruned, tree) {
+  if (pruned.taskProxies || pruned.familyProxies || pruned.jobs) {
+    console.table(pruned)
+  }
   Object.keys(PRUNED).forEach(prunedKey => {
     if (pruned[prunedKey]) {
       for (const id of pruned[prunedKey]) {
@@ -97,6 +100,11 @@ const ADDED = {
  * @param {CylcTree} tree
  */
 function applyDeltasAdded (added, tree) {
+  if (added.cyclePoints) {
+    added.cyclePoints.forEach((cp) => {
+      console.log(`Added cyclepoints: ${cp.cyclePoint}`)
+    })
:...skipping...
diff --git a/src/components/cylc/tree/deltas.js b/src/components/cylc/tree/deltas.js
index 3bfe054..e4bc3c7 100644
--- a/src/components/cylc/tree/deltas.js
+++ b/src/components/cylc/tree/deltas.js
@@ -50,6 +50,9 @@ const PRUNED = {
  * @param {CylcTree} tree
  */
 function applyDeltasPruned (pruned, tree) {
+  if (pruned.taskProxies || pruned.familyProxies || pruned.jobs) {
+    console.table(pruned)
+  }
   Object.keys(PRUNED).forEach(prunedKey => {
     if (pruned[prunedKey]) {
       for (const id of pruned[prunedKey]) {
@@ -97,6 +100,11 @@ const ADDED = {
  * @param {CylcTree} tree
  */
 function applyDeltasAdded (added, tree) {
+  if (added.cyclePoints) {
+    added.cyclePoints.forEach((cp) => {
+      console.log(`Added cyclepoints: ${cp.cyclePoint}`)
+    })
+  }
   Object.keys(ADDED).forEach(addedKey => {
     if (added[addedKey]) {
       added[addedKey].forEach(addedData => {
diff --git a/src/services/workflow.service.js b/src/services/workflow.service.js
index ba86405..0da5fb3 100644
--- a/src/services/workflow.service.js
+++ b/src/services/workflow.service.js
@@ -70,6 +70,10 @@ class WorkflowService extends GQuery {
     if (!variables) {
       variables = {}
     }
+    if (this.deltasObservable !== null) {
+      console.warn('Trying to start a deltas subscription while another one is already active')
+      return
+    }
     if (this.debug) {
       // eslint-disable-next-line no-console
       console.debug('graphql query:', query.loc.source.body)
@@ -96,6 +100,7 @@ class WorkflowService extends GQuery {
   stopDeltasSubscription () {
     if (this.deltasObservable) {
       this.deltasObservable.unsubscribe()
+      this.deltasObservable = null
     }
   }
```

For the workflow `families2` below

```
[scheduling]
  cycling mode = integer
  initial cycle point = 1
  [[dependencies]]
     [[[R/^/P1]]]  # 1, 2, 3, 4, 5, ...
        graph = """foo[-P1] => foo
                 foo => f1 & f2 => bar"""
     [[[R/^/P2]]]  # 1, 3, 5, ...
        graph = "foo => f3 & f4 => bar"

[runtime]
  [[root]]
      script = "sleep $((5 + RANDOM % 10))"
  [[FAM]]
  [[f1, f2, f3, f4]]
     inherit = FAM
```

the browser console is pretty consistent at logging 1 cyclepoint out, another one added, 1 cyclepoint out, another one added. In a nice sequence, that is easy to be monitored.

The moment I added a Graph widget, causing the existing GScan subscription to be stopped, and a new one with GScan+Query to be created, **the deltas subscription didn't receive 1 cyclepoint**.

![image](https://user-images.githubusercontent.com/304786/86319031-96831000-bc87-11ea-987b-a379b12ec916.png)

That caused JS errors due to missing parents, similar to the error in this issue.

**Comment by dwsutherland** [comment]
Figured out the issue while investigating bugs in #3811 

**From Element:**

> The missing parent happens when the data-store is queried and/or read during pruning, i.e. a first parent is pruned before its task is deleted, so when the resolvers look up the task first parent to resolve it it's no-longer there..
But it might be worse than that; even if we ordered the data store pruning appropriately or made the data-store update atomic, the GraphQL query/sub may start before the update/pruning and the first parent resolving happen after the update/pruning..

After spending ages trying to find a fault in my pruning scheme, I tried to search  for a task without firstParent after delta application:
```
        # Apply deltas to local data-store
        data = self.data[self.workflow_id]
        for key, delta in self.deltas.items():
            if delta.ListFields():
                delta.reloaded = reloaded
                apply_delta(key, delta, data)
        no_parent_tps = [
            n_id
            for n_id, n_val in data[TASK_PROXIES].items()
            if n_val.first_parent is None
        ]
        if no_parent_tps:
            print('Task Proxy Node has no First Parent!')
            print(no_parent_tps)
        no_parent_fps = [
            n_id
            for n_id, n_val in data[TASK_PROXIES].items()
            if n_val.first_parent not in data[FAMILY_PROXIES]
        ]
        if no_parent_fps:
            print('First Parent does not exist!')
            print(no_parent_fps)
```

Then I reproduced the bug on both the n-window and master branch   .. but couldn't find anything in the suite log

> It's happening more often with the n-window because the pruning is more frequent

> The API is running on a different thread at the WFS, and the delta application on the different thread (from main) at the UIS ... So even though we could try make the update/pruning as close to atomic as possible, it can still happen between resolving the child and that child's first parent subfield.. 
(same could happen on the same thread as async tasks I suppose) .. The other, and less desirable way, would be to queue up all the read/writes on the data-store
but that would mean the GraphQL root query would have to be treated as a queue item.. which wouldn't probably work with the subscription async gen.


To fix this issue we may need to do one or more of the following:
- Move the WFS server from threads to async no wait receive. And move the UIS delta application and/or delta sync process from threads to async no wait receive.
- Make the query resolvers/executor non-async, and only use async at the root query and/or graphql endpoint.
- . . .something else.

I think having the query resolution and delta application in the same thread is a good start.

Everything inheritance node (apart from root) should have a parent, and if it doesn't, then it will have been pruned by the time the query finished resolving (i.e. at the same time as the parent)

So, for now we just need to ignore nodes with missing parents by either:
- Ignore/remove no first parent issue appropriately in the clients
- Do some tricky filtering of the result, much like the null-stripping, by specifying compulsory fields or something

**Comment by dwsutherland** [comment]
Is this still an issue?

**Comment by dwsutherland** [comment]
> Is this still an issue?

Ignore that... I should trust my past self (as I don't think we've done all that I proposed above)

**Comment by hjoliver** [comment]
Closing as probaby fixed, by recent UIS changes.
