### ISSUE TITLE
platforms: is_remote_platform or is_remote_filesystem

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3662]
From Riot (in reference to using a different user account as a remote platform):

> We should go through the code and look at all 'is remote host?' tests to understand exactly how this sort of hack falls short of a real remote host ... but not a high priority when it's not too hard to use an actual/real remote host.

After the initial platforms work has been merged we should evaluate the `is_remote_platform` logic which currently relies on DNS/FQDN logic.

However, platforms are really defined by their filesystem so should this logic change to `is_remote_fs`?

For example the following is an entirely valid platform configuration:

*`~/.cylc/flow/<version>/flow-tests.rc`*
```ini
[platforms]
    [[local-remote]]
        hosts = local-remote
```

*`~/.ssh/config`*
```ini
Host local-remote
     Hostname localhost
     User bob
```

But it's all on the same host!

The correct answer is probably a combination of both.

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Ping @matthewrmshin in case he wants to express an opinion on this!

**Comment by hjoliver** [comment]
(seems to me, yes it should `is_remote_fs`...)

**Comment by matthewrmshin** [comment]
We may be using the function for cross purpose here. Are we asking the question for whether we need to sync some files? Or are we asking where we should be running the job submission command? You can have a situation where you have a shared file system, but still need to run the job submission command on a remote host. You can even have platforms where you have no shared file system but you are allowed to run the job submission command locally.

**Comment by matthewrmshin** [comment]
And I've recently set something up where I've the filesystem partially shared. (Not that I want to be awkward. It was due to filesystem performance issues.)

**Comment by matthewrmshin** [comment]
What are you considering for the platform change? What if you can answer these questions at the configuration level?

**Comment by oliver-sanders** [comment]
Sorry, badly worded question, the issue is more like "re-align FS/hostname checks in the wake of platforms work" rather than "replace one check with another".

We need checks for:

1. Determining when to install files.
2. Telling one platform from another.
3. Avoiding un-necessary SSH (difficult as the user can be fiddled in the ssh config).

> And I've recently set something up where I've the filesystem partially shared.

Yikes, luckily in our case we are only really interested in the `cylc-run` directory. We may have to make the assumption that this is held on a single volume.

**Comment by matthewrmshin** [comment]
OK. Let's take a look at the `~/cylc-run/SUITE/` directory. We have several parts:
* Source and configuration files that are used by tasks on different platforms.
* Job log files. Generated on the task host, but may need to be copied back.
  * To complicate matters slightly. The Job file, located in the same hierarchy, is currently generated by the scheduler and installed on the job host on job submission.
* Files related to Scheduler <> Job interaction. E.g. `.service/`.
* Shared output `share/` - which may need to be shared between tasks hopefully only in the same platform.
* Other parts that we don't care in the context of this issue. E.g. `work/`.

I guess we care most about bullet 1, 2 and 3? In the current set up, I suppose they all live in the same file system _per platform_. (But is this always going to be true?)

Some extra thoughts:
* If you need to run a _background_ job in a remote host with a shared file system, you will no need to copy files, but you will have to run a SSH command to submit the job.

**Comment by oliver-sanders** [comment]
Closed by install target logic.
