### ISSUE TITLE
conditional prerequisite bug

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3664]
**Describe the bug**

Diagnosed after [user bug report on Discourse forum](https://cylc.discourse.group/t/suite-shutting-down-with-name-archive-bool-is-not-defined-error/254/3)

Construction of conditional prerequisite expression fails for `NAME | preNAME => blah` due to overly simplistic string replacement in the `Prerequisite.set_condition()` method of `prerequisite.py`:
```python
# Make a Python expression so we can eval() the logic.
for message in self.satisfied:
    expr = expr.replace(self.MESSAGE_TEMPLATE % message,
                        self.SATISFIED_TEMPLATE % message)
```
**Release version(s) and/or repository branch(es) affected?**

- 7.8.x
- master (Cylc 8)

**Steps to reproduce the bug**

This simple case even fails validation (some only fail at runtime because we don't evaluate all prerequisites during validation):
```ini
[scheduling]
   [[graph]]
      R1 = "foo | xfoo => bar"
```
Validation:
```
$ cylc val foo
name 'xbool' is not defined
SuiteConfigError: bar: failed to evaluate triggers.
```

This probably warrants another Cylc-7 release too :grimacing: 

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
Note: the simple case is not reproduceable 100% of the time because the `Prerequisite.satisfied` dict is added to in an non-ordered way, so sometimes `xfoo` comes before `foo` in the loop and the string replacement works ok.

**Comment by hjoliver** [comment]
@MetRonnie - apologies for taking over this one, just trying to get it in for the beta3 release very soon (and you're on leave). Hope you hadn't wasted any time on it.
