### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#3675]
I was trying to look up coverage and a look at https://codecov.io/gh/cylc/cylc-flow reveals it hasn't updated in 2 months. I'm guessing this was the move from Travis to GH Actions?

**Pull requests welcome!**

**Comment by kinow** [comment]
I think we disabled it to ease the migration to gh actions, but there were problems with the reported values.

IIRC, codecov didn't/doesn't merge the reports well, giving a different coverage value.

Also, it wasn't reporting subcommand coverage (there's an issue for that somewhere).

**Comment by MetRonnie** [comment]
I now see there's already #3598 for this - it didn't show up when I searched yesterday for some reason

**Comment by hjoliver** [comment]
Closing as duplicate...
