### ISSUE TITLE
platforms: platform aliases

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3686]
Add support for groups of platforms called platform-aliases e.g:

```ini
[platforms]
    [[hpcl1-bg]]
        hosts = hpcl1
        retrieve job logs = True
        batch system = background
    [[hpcl2-bg]]
        hosts = hpcl2
        retrieve job logs = True
        batch system = background
[platform aliases]
    [[hpc-bg]]
        platforms = hpcl1-bg, hpcl2-bg
```

At its most basic we pick which platform to use from a group randomly.

See the [platforms proposal document](https://cylc.github.io/cylc-admin/proposal-platforms.html#further-enhancements) for more information.

**Extension:**

We might as well integrate the host-select logic currently used for picking suite servers as there is an [existing interface](https://github.com/cylc/cylc-flow/blob/c6c90629546854378a96292226a7a65ee4a9e6a3/cylc/flow/host_select.py#L57-L62
) which was written to fulfil this function e.g:

```ini
[platform aliases]
    [[hpc-bg]]
        platforms = hpcl1-bg, hpcl2-bg
        ranking = """
            cpu_percent()
        """
```

**Pull requests welcome!**

**Comment by wxtim** [comment]
PR #3793 adds the basic functionality described in this issue. The selection method to be addressed in a follow up.

**Comment by wxtim** [comment]
PR #3793 was merged, but leaving this open becuase the advanced selection options are required.

**Comment by oliver-sanders** [comment]
Only the selection component of this issue remains so opening a new issue (#3827) for that and closing this.
