### ISSUE TITLE
platforms: suite installation on remote platforms

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3687]
Bullet point (1) "Installation of suites on platforms" as outlined in the [platforms proposal document](https://cylc.github.io/cylc-admin/proposal-platforms.html#enhancements-to-support-rose-suite-run-functionality):

* Install the suite using `rsync`.
* Determine what to transfer by includes or excludes.
* Dump the rsync output in a log file (e.g. could be `<suite dir>/log/remote-init/<install target>-<timestamp>`).
* Use an `install target` to prevent duplicate attempts at suite installation.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Assigning @datamel who is currently looking into the `rsync` functionality.

**Comment by wxtim** [comment]
@datamel - Where does your PR leave this issue?
