### ISSUE TITLE
platforms: support symlinking directories to configured locations

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3688]
Bullet point (2) "Support moving some directories to different locations with symlinks to the original location" from the [platforms proposal document](https://cylc.github.io/cylc-admin/proposal-platforms.html#enhancements-to-support-rose-suite-run-functionality).

Re-implement the [`root-dir`](http://metomi.github.io/rose/doc/html/api/configuration/site-and-user.html#rose:conf:rose.conf[rose-suite-run]root-dir) functionality from `rose suite-run` in Cylc. This allows, for example, the `log` directory to be placed on a more appropriate filesystem.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
This issue comes in two parts:

1. The initial creation of the directories on the "localhost" platform when the suite is run.
2. The subsequent creation of these directories on other install targets (filesystems) during the remote-init process when the first job is submitted to a new install target.

**Comment by hjoliver** [comment]
Note that run-dir symlinking will render `cylc register --run-dir=RUNDIR` obsolete. The PR for this Issue should remove that option.
