### ISSUE TITLE
conf: [scheduling]stop after cycle point

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3694]
Implement a `[scheduling]stop after cycle point` configuration to match the `cylc run --stop-cycle-point=POINT` cli option.

See the [config change proposal document](https://cylc.github.io/cylc-admin/proposal-config-changes.html#schedulingstop-after-cycle-point---new).

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
What is the difference between this and `[scheduling]final cycle point`?

**Comment by oliver-sanders** [comment]
Cycling recurrences can be (and are by default) written relative to the initial cycle point, however, they can also be written relative to the final cycle point.

This (obscure) feature allows you to draw a line in the sand for the workflow without effecting the graph in any way.

**Comment by hjoliver** [comment]
In other words, you can tell the scheduler to stop in the middle of the graph, instead of at the end of it.

**Comment by wxtim** [comment]
I'm writing my PR on the basis that you want the command line to over-ride `flow.cylc` - Objections?

**Comment by oliver-sanders** [comment]
Yep, we always allow CLI to override config.
