### ISSUE TITLE
xtriggers: handle non bash-friendly characters in labels

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3703]
We currently permit hyphens in xtrigger labels e.g:

```ini
[scheduling]
    [[xtriggers]]
        foo-1 = ...
```

This works fine and as expected, provided that the xtrigger does not return any data. If the xtrigger does return data, however, you will get job failures due to bash syntax errors:

```bash
cylc_job_inst__user_env() {
    # TASK RUNTIME ENVIRONMENT:
    export foo-1_key
    foo-1_key=value
}
```

Solutions:

1) ✅ Restrict xtrigger labels to bash-friendly characters.
2) 👎  ~When writing environment variables replace non bash-friendly characters with underscores.~

See also #2979 

**Pull requests welcome!**

**Comment by hjoliver** [comment]
I vote for 1.

**Comment by oliver-sanders** [comment]
I think I lean to 1 as well since the xtriggers are a Python interface.
