### ISSUE TITLE
job_file: CYLC_SUITE_DEF_PATH not set correctly

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#3715]
#3651 attempted to fix an issue when `[[ $(realpath "$HOME") != "$HOME" ]]`. However, it simply bypassed the substitution so  CYLC_SUITE_DEF_PATH is still not set correctly (and is actually worse if the same setup applies on the remote host).

Before we change this again I suggest we decide whether we need this variable. Once we've completed the `rose suite-run` migration I think we should either remove it (and CYLC_SUITE_DEF_PATH_ON_SUITE_HOST) or deprecate it and set it equal to CYLC_SUITE_RUN_DIR.

**Comment by hjoliver** [comment]
Not sure I've seen a use for this variable in recent times. I think it dates back to the early run-in-place cylc model where jobs might expect to find suite files in the suite source directory. But now will install files to the run directory and jobs can find them there.

**Comment by dwsutherland** [comment]
I might have use for it... I think I did a PR to make some more of these variables available in the environment after suite start-up..

**Comment by hjoliver** [comment]
Repeating from Element.io discussion:

For suites launched with `rose suite-run`, `CYLC_SUITE_DEF_PATH` is the same as `CYLC_SUITE_RUN_DIR`.

We only need to worry about those not using `rose suite-run`. It is possible, by raw cylc, that they have task jobs accessing files directly in the original suite source directory.

We'll just have to warn people about this.  (Cylc 8 is moving to the `rose suite-run` installed-suite model anyway).

**Comment by oliver-sanders** [comment]
Should be closed by https://github.com/cylc/cylc-flow/pull/4154/files, `CYLC_SUITE_DEF_PATH` is now set to `CYLC_SUITE_RUN_DIR`.
