### ISSUE TITLE
cylc spawn: command name

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3735]
Should we rename the `cylc spawn` command?  

This was suggested during SoD implementation discussions.  However I think the existing name is fine.  The command forces a parent task to **spawn** the children of its (specified, or default success) outputs.

**Comment by oliver-sanders** [comment]
The old "insert" name probably makes more sense to users even if it's a less technically fitting description.

**Comment by hjoliver** [comment]
But the old command literally inserted the user-specified task.  This command will "insert" downstream dependent tasks of the user-specified one.  So I'm not convinced that "insert" is right for this.

**Comment by hjoliver** [comment]
If we really think the word "spawn" is too esoteric, we should think of a name that nicely describes how users will see this (to state the obvious).

I'll be super-explicit about how this works, so all of @cylc/core can think about the command name.

![foo](https://user-images.githubusercontent.com/2362137/93027959-b316cd80-f664-11ea-8fd0-1e8da2a40ea3.png)

```
[scheduling]
    cycling mode = integer
    initial cycle point = 1
    [[graph]]
        R1 = foo => bar & baz => waz => qux
[runtime]
    [[root]]
        script = sleep 10
    [[qux]]
        script = false
```
(Stalls with `qux.1` failed so we can play about with spawning upstream tasks).

Current best way to view the task pool alone (till we can choose n=0 datastore):
```
watch cylc dump -t <flow>
```

Here,
```
cylc spawn <flow> foo.1
``` 
... will not "insert" `foo.1`; rather it will spawn `bar.1` and `baz.1`, which will run because their prerequisites (`foo.1:succeed` only) are satisfied).

And,
```
cylc spawn <flow> bar.1
```
... will not insert `bar.1`; rather it will spawn `waz.1` in the waiting state, which will not run because it's other prerequisite (`baz.1:succeed`) is not satisfied.

IMO we can't use "insert" for the command name because it is not the targeted task that gets inserted.

And we can't use "trigger" for the same reason.  Plus, as the 2nd example above shows, the spawned downstream tasks do not necessarily get triggered.

The functionality is most similar to `cylc trigger --reflow` though:
- `cylc trigger --reflow <flow> foo.1`: insert and trigger `foo.1` and flow on from there
- `cylc spawn <flow> foo.1`:  insert children of `foo.1` and flow on from there if possible (if child prereqs are satisfied)

Here's an idea:
- `cylc trigger <flow> foo.1`:  trigger `foo.1` with no reflow
- `cylc reflow <flow> foo.1``: trigger `foo.1` with reflow (currently `cylc trigger --reflow`
- `cylc reflow --children <flow> foo.1`: spawn children of `foo.1` and continue on (reflow) if possible

**Comment by dwsutherland** [comment]
How do you "insert" a family of tasks (with inter-dependencies)? You don't want to "trigger" them all at once, and you may not have a parent task of that family to "spawn" and/or a single point of "reflow"

**Comment by hjoliver** [comment]
If a family has internal dependencies, in the SoD world you do not need to "insert" them all at once, just trigger the top task(s) in the graph and their children will flow-on from them.  You would probably do it by triggering (or "spawning the outputs of" as above) the upstream task(s) that lead into the family, but you could of course target family members if you wanted to.

**Comment by hjoliver** [comment]
(From chat session):

Maybe `cylc complete-outputs <flow> bar.1` would be clearest for users, even though it's a bit ungainly. 

It has exactly the same effect as if the affect outputs were completed naturally (i.e. by the targeted task actually running).

**Comment by dwsutherland** [comment]
>  just trigger the top task(s) in the (internal family) graph and their children will flow-on from them

That is less convenient and you might want to do it on mass to multiple workflow (that potentially contain different dependencies to the same named family)

> You would probably do it by triggering (or "spawning the outputs of" as above) the upstream task(s) that lead into the family, but you could of course target family members if you wanted to.

Also less convenient, and you may not have a preceding task (if they're the first family in the workflow).

**Comment by dwsutherland** [comment]
The only other thing I can think of is; have a different behaviour when using `cylc trigger` on a FAMILY  (i.e. workout the dependencies and satisfy the top task(s))

**Comment by hjoliver** [comment]
@dwsutherland - off topic for this issue, but never mind.

> >    just trigger the top task(s) in the (internal family) graph and their children will flow-on from them
>
> That is less convenient ...


It's not obvious to me that that's the case - can you give a specific example where the Cylc 7 way is more convenient?

In Cylc 7, if you `cylc insert FAM` then `cylc trigger FAM` that will insert all family members then trigger them all at once regardless of internal dependencies in FAM.

In Cylc 8, `cylc trigger FAM` will have the same result (all member run at once regardless of internal dependencies in FAM) but at least you don't have to manually insert them as well as trigger them.

If FAM has members f1, f2, and f3 (say); and dependencies `f1 => f2 => f3`; then in Cylc 7 you would do this to retrigger the family whilst respecting internal dependencies:

1. `cylc insert FAM`
2. `cylc trigger f1`

In Cylc 8, 
1. `cylc trigger f1`

Bosh, job done.  Seems to me Cylc 8 wins, still.
