### ISSUE TITLE
more restrictive auto-spawning?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3740]
Under SoD, parent-less and absolute-parented tasks are successively auto-spawned.
```
R1 = "start-up"
P1 = """
   start-up[^] => foo => bar
   woo => baz
        """
```   
Here, `foo.1` will be spawned by `start-up[^]`, then `foo.2` will be auto-spawned when `foo.1` drops out of the runahead pool, and so on.

And, `woo.1` will be auto-spawned at start-up, then `woo.2` will be auto-spawned when `woo.1` drops out of the runahead pool, and so on.

This (or something similar) is unavoidable because we can't feasibly spawn all (potentially infinite) such tasks at once in future cycle points. 

Currently this is done for any absolute-parented task.  But if such a task also has other normal parents we could just wait for the normal parents to spawn it:
```
R1 = "start-up"
P1 = """
   start-up[^] & other => foo  # no need to auto-spawn foo?
        """
```   

But, not sure it matters much.

**Comment by TomekTrzeciak** [comment]
Will this work in SOD?
```
R3//P1 = "foo => bar"
P1 = "bar"
```

**Comment by hjoliver** [comment]
> Will this work in SOD?

It should!  But well done, you've identified a bug :bouquet:   A one-line fix coming soon :relieved:

**Comment by hjoliver** [comment]
Pretty sure this doesn't matter
