### ISSUE TITLE
Retire "task pool" as a user-facing concept

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3748]
Post SoD users should no longer need to be aware of the scheduler "task pool" concept.  They should only need to understand active (n=0) and non-active tasks.

- Get rid of remaining CLI task pool globbing by state (`cylc trigger` already converted over to targeting abstract tasks)
- Ensure that retriggering has the same effect whether or not the target task has a proxy in the pool already.
- (anything else?)

**Comment by oliver-sanders** [comment]
Update:

* We have decided to keep globbing within the active window.
* Trigger now inserts the task if it is not present.

@hjoliver anything else or can we close this?
