### ISSUE TITLE
reflow when triggering an incomplete task?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3749]
[title updated for compat with #4343 ]

The retrigger vs reflow distinction is clear when the target task is well in front of or behind the original flow, but what about retriggering a failed task? Presumably that should result in the original flow continuing (if the retriggered task succeeds and satisfies downstream prerequisites) even if the user did not use `cylc trigger --reflow`?

**Comment by dpmatthews** [comment]
We now need to think about required outputs rather than failed tasks. If a task finished without completing all required outputs then the flow is effectively stalled at this point so I think it makes sense for retriggering to continue the original flow in this case.

**Comment by hjoliver** [comment]
Yes, and that should happen naturally since incomplete tasks will be remain in the pool and already belong to the original flow.  I'll confirm by testing on the optional outputs PR branch ...

**Comment by hjoliver** [comment]
OK it works, but it does merge in a new flow number which I think is harmless, but it's unnecessary.  I'll add a TODO on the optional outputs PR, to close this.
