### ISSUE TITLE
paths in cylc configurations

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3767]
Attempt after: #3626

At present the environment variable `$HOME` [is expanded](https://github.com/cylc/cylc-flow/blob/6168bf30ae676dcae911c1f3c0615b1704842e4f/cylc/flow/cfgspec/globalcfg.py#L853-L856) in the global configuration.

As of #3626 the centralisation of this logic has been removed to preserve the path allowing delayed expansion (e.g. in SSH/rsync commands) which saves us manually bodging it.

For now this has been done with `os.expandvars` which does the job but brings with it a lot more capability than was present before, capability which we probably don't want.

**Proposal:**

* [ ] Replace `os.path.expandvars` with `os.path.expanduser`.
  * I don't think there should be the need for environment variables in configured paths any more.
  * This would apply to all paths configured with Cylc Flow.
* [ ] Create a new parsec validator type for paths.
  * Mostly just to centrally document that `~` is allowed.
  * Consider using this datatype to return `pathlib` `Path` objects (possible future enhancement).

**Comment by hjoliver** [comment]
> I don't think there should be the need for environment variables in configured paths any more.

We should think carefully about that. E.g. for symlinked data-dir locations under cylc-run ... users might need to use vars like  `$PROJECT`

**Comment by oliver-sanders** [comment]
I don't think we supported environment variables other than `$HOME` (and perhaps `$USER`) in configured paths before though did we?

**Comment by hjoliver** [comment]
> I don't think we supported environment variables other than `$HOME` (and perhaps `$USER`) in configured paths before though did we?

I can't remember ... we should probably check by putting variables in every relevant config item, and see what happens.

**Comment by oliver-sanders** [comment]
It seems that it doesn't work in the config, however, at least for the `work directory` config does work, though whether that is purposeful or accidental?

```console
$ export FOO="$HOME/foo"
$ cylc get-global-config --sparse
[hosts]
    [[localhost]]
        work directory = $FOO/bar
$ mkdir $FOO
$ cylc run <flow>
$ tree $FOO
└── bar
    └── generic
        ├── share
        └── work
            └── 20191209T0900Z
```

**Comment by hjoliver** [comment]
> It seems that it doesn't work in the config, however, at least for the work directory config does work, though whether that is purposeful or accidental?

Are you saying that `work directory` is the only path config that currently takes (and expands) environment variables?

**Comment by oliver-sanders** [comment]
I've not tested any other variables, but it doesn't appear that any expansion is centralised so the behaviour is pre-use.

**Comment by oliver-sanders** [comment]
(reminder to self, currently assigned whilst I work out whether this is still valid. Env vars are valid in some contexts e.g. symlink-dirs, are there other contexts where they should not be allowed?)

**Comment by oliver-sanders** [comment]
Would be nice to clear paths up a bit, however, there may be use cases and not essential for 8.0.0.
