### ISSUE TITLE
polled start event bug

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3769]
If using polling to get remote task status, the `started` event will be missed if the job finishes before the first poll is done.

Prior to spawn-on-demand (e.g. 8.0a2):
- the started event is missed
- but `:start` triggers work
   - presumably we artificially update the `started` output as well when the task polls as `succeeded`

After spawn-on-demand (master):
- the started event is missed
- `:start` triggers don't work (triggering is now event-driven)

Test case:
```
[scheduling]
    [[graph]]
        R1 = "foo:start => bar"
[runtime]
    [[foo]]
        platform = maui 
        # script = "sleep 20"  # slow task will poll as started, then succeeded - GOOD
        script = "true"  # fast task will only poll as succeeded - BAD
        [[[events]]]
             started handler = echo "!!!!! STARTED"
```
With the following global config to configure  polling:
```
# ~/.cylc/flow/8.0a3.dev/flow.rc 
[platforms]
    [[maui]]
         hosts = w-nwp01.maui
         communication method = poll
         submission polling intervals = PT5S
         execution polling intervals = PT5S
```
If you run the test case,
- on master: the event  handler will not execute, and the scheduler will shut down as finished without spawning `bar`
- at 8.0a2 (with pre-platforms global and workflow config) the event handler will not execute, but `bar` will trigger

**Comment by hjoliver** [comment]
The scheduler does recognize that `foo` apparently succeeded without starting:
```
[foo.1] -Succeeded with outputs not completed:
          started
```
So presumably when the task event manager logs this message we also need to:
- artificially trigger the started event handler
- artificially complete the started output **and** spawn any children that depend on it

Artificially completing the `started` output in this way is reasonable. because a task can't finish if it did not first start.

We should also consider custom outputs too, but that's more difficult:
- need to check the `job.status` file to see if they were completed or not before the job finished
- maybe only do this if a task *polls* as succeeded (not if it self-reports via `cylc message`) to avoid routine `job.status` file checking caused by custom outputs that are not expected to be completed in every run?

**Comment by hjoliver** [comment]
(Not super urgent because this is unlikely to affect real workflows - needs both a `:start` trigger and a task that runs fast enough to beat the first poll).

(Marking as SoD-follow-up; it's also a pre-SoD bug, but the consequences are slightly worse post-SoD).

**Comment by MetRonnie** [comment]
I think I've managed to fix it, not finished yet but I thought I'd share this amusing behaviour I have inadvertently created - it now logs:
```
[foo.1] -Succeeded with outputs not completed:
          succeeded
```

**Comment by kinow** [comment]
If someone else tries to reproduce the issue, just replace "~/.cylc/flow/8.0a3.dev/flow.rc " by "~/.cylc/flow/8.0a3.dev/global.cylc" (spent some 5 minutes scratching my head to understand why it was not finding my "enterprise" platform :grimacing: )
