### ISSUE TITLE
time zone related test failures

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3794]
Since the recent isodatetime upgrade in Cylc8 two tests are failing on non-UTC time zones.

* tests/functional/cyclers/20-multidaily_local
* tests/functional/cylc-show/03-clock-triggered-non-utc-mode

We should probably consider running tests in non-UTC time zones to catch any potential issues as part of the fix.

**Comment by MetRonnie** [comment]
Running all the functional tests in a different time zone seems like a bit of a pain

**Comment by oliver-sanders** [comment]
Pain because they fail or pain because it's hard to achieve?
