### ISSUE TITLE
Swap REG for FLOW (or similar) in command help

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3817]
Blocked by #3931 

The command help metavar REG, used throughout the CLI, stands for "REGistered name" (a la `cylc register REG <path>`).

However, "REG" is annoyingly obtuse; we should change it to something more obvious like FLOW.

**Comment by oliver-sanders** [comment]
Perhaps we should hash this out along with the new cylc run|restart|hold|release semantics.

**Comment by oliver-sanders** [comment]
Another classic Cylc nomenclature debate, hopefully it doesn't turn out as bad as [this gem](https://github.com/cylc/cylc-flow/issues/600)!

We have multiple uses of the word "flow":

* Cylc **Flow** - The system for writing, running and interacting with workflows.
* A **Flow** - A workflow implemented in a `flow.cylc` file.
* A (re)**flow** - A logical "run" of a workflow.
* A **flow** - By extension of the above `myflow/run1` and `myflow/run2` are different "flows" of the "Flow" "myflow".

(Obviously the collective noun is "gaggle")

**Comment by hjoliver** [comment]
> Another classic Cylc nomenclature debate, hopefully it doesn't turn out as bad as this gem!

To be fair "REG" is pretty obscure, and it'll make even less sense once `cylc register` is no more #3893

> (Obviously the collective noun is "gaggle")

A *flood of flows*!

**Comment by oliver-sanders** [comment]
With #3931 the old `REG` meta arg becomes `ID` as it is not *just* for specifying the workflow reg but also potentially other information too i.e:

```
<flow>
<flow>//<cycle>
<flow>//<cycle>/<task>
<flow>//<cycle>/<task>/<job>
```
