### ISSUE TITLE
Take waiting tasks out of the n=0 window

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3822]
Post SoD, waiting tasks are spawned "on demand" when the first upstream output that they depend on gets completed. 

These waiting task proxies don't pose a problem in and of themselves: they are just a natural way to keep track of partially-satisfied prerequisites, and users need to see waiting tasks at those points in the graph whether or not there are task proxy objects behind them.  

However, they probably shouldn't appear in the n=0 window, otherwise we have to explain why partially satisfied tasks are "active" when wholly unsatisfied ones aren't.  That isn't entirely insane IMO (these tasks are "in the process of becoming satisfied" which is kind of active, in a sense) ... but still, it probably makes more sense to exclude them from n=0.

We might be able to do this by simply keeping these tasks in the runahead pool until they are fully satisfied...

**Comment by oliver-sanders** [comment]
Seems like a good simple solution, makes the meaning of the task pool clear.
