### ISSUE TITLE
Platforms: Remove support for `platform = `some cmd`

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#3825]
In Cylc 7 the host setting for a task could be set as a bash subshell either in the form
```bash
$(my-command)   # or
`my-command`
```
my-command```. @dpmatthews proposes dropping support for the backtick ``my-command`` syntax for platforms at Cylc 8. 

Reasons why:
- This is very, very old syntax.
- Handling of single quotes and backslash escaping inside backticks is horrible.
- Nested backticks are hard to read.
- Backticks are visually difficult to distinguish from single quotes.
- Backticks are increasingly rarely used.

Are there any objections to doing this?
(I already have a branch for this purpose.)

n.b. Trying to write about this in GH Markdown is horrible.

**Comment by hjoliver** [comment]
No objections!  Back-ticks are evil, confusing, and ugly.
