### ISSUE TITLE
Disallow nested run directories

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#3835]
Reported by @kinow 

Currently you can register and run nested flows:
```bash
$ cylc register f1 ~/suites/foo
$ cylc register f1/f2 ~/suites/foo
```

Cylc scan (and hence the UI) does not see the running `f1/f2` flow though, because it stops recursing deeper into `cylc-run/` whenever it finds a valid run directory.

Can't think of a good reason to allow this - particularly given this `cylc scan` problem and the potential for *huge* run directories. 

We should prevent this at the registration stage.

**Comment by MetRonnie** [comment]
Should we always prevent `f1/f2` or only if `f1` is valid run directory ( - and what is valid? If it has `.service` or `flow.cylc`/`suite.rc` in it?)

cc @oliver-sanders

**Comment by oliver-sanders** [comment]
The `.service` directory is created in the registration process so would be the easiest option.

**Comment by oliver-sanders** [comment]
Couple of things:

1. In-place installations (e.g. run a suite in a temp dir)
   - Should we permit these, e.g. in the work dir (for subsuites).
2. Might be a good time to remove the `cylc register --run-dir=RUNDIR` option.
    - Obsolete once we have symlink support built-in.
