### ISSUE TITLE
cli: tidy

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3893]
Having gone through the command list while working on the `rose suite-run` migration proposal, propose a quick tidy of commands and command help:

1) Hide all "internal" commands by default.
2) Drop the category system for invoking commands (i.e. the `task` in `cylc [task] message`).
3) Consider dropping the category system.
4) Replace `% cmd` code examples with `$ cmd` (because [bashism](https://en.wiktionary.org/wiki/bashism), but also [colour formatting](https://github.com/cylc/cylc-flow/pull/3680))
4) Remove the following commands in due course: (commented on #1249)
    * `check-software` - outdated and messy, setup.py ensures dependency compatibility.
    * `checkpoint` - #3891 
    * `client` - somewhat obsolete since GraphQL, remove or rename to `query` to match `subscribe`.
    * `get-directory` - will be made obsolete by #3889 
    * `ls-checkpoints` - #3891 
    * `register` - will be made obsolete by #3889 

Ping @hjoliver

**Comment by hjoliver** [comment]
Agreed on all items :+1: 

I'll remove the question label. Others can argue points if they want, but it all seems pretty uncontroversial to me.

**Comment by oliver-sanders** [comment]
Should we add `cylc nudge` to the kill list?

**Comment by hjoliver** [comment]
Yes, kill it.
