### ISSUE TITLE
cli: play|pause|stop

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3897]
Rename the existing workflow lifecycle commands to match the [rose suite-run migration proposal](https://github.com/cylc/cylc-admin/blob/master/docs/proposal-rose-suite-run.md#cli-changes) and implement the other CLI changes.

I.E. do what it says in the proposal under the following sections:

* `cylc play`
  * With the exception of the `--re-run` option - #3898
* `cylc pause`
* `cylc release`

**Comment by hjoliver** [comment]
Not sure why this didn't occur to us before, but `cylc resume` makes more sense than release, as a counterpart to `cylc pause`.

- `cylc hold` vs `cylc release` for tasks
- cylc play` vs `cylc resume` for the flow

**Comment by oliver-sanders** [comment]
`cylc play` - we can crack on with the following points (from the proposal):

* Options will look very similar to current cylc run command but with no [START_POINT] argument (already supported as an option)  (((i.e. remove the START_POINT arg)))
* Fail if the workflow has already completed (need to be able to detect this).
* Continue running the workflow if it was stopped before completion (replaces cylc restart).

**Comment by MetRonnie** [comment]
Do we want to keep an alias `run -> play` or `restart -> play`?

**Comment by oliver-sanders** [comment]
Nope, but we should add a "dead end" (see `cylc.flow.scripts.cylc`)

**Comment by MetRonnie** [comment]
What happens to warm/cold starts? Am I right in thinking the concept of warm start disappears?

**Comment by oliver-sanders** [comment]
The desire is to get rid of warm starts, however, I'm not sure that we can do that right now.

I think we should get rid of the aliases.

**Comment by MetRonnie** [comment]
Just to note down some further info Oliver sent me:
> The hold/release commands do two things, they can hold/release a flow OR tasks within a flow. These seem similar but are actually very different concepts. hold/release a flow is setting the state of the task pool. hold/release a task is adding/removing xtriggers to tasks (currently implemented a little differently).
>
>The idea is to pull the flow and task features apart.
> - play/pause (flow state)
> - hold/release (task state)

**Comment by MetRonnie** [comment]
What's the difference between
- `cylc run --warm SUITE [START_CYCLE_POINT]` and
- `cylc run SUITE --startcp=START_CYCLE_POINT`?

**Comment by hjoliver** [comment]
Yep.  In fact the command help says `--startcp` "implies `--warm`".  The term "warm start" comes from the modeling terminology for warm starting a cycling model, of course.  But in terms of Cylc and the graph, "start cycle point" probably is a better term - more generic, and descriptive of what Cylc is actually doing.  (Note also spawn-on-demand will make warm start obsolete, except perhaps as a convenience where multiple tasks have to be triggered at once to start the flow).

**Comment by oliver-sanders** [comment]
It's a much nicer interface, should we drop the `--warm` option and move the warm documentation onto the `--startcp` argument?

**Comment by MetRonnie** [comment]
Ah ok, so the concept of warm start stays but the cli option goes

**Comment by MetRonnie** [comment]
> Would also suggest rationalising the many aliases for the initial and final cycle point

Does that mean I should get rid of:
- `--ict` (icp)
- `--initial-point` (icp)
- `--until` (fcp)
- `--final-point` (fcp)
- `--start-point` (startcp)
- `--stop-point` (stopcp)

**Comment by MetRonnie** [comment]
(Although from the changelog, `--until` was only just added in 8.0a1!)

**Comment by oliver-sanders** [comment]
`--until` goes back a while, the changelog says:

> `--until=POINT` option is now an alias for `--final-cycle-point=POINT` option.

**Comment by MetRonnie** [comment]
What are some good concrete example(s) of `cylc hold` to put in the docstring, rather than `cylc hold REG TASK_GLOBS ...` which is identical to the `ARGS`?

**Comment by oliver-sanders** [comment]
> Should it be possible to hold tasks after a certain point

This is the `--after` option?

I've just noticed that the documentation for `cylc hold` and the `hold` mutation do not match. It is definitely a cycle point not a wallclock time (implemented in `cylc.flow.scheduler.Scheduler.hold_suite`).

> Also, what are some good concrete example(s) of cylc hold to put in the docstring

How about this:

```bash
# hold mytask at cycle 1234 in myflow
$ cylc hold myflow mytask.1234

# hold all tasks in cycle 1234 in myflow
$ cylc hold myflow '*.1234'

# hold all active instances of mytask in myflow
$ cylc hold myflow 'mytask.*'
```

**Comment by MetRonnie** [comment]
If a workflow has some held tasks (but is not paused), should running `cylc play` release the held tasks or do nothing?

**Comment by oliver-sanders** [comment]
Do nothing, `cylc play` shouldn't go messing with task states.

**Comment by MetRonnie** [comment]
For `cylc play`, what should happen to `--hold` and `--hold-point`/`--hold-after`? Should they be replaced by `--pause` and `--pause-point`/`--pause-after`?

Also, in line with the other aliases, should `--hold-point`/`--pause-point` change to `--holdcp`/`--pausecp`?

**Comment by MetRonnie** [comment]
> If a workflow has some held tasks (but not all, i.e. it is not paused), should running `cylc play` release the held tasks or do nothing?

Also, if a workflow is paused, what should `cylc release task.n` do? Should it go ahead and release the task(s)? If so, wouldn't that imply the task pool is not held anymore, therefore the workflow is no longer paused?

**Comment by oliver-sanders** [comment]
> if a workflow is paused, what should cylc release task.n do? Should it go ahead and release the task(s)?

It should release the task which shouldn't run because the scheduler is "held".

So the behaviour for the logical combinations of play/pause and hold/release would be:

```bash
$ cylc install x

# start a Scheduler pre-paused
# (a.1 won't run because Scheduler paused)
$ cylc play --pause x

# hold task a.1
# (a.1 won't run because Scheduler paused and task held)
$ cylc hold x a.1

# un-pause the Scheduler
# (a.1 won't run because task held)
$ cylc play x

# release task a.1
# (a.1 will run)
$ cylc release x a.1
```

However, as you've noticed, that's not how things work at the moment. For now it's a good start just to separate the interfaces, we can fix the internals later, however, if you fancy taking a deeper dive it should be fairly straight forward to change the behaviour of the `task_pool` hold mechanism.

The tasks are actually submitted from somewhere in the `Scheduler`, that's the bit you will need to skip if `Scheduler.pool.held is True`. You may need to do something to get the workflow state set correctly, not sure how that gets done nowadays.

**Comment by MetRonnie** [comment]
Another thing: I suppose `flow.cylc[scheduling]hold after cycle point` will have to be depracted in favour of `pause after cycle point`

**Comment by hjoliver** [comment]
> However, as you've noticed, that's not how things work at the moment. 

Yeah, it's all done by holding tasks at the moment, needs to be fixed.

**Comment by MetRonnie** [comment]
Question about final cycle point: say you have the workflow
```
[scheduling]
    cycling mode = integer
    final cycle point = 5
    [[graph]]
        P1 = foo
```
Then you run:
1. ```shell
    $ cylc run temp3 -n --fcp=2
    ...
    INFO - Initial point: 1
    INFO - Final point: 2
    ...
    INFO - [foo.1] -triggered off []
    INFO - [foo.2] -triggered off []
    ...
    INFO - Suite shutting down - AUTOMATIC
    ```

2. ```shell
    $ cylc restart temp3 -n --ignore-final-cycle-point
    INFO - LOADING suite parameters
    ...
    INFO - Initial point: 1
    INFO - Final point: 5
    INFO - Suite shutting down - AUTOMATIC
    INFO - DONE
    ```

In (2), nothing runs. Is this meant to happen?

---

P.S., in (2), in the snipped bit (`...`), I get this:
```
INFO - LOADING task action timers
INFO - + foo.1 poll_timer
WARNING - foo.1: task not found, skip
INFO - + foo.1 ['try_timers', 'submission-retry']
WARNING - foo.1: task not found, skip
INFO - + foo.1 ['try_timers', 'execution-retry']
WARNING - foo.1: task not found, skip
INFO - + foo.2 poll_timer
WARNING - foo.2: task not found, skip
INFO - + foo.2 ['try_timers', 'submission-retry']
WARNING - foo.2: task not found, skip
INFO - + foo.2 ['try_timers', 'execution-retry']
WARNING - foo.2: task not found, skip
```
Why so many warnings?

**Comment by oliver-sanders** [comment]
In Cylc7 the workflow would pick up where it left off and continue to the configured FCP (i.e. 5). I think this is an SoD quirk perhaps caused by restarting with an empty task pool?

Think that should go up as a bug.

**Comment by MetRonnie** [comment]
Ok, as discussed in our meeting, if that's a bug it can be fixed after #4040 is merged

**Comment by hjoliver** [comment]
> In Cylc7 the workflow would pick up where it left off and continue to the configured FCP (i.e. 5). I think this is an SoD quirk perhaps caused by restarting with an empty task pool?
> 
> Think that should go up as a bug.

I'm not so sure that's a bug!  The workflow ran to completion at FCP=2.  A restart starts from the previous record state, which was already "completed", so nothing will happen.

It makes some sense to restart with an extended FCP if you haven't already run to completion, but not if you have.

Also, what if you'd already run special tasks in the last cycle(s)?  The only sensible way to do this kind of a "restart" would be to do warm start part-way through the new (extended) graph.

**Comment by oliver-sanders** [comment]
Ah sorry, miss read, I thought the flow had been stopped before the fcp. After the `cylc play` work is finished we would expect the "restart" to be rejected since the flow has already run to completion so I don't think this circumstance should be possible going forward?

**Comment by MetRonnie** [comment]
I see, the real test of whether `--fcp=ignore` works is:
```
[scheduling]
    runahead limit = P1
    cycling mode = integer
    final cycle point = 5
    [[graph]]
        P1 = foo
[runtime]
    [[foo]]
        script = """
            if [[ "$CYLC_TASK_CYCLE_POINT" == 2 ]]; then
                cylc stop temp3
            fi
        """
```
Then

1. `$ cylc play temp3 -n --fcp=3` runs to cycle point 2 and shuts down
2. `$ cylc play temp3 -n --fcp=ignore` restarts at cycle point 3 and runs to 5

**Comment by hjoliver** [comment]
> 2. $ cylc play temp3 -n --fcp=ignore restarts at cycle point 3 and runs to 5

It wouldn't stop at point 5, because you told it to ignore the fcp.

**Comment by MetRonnie** [comment]
But the `ignore` means ignore the fcp stored in the DB only, reverting to whatever is in flow.cylc?

From `cylc restart --help`:
```
  --ignore-final-cycle-point
                        Ignore the final cycle point in the suite run
                        database. If one is specified in the suite definition
                        it will be used, however.
```

**Comment by MetRonnie** [comment]
> > if a workflow is paused, what should cylc release task.n do? Should it go ahead and release the task(s)?
> 
> It should release the task which shouldn't run because the scheduler is "held".

([full comment here](https://github.com/cylc/cylc-flow/issues/3897#issuecomment-767558459))

Just to seek some further clarity on that - the idea of "`cylc pause` pauses the workflow by holding all tasks" should become "it pauses the workflow"?

**Comment by oliver-sanders** [comment]
Not sure where the "pauses the workflow by holding all tasks" quote comes from?

We would like `cylc pause` to pause the workflow but not to pause any of the tasks within it.

**Comment by MetRonnie** [comment]
> Not sure where the "pauses the workflow by holding all tasks" quote comes from?

That was my initial understanding of "pause" based on the pre-existing behaviour

**Comment by MetRonnie** [comment]
Actually, if pause does not hold tasks, how can we pause after a particular cycle point? Depending on the runahead limit, there's nothing to stop tasks running beyond the pause point if any one task still hasn't reached it
