### ISSUE TITLE
cylc play --re-run

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3898]
Better to attempt after #3897

Add a `--re-run` option to `cylc play` to enable the workflow to be rerun without being reinstalled.

See the [rose suite-run migration proposal](https://github.com/cylc/cylc-admin/blob/master/docs/proposal-rose-suite-run.md#cli-changes).

* The user would first have to invoke `cylc clean` to move the `log` dir to `log.<timestamp>` (or just move / delete it themselves).
* Then `cylc play --re-run` can be invoked.
* If `cylc play --re-run` is invoked and the `log` dir exists the command should fail.

The proposal suggests that `cylc play` should `--re-run` automatically if the `log` directory is not present, however, the explicit presence of the `--re-run` argument is probably better for clarity / safety. Adding the question label (ping @dpmatthews).

**Questions:**

* `--re-run` automatically? - **No**

**Comment by dpmatthews** [comment]
The proposal gave 2 options but I think I prefer the explicit presence of the `--re-run` argument.

**Comment by oliver-sanders** [comment]
Ditto, will remove the question label.

**Comment by oliver-sanders** [comment]
This has now become absorbed into point (3) in https://github.com/cylc/cylc-flow/issues/3887
