### ISSUE TITLE
test cylc run|restart command reinvocation

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3927]
`cylc run --host=someotherhost` should invoke `cylc run` over SSH on `someotherhost`.

This functionality is currently untested in CI and has been accidentally broken a couple of times.

Write a new functional test using the `_remote_background_shared_(tcp|poll)` test platform to ensure we don't break it again.

**Pull requests welcome!**

**Comment by wxtim** [comment]
Is this functionality I'm looking to test working right now?
