### ISSUE TITLE
templatevars: add dictionary of all templatevars

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3988]
Rose provides a dictionary containing all template variables called `ROSE_SUITE_VARIABLES`.

For example this config:

```
[jinja2:suite.rc]
ANSWER=42
```

Will result in this `ROSE_SUITE_VARIABLES` dict:

```python
ROSE_SUITE_VARIABLES = {
    'ANSWER': 42
}
```

This functionality is specific to Rose so if you override a variable on the Cylc command line it will not effect the Rose output:

```bash
# this will set ANSWER to 43, however the value in ROSE_SUITE_VARIABLES will still be 42
cylc validate -s ANSWER=43
```

This is a bit messy, however, there is a simple solution, just add this functionality into Cylc. Export a dictionary called `CYLC_TEMPLATE_VARS` or something of that ilk.

Tagged against 8.x as this is not essential for 8.0.0, however, it should be pretty quick to implement so may be done before then.

**Comment by wxtim** [comment]
Will require much more effort to test than to implement. Have assigned myself. Pretty sure that I know what I need to do.
