### ISSUE TITLE
job runners: upgrade doc examples to platforms

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3997]
Upgrade documented examples to use platforms syntax.

For example see https://github.com/cylc/cylc-flow/pull/3992#discussion_r541372392

**Pull requests welcome!**

**Comment by wxtim** [comment]
Closed by #3992

**Comment by wxtim** [comment]
Misread and closed in error.

**Comment by wxtim** [comment]
AFAIK/Can tell this is actually the only example of this in the job runner handlers. I remember converting them, so I'm not sure why this one slipped the net. <poor excuse>Perhaps because there were two examples in one docstring</poor excuse>.
