### ISSUE TITLE
Trying to ssh into localhost on restart

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4058]
**Describe the bug**

When there are orphaned task jobs on shutdown, Cylc tries to ssh into localhost as part of remote init on restart.

**Release version(s) and/or repository branch(es) affected?**

master @ d6a09baa93d386a41a7e781d9f372e1347f4d52a

**Steps to reproduce the bug**

flow.cylc:
```ini
[scheduling]
    runahead limit = P1
    cycling mode = integer
    [[graph]]
        P1 = foo:submit => bar
[runtime]
    [[foo]]
        script = sleep 20  # long running task
    [[bar]]
        script = cylc stop --now my_flow
```
Then run it:
```console
$ cylc run -n my_flow
...
WARNING - Orphaned task jobs:
	* foo.1 (running)
	* bar.1 (running)
INFO - DONE
```

Now restart:
```console
$ cylc restart -n my_flow
...
ERROR - localhost: initialisation did not complete:
	COMMAND FAILED (255): ssh -oBatchMode=yes -oConnectTimeout=10 localhost \
            env CYLC_VERSION=8.0a3.dev bash --login -c ''"'"'exec "$0" "$@"'"'"'' \
            cylc remote-init localhost '$HOME/cylc-run/my_flow'
	COMMAND STDERR: Host key verification failed.
```

**Expected behavior**

Cylc should not try to ssh into localhost.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
Reproduced (although it doesn't caused a problem if you've configure self-ssh)
