### ISSUE TITLE
install target = localhost

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4060]
At present we determine if a platform is a "remote" platform based on whether its install target is `localhost`.

This is the default, however, you can mess with it.

```ini
# global.cylc
[platforms]
    [[localhost, linux\d\d\d]]
        install target = filesystem1
    [[[cluster]]]
        install target = filesystem2
```

I think we need the following logic change:

```diff
-if platform['install target'] == 'localhost':
+if platform['install target'] == get_platform('localhost')['install target']:
```

Can tidy this away as a method or whatnot.

**Comment by MetRonnie** [comment]
Would it be a good idea to use a data class to represent a Platform rather than using dicts?

**Comment by oliver-sanders** [comment]
I don't think a dataclass would help, the result would still be Python objets which would still require deepcopy?

**Comment by MetRonnie** [comment]
But we could avoid having to set items on the fly, e.g. instead of https://github.com/cylc/cylc-flow/blob/0a2170a84665849a607e7d6494fd8accde182c89/cylc/flow/platforms.py#L420-L432

we could have
```python
class Platform:
    ...
    @property
    def install_target(self):
        if self._install_target is None:
            return self.name
        return self._install_target
```

**Comment by oliver-sanders** [comment]
That wont help with the platform name which can be a regex value e.g. `linux\d\d\d` which we have to resolve e.g. to `linux012`.
