### ISSUE TITLE
review CLI and schema docs

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4091]
A lot has changed in Cylc8, we should make a pass through the CLI help to update terminology and make sure nothing has slipped the net.

The Schema docs (used for GraphiQL and the Cylc UI) were largely transferred from the CLI help during earlier Cylc8 development and may have drifted slightly, sometimes purposefully.

Suggest updating the CLI then transferring that across to the Schema. Note that the schema docs are interpreted as markdown.

**Comment by oliver-sanders** [comment]
https://github.com/cylc/cylc-flow/issues/3340

**Comment by wxtim** [comment]
This should have been closed by #4473
