### ISSUE TITLE
[docker] Investigate reducing the size used for running tests with Docker

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#4104]
**Describe exactly what you would like to see in an upcoming release**

Via Twitter found an interesting [post from Uwe](https://uwekorn.com/2021/03/01/deploying-conda-environments-in-docker-how-to-do-it-right.html) (Conda & other OSS projects maintainer) about how he reduced the disk space used for a container used to run a ML model application (TL;DR from 4GB down to ~200MB).

There might be a few things he's doing that we could adapt to our Docker containers, producing smaller images, and also speeding up test executions. I don't have the images locally as my SSD doesn't have a lot of disk space, but from what I recall we were using at least 1GB, at least when the pull request for Docker was under review (I remember `docker system prune`'ing it to make space for other things).

**Additional context**

https://uwekorn.com/2021/03/01/deploying-conda-environments-in-docker-how-to-do-it-right.html

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
I investigated an approach for building Docker images with Conda where:

* You use two images, one with Conda (or Mamba for faster builds) installed, one without.
* Install the desired environment in the first image.
* Transfer the environment from to the second image using `conda pack`.
* Skip the `conda activate` step by plonking the Conda env into `$PATH` ([appropriate for most but not all environments](https://github.com/cylc/cylc-flow/issues/3704#issuecomment-897442365)).
* Dispose of the first image.

This avoids actually installing Conda on the image you want to use and reduces the environment to the contents of the `conda pack`'ed archive.

There is a similar approach (doesn't use conda-pack, can't use environment files, requires conda activate) in a blog post somewhere, will try to dig it out.
