### ISSUE TITLE
configurable source directories

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4107]
We would like the UI to be able to display uninstalled source workflows so that they can be installed and run without leaving the UI.

**1) Configuration**

Since users may have established source repositories (e.g. `~/roses`) this should be configurable, proposal:

```ini
# global.cylc
[install]
     source dirs = ~/cylc-src, ~/roses, /some/shared/repo, ...
```

**2) Configuration Default**

Proposing that the default should be `~/cylc-src` as an analogue to `~/cylc-run`.

**3) Cylc Install Default**

The first item in this list could be used by `cylc install` as the "default" source location.

Propose using the first argument of `cylc install` to specify the name of a flow within `source dirs[0]` to install i.e:

```ini
# global.cylc
[install]
     source dirs = ~/cylc-src, ~/roses
```

```console
$ cd "$HOME"
$ cylc install foo
INSTALLED foo from ~/cylc-src/foo -> ~/cylc-run/foo/run1
```

As a more convenient alternative to:

```console
$ cylc install -C ~/cylc-src/foo
# OR
$ cd ~/cylc-src/foo; cylc install
```

> **Note:** `cylc install` currently has an argument, however, it is unused in the code.

**Questions:**

* [x] 1 ok?
* [x] 2 ok?
* [x] 3 ok?

**Comment by hjoliver** [comment]
(Ticked the boxes - if others disagree we can discuss, but it seems straightforwardly sensible to me!)

**Comment by oliver-sanders** [comment]
Ran by Dave, removed the question label.

**Comment by TomekTrzeciak** [comment]
> The first item in this list could be used by cylc install as the "default" source location.
>
> Propose using the first argument of cylc install to specify the name of a flow within source dirs[0] to install

Why not use source dirs as a search path and check all of them for a given install name?

**Comment by oliver-sanders** [comment]
Could do, more potential for users to trip up, however, the `install` command prints the location it is installing from so any mistake can be quickly caught.

**Comment by MetRonnie** [comment]
Should the PWD take precedence over `global.cylc[install]source dirs`?

**Comment by oliver-sanders** [comment]
If no argument is provided it should use `$PWD`, if an argument is provided it should use `global.cylc[install]source dirs`.

**Comment by MetRonnie** [comment]
In that case, the first example in the `cylc install` help will need changing https://github.com/cylc/cylc-flow/blob/e826bc58362c1173ca1f026712b6cd8f4da9a7ae/cylc/flow/scripts/install.py#L38-L43

**Comment by oliver-sanders** [comment]
Yes it will, however, this example is incorrect as the first argument is not currently used in the code.

**Comment by MetRonnie** [comment]
In the functional tests, there's a test for `cylc install flow.cylc` where flow.cylc is in `$PWD`. This doesn't correspond to any of the usage examples in install.py's docstring. I presume `cylc install flow.cylc` is going away?

**Comment by oliver-sanders** [comment]
The argument is unused in the code so this is actually just testing `cylc install` with no arguments:

https://github.com/cylc/cylc-flow/blob/793d251cf85ad090bf964155aa96048972a79a30/cylc/flow/scripts/install.py#L158

I think this usage was copied from other commands (e.g. validate), no need to keep it.
