### ISSUE TITLE
cylc review: cylc8 support

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4113]
> **Context:** Cylc Review (formerly Rose Bush) is the old Cylc7 web app used for monitoring workflows and viewing log output. This is not related to the old GTK Cylc GUI which is a whole other thing. Cylc Review is a simple static HTML5/CSS3 web UI, the static files can be found in the cylc-flow source code. The server is Python2 / cherrypy, it gets workflow information from the database and file system.

There have been some changes in Cylc8 which will cause issues for Cylc Review for example:

* Database changes (host has been renamed platform)
* suite.rc => flow.cylc

We would quite like to keep Cylc Review going in the short term to provide a Cylc7/Cylc8 compatible monitoring tool and ease the transition to Cylc8 whilst we continue to develop the UI. Hopefully this won't be too much work, just need to detect the Cylc version and act accordingly.

**Comment by wxtim** [comment]
I think (still working on proper testing) that I have managed to fix:
- The task view.
- Get  `flow.cylc` and `flow.cylc` processed from the files drop-down.

Which other files to I want to make available?
flow-config/<datetime>-run.cylc
install/<datetime>-install.log

rose files?

**Comment by oliver-sanders** [comment]
Good enough to just preserve the pre-existing functionality. I can't remember if `cylc review` shows the `rose-suite-run.log` file, if so that is equivalent to the new install log thing.

**Comment by wxtim** [comment]
Closed. Further enhancements for cylc review should be a new issue.
