### ISSUE TITLE
ssh client: add async_request method

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4129]
Follow on from #4119

> **Note:** Low priority.

Add an `async_request` method to the SSH client to match the ZMQ client.

```python
async def async_request(self, ...)
    proc = remote_cylc_cmd(...)
    while True:
        if proc.poll():
            break
        await asyncio.sleep(self.SLEEP_INTERVAL)
    ...
```

This can be used in `cylc scan` via the `get_client` abstraction to support the SSH interface in this command.

**Pull requests welcome!**

**Comment by datamel** [comment]
Unfortunately UID has caused this to be a breaking change which needs fixing before 8.0rc1. Updating the milestone.

**Comment by oliver-sanders** [comment]
This has now become a bug, my bad.
