### ISSUE TITLE
config: consider making sparse the default

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4143]
By default `cylc config` shows us all of the default values (mostly blank) which isn't especially helpful for most uses.

Since the command is changing anyway (`get-config`, `get-site-config` -> `config`) now would be a good opportunity to rethink this.

**Question:** Should we make `--sparse` the default and add a `--defaults` option (or something like that).

**Comment by hjoliver** [comment]
I vote :+1:

**Comment by oliver-sanders** [comment]
Ditto.
