### ISSUE TITLE
cylc wrapper: arbitrary environment names

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4165]
Currently the `cylc` wrapper requires virtual envs to be named as the cylc-flow version, so that users can continue to use `$CYLC_VERSION` Cylc 7 style.

Setting `CYLC_VERSION=my-env-name` doesn't work, because `CYLC_VERSION` is set to `cylc.flow.__version__` in job scripts, so that's what the wrapper sees for job-invoked commands.

This means we can't have multiple installs at the same release version, which isn't ideal because we might want to mix-and-match component versions within the full package, or have different plugins installed in different envs.

We should make the wrapper work with arbitrary environment names.  Probably requires a new variable `CYLC_VIRTUAL_ENV` or similar, that gets written to jobs scripts in addition to `CYLC_VERSION`.

**Comment by hjoliver** [comment]
Meeting: agreed we need this. Probably need to use a new variable in addition to `CYLC_VERSION` .. .e.g.  `CYLC_ENVIRONMENT_NAME`, to allow fully arbitrary names.  Also consider `CYLC_ENVIRONMENT_TYPE` (e.g. "conda", "conda-pack", ...) so we don't have to figure out what the environment is and hence how to activate it.

**Comment by oliver-sanders** [comment]
Clarification.

After this change `CYLC_VERSION` becomes a user-facing feature allowing users to conveniently select an environment without having to learn the env naming pattern.

### input(CYLC_VERSION)

We derive `CYLC_ENV_NAME` from `CYLC_VERSION` and export it.

### input(CYLC_ENV_NAME)

We activate `$CYLC_ENV_NAME`

### input(CYLC_ENV_NAME, CYLC_VERSION)

We activate `$CYLC_ENV_NAME`

**Comment by oliver-sanders** [comment]
(closed by #4367)
