### ISSUE TITLE
Platforms not selected from host on Cycle > 1

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#4167]
**Describe the bug**
Running a workflow such as 
```ini
[scheduler]
    UTC mode = true

[scheduling]
    initial cycle point = 2013
    final cycle point = 2015
    [[graph]]
        P1Y = my_task

[runtime]
    [[my_task]]
        script = echo "HOSTNAME: ${HOSTNAME}"
        # platform = testplat
        [[[remote]]]
            host = testplat
```

Only Cycle 1 runs correctly on `testplat`, subsequent cycles run ``my_task`` on localhost.

Where global.cylc
```ini
[platforms]
    [[testplat]]
        hosts = testplat
        ssh command = ssh -oBatchMode=yes -oConnectTimeout=10 -q
        retrieve job logs = true

```

**Expected behavior**
Each cycle should run on the same remote platform.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Could you add your global configuration for the `testplat` platform.
