### ISSUE TITLE
Fix install examples

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4186]
Ref https://github.com/cylc/cylc-flow/pull/4161#issuecomment-814981966

**Comment by MetRonnie** [comment]
[From the linked comment]

I think this example is broken

https://github.com/cylc/cylc-flow/blob/75c403f77a2ddef6f24eb2045fa4058a07cbd75d/cylc/flow/scripts/install.py#L59-L61

`cylc install -C bunny/rabbit` would install it as `rabbit` with run dir `~/cylc-run/rabbit/run1`

(The example was already broken to begin with)

Also, the next one

https://github.com/cylc/cylc-flow/blob/75c403f77a2ddef6f24eb2045fa4058a07cbd75d/cylc/flow/scripts/install.py#L63-L65

I think it should be `Install $PWD/cats/flow.cylc as "cats", if $PWD is ~/cats, overriding...`
