### ISSUE TITLE
cylc config --sparse: item not found

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4187]
`cylc config --sparse -i ITEM` aborts with an error if a legal `ITEM` is not explicitly-set: 

```console
$ cylc config -i 'task mail'           
from = 
to = 

$ cylc config -i 'task mail' --sparse 
ItemNotFoundError: item not found: task mail
```

**Question:** should this return:
- error status - `ITEM` not found in sparse config
- success status but no result - `ITEM` legal but not set

IMO, the latter is more sensible.

**Comment by oliver-sanders** [comment]
Note `--sparse` is now the default, complemented by `--defaults`.

**Comment by hjoliver** [comment]
(note: we do get an error if requesting a section)

**Comment by hjoliver** [comment]
Check the item exists in the spec.  Fail hard, but make the error message very clear as to what it means.

**Comment by hjoliver** [comment]
(Will help users upgrade from C7)

**Comment by wxtim** [comment]
> (note: we do get an error if requesting a section)

Yes.
