### ISSUE TITLE
review: failed jobs from cylc 8 workflows not showing

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4207]
Failed jobs in Cylc 8 workflows are not appearing in the "task jobs list" in Cylc review. Perhaps an unhandled DB change.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
You can see the job files by changing the URL, on those pages the job status appears correctly so this seems to be limited to the task jobs listing.

**Comment by wxtim** [comment]
@oliver-sanders I cannot replicate this with my trial workflow:
```ini
[scheduling]
    initial cycle point = 1100
    [[dependencies]]
        P1Y = Quokka & Quoll:fail => Numbat => Wambenger

[runtime]
    [[MARSUPIALS]]
        script="""
            sleep 10
            echo "${CYLC_TASK_NAME} has slept for 10 seconds"
            echo "${CYLC_TASK_NAME} hasn't really failed, just testing stderr" >&2
        """

    [[Quokka]]
        inherit=MARSUPIALS
        platform = exvcylcdev01
    [[Numbat]]
        inherit=MARSUPIALS
    [[Wambenger]]
        inherit=MARSUPIALS
    [[Quoll]]
        inherit = MARSUPIALS
        script = false
```

**Comment by wxtim** [comment]
@oliver-sanders  - has Mike come across this again?

**Comment by wxtim** [comment]
Added blocked because we've had no further report of this problem.

**Comment by wxtim** [comment]
No-one seems able to reproduce....
