### ISSUE TITLE
config: handle error on config (re)load

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4216]
* A `ParsecError` raised in `cylc.flow.config` should be an "expected error" that gets formatted nicely for the user.
* A `ParsecError` raised during workflow runtime is an "unexpected error" (i.e. bug) that should be reported and fixed.

Additionally, a `ParsecError` (or `CylcError`) raised during config reload will cause the scheduler to crash. This is a change in behaviour for those moving from Rose 2019 as `rose suite-run --reload` invoked `cylc validate --strict` before attempting reload.

Suggest:

* The scheduler should not die on config errors at reload.
* `ParsecError` should be handled differently at config-time as at run-time.

One approach for separating config-time errors is to add a flag on the exception:

```python
try:
    self.cfg = WorkflowConfig(...)
except ParsecError as exc:
    exc.config_time_error = True
    raise
```

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
> A `ParsecError` raised during workflow runtime is an "expected error" (i.e. bug)

Did you mean "unexpected error"?

Regardless, I don't think we should be logging traceback for `ParsecError`s, as the traceback is irrelevant to the user. They just need to know what config item is illegal

**Comment by oliver-sanders** [comment]
Yes.

If the `ParsecError` occurs at runtime then we do need the traceback because:

* This error should not be possible, we need to know where it is coming from.
* Users may report scary traceback but will treat error messages as their own problem.

**Comment by MetRonnie** [comment]
Why should it not be possible? What if a user runs a workflow with `bad setting = P1` - they will get an `IllegalItemError`

**Comment by oliver-sanders** [comment]
Such errors should *only* surface in `cylc.flow.config` when the configuration is loaded, they should not be able to occur whilst the workflow is running *after* the configuration has been loaded.

**Comment by MetRonnie** [comment]
Ah ok, so the workflow config should be loaded before the scheduler starts, instead of in `Scheduler.configure()`?

**Comment by oliver-sanders** [comment]
That would be nice but isn't really possible ATM (see also reloads which *must* happen whilst the scheduler is running), this issue suggests catching and handling errors raised from these config loads.

**Comment by oliver-sanders** [comment]
> *Aside*
>
> Long term it would be nice to move to an interface more like `Scheduler(config)` than `Scheduler(reg)`
> this would help with the transition to Python API and running workflows from in-memory configs
> rather than requiring the flow to be configured on the filesystem.

**Comment by MetRonnie** [comment]
@oliver-sanders I'm a little confused - how can we get a `ParsecError` other than during loading of config?

**Comment by MetRonnie** [comment]
Wait so if a user makes a syntax mistake and reloads, what is supposed to happen? I would have thought:
- log a single line warning
- don't exit/shutdown
 
Currently we
- log (at warning level) the whole traceback
- don't exit

**Comment by oliver-sanders** [comment]
> * log a single line warning
> * don't exit/shutdown

Sounds good.

If a `ParsecError` were to somehow slip outside of the reload context and get into the workflow bubbling up in another location, then we need to log the whole traceback.
