### ISSUE TITLE
symlink dirs: move into [install] section

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4219]
The `[symlink dirs]` section applies only to the `cylc install` command, propose moving it into the `[install]` section.

For reference the config tree currently looks like so:

```python
>>> from cylc.flow.cfgspec.globalcfg import SPEC
>>> print(SPEC.tree())
global.cylc
    ...
    [install]
        source dirs
    ...
    [symlink dirs]
        [<install target>]
            run
            log
            share
            share/cycle
            work
```

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
So it would be `[install][symlink dirs][<install target>]...`? Can't see any reason not to

**Comment by dpmatthews** [comment]
> The [symlink dirs] section applies only to the cylc install command

Also used by `cylc play` (as part of remote init)

**Comment by datamel** [comment]
In my mind, I think it makes sense to move `[symlink dirs]` into the install section, even though it is used by cylc play. I can see see the `install` section as a setup type section, that deals with installation of files for a workflow. Rather than being only strictly used for `cylc install`?
