### ISSUE TITLE
log version control: diff from outside the workflow source dir listed

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4220]
The `log/version/` files log changes for files that aren't in the workflow source dir.

For example if we have this directory structure:

```
myproject/
    src/
    ...
    test-workflow/
        bin/
        flow.cylc
        ...
    build/workflow/
        flow.cylc
        ...
```

And we install like so:

```console
$ cylc install -c 'myproject/test-workflow'
```

We could see uncommitted diff from `myproject/build-workflow` listed in the log files. This is the case for `git` vc, haven't tested `svn`.

The `rose-stem` pattern often sees test workflows embedded in much larger projects, listing the diff of the whole project would be over the top for Cylc purposes. It could be useful for provenance, however, Cylc doesn't capture full information about its run environment so should this be captured via other means?

**Question:**

* Should we restrict this to just show changes from within the workflow source directory? - **Yes**

**Pull requests welcome!**

**Comment by hjoliver** [comment]
> Should we restrict this to just show changes from within the workflow source directory?

IMO yes.  That's all that affects the running of the workflow in question (unless it accesses external files, which could just as well be anywhere, not just under an umbrella project source),

**Comment by oliver-sanders** [comment]
I think so too, no one's screamed, removing the question label.
