### ISSUE TITLE
Warn the user if the stop CP is never going to be used

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#4226]
**Describe exactly what you would like to see in an upcoming release**

If you have a start CP `1`, and final CP `2`, and define stop CP as `100`, your stop CP is just going to be ignored and never used. It would be helpful to users to log a warning.

```
rm -rf .service && cylc play --no-detach five --initial-cycle-point=1 --final-cycle-point=2 --stop-cycle-point=4
```

**Additional context**

From General element chat room.

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
Best place to put this check is probably in
https://github.com/cylc/cylc-flow/blob/87e22ab623ccccb48f990dd9d64357453c1c8a56/cylc/flow/scheduler.py#L1868

Side note: maybe that method should be moved into `cylc.flow.config.WorkflowConfig` where the rest of the `process_*_point` methods are? Although it could be that there is something preventing it

**Comment by oliver-sanders** [comment]
```
warning: --stop-cycle-point=<stop-cycle-point> ignored because it is after the final cycle point (<final-cycle-point>)
```
