### ISSUE TITLE
Improved control command interface.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#423]
Control commands return immediately after queuing a command request to the suite. If the command is successful the user will see the expected result via suite monitoring, but if not (e.g. a supplied task ID regex does not match in tasks in the suite) the suite log must be examined to see what happened.

One idea I've had is to generate a unique ID at the time the request is queued, report it back to the user ("command ade3af99 queued" instead of just "command queued") and then have the suite log the result against the ID.  This would allow a --wait option to make the command script wait until the result shows up, and report it, before exiting.  Would have to allow for possible log rollover during the wait time (or else use the run-db instead of the log.

**Comment by hjoliver** [comment]
[meeting] we agreed:
 *  the command ID would work, possibly with a new command to retrieve the result of a command (given the ID), plus `--wait` options for all commands.
 * some commands may be able to report failure back immediately, e.g. if a task-matching regex does not match any tasks to operate on.

**Comment by matthewrmshin** [comment]
In the proposed new web architecture, we should be able to make use of asynchronous 2-way communication to achieve the feedback functionality.

**Comment by oliver-sanders** [comment]
#3329
