### ISSUE TITLE
flake8: simplify

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4239]
The [flake8-simplify](https://github.com/MartinThoma/flake8-simplify) plugin helps you write better code (I use it in my editor for that purpose).

I think this is a useful tool which would help automate code review, here are some examples of its recommendations - https://github.com/MartinThoma/flake8-simplify#sim102

Raising this as a question as it is somewhat more verbose than plain flake8.

**Comment by hjoliver** [comment]
I'd be happy to use this.  @cylc/core - anyone disagree?

**Comment by kinow** [comment]
Keen to try it :+1:

**Comment by MetRonnie** [comment]
I'll have a go with it

**Comment by MetRonnie** [comment]
Note: to run flake8 without it you can do `flake8 --extend-ignore=SIM`

**Comment by oliver-sanders** [comment]
Yeah there were a fair few violations, I looked through the first so many and the corrections looked sensible, the sort of thing we usually haggle over in code review.

If you install flake8-simplify you should be able to use it in your text editor without any extra config (is how I run it).

**Comment by hjoliver** [comment]
I'm using it in vim now, very useful.
