### ISSUE TITLE
evaluate paths in directives relative to $HOME

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4247]
> Small Cylc7->8 regression bug.

For remote remote PBS submissions both Cylc7 & Cylc8 set:

```
#PBS -o cylc-run/<flow>/log/job/<cycle>/<task>/<NN>/job.out
#PBS -e cylc-run/<flow>/log/job/<cycle>/<task>/<NN>/job.err
```

However, for local submissions Cylc7 prepends the home directory to the out/err path:

```
#PBS -o <home>/cylc-run/<flow>/log/job/<cycle>/<task>/<NN>/job.out
#PBS -e <home>/cylc-run/<flow>/log/job/<cycle>/<task>/<NN>/job.err
```

Cylc 8 has lost this behaviour.

This applies to local submissions for all batch systems other than background & at.

> [edit]
>
> Options:
>
> 1. `cd $HOME` for job submission
> 2. `cd <job-log-dir>` and change paths accordingly
> 3. Restore Cylc 7 logic
>
> Consensus is that (1) is the cleanest option

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
The reason this is necessary, I think, is that PBS takes the job log path to be relative to the working directory where `qsub` is executed, i.e. it is not relative to `$HOME`. The relative path works for remote hosts because `ssh` puts us in the user's home directory, to do the remote `qsub`.

**Comment by hjoliver** [comment]
Presumably all the batch systems we support are the same in this respect, else remote job submissions with  relative path would fail (unless some require path relative to `$HOME` regardless of the job submission working directory, which seems unlikely).

If so, we could either cd to home dir or job log dir (with appropriate relative paths), or revert to Cylc 7 absolute path for local jobs.
