### ISSUE TITLE
GraphQL subscriptions on the same request/connection share the same ID

### ISSUE THREAD

**Issue by dwsutherland** [cylc/cylc-flow#4252]
An issue in `master` but manifests itself in cylc/cylc-ui#543 :
https://github.com/cylc/cylc-ui/pull/543#issuecomment-852549778

UI subscriptions share the same subscription/graphql handler, where each GraphiQL request creates a new handler at the UIS.. Which causes clashes on resolving data.

**Steps to reproduce the bug**
Using cylc/cylc-ui#543 branch:
- run the UI
- `cylc install workflow`
- `cylc clean workflow`
- Repeat above two steps until after an install, the workflow doesn't appear in the UI.

**Expected behavior**
UI would have a clean feed from each subscription; multiple subscriptions wouldn't interfere with each other.

**Additional context**
To show this is the issue, I put an ID;
```
            'subscription_id': uuid4(),
```

in the handlers context:
```
class SubscriptionHandler(BaseHandler, websocket.WebSocketHandler):
    def initialize(self, sub_server, resolvers):
        self.queue = Queue(100)
        self.subscription_server = sub_server
        self.resolvers = resolvers
    def select_subprotocol(self, subprotocols):
        return GRAPHQL_WS
    @websockets_authenticated
    @authorised
    def get(self, *args, **kwargs):
        # forward this call so we can authenticate/authorise it
        return websocket.WebSocketHandler.get(self, *args, **kwargs)
    @websockets_authenticated
    @authorised
    def open(self, *args, **kwargs):
        IOLoop.current().spawn_callback(self.subscription_server.handle, self,
                                        self.context)
    async def on_message(self, message):
        await self.queue.put(message)
    async def recv(self):
        return await self.queue.get()
    def recv_nowait(self):
        return self.queue.get_nowait()
    @property
    def context(self):
        wider_context = {
            'request': self.request,
            'resolvers': self.resolvers,
            'subscription_id': uuid4(),
        }
        return wider_context
```

And when I started up the UI (with it's two subscriptions), along with the two GraphiQL subscriptions:
```
.
.
.
[I 2021-06-04T17:30:40.956 JupyterHub log:189] 200 GET /hub/api/authorizations/token/[secret] (sutherlander@127.0.0.1) 43.76ms
17:30:42.218 [ConfigProxy] error: 503 GET /user/sutherlander/favicon.png socket hang up
[I 2021-06-04T17:30:42.339 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fsutherlander%2Ffavicon.png (@127.0.0.1) 118.23ms
d9d09ba3-ef7c-4479-ba2d-4cf0cacd6d9a
d9d09ba3-ef7c-4479-ba2d-4cf0cacd6d9a
15cbbf57-c8b5-4104-8155-b8228a4e5b1c
2eb00ab2-2494-4700-b442-8ace6d0fe6cc
```

from a print in in the root resolver (`cylc.flow.network.resolver`):
```
        if 'subscription_id' in info.context:
            print(info.context['subscription_id'])
```

You can see the first two are the same (the UI dashboard and gscan subscriptions share the same request)

GraphQL subscriptions need to use an object local to only it's resolvers  to store the sub_id (not use `context` which is shared with all subscriptions in the request)

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Thanks @dwsutherland !!!
