### ISSUE TITLE
Extra log files in log viewer dropdown when running multiple jobs (GUI)

### ISSUE THREAD

**Issue by GlennCreighton** [cylc/cylc-flow#4298]
**Describe the bug**
Extra log files show up in log viewer dropdown when running multiple jobs.

**Release version(s) and/or repository branch(es) affected?**
7.9.3

**Steps to reproduce the bug**
Add a file name to "extra log files".  Run the job more than once, check log viewer dropdown shows duplicates.

**Expected behavior**
Dropdown should only show each log in the "extra log files" list once.

**Screenshots**

![image](https://user-images.githubusercontent.com/30250387/125150856-89a1c380-e108-11eb-95a6-4426297de44a.png)

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

I've got a fix for this if you would like it.  Problem is on line 829 of task_job_mgr.py, solution is to add a quick check that the file is not in the list before appending, e.g. 
![image](https://user-images.githubusercontent.com/30250387/125150946-26646100-e109-11eb-9c41-6d4bf468d020.png)

**Comment by GlennCreighton** [comment]
Okay, attempted a pull request with my fix, let me know if that works!

**Comment by oliver-sanders** [comment]
closed with #4299
