### ISSUE TITLE
cylc clean needs to update runN symlink

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4323]
Say you have
```
~/cylc-run/myflow
|-- run1
|-- run2
`-- runN -> run2
```

`cylc clean myflow/run2` doesn't currently change the target of `runN` to `run1`, instead it will leave it broken.

**Pull requests welcome!**

**Comment by wxtim** [comment]
I'm working on this:
### Mini proposal:
If clean removes a directory in the form of `runN` where N=X point the link at the highest value of N lower than X.

**Comment by wxtim** [comment]
After a discussion with @dpmatthews today I've been convinced that the correct behavior is to unlink the Symlink. It is not clear how Clean should pick an alternative dir to link to, so don't.

**Comment by MetRonnie** [comment]
What reason is there not to choose the next-highest run number?

**Comment by dpmatthews** [comment]
The `runN` link is designed to make it easy to access the latest run (e.g. paths to data files). If you delete the latest run does that mean that you're happy for `runN` to point to an older run? Maybe in some cases but not others? I think removing the link is the safer option.

**Comment by MetRonnie** [comment]
Opened a question issue for it: #4369
