### ISSUE TITLE
Add "changed in version x.y.z" notes to config descriptions

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4342]
cylc-sphinx-extensions provides prominent versionchanged labels which would be nice to use in the workflow and global config docs, in order to bring attention to changes.

https://cylc.github.io/cylc-sphinx-extensions/extensions/cylc.sphinx_ext.rtd_theme_addons.html#module-cylc.sphinx_ext.rtd_theme_addons

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Yes please!

Was going to raise this on the 8.x timeframe, however, it would be good to mark any configurations which have changed between versions 7 and 8 as "changed in version 8.0.0".

**Comment by wxtim** [comment]
note to self
```rst
   .. versionchanged:: 1.2.3

      Something changed!

```

**Comment by wxtim** [comment]
This looks fairly horrible to do in practice in terms of trawling through the history. I'm going to make a PR for all the changes I can remember making, especially focusing on Cylc 8 changes. IMO the really important places to put these labels are on changes that are being made from now on.

**Comment by MetRonnie** [comment]
There is also

```rst
.. versionadded:: 8.0.0
```

which results in
> **_New in version 8.0.0._**

**Comment by wxtim** [comment]
Look at
- Your tickets tagged with config change
- https://github.com/cylc/cylc-flow/issues/3696

**Comment by hjoliver** [comment]
Meeting: move to general doc overhaul (Issue "review CLI and schema **and stuff**")

**Comment by oliver-sanders** [comment]
(I.E. It would be easiest to do this along with #4091)
