### ISSUE TITLE
Changelog always conflicts

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4356]
If someone else's PR is merged while yours is open, it's more than likely there'll be a conflict in CHANGES.md, meaning you have to merge master into your branch or rebase. This is especially a pain for long running PRs.

We could switch to the system GitLab uses: https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/ 

Every changelog entry would go in its own file and get added to CHANGES.md automatically as part of the release process. Downside is we would probably have to implement this ourselves.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Cool solution but probably more work to implement than fixing the odd conflict in the changelog.

We could reduce the conflict jitter by adopting a convention of adding new items to either the top or bottom of the list.

**Comment by hjoliver** [comment]
> We could reduce the conflict jitter by adopting a convention of adding new items to either the top or bottom of the list.

I don't think that would work, would it?

However, change log conflicts don't strike me as too much of an annoyance. If it's just the change log, it's pretty easy for reviewers to fix the conflict via GitHub UI.

**Comment by oliver-sanders** [comment]
I don't think this is sufficient a problem to justify the work. Development will calm down, one day, ...

**Comment by hjoliver** [comment]
Closing this for now.
