### ISSUE TITLE
Should `cylc clean` re-link the runN symlink to the next-highest run number?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4369]
Follow-up to #4323

Say you have
```
~/cylc-run/myflow
|-- run1
|-- run2
`-- runN -> run2
```

Currently, `cylc clean myflow/run2` will just remove `runN`. Should it instead change the target of `runN` to the next-latest run, in this case `run1`?

Discussion from #4323:

> @MetRonnie: What reason is there not to choose the next-highest run number?

> @dpmatthews: The `runN` link is designed to make it easy to access the latest run (e.g. paths to data files). If you delete the latest run does that mean that you're happy for `runN` to point to an older run? Maybe in some cases but not others? I think removing the link is the safer option.

---

Note: currently, this behaviour leaves `cylc install` broken afterwards, see #4368

**Comment by MetRonnie** [comment]
If the answer is no, perhaps we could include a cli option like `--relink` to recreate the `runN` symlink? Could be an option of `cylc clean` or `cylc install`?

**Comment by MetRonnie** [comment]
Maybe if the user is not happy for `runN` to point to an older run after deletion of the latest, they should be using named runs instead of numbered runs?

**Comment by MetRonnie** [comment]
Pinging @cylc/core

**Comment by oliver-sanders** [comment]
I agree with Dave, if you remove the latest run the `runN` link should go with it.

A subsequent installation would add a new run and restore the link.

**Comment by hjoliver** [comment]
@wxtim to double check for dangling symlink and close this.

**Comment by wxtim** [comment]
> @wxtim to double check for dangling symlink and close this.

I can confirm that dangling symlinks are removed by Cylc Clean.
