### ISSUE TITLE
abort on timeout vs abort on stalled

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4372]
Currently:
- the `abort on timeout` timer is only used if the workflow stalls
- and `abort on stalled` is a boolean switch for immediate abort on stall

Workflow timeout should probably work like a job timeout: abort the workflow if it is still running after some timeout interval.

And `abort on stalled` should have an associated timeout especially to cause a shutdown some interval after a stall occurs.

@cylc/core - do you agree?

(Noticed when implementing the new default PT1H stall timeout on #4343 )

**Comment by wxtim** [comment]
If you don't want loads of pain in the test battery `abort on stalled = True` without the new timeout should default to zero.

**Comment by hjoliver** [comment]
> If you don't want loads of pain in the test battery `abort on stalled = True` without the new timeout should default to zero.

Trouble is, we want a PT1H stall timeout for normal use.  It'd affect a lot of tests, but easy to fix (grep for "abort on stalled"...)

**Comment by hjoliver** [comment]
TODO: and these config items need doc strings in `cfgspec/globalcfg.py`

**Comment by oliver-sanders** [comment]
> Workflow timeout should probably work like a job timeout: abort the workflow if it is still running after some timeout interval.

Is there still a use case for a generic `abort on timeout`?

I guess it can be useful if jobs don't have execution time limits, it could shutdown a workflow whilst jobs are running and xtriggers are unsatisfied.

> And abort on stalled should have an associated timeout especially to cause a shutdown some interval after a stall occurs.

:+1:

**Comment by hjoliver** [comment]
#4343 now implements the above.

**Comment by hjoliver** [comment]
(Note changing `stalled timeout` to `stall timeout` (etc.) - less clunky.)

**Comment by dpmatthews** [comment]
We also have `abort on inactivity` & `inactivity`. For consistency we'll need to change  `inactivity` to  `inactivity timeout`.

**Comment by MetRonnie** [comment]
Yes, those are also included in #4343

**Comment by hjoliver** [comment]
Decision:
- get rid of the abort on stalled flag
- get rid of the "abort on handler failed" settings

**Comment by hjoliver** [comment]
@dpmatthews - review what timeout used to mean in Cylc 7

**Comment by hjoliver** [comment]
(Can be a follow on to 4343 - in which case that should not close this)

**Comment by dpmatthews** [comment]
I'm not really convinced about the need for a workflow timeout but I guess it's harmless.

I'm not sure what the new proposed event names are.  At Cylc 7 we have https://cylc.github.io/cylc-doc/7.8.8/html/appendices/suiterc-config-ref.html#cylc-events-event-handler
* I'm assuming `inactivity` stays the same
* `stalled` -> `stall` ?
* Does `timeout` change to `stall timeout`?
  * If so I assume `inactivity` -> `inactivity timeout`?
  * But do we want spaces in event names given they get passed as arguments to the handlers and are included in lists
    * e.g. `handler events = inactivity timeout, stall timeout, shutdown`

Unrelated, but I've also noticed there is an inconsistency with `[cylc][events]handlers` vs `[cylc][events]shutdown handler`. Both accept a list of commands (not really sure why) so it makes no sense for one to be plural but not the other.

**Comment by hjoliver** [comment]
> I'm not really convinced about the need for a workflow timeout but I guess it's harmless.

> I'm not really convinced about the need for a workflow timeout but I guess it's harmless.

Note from analysis of the Cylc 7 code (as posted on Element) the old `timeout` timer gets set initially at scheduler startup, and the check-timer method is then called in every main loop iteration (even if the workflow is not stalled).  That suggests the intention was an absolute timeout which perhaps later got bodged into a stall timeout. So, I wasn't really inventing a new thing here so much as making the original thing work like it says on the tin.

Yes it is harmless - you don't have to use it, and we can warn of the consequences. But it might occasionally be useful too, e.g. for the reasons we discussed in the meeting. And if you need that, you can't use `timeout cylc play` because the scheduler detaches.

I've made all the timeout-related config names consistent and unambiguous:
- workflow timeout, workflow timeout handler, abort on workflow timeout
- stall timeout, stall timeout handler, abort on stall timeout
- inactivity timeout, inactivity timeout handler, abort on inactivity timeout

I'll come back to your questions on spaces and handler vs handlers (we probably need to fix the latter - good spotting)

**Comment by hjoliver** [comment]
(and removed `abort on stall` as discussed in the meeting)

**Comment by dpmatthews** [comment]
> I'll come back to your questions on spaces and handler vs handlers (we probably need to fix the latter - good spotting)

@hjoliver Did these get addressed in your PR?

**Comment by hjoliver** [comment]
- plural handlers: :heavy_check_mark: 
- spaces: oops forgot ... I'll reopen this temporarily

**Comment by hjoliver** [comment]
@dpmatthews I've confirmed that event names with spaces are correctly passed to handlers. Close this Issue again if you agree.

```ini
[scheduler]
    [[events]]
        workflow timeout = PT5S
        inactivity timeout = PT2S
        handler events = workflow timeout, inactivity timeout
        handlers = /home/oliverh/bin/reflect %(event)s %(workflow)s
[scheduling]
    [[graph]]
        R1 = "foo"
[runtime]
    [[foo]]
        script = sleep 10
```

handler:
```bash
#!/bin/bash

for var; do
  echo "------> $var"
done
```
result:
```
...
2021-09-14T23:36:02+12:00 INFO - [foo.1] status=submitted: (received)started at 2021-09-14T23:36:02+12:00  for job(01)
        flow(a)
2021-09-14T23:36:02+12:00 INFO - [foo.1] -health check settings: execution timeout=None, polling intervals=PT15M,...
2021-09-14T23:36:04+12:00 WARNING - inactivity timer timed out after PT2S
2021-09-14T23:36:05+12:00 INFO - [('workflow-event-handler-00', 'inactivity timeout') cmd] /home/oliverh/bin/reflect
        'inactivity timeout' spaces/run3
        [('workflow-event-handler-00', 'inactivity timeout') ret_code] 0
        [('workflow-event-handler-00', 'inactivity timeout') out]
        ------> inactivity timeout
        ------> spaces/run3
2021-09-14T23:36:05+12:00 WARNING - workflow timer timed out after PT5S
2021-09-14T23:36:06+12:00 INFO - [('workflow-event-handler-00', 'workflow timeout') cmd] /home/oliverh/bin/reflect
        'workflow timeout' spaces/run3
        [('workflow-event-handler-00', 'workflow timeout') ret_code] 0
        [('workflow-event-handler-00', 'workflow timeout') out]
        ------> workflow timeout
        ------> spaces/run3
2021-09-14T23:36:12+12:00 INFO - [foo.1] status=running: (received)succeeded at 2021-09-14T23:36:12+12:00  for job(01)
...
```

**Comment by dpmatthews** [comment]
Agree
