### ISSUE TITLE
Suite UUIDs

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#439]
- https://github.com/cylc/cylc/issues/204#issuecomment-11289371
- https://github.com/cylc/cylc/pull/364#issuecomment-15887992

**Comment by hjoliver** [comment]
Suite should pass UUID to tasks, which use it in return comms.  Do with comms refactor #1872.

**Comment by matthewrmshin** [comment]
I propose to do this:
* `cylc run` creates a new UUID for a suite, and stores it in the suite runtime database.
* `cylc restart` loads the UUID from the suite runtime database.
* Writes UUID in the suite contact file.
* Writes UUID in task job environment.
* `cylc message` will only send message to suite if the UUID in task job environment is the same as the UUID in the suite contact file.
  * (This is probably good enough. A slightly more complete solution is to have `cylc message` send the UUID with the message as well, and the suite should reject the message if it is different from its current UUID.)
