### ISSUE TITLE
Allow graph line splitting on AND and OR?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4390]
Ref: https://cylc.discourse.group/t/cylc-8b2-graphparseerror/374

Currently we only join on `=>`.

I can't think of any reason not to allow this. It's simple line joining so we don't need to worry about operators embedded in complex conditional expressions.

**Comment by wxtim** [comment]
IMO Reasonable.

**Comment by hjoliver** [comment]
Decision: do it.

**Comment by wxtim** [comment]
Hoping that this will be simple and try to do it today.

**Comment by wxtim** [comment]
I'll have a go today. I'm off on holiday, so I'll either create a PR, unassign or handover.

**Comment by hjoliver** [comment]
> Does it _really_ need to be an 8.0 issue? It relaxes the rules, so it won't break anything.

Fair point, strictly it doesn't, but it is a deficiency reported by a user, and it should be easy to fix (I hope), just extend this a bit:   https://github.com/cylc/cylc-flow/blob/master/cylc/flow/graph_parser.py#L215-L234
