### ISSUE TITLE
line continuation in graph strings

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4392]
Cylc registers `=> *\n` as an implicit line break:

```
# valid
a & b =>
c
```

However this does not hold for the other graph operators `(`, `)`, `&`, `|`:

```
# invalid
a &
b => c
```

Any reason we can't extend this handling to reduce / remove the need for line break characters?

This often causes confusion, example - https://cylc.discourse.group/t/cylc-8b2-graphparseerror/374.

**Comment by dpmatthews** [comment]
Duplicate of #4390
