### ISSUE TITLE
Disallow runX as a workflow name

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4394]
As described by Bruno on Element, `cylc install --flow-name=foo/run4` results in a run directory `~/cylc-run/foo/run4/run1` which is confusing, so should probably be disallowed. This should mean disallowing names matching the regex `run\d+` <del>(I think `runN` is already disallowed, but need to check that)</del> and `runN`.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
>(I think runN is already disallowed, but need to check that).

You are allowed to install `a/b/c/runN`. It creates the folders, but somewhere down the line Cylc Flow understands that is invalid and doesn't show it on `cylc scan`.

![image](https://user-images.githubusercontent.com/304786/133022137-fb60c247-fe19-4f9f-b71d-42bd42329783.png)

```
(venv) kinow@ranma:~/cylc-src/three$ cylc install --flow-name=a/b/c/runN
INSTALLED a/b/c/runN/run1 from /home/kinow/cylc-src/three
(venv) kinow@ranma:~/cylc-src/three$ cylc scan --state=all
five
747
three/run8
a/run1
a/b/run1
one/two/three/run2
one/two/three/run4 ranma:43010
one/two/three/run3 ranma:43023
one/two/three/run1 ranma:43085
```
