### ISSUE TITLE
Disallow nested installation dirs

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4396]
Somewhat related to #4394 

We should probably not allow installation into a subdir of an installation dir (a dir that contains `_cylc-install`). E.g. if you have
```
~/cylc-run
`-- foo
    |-- _cylc-install
    `-- run1
```
then you should not be able to do `cylc install --flow-name foo/bar` because this will result in nested installation dirs:
```
~/cylc-run
`-- foo
    |-- _cylc-install
    |-- run1
    `-- bar
        |-- _cylc-install
        `-- run1
```
(here we have the installation dir `foo/bar` nested inside the installation dir `foo`.

Note that nested _run dirs_ are already disallowed. We might be able to modify this function for installation dirs: https://github.com/cylc/cylc-flow/blob/47350434cc909da4c1997cc6c51879728a0b1f45/cylc/flow/workflow_files.py#L1230

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Note that the run dirs aren't themselves nested so this isn't a problem for workflow identification. The issue is the mapping of run and src dirs provided by the `_cylc-install/source` symlink.

**Comment by hjoliver** [comment]
Decision: don't allow nesting.  Checking has to go up and down.
