### ISSUE TITLE
master currently needs typing_extensions

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4397]
`pip install .` generates a borked Cylc installation at the moment, because of a `from typing_extensions import Literal` and associated use of `Literal`.  The `typing_extensions` module is only installed via `mypy>=0.900` if you do `pip install .[all]`:

https://github.com/cylc/cylc-flow/blob/master/cylc/flow/workflow_files.py#L38

Note this is probably not worth fixing because the affected code is removed again by #4343 - just flagging it here in case we don't get that merged quickly.

If we were to fix it though, I guess the correct thing to do would be to hide the import in the `if TYPE_CHECKING` block and quote all use of `Literal` in type annotations?  - ping @MetRonnie (fingered by `git blame`!)

**Comment by MetRonnie** [comment]
Oops, VSCode can be very eager with its auto-imports when using autocompletion. But yes, I think you're right about using `if TYPE_CHECKING`
