### ISSUE TITLE
Decide on optional output syntax for finish triggers

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4402]
#4343 provisionally requires `?` on `:finish` triggers, because `:finish` is a pseudo-output that is really equivalent to `foo:succeed? | foo:fail?`.  But there's an argument that `foo:finish? => bar` looks weird/confusing.

Needs to be resolved before we release 8.0!

TBD: copy the arguments for and against to this page.

**Comment by hjoliver** [comment]
Decision: no question mark!

**Comment by oliver-sanders** [comment]
(document that `:finish` is shorthand for `:succeed? | :fail?`)
