### ISSUE TITLE
Cylc Flow ps command syntax not compatible with Alpine Linux busybox

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#4416]
**Describe the bug**

Running a workflow with Cylc Flow 8.0b2 will result in a `ps` command being executed that is not compatible with the [Busybox](https://www.busybox.net/) syntax. Something changed in the syntax from 8.0a1 as that version still worked with Alpine linux.

```bash
2021-09-17T00:20:18Z INFO - Final point: None
2021-09-17T00:20:18Z ERROR - cannot get process "args" from "ps": ps: unrecognized option: w
	BusyBox v1.33.1 () multi-call binary.
	Usage: ps [-o COL1,COL2=HEADER] [-T]
	Show list of processes
	        -o COL1,COL2=HEADER     Select columns for display
	        -T                      Show threads
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.7/site-packages/cylc/flow/scheduler.py", line 562, in start_scheduler
	    self._configure_contact()
	  File "/usr/local/lib/python3.7/site-packages/cylc/flow/scheduler.py", line 1009, in _configure_contact
	    'cannot get process "args" from "ps": %s' % err)
	RuntimeError: cannot get process "args" from "ps": ps: unrecognized option: w
	BusyBox v1.33.1 () multi-call binary.
	Usage: ps [-o COL1,COL2=HEADER] [-T]
	Show list of processes
	        -o COL1,COL2=HEADER     Select columns for display
	        -T                      Show threads
	
2021-09-17T00:20:18Z CRITICAL - Workflow shutting down - cannot get process "args" from "ps": ps: unrecognized option: w
	BusyBox v1.33.1 () multi-call binary.
	Usage: ps [-o COL1,COL2=HEADER] [-T]
	Show list of processes
	        -o COL1,COL2=HEADER     Select columns for display
	        -T                      Show threads
	
2021-09-17T00:20:19Z INFO - DONE

```

**Release version(s) and/or repository branch(es) affected?**

8.0b2.

**Steps to reproduce the bug**

- clone <https://github.com/kinow/cylc-docker/tree/>
- `cd cylc-flow/8.0b2`
- `docker build --tag kinow/cylc-flow:8.0b2-alpine .`
- `docker run --rm --name cylc-flow -t -i kinow/cylc-flow:8.0b2-alpine`

Follow instructions from the image `README.md` file, or just install and play any workflow. You should see the error message in the workflow logs.

**Expected behavior**

No errors.

**Screenshots**

**Additional context**

Not a blocker for releases, but in case there are no plans to support busybox syntax, it might be good to document that cylc is not compatible with alpine distro (and any others that use it). Debian has a slim image that's small enough too.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Here's how to reproduce it too:

On Ubuntu LTS 20.04:

```bash
kinow@ranma:~/Development/python/workspace/cylc-docker$ ps -wopid,args
    PID COMMAND
   9057 bash
   9211 /opt/sublime_text/sublime_text --multiinstance --fwdargv0 /usr/bin/subl .
   9233 /opt/sublime_text/plugin_host-3.3 9211 /opt/sublime_text/sublime_text /home/kinow/.config/sublime-text-3 /home/kinow/.cache/sublime-text-3 /ho
   9236 /opt/sublime_text/plugin_host-3.8 9211 /opt/sublime_text/sublime_text /home/kinow/.config/sublime-text-3 /home/kinow/.cache/sublime-text-3 /ho
  20209 ps -wopid,args
```

On Alpine 5.4.0-84-generic:

```bash
bash-5.1$ ps -wopid,args
ps: unrecognized option: w
BusyBox v1.33.1 () multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
	-T			Show threads
```

From Ubuntu's `ps` man:

>       -w     Wide output.  Use this option twice for unlimited width.

That option is not available for Busybox `ps`. Can't tell whether it's safe to remove it as I'm not sure whether somewhere in Cylc Flow we are using the wide output or not.

https://github.com/cylc/cylc-flow/blob/a873629faa1f6a359deb58945d8a43dd7b215298/cylc/flow/workflow_files.py#L305

**Comment by kinow** [comment]
Oh, I hacked my local file, removing the `w`, and my workflow ran with no issues. So I guess that's only so we have more information in the logs?

**Comment by hjoliver** [comment]
Good spotting. Did you figure out whether we really need `-w` or not?

**Comment by hjoliver** [comment]
Huh, I always used `ps -f` at the command line to get full process name.

**Comment by hjoliver** [comment]
We should probably use `psutil` instead of calling `ps` in a subprocess.

**Comment by kinow** [comment]
> Good spotting. Did you figure out whether we really need `-w` or not?

A [very simple workflow](https://github.com/kinow/cylc-docker/blob/master/cylc-flow/8.0b2/cylc-suites/hello/flow.cylc) is working without the `-w`. I used `sed` to remove the `-w` and it worked.

**Comment by kinow** [comment]
> We should probably use `psutil` instead of calling `ps` in a subprocess.

Oh, good point and we have the `psutil` cylc script/command.

**Comment by hjoliver** [comment]
Actually `ps` gets called over an `ssh` connection, so `psutil` is not quite so useful there.

**Comment by oliver-sanders** [comment]
I'm guessing `ps -w` ain't POSIX!

> Actually ps gets called over an ssh connection, so psutil is not quite so useful there.

We can always call psutil over an SSH connection as we already do for host selection with the `cylc psutil` command:

https://github.com/cylc/cylc-flow/blob/4aee2008c5cd2204b047dbad323cd82eb5f14cbc/cylc/flow/scripts/psutil.py

We should be able to reuse this command.

**Comment by oliver-sanders** [comment]
Here's an example using the `cylc psutil` command to retrieve information about `pid=1`:

```console
$ cylc psutil <<< '[["Process", 1]]'
```

It should return a JSON serialisation of the `psutil.Process` object.

Note the `Process` object seems to have a different serialisation method to the other `psutil` objects used so far so I had to make the following diff:

```diff
diff --git a/cylc/flow/scripts/psutil.py b/cylc/flow/scripts/psutil.py
index 0736a9dc9..c92c91ea9 100644
--- a/cylc/flow/scripts/psutil.py
+++ b/cylc/flow/scripts/psutil.py
@@ -52,6 +52,8 @@ def _psutil(metrics_json):
     for ind, item in enumerate(ret):
         if hasattr(item, '_asdict'):
             ret[ind] = item._asdict()
+        elif hasattr(item, 'as_dict'):
+            ret[ind] = item.as_dict()
 
     return ret
```

**Comment by oliver-sanders** [comment]
Taking a look to see if I can solve this along with #3965
