### ISSUE TITLE
cylc-review:  Check for Cylc 8 compatibility

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#4428]
**Describe exactly what you would like to see in an upcoming release**

Cylc (7) review should be capable of correctly showing items from Cylc 8.
See #4407 

Things which need considering:
- Relocation of `suite.rc.processed` / `flow.cylc.processed`
- Renaming of `flow.cylc.processed`

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
See also #4113

**Comment by hjoliver** [comment]
Closed by #4429
