### ISSUE TITLE
Polling can result in incorrect submit-failed

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#4431]
See problem reported on Discourse: https://cylc.discourse.group/t/how-does-cylc-read-pbs-job-exit-code/375/4

I've looked at the polling logic: https://github.com/cylc/cylc-flow/blob/7.8.7/lib/cylc/batch_sys_manager.py#L299
If I understand it correctly, we read all the job status files and then check the queue status for any jobs which haven't previously exited. This means there is a chance of inconsistency if the polling checks the job status file and finds it hasn't started yet but then, by the time it checks for the job in the queue it has already run and exited the queue. The polling would then report the job as exited without having started which results in submit-failed.
In normal circumstances this is very unlikely to happen but if we are polling a large number of jobs at the same time and/or the login node is heavily loaded it is a possibility.

I have been able to reproduce the problem (using Cylc 7.8.7) by inserted a sleep in the code in between the read of the status files and the queue status check (to mimic the read of the status files taking a long time).

To fix the problem I think we should re-read the status file for any job found to have exited the batch system to ensure we report up to date information.

**Comment by hjoliver** [comment]
- [x] fix for 7.8.x.  #4437 merged
- [  ] fix for 8.x  (presumably it will have the same problem)

**Comment by hjoliver** [comment]
Moving to an 8.0 milestone now that the 7.8.x fix is done.
