### ISSUE TITLE
workflow name environment variable

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4438]
Cylc 8 has introduced the concept of run names. This means that with regular usage `CYLC_SUITE_NAME` has changed from `<name>` to `<name>/<run>`.

Unfortunately `CYLC_SUITE_NAME` and `ROSE_SUITE_NAME` are often used within workflows to derive other properties such as file names, data labels and file hierarchies.

To help ease the transition to Cylc 8 and to prevent the myriad of enevitable bodges e.g:

```bash
cut -d '/' -f 1 <<< $CYLC_SUITE_NAME
echo $(echo $CYLC_SUITE_NAME | sed 's/\/run[0-9]//')
echo ${CYLC_SUITE_NAME/run*}
```

We could consider providing the base workflow name with a separate variable.

Proposal:

* Rename `CYLC_WORKFLOW_NAME` to `CYLC_WORKFLOW_ID` (to match universal ID and CLI use). See also:
  * #3817
  * https://github.com/cylc/cylc-admin/blob/master/docs/proposal-universal-id.md
  * https://github.com/cylc/cylc-doc/pull/224
* Add a `CYLC_WORKFLOW_NAME` variable which is the same but with the run name removed.

We could consider backporting this to Cylc 7 to assist with migration efforts.

**Comment by hjoliver** [comment]
:+1:
