### ISSUE TITLE
datastore: create job proxies at the submitted state

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4484]
"Preparing" is not supposed to be a job state - see https://cylc.github.io/cylc-admin/proposal-state-names.html#taskjob-states  Strictly speaking it's not needed as a job state because the preparing task state shows what the scheduler is doing.

However, job proxies currently get created at the transition to task state "preparing", and they contain some transient data available in the scheduler at that stage.

#4482 and https://github.com/cylc/cylc-ui/pull/824 make the UIs correctly represent the data that they're receiving (attempting to interpret the data as if the datastore implemented the proposal in this respect was causing some buggy behaviour).

We should:
- probably: delay job proxy creation in the store, or hide job proxies until they reach the submitted state.
- maybe: consider keeping the preparing job icons, as it can be argued both ways - need a quick decision as this is user facing

**Comment by oliver-sanders** [comment]
I would prefer not to add the psuedo job to the store because:

* It doesn't make sense and likely contradicts the documentation, the user cannot query or interact with the psudo job because it does not yet exist.
* It breaks universal ID for jobs.
* The task status reflects the state perfectly, there is nothing to gain by shadowing the state.
* It makes the UI needlessly complex, breaking the previously simple job state model.

**Comment by hjoliver** [comment]
Hehe, I think you're rather overstating the case!

It makes sense either way, it's just a choice. There's nothing particularly nonsensical about a job icon first appearing when the job is being prepared by the scheduler.

The user could query it too. There wouldn't be much useful information, to be sure, but we could add (e.g.) a timestamp to show how long it had been in preparation (in case of a stuck process pool), target platform(s), and maybe more.

And adding one more usually-transient job icon, even if technically redundant without extra info, would hardly "make the UI needlessly complex" or "break the previously simple job state model"!

However, I prefer Plan A myself (hence "probably" vs "maybe" in the description above). I just mentioned (regrettably :rofl: ) the other as a possibility after (re)discovering when the job proxies were being created. So OK, let's stick with Plan A.
