### ISSUE TITLE
Stop symlinking flow.cylc to suite.rc?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4500]
With the introduction of Cylc 7 backward compatibility mode, there is little point in creating a flow.cylc symlink to suite.rc. In fact, it has disadvantages:
- Users will have to delete the symlink before renaming suite.rc to flow.cylc
- Unnecessary complexity in the codebase to create/deal with the symlink

Should we get rid of the symlinking? Possible disadvantages to doing this:
- Cylc more or less works as-is
- We might have to account for the existence of the symlink in workflows run before on a previous Cylc 8 beta

However, if we don't remove symlinking, it's likely we'll be stuck with it for Cylc 8. It may be safer to remove it now in case any unforeseen consequences emerge later?

**Pull requests welcome!**

**Comment by hjoliver** [comment]
I vote to remove it.
