### ISSUE TITLE
Future of `WorkflowRuntimeServer.get_graph_raw()`

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4523]
Is this endpoint no longer used, and can it be removed?

https://github.com/cylc/cylc-flow/blob/fd37bb1d7401d8cc067835a56a15061ec59aae3b/cylc/flow/network/server.py#L338-L343

And what about `WorkflowRuntimeServer.api()`?

https://github.com/cylc/cylc-flow/blob/fd37bb1d7401d8cc067835a56a15061ec59aae3b/cylc/flow/network/server.py#L262-L267

**Comment by oliver-sanders** [comment]
This could be useful for static graph visualisation, however, we should provide that endpoint from the UIS.

So long as it isn't currently used by cylc-flow/cylc-uiserver (which it shouldn't be, then it's good for removal)

**Comment by wxtim** [comment]
> This could be useful for static graph visualisation, however, we should provide that endpoint from the UIS.
> 
> So long as it isn't currently used by cylc-flow/cylc-uiserver (which it shouldn't be, then it's good for removal)

@oliver-sanders  - Is your answer definitive enough to remove the question tag?

**Comment by oliver-sanders** [comment]
Unused but also harmless. Low priority.
