### ISSUE TITLE
Add Metadata to Platforms

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#4528]
Add a metadata section to platforms so that users can do `cylc config -i [platforms]` to get information on platforms and usage.

For example I anticipate local usage to include details of maximum memory and "CPU"'s allowed on a platform.

[Copied from conversation on Element](https://matrix.to/#/!hwZqSYihGPuhDdIzIP:matrix.org/$1637628839316531Hdgzu:matrix.org?via=matrix.org]

[I've put this under 8.x because it's not a breaking change to the config]

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Good idea, removing question label.
