### ISSUE TITLE
Consider format of version control log fille

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#4546]
in metomi/rose#2510 there is [a brief discussion](https://github.com/metomi/rose/pull/2510#discussion_r763229037) about the most appropriate way to store version control information. It seems sensible to store it in either JSON, XML (parsers available in the standard library) or the Cylc data format to make reading it easier for other programs. 

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
JSON would be easy to implement and is quite human readable. One potential disadvantage compared to Cylc (modified INI) format is readability of the `status` part

Cylc format (note the whitespace is important for the meaning, the status letters are in specific columns):
```
status = """
 M flow.cylc
A  whatever.txt
"""
```
JSON (possibility):
```json
{
    "status": [
        " M flow.cylc",
        "A whatever.txt"
    ]
}
```
Having said that, it's not looking bad

**Comment by wxtim** [comment]
It's overkill for our purposes now, but we could always do 
```
    "status": [
        " M flow.cylc",
        "A whatever.txt"
    ]
    "jsonstatus": {
        "M": ["flow.cylc"],
        "A": ["whatever.txt"]
    }
```

**Comment by MetRonnie** [comment]
I don't think we can do that - it loses the columns

> note the whitespace is important for the meaning, the status letters are in specific columns

As long as each status line is recorded, no need to process them any further

**Comment by MetRonnie** [comment]
Actually, if I can turn it to JSON in half an hour, it might be worth doing now? Would probably save effort in the long run

**Comment by wxtim** [comment]
Up to you - Don't forget that you need to update the rose interface to match
