### ISSUE TITLE
Scripts should turn colour off in non-interactive shells

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#4552]
> >  Because this command is likely to used by other scripts this should not have the colour options.
> 
> Maybe we should just turn off colour output automatically, for all commands, if a non-interactive shell is detected.

_Originally posted by @hjoliver in https://github.com/cylc/cylc-flow/pull/4550#issuecomment-989747223_

**Comment by oliver-sanders** [comment]
> Maybe we should just turn off colour output automatically, for all commands, if a non-interactive shell is detected.

We already do!

https://github.com/cylc/cylc-flow/blob/5169362f792a7b5bd2fae9f0085325df305e76c5/cylc/flow/terminal.py#L203-L207

**Comment by wxtim** [comment]
Duplication off effort. Rah!

**Comment by hjoliver** [comment]
> We already do!

But not enough ... #4562
