### ISSUE TITLE
install: can install over the top of workflows

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4594]
Install should check that it isn't messing up an existing workflow. Something has gone wrong with this logic when the existing workflow was manually installed and a run name is used.

```console
$ cd cylc-run

$ # manually install a workflow
$ mkdir two
$ touch two/flow.cylc

$ # install a workflow with the same --flow-name
$ cylc install two              
INSTALLED two/run1 from ~/cylc-src/two

$ # hmm, I now have a nested cylc-run directory
$ ls two
_cylc-install  flow.cylc  run1  runN
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
For some reason we only check for the `.service` dir, not `flow.cylc` or `suite.rc`.

https://github.com/cylc/cylc-flow/blob/ccbfdb378cfee3a36db2de4cfce0ee304cb135f3/cylc/flow/workflow_files.py#L1329-L1339

**Comment by oliver-sanders** [comment]
> Update: this is the reason

Hmm, I think we should be checking for `flow.cylc` and `suite.rc` here, I'm not sure why you would have workflow configuration files in places besides src and run dirs? @hjoliver 

Note we use multiple indicators for `cylc scan`:

https://github.com/cylc/cylc-flow/blob/590e3e33f72511ad9b8eab01b963b69771d722fe/cylc/flow/network/scan.py#L83-L110

**Comment by hjoliver** [comment]
Hmmm.   I think I forgot about "manual installation", which is not something I ever do.

(`cylc install` creates an empty `.service` directory.  Maybe it shouldn't do that, since `cylc play` does it anyway).

**Comment by MetRonnie** [comment]
Ok I will make install check for flow.cylc / suite.rc
