### ISSUE TITLE
ssh client: patch over the differences with the zmq client

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4611]
The SSH client does not inherit from the ZMQ client so their functionality has drifted a little e.g. the SSH client does not support the `timeout_handler` which can detect when workflows have stopped or restarted.

Suggest refactoring out a common base class with two concrete implementations.

Should be suitable for a later release candidate (no interface changes).

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
Was thinking the same, happy to take this on in the near future

**Comment by MetRonnie** [comment]
Is this
https://github.com/cylc/cylc-flow/blob/4ca97df6b05e3670dae42ca4d5e680912d0cfdbc/cylc/flow/network/client.py#L199-L201

specific to the ZMQ WorkflowRuntimeClient or should it be moved into the shared `timeout_handler` method?

**Comment by oliver-sanders** [comment]
That should be shared logic.

**Comment by dwsutherland** [comment]
Eventually this may be share with HTTP also (if we can ever get the CLI via hub/server working)
