### ISSUE TITLE
direct validation of flow.cylc should NOT work

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4615]
```console
$ cylc validate flow.cylc 
WorkflowFilesError: No flow.cylc or suite.rc in /home/oliverh/cylc-run/flow.cylc
```

I think we can infer that `flow.cylc` is not a workflow name, in this case!

(Without having to write `./flow.cylc`, that is).

[UPDATE] we decided that this should NOT work, so the issue will be closed by disabling the non-relative path cases that currently do work.

**Comment by oliver-sanders** [comment]
This was purposefully disabled as a consequence of the UID proposal in cylc-admin.

**Comment by hjoliver** [comment]
Agreed on hierarchical names. 

I just think would be desirable to make it work for `./flow.cylc` and `./suite.rc` - because that's a) unambiguously a local action; and b) very commonly done when working in a source dir.

**Comment by oliver-sanders** [comment]
That should be easy enough, although it may result in confusion when users try to run the command on another `.cylc` file.

**Comment by oliver-sanders** [comment]
Discussed this at our end, we don't think we should support this:

* The workflow ID refers to a directory not a file.
* These directories contain the flow.cylc but potentially other resources involved in workflow definition including Jinja2Globals/Filters, Rose configuration files, `lib/python` scripts, etc.
* So it is not meaningful/sensible to consider different `.cylc` files in the same directory (i.e. we should not support `cylc validate flow2.cylc`).
* So supporting `cylc validate flow.cylc` is inconsistent and could lead to users expecting paths to files to be valid in other situations.
* There is a shorter, simple alternative to `cylc validate flow.cylc`, it's `cylc validate .`.

**Comment by hjoliver** [comment]
OK, agreed.

In that case, we should just fix the seemingly-nonsensical error message:

```
$ cylc validate flow.cylc 
WorkflowFilesError: No flow.cylc or suite.rc in /home/oliverh/cylc-run/flow.cylc
```

(I know the word "in" makes it technically correct, but to users that'll seem like splitting hairs).

**Comment by hjoliver** [comment]
A-ha, that's already been improved!

On current master:
```
cylc val flow.cylc
UserInputError: Path does not exist: /home/oliverh/cylc-run/flow.cylc
```
Although, users might still have to think pretty hard to figure out where that comes from.

**Comment by hjoliver** [comment]
Hmm, this still needs cleaning up.

> - The workflow ID refers to a directory not a file.
> - These directories contain the flow.cylc but potentially other resources involved in workflow definition including > Jinja2Globals/Filters, Rose configuration files, lib/python scripts, etc.

Current behaviour contradicts this. 
```
$ cylc val $PWD/flow.cylc  # OK
$ cylc val ./hydro/flow.cylc  # OK
$ cylc val ./flow.cylc  # OK
```
In these cases we detect the flow file name, use that to infer it is a source path not an ID, and take the parent directory as the source path.

How is that any different from what I was proposing:
```
$ cylc val flow.cylc  # ERR
$ cylc val hydro/flow.cylc  # ERR
```

In these cases, we can detect the flow file name, use that to infer it is a source path not an ID, and take the parent directory as the source path.  The only difference is here it's a relative path. We don't allow run IDs containing `flow.cylc` so there's no possible ambiguity.

So, options are:
 1. disallow any `cylc validate` arg ending in `flow.cylc`, or
 2. allow absolute *and* relative paths ending in `flow.cylc`
    - but document this really means the parent directory of the file 

Which do you prefer?

For user convenience, 2. seems more sensible to me. Users are definitely going to attempt `cylc val flow.cylc` on a regular basis.

> - So it is not meaningful/sensible to consider different .cylc files in the same directory (i.e. we should not support cylc validate flow2.cylc).

That's not really a big deal. Just flag the non-standard file name as an error.
