### ISSUE TITLE
Triggering runahead tasks causes workflow to finish early

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4619]
To reproduce:
```
[scheduler]
    allow implicit tasks = True
[scheduling]
    cycling mode = integer
    runahead limit = P3
    [[graph]]
        P1 = foo
```
When starting this workflow the first 3 cycles spawn and `4/foo` is in the runahead state.

If you quickly trigger `4/foo` while it is in runhead (before the other tasks have finished running), it will start running and when all tasks finish, the workflow shuts down (permanently finishes) even though there is no final cycle point.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
I think I can see what's going on here.

**Comment by hjoliver** [comment]
This is related to how we auto-spawn next-instances of parentless tasks on release from runahead.
