### ISSUE TITLE
queues: hold is ignored for queued tasks

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4628]
Related to https://github.com/cylc/cylc-flow/issues/4278

### Steps to reproduce

```ini
[task parameters]                                                                    
    x = 1..20    
             
[scheduling]    
    [[queues]]    
        [[[default]]]    
            limit = 5    
    [[graph]]    
        R1 = <x>    
             
[runtime]    
    [[<x>]]  
        script = sleep 5
```

```console
$ cylc play <id>
$ # first 5 tasks will submit right away
$ cylc hold '<id>//*'
$ # all the tasks will be marked as held but will run anyway
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
I think this is precisely the same problem as #4278, just closer to the bullseye

**Comment by oliver-sanders** [comment]
> I think this is precisely the same problem as #4278, just closer to the bullseye

I think it's slightly different in that with the reported example in #4278 the tasks were dequeued *before* they were held (i.e. they were already in `Scheduler.pre_submit_tasks`), so they were already out of the queue before the held status was applied.

With this issue the held status is being applied to tasks whilst they are still in the queue and there is no need to pause the scheduler to reproduce.

**Comment by MetRonnie** [comment]
Hmm, so we need to both:
- Prevent queued tasks that get held from being de-queued, and
- Prevent de-queued tasks that get held (e.g. while the workflow is paused) from being submitted?

**Comment by oliver-sanders** [comment]
> Prevent queued tasks that get held from being de-queued

Yes

> Prevent de-queued tasks that get held (e.g. while the workflow is paused) from being submitted

Could do but I think the nicer option is to prevent tasks being dequeued whilst the scheduler is paused as this prevents dequeued tasks building up in `pre_submit_tasks`.

https://github.com/cylc/cylc-flow/pull/4620#issuecomment-1024182870

**Comment by hjoliver** [comment]
(Ouch, dunno how we missed this one earlier :grimacing: )
