### ISSUE TITLE
flow_nums: standard interface for loading/dumping

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4672]
The `flow_nums` define the flows to which a task belongs.

> **Context:**
> * Under normal conditions `flow_nums = {1}  # task belongs to the original flow`.
> * Reflow tasks differ `flow_nums = {2}  # task belongs to a new flow`.
> * When flows merge their numbers merge `flow_nums = {1, 2}  # flows 1 & 2 merged`.
> * Triggered tasks are special cases `flow_nums = {}`.

Because `flow_nums` are a set order is not guaranteed. Consequently we should take care to serialise / deserialise `flow_nums` via a standard interface to ensure they always match.

Suggest the following:

```python
def serialise(flow_nums):
   return json.dumps(sorted(flow_nums))

def unserialise(flow_num_str):
    set(json.loads(flow_num_str))

def db_serialise(flow_nums):
    return sorted(flow_nums)
```

If we don't sort the nums there is a risk that they could come out in a different order than they went in e.g. `{2, 1}` rather than `{1, 2}` which would break some internal comparison logic as well as making life harder for the UIs which would prefer one canonical form for each set.

**Pull requests welcome!**

**Comment by hjoliver** [comment]
This won't hurt, but I'm not sure it's necessary - any comparison logic ought to take account of the fact that it's comparing (unordered) sets, no?

**Comment by oliver-sanders** [comment]
> This won't hurt, but I'm not sure it's necessary - any comparison logic ought to take account of the fact that it's comparing (unordered) sets, no?

If they are in set form, yes, however, if they are serialised, no, e.g:

https://github.com/cylc/cylc-flow/pull/4581#discussion_r803682357

**Comment by hjoliver** [comment]
Ok, duh. Got it 👍🏻
