### ISSUE TITLE
tests/f: remote/01 find a better way to simulate slow rsync

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4696]
The test `tests/functional/remote/01-file-install.t` simulates a slow rsync by installing a 1GB file.

This can cause issues in testing. Find another way, perhaps we could make the `rsync` command configurable and swap it for `sleep 10`?

**Pull requests welcome!**

**Comment by wxtim** [comment]
As this is a testing issue can we push it to 8.x?
