### ISSUE TITLE
Fix stop after cycle point inconsistency with other cycle point options

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4709]
(Re-written)

The final cycle point is only stored in the DB if specified via command line option `--fcp`, whereas the stop after cycle point is stored in the DB regardless of whether it was specified via command line option or flow.cylc.

This means changing the final cycle point in flow.cylc and reinstalling + restarting will use the new point, but doing the same for stop after cycle point will ignore the new point. Why should this be the case?

**Comment by MetRonnie** [comment]
This is also the case in Cylc 7

**Comment by hjoliver** [comment]
So for "stop-after-point" the original DB value is used on restart regardless of attempts to override it?

It seems to me we should a) always store both in the DB; and b) always use a new value - if given (command line or `flow.cylc`)  - on restart

The only complication I've thought of is that changing the FCP alters the length of the graph and brings forward any parts of it defined relative to the FCP. So ideally we'd be careful with that, but it might be difficult to figure out how.

**Comment by MetRonnie** [comment]
> So for "stop-after-point" the original DB value is used on restart regardless of attempts to override it?

Yes unless you use `--stopcp=<cycle-point>` or `--stopcp=reload`, the latter will take the value from flow.cylc.

> It seems to me we should a) always store both in the DB...

Store _both_? Why?

> ...and b) always use a new value - if given (command line or flow.cylc) - on restart

But the point of storing in the DB is to use the stored value on restart (unless overridden on CLI), so then what would be the point of storing in the DB at all?

**Comment by hjoliver** [comment]
> >    It seems to me we should a) always store both in the DB...
> 
> Store both? Why?

One defines the end of the graph, one says where to stop prior to that. Why would we not store both in the DB?

> But the point of storing in the DB is to use the stored value on restart (unless overridden on CLI), so then what would be the point of storing in the DB at all?

Ah, I'm not sure if I've missed the point, or if I should have been more explicit!  

At start-up, either item can be gotten from the config or from the CLI.  At restart, the used value can be (attempted to be, at least) overridden on the CLI or via updating and reinstalling the config.  Shouldn't we be keeping track of all of that, so we can figure it out even if the user changed the value in the config, after initially using the CLI?

**Comment by MetRonnie** [comment]
> One defines the end of the graph, one says where to stop prior to that. Why would we not store both in the DB?

Oh I see, you mean store both the stopcp and the fcp (I thought you meant store both the config and cli values of stopcp)

**Comment by MetRonnie** [comment]
Actually I think this is simply a bug introduced in https://github.com/cylc/cylc-flow/commit/a1955732b976d02c4c511198cacaef0be9602610

**Comment by wxtim** [comment]
@MetRonnie - If you are happy to do so, please re-tag this as RC3.

**Comment by dpmatthews** [comment]
This is no longer a question but I need to raise a follow-up issue before we close this one.

**Comment by wxtim** [comment]
> This is no longer a question but I need to raise a follow-up issue before we close this one.

Can I suggest that we change the name of the issue when it ceases to be a question?

**Comment by hjoliver** [comment]
> > This is no longer a question but I need to raise a follow-up issue before we close this one.
> 
> Can I suggest that we change the name of the issue when it ceases to be a question?

@MetRonnie can you change the issue title appropriately? (It's not entirely clear to me how the proposed solution relates to the original question, so not changing the title myself...)
