### ISSUE TITLE
cat-log: address UserWarning

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4723]
A strange warning appears when running `cylc cat-log`:

```console
$ cylc cat-log <workflow>//<cycle>/<task> -f a
cylc/flow/__init__.py:20: UserWarning: Module cylc was already imported from None, but ~/osanders/cylc-flow is being added to sys.path
  import pkg_resources
...
<the rest of the file as normal>
```

**Pull requests welcome!**

**Comment by hjoliver** [comment]
I don't see this. Does it happen every time for you?

**Comment by oliver-sanders** [comment]
Did at the time, struggling to reproduce, likely an interaction with the wrapper script.

Assigned to me whilst I try to replicate.

**Comment by oliver-sanders** [comment]
Can't replicate, closing, will reopen if I see it again.
