### ISSUE TITLE
cylc play --set not working in combination with [scheduler][run hosts]

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#4760]
If I have `[scheduler][run hosts]` configured the following command fails:
```
$ cylc play --set='TEST="test"' test
UserInputError: Invalid template variable: test
(note string values must be quoted)
ERROR: ERROR: command terminated by signal 1: ssh -oBatchMode=yes -oConnectTimeout=8 -oStrictHostKeyChecking=no -n cylchost env CYLC_VERSION=8.0rc2.dev CYLC_ENV_NAME=cylc-8.0rc2.dev-1 bash --login -c ''"'"'exec "$0" "$@"'"'"'' cylc play '--set=TEST="test"' test --host=localhost
```
However, `cylc play --host=localhost --set='TEST="test"' test` works fine.

Note that I've confirmed this used to work correctly with Cylc 7.

**Comment by hjoliver** [comment]
Hmmm, in retrospect that result isn't too surprising, with extra shell processing involved.

**Comment by hjoliver** [comment]
Protecting the quotes works (although not ideal because the command will then fail for a local run):
```console
$ cylc play --set='TEST=\"test\"' test
```

**Comment by hjoliver** [comment]
Fix coming...
