### ISSUE TITLE
Misleading error message when run directory doesn't exist

### ISSUE THREAD

**Issue by jhaiduce** [cylc/cylc-flow#4766]
If I try to run `cylc play` on a workflow or run that doesn't exist, cylc issues an error message of the form:

```
WorkflowFilesError: runN directory at /home/user/cylc-run/nonexistent-workflow/runN is a broken or invalid symlink
```

The error message implies that the workflow exists, but the link to the run directory is broken. But this same error message is issued if the requested workflow/run doesn't exist at all.

**Comment by hjoliver** [comment]
@jhaiduce I can't reproduce this unless I explicitly target runN (which we're not supposed to do) in a non-existent run directory.

Below, if there is no workflow called "none" installed at all:

![Screenshot from 2022-03-25 10-01-44](https://user-images.githubusercontent.com/2362137/160009716-bbfe95fe-cf5a-48de-b9f1-3243404f0c48.png)

**Comment by hjoliver** [comment]
Could you describe the exact circumstance that causes this for you?

**Comment by jhaiduce** [comment]
I was explicitly targeting runN, and I had a typo in the workflow name.

**Comment by jhaiduce** [comment]
> @jhaiduce I can't reproduce this unless I explicitly target runN (which we're not supposed to do) in a non-existent run directory.

I didn't know we weren't supposed to explicitly target runN. Someone gave me instructions on the matrix.org chat a while back (maybe a year ago) and I've been doing it that way ever since.

**Comment by hjoliver** [comment]
Ah, OK.  There was a short period when the `runN` symlink was implemented but not yet used by commands to infer that lastest run automatically.

Now you can do this:
```
~/cylc-src/foo$ cylc install  # install foo/run1
~/cylc-src/foo$ cylc play foo  # play foo/run1

~/cylc-src/foo$ cylc install  # install foo/run2
~/cylc-src/foo$ cylc play foo  # play foo/run2

~/cylc-src/foo$ cylc stop foo  # stop foo/run2
~/cylc-src/foo$ cylc stop foo/run1  # (explicit run1 required here)
```

**Comment by hjoliver** [comment]
However, I'll leave this issue open. We should:
- make the error message better if you do explicitly target `runN`
- perhaps also warn that explicit use of `runN` is not necessary

**Comment by jhaiduce** [comment]
Thanks for explaining that @hjoliver. It's certainly easier not to put /runN there every time!
