### ISSUE TITLE
ERROR - Workflow shutting down - CylcError: Could not load plugin: "health check"

### ISSUE THREAD

**Issue by hiker** [cylc/cylc-flow#4796]
When following the tutorial and trying to `cylc play...`, I get:
``` 
ERROR - Workflow shutting down - CylcError: Could not load plugin: "health check"
$ cylc --version
8.0rc2
```
fresh installed on a system without previous cylc installation, using `pip install`, so I believe I'm on the latest available version.

To reproduce: install a dummy suite and to `cylc play ...`.

I could work around this issue by creating a global config file ($HOME/.cylc/flow/global.cylc) containing:
```
$ cylc config
[scheduler]
    [[main loop]]
        plugins = 
```

The documentation states that the plugin default is 'health, auto restart". Note that `cylc config` did not report any config details, so nothing else was installed.

It would appear that either the default value for plugins should be changed, or a config file installed, or the tutorial needs to be updated to indicate what needs to be done.

**Comment by hjoliver** [comment]
Thanks for the bug report!

That's strange. The core plugins (including health check) should get installed by default.  A quick `pip install cylc-flow` from PyPI, into a clean venv, works for me. I'll take a closer look tomorrow if the UK team doesn't pitch in overnight.

**Comment by hiker** [comment]
I am not using a virtual env, but I also just tried in a clean on an aws instance, and it worked fine there. Please ignore this issue for now, I will try a clean install on my laptop tomorrow and see if I can reproduce this issue. Maybe I did something ... strange :(

**Comment by hiker** [comment]
I uninstalled cylc, and re-installed first 8.0b3, which I then updated to 8.0rc2 - and I still have the problem (not with 8.0b3). I will try to debug this a bit further in the next days.

**Comment by hjoliver** [comment]
Can you try using a virtual env, to see if that gives a clue as to what's going on?

**Comment by hiker** [comment]
OK, found the problem. I had protobuf 3.17 installed in my `$HOME/.local`, and (after updating most of my systems) protobuf 3.20 in `/usr/local/...`. I am not certain why I had two :(

The full error message is actually:
```
2022-04-05T12:11:34+10:00 ERROR - Workflow shutting down - CylcError: Could not load plugin: "health check" - error message: (protobuf 3.20.0 (/usr/local/lib/python3.8/dist-packages), Requirement.parse('protobuf==3.19.*'))

```
So I uninstalled protobuf from `$HOME/.local`, downgraded my system protobuf to 3.19, and now it works. I am reasonable certain that I got warnings about some version mismatch when installing cylc (my system was quite outdated, but while chasing this I updated everything, hence protobut 3.20)/

Could I recommend to include the full error message when raising the error about plugin problems. Here what I printed in `.../cylc/flow/main_loop/__init__.py`:
```
        try:
            module = module_name.load()
        except Exception as err:
            raise CylcError(f'Could not load plugin: "{plugin_name}" - error message: {err}')       
```

Thanks a lot for your help, from my point of view this ticket can be closed, not really cylc faults.

**Comment by hjoliver** [comment]
Ah, OK, cool. I've been bitten by `.local` packages myself, in the past.

Evidently if any Python packages are installed in `.local/lib/python<version>/` that will automatically be added to `sys.path` on interpreter start-up, *but not in virtual environments* (another plus for venvs):
```console
$ /usr/local/bin/python3.9 -c "import sys; print([p for p in sys.path if '.local' in p])"
['/home/oliverh/.local/lib/python3.9/site-packages']

$ ./venv/bin/python3.9 -c "import sys; print([p for p in sys.path if '.local' in p])"
[]
```

BTW, in case you aren't aware of it, Cylc 8 is designed to work with multiple versions installed each in their own virtual env (via  `pip` and/or `conda`). You just to put the `cylc` wrapper in `$PATH` and adapt slightly to specify the location of your environments.

> Could I recommend to include the full error message when raising the error about plugin problems. 

Probably a good idea :+1: 

Also, it wouldn't hurt for us to warn about the `.local/lib` problem in the docs, even though it's not specifically a Cylc problem.







 I'll leave this issue open for the moment till we decide what to

**Comment by hjoliver** [comment]
Follow-ups: 
- https://github.com/cylc/cylc-doc/pull/453
- #4799

**Comment by hiker** [comment]
I think the `.local` wasn't the main problem - even without that it wouldn't have worked (since my system protobuf was 3.20). And at least I tend to ignore warnings if a version on my systems is newer. 

I wonder if you could change protobuf==3.19 to protobuf>=3.19. I just changed the setting in my METADATA file, and at least a 'hello world' locally worked. No idea what was changed :) And obviously not a change you want to do in rc2 ;)

Anyway, thanks a lot for your support!

**Comment by hjoliver** [comment]
(I'll need to discuss protobuf version pinning with the team)

**Comment by oliver-sanders** [comment]
Yep, I've been stung by `.local` too!

Unfortunately `pip` will happily create broken installations depending on what is already in an environment. Interesting that setuptools raised an error when trying to import a plugin for a dependency which applies to the entire project? Surely the `cylc` command should have raised this error too?

This is a large part of why we recommend Conda or Virtualenv which provide environment isolation and allow multiple versions to be installed side-by-side.

> I wonder if you could change protobuf==3.19 to protobuf>=3.19

Probably yes, however, the reason we don't is that the distributed nature of Cylc means we end up with multiple installations of Cylc over different machines, all of which need to be able to communicate with each other. Pinning protobuf in this way ensures that all Cylc installations at the same version have matching versions of protobuf.

With a bit of reading into protobuf releases we could potentially consider loosening this to `protobuf==3.*` depending on our confidence in back-compatibility between minor releases.
