### ISSUE TITLE
Don't hide true plugin errors

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4799]
Ref: https://github.com/cylc/cylc-flow/issues/4796#issuecomment-1088198773

**Comment by MetRonnie** [comment]
I.e. include the exception text in this `raise`: https://github.com/cylc/cylc-flow/blob/d14800f1fcfe4c1bf0d976b4d020513070a1b77f/cylc/flow/main_loop/__init__.py#L334-L338
