### ISSUE TITLE
`global.cylc[install]source dirs` should not accept relative paths

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4815]
`global.cylc[install]source dirs` should only accept absolute paths. It should be a global config error if you specify a relative path.

**Steps to reproduce the bug**

No error is raised for
```
[install]
    source dirs = foo/bar
```
e.g. if you validate a random workflow, the global config validation step should fail first of all, but it doesn't.

**Additional context/questions**

~When checking if a path is absolute or relative, make sure to call `cylc.flow.pathutil.expand_path()` on the path first, because env vars or tilde prefixes might be present.~ (Edit: don't do this - see [Dave's reponse](https://github.com/cylc/cylc-flow/issues/4815#issuecomment-1126017981) to the question below)
- What should happen if an env var fails to expand (i.e. non-existent env var)?

**Comment by oliver-sanders** [comment]
I'm fine with this, I'm guessing relative paths are probably evaluated relative to `$PWD` rather than `$HOME` which would be confusing as heck anyway.

**Comment by dpmatthews** [comment]
Non-existent env var: I suppose it's possible you could have a global config shared between 2 machines and you could refer to an env var only present on one of them.
Therefore probably best not to fail on non-existent env var.

This is consistent with the behaviour of `[install][symlink dirs][localhost]` - a non-existent env var in this section only causes an error when you run `cylc install` / `cylc play`.
