### ISSUE TITLE
runahead limit not being cleared

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4817]
(see also #4037)

I have seen running ("naturally triggered") tasks appear in the GUI as runahead limited. We are probably missing a data store update somewhere causing the runahead status to get out of date. These tasks were probably both internally queued and runahead limited at the same time which might possibly be the cause of the issue?

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
Investigating...

**Comment by hjoliver** [comment]
I've failed to reproduce this - do you have the workflow you saw it in?

> These tasks were probably both internally queued and runahead limited at the same time which might possibly be the cause of the issue?

Pretty sure that's not supposed to happen. Tasks should get queued only on release from runahead.

**Comment by oliver-sanders** [comment]
> do you have the workflow you saw it in?

Yes, but I don't think it will help much (it's a beast).

Here's a GUI screenshot showing a running task with a running job that is in the runahead state:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/16705946/163138307-bed8be75-0d1f-4f5a-8028-4f986860d837.png)

If I see this in the wild I will try to grab some graph GraphQL output and test in Tui to check whether the issue is definitely data store side.

> These tasks were probably both internally queued and runahead limited at the same time which might possibly be the cause of the issue?
>> Pretty sure that's not supposed to happen.

This was more of a "steps to reproduce" than a description of what happened at the implementation level. I meant that the task could be considered to be held back by both runahead limit and (likely multiple) queues, perhaps the interaction between the two could be the root cause.

**Comment by hjoliver** [comment]
(might be fixed by recent changes: #4906 ?)

**Comment by oliver-sanders** [comment]
This hasn't been seen in the wild for a while so closing this issue. Please re-open if this is spotted again.
