### ISSUE TITLE
Another User's Suite Appearing in GScan

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-flow#4825]
**Describe the bug**
Reported by a user: 
A suite of another user appeared in cylc gscan window (screenshot was provided).
Suite “u-by758” belonged to another account, no "u-by758" suite present in user's cylc-run dir. 
The user went on to try to launch the gui (gscan reported the suite status as running) and it provided them with an empty window. The suite disappeared from gscan entirely.

Verified by me:
I found the owner account of the "u-by758" suite. This suite had been run on the same cylc server, using the same CYLC_SUITE_PORT as a suite of the bug reporter.

The user went on to try to launch the gui (gscan reported the suite status as running) and it provided them with an empty window. The suite disappeared from gscan entirely.

I suspect the chances of this coincidence reoccurring are small, nonetheless, I am raising the issue for discussion. Since no passphrase was available to the reporting user I suspect that there is no security risk with regards to interactivity with the suite.

Note the associated cylc versions are as follows:
- "u-by758" was running with Cylc 7.8.11
- the conflicting suite of the reporting user was run with Cylc 7.8.7

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
Pretty sure I have seen this before. Wracking by tired brains for the details, I have a feeling it is this:

The user has a defunct contact file in their run directory that points to a host-and-port combo since taken by the other user's scheduler.

**Comment by oliver-sanders** [comment]
This is an old bug which occurs if workflows are killed (or crash) in an uncontrolled manner (e.g. loose access to the filesystem) so are unable to clean up after themselves on shutdown.

The stale contact files list host:port pairs which GScan will look up. In multi-user setups with shared workflow-servers it is likely that another workflow will be running at the same host:port which will cause GScan to list a foreign workflow in the results providing that the user is authorised to do so (this bug does not / can not sidestep Cylc 7 authorisation).

Cylc 7 has some logic to detect these "stale" contact files and remove them, however, it is not called often enough to suppress this bug instantly:

https://github.com/cylc/cylc-flow/blob/b5b971986572eb8cb2d07589a2cdf569bc4d78b9/lib/cylc/suite_srv_files_mgr.py#L117-L137

This logic persists at Cylc 8, it is now run by the network-client every time it attempts to connect to a workflow:

https://github.com/cylc/cylc-flow/blob/ef45ec02ad469a86b4bf083184c1c726bb85bfc0/cylc/flow/workflow_files.py#L450-L474

By default `cylc scan` runs off of the filesystem alone (no client connection) so these "stale" contact files will result in workflows being (erroneously) marked as running in `cylc scan` results but will *not* result in the contact files being removed.

When `cylc scan` is run with additional options (e.g. `--state=paused` or `--format=rich`) it *will* open a client so the stale contact file will be detected and removed. The UIS works in this way so a running UIS will continually check for and remove stale contact files suppressing this issue.
