### ISSUE TITLE
cylc 7: check cylc 8 safety check still works

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4835]
Double check that Cylc 7 won't mess with Cylc 8 backwards-compatible (`suite.rc`) workflows since the removal of the `flow.cylc -> suite.rc`.

In particular we don't want `cylc run` or `cylc restart` to mess with a Cylc 8 workflow.

Another command that could potentially cause issues is `cylc reg`.

**Comment by MetRonnie** [comment]
Tested:
- 🐞  `cylc run` will works on a `suite.rc` workflow that was played with Cylc 8

**Comment by MetRonnie** [comment]
Not sure why this didn't autoclose
