### ISSUE TITLE
Check Config Documentation for items over-ridden in workflow config

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#4851]
#### Checks

- [x] Ensure that in all cases where config items are present in [global.cylc](https://github.com/cylc/cylc-flow/blob/master/cylc/flow/cfgspec/globalcfg.py) and over-ridden in [flow.cylc](https://github.com/cylc/cylc-flow/blob/master/cylc/flow/cfgspec/workflow.py) that there are references in both configs to the other, but a full description in only one.
  - For example, `abort handlers`, which only has a link from global config to workflow, and not vice-versa.
- [x] Add an explanation to `[runtime][__task__][remote]` and `[job]` sections are only used to select a platform. Remove any suggestion that they over-ride other configs.

#### Decision making paper trail

From https://github.com/cylc/cylc-flow/pull/4896#discussion_r881662476:

> ... Dave and I have had a discussion about this, which we've not documented, but we have it in mind to go through all these cases: I think the agreement was that there should be:
> 
> * A headline description [both]
> * A fuller description [only one config]
> * A link to the other conifg [both]

#### Pull requests welcome!
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
I'm assuming no longer blocked as https://github.com/cylc/cylc-flow/pull/4848 has been merged

**Comment by MetRonnie** [comment]
Split off #4915 from this
