### ISSUE TITLE
Investigate how execution timeout is set

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#4859]
As noted in #3706, execution timeout gets set if you define `execution time limit` but this doesn't appear to be documented and the way it is done probably doesn't make much sense.

**Comment by oliver-sanders** [comment]
Execution time limit is a "feature" of the "job runner handler", it may or may not be implemented (though in practice it is).

For example here's the implementation for the "background" handler:

https://github.com/cylc/cylc-flow/blob/3af18367c3bf61250444293c4d439ee37e086e44/cylc/flow/job_runner_handlers/background.py#L60-L64

And here's the PBS implementation:

https://github.com/cylc/cylc-flow/blob/3af18367c3bf61250444293c4d439ee37e086e44/cylc/flow/job_runner_handlers/pbs.py#L105-L107

**Comment by dpmatthews** [comment]
Tested with this workflow:
```
[scheduling]
    [[graph]]
        R1 = neither & limit & timeout & limit-timeout
[runtime]
    [[root]]
        script = "echo Hello"
    [[neither]]
    [[limit]]
        execution time limit = PT3M
    [[timeout]]
        [[[events]]]
            execution timeout = PT2M
    [[limit-timeout]]
        execution time limit = PT3M
        [[[events]]]
            execution timeout = PT2M
```
Relevant log entries:
```
2022-05-06T16:20:26+01:00 INFO - [1/neither running job:01 flows:1] health: execution timeout=None, polling intervals=PT1H,...
2022-05-06T16:20:26+01:00 INFO - [1/timeout running job:01 flows:1] health: execution timeout=PT2M, polling intervals=PT1H,...
```
Both fine.
```
2022-05-06T16:20:26+01:00 INFO - [1/limit running job:01 flows:1] health: execution timeout=PT13M, polling intervals=PT4M,PT2M,PT7M,...
```
Undocumented behaviour.
The execution timeout is set to the `execution time limit` + the sum of the `execution time limit polling intervals` here:
https://github.com/cylc/cylc-flow/blob/3af18367c3bf61250444293c4d439ee37e086e44/cylc/flow/task_events_mgr.py#L1513
This doesn't make much sense, especially given that the last interval gets used repeatedly so the sum of the intervals doesn't really mean anything.
```
2022-05-06T16:20:26+01:00 INFO - [1/limit-timeout running job:01 flows:1] health: execution timeout=PT13M, polling intervals=PT4M,PT2M,PT7M,...
```
As above but in this case the configured timeout is being ignored which I think is a bug.

I propose we just remove the line shown above. Execution timeout will then only be set if configured and won't be affected by whether `execution time limit` is set.

**Comment by oliver-sanders** [comment]
> The execution timeout is set to the execution time limit + the sum of the execution time limit polling intervals

:fearful: 

> I propose we just remove the line shown above

Yeah, that makes sense, but why was it there in the first place?!

**Comment by hjoliver** [comment]
> > The execution timeout is set to the execution time limit + the sum of the execution time limit polling intervals
> 
> fearful
> 
> > I propose we just remove the line shown above
> 
> Yeah, that makes sense, but why was it there in the first place?!

git blames Matt for that, March 2018.  

Maybe this was the logic: 
  If you set execution timelimit polling intervals, that suggests you think the task *could* task that long to finish, so it wouldn't make sense to time out before the end of polling.  (Did "the end of polling" used to be a thing for this, as opposed to repeated use of the final interval?)

**Comment by dpmatthews** [comment]
Regardless of the original motivation, this behaviour was never documented.
As noted in https://github.com/cylc/cylc-flow/pull/4863#discussion_r869466249, if there really if a requirement to set the execution timeout based on the time limit then I don't think using the execution polling intervals is the right way to do it.
So, I think it's better to remove this behaviour.
