### ISSUE TITLE
reload: xtriggers should be preserved by reloads

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4866]
At the moment if you reload a workflow any `execution retry delays` (probably the same for submission too) get wiped.

E.G. if you run the following that `PT1H` retry delay will be ignored after the reload and the task will run right away:

```
[scheduling]                                                                      
    [[graph]]                                                                     
        R1 = """                                                                  
            flaky:fail? => reload                                                                                              
        """                                                                       
                                                                                  
[runtime]                                                                         
    [[flaky]]                                                                     
        script = """                                                              
            # REPLACE                                                             
            cylc trigger "${CYLC_WORKFLOW_ID}//${CYLC_TASK_CYCLE_POINT}/reload"
            false                                                                 
        """                                                                       
        execution retry delays = PT1H                                                             
                                                                                  
    [[reload]]                                                                    
        script = """         
            sleep 2  # let flaky/01 fail    
            sed -i 's/# REPLACE/exit 0/' "${CYLC_WORKFLOW_RUN_DIR}/flow.cylc"    
            cylc reload "${CYLC_WORKFLOW_ID}"    
        """    
```

Of course the retry delays can change as a result of the reload which is probably the reason for the current behaviour? However, maybe it can be done more nicely?

What do we think the correct behaviour is here?

**Pull requests welcome!**

**Comment by dpmatthews** [comment]
I think reload shouldn't affect any existing retry delay (i.e. an existing xtrigger) but should affect any subsequent retry delay.

**Comment by oliver-sanders** [comment]
This turns out to be a symptom of a larger issue with xtriggers and reloads.

The cause is the same as for #4984. When we perform a reload we create a new task proxy and transfer the attributes of the old onto it. For some reason, xtriggers are not currently transferred.

This is likely a Cylc 7 issue which has only been spotted at Cylc 8 because we've converted the retry mechanism to use xtriggers.

**Comment by oliver-sanders** [comment]
> This is likely a Cylc 7 issue which has only been spotted at Cylc 8 because we've converted the retry mechanism to use xtriggers.

Cannot replicate at Cylc 7 or 8 with pre-configured xtriggers e.g:

```
@mytrig => foo
```

I think it's only triggers which were dynamically added at runtime which pose an issue.
