### ISSUE TITLE
play: use infered run number in command reinvocation

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4885]
Because of the way run numbers are inferred the exact run number of the workflow does not appear in the process listing.

For example if you `cylc play foo` you see `foo` in the process listing rather than `foo/run1`:

```console
$ cylc install foo
...
INSTALLED foo/run1 from ...
$ cylc play foo
...
$ ssh <host> ps -fu $USER | grep 'cylc play'
...
... cylc play --host=localhost foo
```

This isn't a problem normally, however, when `[run hosts]` are configured this is bad for monitoring as we want to be able to list all workflows running on a server from a process listing (e.g. `ps`) - e.g. exvcylc-monitor.

Suggest that when we reinvoke the `cylc play` command we use the inferred run number so that this can be seen in a process listing on the suite server.

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
Closed by #4939?
