### ISSUE TITLE
Improve schema docs for `broadcast` mutation

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4902]
- [ ] The description for the `broadcast` mutation in `cylc.flow.network.schema` seems copied from `cylc.flow.scripts.broadcast` without much modification. It ought to be refined, seeing as how the user interacts with the mutation form in the UI is quite different from using `cylc broadcast`. At present, it is unclear how the `Clear` and `Expire` modes work in the UI.
- [ ] It is unclear how to use `settings` in the mutation form in the UI

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Moving the UI aspects of this to cylc-ui (cylc-flow defines the schema not the forms) into umbrella issue for improving UI forms: https://github.com/cylc/cylc-ui/issues/647

**Comment by oliver-sanders** [comment]
cylc-flow actually has quite good documentation for BroadcastSettings, however, this is not displaying in the UI help.

https://github.com/cylc/cylc-flow/blob/4a1ed03fcd5e1223127bfa4cd11fe29360675c20/cylc/flow/network/schema.py#L1284-L1298

**Comment by oliver-sanders** [comment]
For info, here's how the API-On-The-Fly (aotf) system works.

We define GraphQL types in cylc-flow:

```
# cylc.flow.network.schema

class CyclePoint(String):                                                          
    """An integer or date-time cyclepoint."""
```

These docstrings become the description field of the type:

```graphql
query {
  __schema {
    types {
      name
      description
    }
  }
}
```
```json
{
  "data": {
    "__schema": {
      "types": [
        {
          "name": "CyclePoint",
          "description": "An integer or date-time cyclepoint."
        },
```

(run this introspection query in GraphiQL to find out more).

The aotf system pulls these descriptions into the help icons:

![Screenshot from 2022-06-23 16-28-35](https://user-images.githubusercontent.com/16705946/175337008-8c124c15-944f-44cf-abca-2c8c8407b656.png)
