### ISSUE TITLE
final cycle point offset giving wrong result

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4908]
> **Note:** Reported with Cylc 7, replicated with Cylc 8.

In this example the final cycle point ends up on the 30th of December rather than the 31st as expected:

```ini
[scheduling]
    cycling mode        = gregorian
    initial cycle point = 20210701T0000Z
    final cycle point   = +P6M-P1D
    [[dependencies]]
        [[[R1/^]]]
            graph = start    # 2021-07-01
        [[[R1/$]]]
            graph = stop     # 2021-12-30
```

This is surprising given isodatetime yields the 31st:

```console
$ rose date 20210701T0000Z --offset '+P6M' --offset '-P1D'  # rose 2019
20211231T0000Z
$ isodatetime 20210701T0000Z --offset '+P6M' --offset '-P1D'
20211231T0000Z
```

Swap months for years and the calculation comes out correctly:

```ini
[scheduling]                                                                         
    cycling mode        = gregorian        
    initial cycle point = 2000             
    final cycle point = +P1Y-P1D           
    [[dependencies]]                       
        [[[R1/^]]]                         
            graph = start  # 2000-01-01    
        [[[R1/$]]]  
            graph = stop   # 2000-12-31  
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
I think this is an isodatetime bug:
```
>>> from metomi.isodatetime.data import *
>>> a = TimePoint(year=2021, month_of_year=7)
2021-07-01T00Z
>>> b = Duration(months=6, days=-1)
P6M-1D
>>> a + b
2021-12-30T00Z
```

**Comment by MetRonnie** [comment]
Actually in the case of `a + Duration(months=6, days=-1)` I think it might be doing
```
a - Duration(days=1) + Duration(months=6)
```
which would explain the answer of `2021-12-30`

**Comment by oliver-sanders** [comment]
> But surely in isodatetime
> ...
> should give the same result as

I'm not sure about that, you could argue both ways. You're asking isodatetime to subtract one day from a month.
