### ISSUE TITLE
Runahead limit consistency: P1 vs PT1H

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4913]
For datetime cycling we can use a time interval `runahead limit`, where the number of active cycles is determined by `<base-cycle-point> + <time-interval>`.  So for a `PT1H` cycle, a  `PT0H` limit allows 1 point (just the base one) to run at a time, `PT1H` allows the base point and one additional point (i.e. two points in total), and so on.

For Cylc 8 we merged the old `max active cycle points` (number of active cycles) setting into `runahead limit` specified as an integer interval (for both integer and datetime cycling), but it seems we forgot to change the value accordingly and ended up with an off-by-one error:
- `P0` means one active point (the base one) :heavy_check_mark: 
- `P1` means ONE active point (the base one) :heavy_multiplication_x:  (should be TWO: base point + a 1-cycle interval)
- `P2` means TWO active points (the base, plus the next one) :heavy_multiplication_x:  (should be THREE ...)
- etc.

IMO this is a bug. The integer interval limit is a new thing in Cylc 8, so we can fix it as long as we do it quickly.  And document that a null runahead **interval** limit is required to restrict activity to one point at a time.

Assigning myself as this will be easier to do on top of or after #4906

Agreed? https://github.com/cylc/cylc-flow/labels/question 

(This might possibly be controversial if people think `P1 == one cycle` is fine - but IMO we shouldn't be using the interval-from-base-point notation if it doesn't actually mean what it says).

**Comment by MetRonnie** [comment]
This change is fine by me. (Note the original issue #3667 called for `max active cycle points = n --> runahead limit = Pn`. However nobody spotted the inconsistency with the time format in that implementation. What is suggested here is `max active cycle points = n --> runahead limit = P(n-1)`)

**Comment by hjoliver** [comment]
(NB: I've just pushed a commit to fix the runahead off-by-one error #4913; this will probably require a minor adjustment to a bunch of tests... which were all passing)
