### ISSUE TITLE
Start task does not accept legacy `<task>.<point>` format

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4920]
```
$ cylc play simple-c7-datetime/ --start-task=foo.20020830 -n

WARNING - Backward compatibility mode ON ...
ERROR - Workflow shutting down - PointParsingError: Incompatible value for <class 'cylc.flow.cycling.iso8601.ISO8601Point'>:
    foo.20020830: Invalid ISO 8601 date representation: foo.20020830
INFO - DONE
```

This may be particularly annoying because the workflow has now started up so you'd have to clean the DB before trying again.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
The `--start-task` option wasn't present in Cylc 7 which is why it doesn't auto-upgrade legacy IDs.

However, fair enough, might as well since the functionality is already implemented.
