### ISSUE TITLE
Cylc install strips directories

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-flow#4930]
**Steps to reproduce the bug**

On master, `cylc install dogs/fido` installs into `fido/run1` 

**Expected behavior**

Expected to install into  `dogs/fido/run1`

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
For reference, installing "flat" was the original design behaviour, however, we changed our mind at a later date.

https://github.com/cylc/cylc-flow/issues/4643#issuecomment-1035032796
