### ISSUE TITLE
cylc clean: don't bail early on a list of workflows

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4934]
`cylc clean` shouldn't bail out if it runs into a problem cleaning one workflow in a list (i.e. it should continue on to clean the next ones).

E.g., install and run a workflow that uses a non-existent job platform, then try to clean it and some others using a wildcard.

**Comment by hjoliver** [comment]
See also #4673

**Comment by oliver-sanders** [comment]
I think we can live with this (provided the non-existant job platform issue can be handled), have downgraded the "bug" label, can we bump this to 8.x?

**Comment by hjoliver** [comment]
If I ask to clean 3 workflows and it stops at 1, that's a bug innit. 

I was expecting this would be a trivial fix, but if not, we can bump it.  I'll have a look...

**Comment by hjoliver** [comment]
BTW, I've actually found this one pretty annoying lately. Functional tests that use fake platforms - e.g. mostly the "intelligent host selection" tests - that fail (and therefore don't purge) can't be cleaned with `cylc clean cylctb*` because of this (and #4935).
