### ISSUE TITLE
cylc clean: continue if remote clean fails?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4935]
If `cylc clean` can't clean a remote job platform used (or attempted) by the target workflow, it should continue on and clean other job platforms, ~~and locally~~, rather than abort immediately.

I'm reasonably sure this is a bug and not a feature(?)

E.g. install and run a workflow that uses a non-existent job platform, then try to clean it.

**Comment by hjoliver** [comment]
see also #4673

**Comment by oliver-sanders** [comment]
It should continue onto other platforms, yes, however, it **should not** clean locally because doing so would delete the database prohibiting `cylc clean` from being able to remove the remote directory at a later date.

**Comment by oliver-sanders** [comment]
(taking a quick look at the broken platform side of this)

**Comment by oliver-sanders** [comment]
This has now been fixed by other changes, see https://github.com/cylc/cylc-flow/pull/4950#issuecomment-2422302745
