### ISSUE TITLE
`:finish` trigger difference in stall behaviour between c7 & c8 back-compat mode

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4965]
**Describe the bug / steps to reproduce**

```ini
# suite.rc
[scheduling]
    initial cycle point = 2002
    [[dependencies]]
        [[[P1Y]]]
            graph = foo:finish => cleanup
[runtime]
    [[foo]]
        script = false
    [[cleanup]]
```
Running with Cylc 7, this keeps going indefinitely.

Running with Cylc 8 (in back compat mode), this stalls:
```log
WARNING - Incomplete tasks:
      * 20020101T0000Z/foo did not complete required outputs: ['succeeded']
      * 20030101T0000Z/foo did not complete required outputs: ['succeeded']
      * 20040101T0000Z/foo did not complete required outputs: ['succeeded']
      * 20050101T0000Z/foo did not complete required outputs: ['succeeded']
      * 20060101T0000Z/foo did not complete required outputs: ['succeeded']
```

**Expected behavior**

Stall behaviour should be the same in Cylc 7 and Cylc 8 back-compat mode?

**Additional context**

Running with Cylc 8 after renaming to `flow.cylc`, it continues indefinitely like it did with Cylc 7.

**Comment by dpmatthews** [comment]
Or just a change in runahead limit behaviour?

**Comment by hjoliver** [comment]
> Running with Cylc 7, this keeps going indefinitely.

Cylc 7 doesn't count failed tasks toward the runahead limit.

> Running with Cylc 8 after renaming to flow.cylc, it continues indefinitely like it did with Cylc 7.

Cylc 8 counts incomplete tasks, but not failed ones (unless they are also incomplete). Here, `foo:succeed` is optional (as implied by the `finish` trigger), so there are no incomplete tasks.

> Running with Cylc 8 (in back compat mode), this stalls

In back compat mode, we mark all `:succeed` outputs as required. 

I vaguely recall looking at `:finish` triggers in this context, but can't find any record of that...

**Comment by hjoliver** [comment]
Fix posted.

**Comment by hjoliver** [comment]
Fortunately we don't need to identify finish triggers in the graph and treat those tasks differently - it's just a matter of emulating Cylc 7 runahead behaviour with incomplete tasks (c8) == failed tasks (c7).
