### ISSUE TITLE
Provide a subcommand to uninstall a workflow

### ISSUE THREAD

**Issue by pletzer** [cylc/cylc-flow#4966]
**Describe exactly what you would like to see in an upcoming release**

Cylc comes with a set of sub-commands, including validate, install, run... It would be nice to have a sub-command that removes the workflow (could be called either uninstall, remove or delete). 

cylc uninstall <workflow>

This would remove all the files under ~/cylc-run/<workflow>. The goal is to end up in the same state as before typing "cylc install <workflow>".

**Additional context**

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Hi @pletzer - thanks for the suggestion... 

... however, in this case we have you covered already! See:

```
cylc clean --help
```

The command is not called `uninstall` because it also removes files generated at run time, not just those installed from the source directory.

**Comment by pletzer** [comment]
Thanks @hjoliver. So cylc -h does not list all the commands. However, "cylc help all" does list "cylc clean".

**Comment by hjoliver** [comment]
Yes. I think we can tweak the main help page to make that clearer.
