### ISSUE TITLE
datastore: failed tasks not cleaned up

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#4969]
This works as expected:
```
P1 = "a? => b?"  # with b fails every time
```

But failed tasks accumulate in the datastore in this case:
```
P1 = "a? => b? => c?"  # with b fails every time
```

**Comment by dwsutherland** [comment]
Using;
```
[scheduling]
    cycling mode = integer
    initial cycle point = 1
    final cycle point = 10
    [[graph]]
        P1 = "a? => b? => c?"
        #P1 = "a? => b?"
[runtime]
    [[a,c]]
        script = sleep 5
    [[b]]
        script = "sleep 5; exit 1"
```
It appears that when b doesn't fail:
- b leaves the pool
- c enters the pool
- pruning of a is flagged.
- c leaves the pool
- pruning of b & c is flagged (as path has finished).

When `b` does fail:
- b leaves the pool.
(c is shown in the data-store, as the n=1 of b)
- c never enters the pool.
- nothing else happens.

So there's some kind of loop hole in the window/pruning management... and it should prune whole path (`a`, `b`, `c`) if no active tasks exist in path..
