### ISSUE TITLE
Invalid workflows fail post-detach

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4982]
When `[scheduler][run hosts]` are used to run scheduler on, validation errors occur post-detatch which makes the failure invisible.

E.G. when you run an invalid workflow:

```console
$ cylc play <id>
...
<id>: <server> PID=<pid>
```

It looks like it worked, but it didn't:

```console
$ cylc cat-log <id>
...
ERROR - Workflow shutting down - WorkflowConfigError: This workflow requires an initial cycle point.
```

This didn't use to be the case, the change was likely caused by recent startup reordering.

Note: #3896 will reduce the pressure on this, however, ideally we would fix this in the `cylc play` command properly.

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
I have reproduced this even without `[scheduler][run hosts]`, so maybe higher priority?

However, I've struggled to figure out when this bug was introduced. I'll have a go testing out earlier cylc 8 releases
