### ISSUE TITLE
reload: address warning for preparing tasks

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4990]
Address warning for preparing tasks post-reload.

We think after a reload preparing tasks may, or may not, be active with pre-reload settings as the job file may, or may not, have been written. Needs a little investigation and a `LOG.warning` worded as appropriate.

See https://github.com/cylc/cylc-flow/pull/4984#issuecomment-1189696933

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
I have looked into this and cannot tell for sure whether a job file would have been written at the point of doing a reload. So having a different warning for preparing tasks saying they "may" be active with pre-reload settings seems sensible.

**Comment by oliver-sanders** [comment]
Sounds good.

I think the mid/long term solution here is probably to flush through preparing tasks before performing the reload for safety.

**Comment by MetRonnie** [comment]
Closing as partially addressed by #5109, with the other part being superseded by #5107
