### ISSUE TITLE
Cylc Review Search

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#5019]
**Describe the bug**

RE: Cylc Revew & Cylc 8 Functionality

On attempting to search within a file from a Cylc 8 workflow the following error message appears. This only happens as far as we can tell when the search is being served by apache, not by the test server.

![image](https://user-images.githubusercontent.com/26465611/181230783-bfcd726a-1879-4336-8c12-cfe628707971.png)

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by dpmatthews** [comment]
Note that the same happens with a Cylc 7 workflow if you run it in a sub-directory of `cylc-run` - the issue is the directory hierarchy

**Comment by oliver-sanders** [comment]
Fixed by #5097
