### ISSUE TITLE
trigger after restarting a completed workflow

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5072]
* If a workflow is run to completion.
* Then a task is added to the graph and the workflow restarted.
* And the predecessor of the new task is triggered (creating a new flow-front in the process).

I would expect the scheduler to follow on to the new task.

We've had a report that it is not doing this: https://cylc.discourse.group/t/adding-new-task-to-succeeded-workflow-explicit-insertion/520/2

> I re-trigger the preceding task, which succeeds, tui now appears to show the new task. However, once the preceding task has finished, the workflow shuts down again

Questions:
* [x] Can we confirm this?
* [ ] Should the new task be triggered in this case?

**Comment by hjoliver** [comment]
Apologies, missed this new issue before posting another on the same topic.

 I'll close this as superseded, because I did some investigation and have explained the result on the other one.
