### ISSUE TITLE
keep-alive timeout for restarted completed workflows

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5078]
https://cylc.discourse.group/t/adding-new-task-to-succeeded-workflow-explicit-insertion/520/3

If a workflow completes and shuts down, but you want to start the scheduler again and trigger some new action (whether past tasks or new ones added to the graph since the workflow completed), currently you have to:
- `cylc play --pause` so the scheduler doesn't just shut down again immediately (workflow finished)
- then `cylc play` (unpause) after triggering tasks, so that the triggered tasks can submit

The above steps are perhaps not very intuitive (for instance, it's not obvious that "pause" should stop the scheduler from shutting down).

QUESTION: If a completed workflow is restarted, should it stay alive for some timeout period to allow user intervention.

(Pegging against 8.1 as would be easy to implement - just a variant of the current stall timer - and we have evidence that it affects users incrementally developing new workflows).

**Comment by oliver-sanders** [comment]
* A short timeout (e.g. PT2M).
* A warning message (saying, workflow completed, trigger a task to (re)start a flow).

The warning message should be flagged in the UI with #4148.

**Comment by hjoliver** [comment]
I'll take that as agreement; removing the question label.

**Comment by hjoliver** [comment]
(I have this done, will post a PR tomorrow)
