### ISSUE TITLE
Require tomli **only** if python < 3.11

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#5089]
**Describe exactly what you would like to see in an upcoming release**
In the files which describe dependencies to pip and conda (`conda-environment.yaml`, `setup.cfg`) have syntax which allow us to specify that dependencies are only installed for some Python versions. Tomli will be included in the standard library for Python 3.11.

Once Python 3.11 is available and included in the Cylc Testing matrix, add the following to the dependency specifications:

```diff 
# setup.cfg
-     tomli>=2.*
+     tomli>=2.*; python_version<"3.11"
```

```diff
# conda-environment.yml
-  - tomli >=2.0.0
+  - tomli >=2.0.0 # [py<3.11] 
```

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
Closed by https://github.com/cylc/cylc-flow/pull/5479
