### ISSUE TITLE
NodesEdges: source and target reversed

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5099]
Occasionally I seem to be getting graph edges with the source and target around the wrong way.

<details>
<summary>Given this example workflow:</summary>
<pre>
[scheduler]
    allow implicit tasks = True
[scheduling]
    initial cycle point = 1
    cycling mode = integer
    [[graph]]
        P1 = """
            a => b1 & b2 & b3 => c1 & c2 & c3 => d
            b1[-P1] => b1
            b2[-P1] => b2
            b3[-P1] => b3
        """
</pre>
</details>

![graph](https://user-images.githubusercontent.com/16705946/186644203-0c50ce06-4f4c-408d-a603-57765356549b.png)

And this Query:

```graphql
query {
  workflows {
    id
    nodesEdges {
      edges {
        id
        source
        target
        suicide
        cond
      }
    }
  }
}
```

I found one edge pointing the wrong way:

```json
            {
              "id": "~oliver/abc//$edge|7/b3|7/c1",
              "source": "~oliver/abc//7/c1",
              "target": "~oliver/abc//7/b3",
              "suicide": false,
              "cond": false
            },
```

Curiously the edge is the right way around in the ID (`b3 => c1`) but the wrong way around in the source target (`c1 => b3`)?

<details>
<summary>Full GraphQL output</summary>
<i>Note data obtained via GraphiQL</i>
<pre>
{
  "data": {
    "workflows": [
      {
        "id": "~oliver/abc",
        "nodesEdges": {
          "edges": [
            {
              "id": "~oliver/abc//$edge|7/b2|8/b2",
              "source": "~oliver/abc//7/b2",
              "target": "~oliver/abc//8/b2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|11/a|11/b3",
              "source": "~oliver/abc//11/a",
              "target": "~oliver/abc//11/b3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b1|7/c2",
              "source": "~oliver/abc//7/b1",
              "target": "~oliver/abc//7/c2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/b2|8/c3",
              "source": "~oliver/abc//8/b2",
              "target": "~oliver/abc//8/c3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|6/c3|6/d",
              "source": "~oliver/abc//6/c3",
              "target": "~oliver/abc//6/d",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|9/a|9/b3",
              "source": "~oliver/abc//9/a",
              "target": "~oliver/abc//9/b3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/b1|8/c3",
              "source": "~oliver/abc//8/b1",
              "target": "~oliver/abc//8/c3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b3|7/c2",
              "source": "~oliver/abc//7/c2",
              "target": "~oliver/abc//7/b3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|9/a|9/b1",
              "source": "~oliver/abc//9/a",
              "target": "~oliver/abc//9/b1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|6/c1|6/d",
              "source": "~oliver/abc//6/c1",
              "target": "~oliver/abc//6/d",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b1|7/c3",
              "source": "~oliver/abc//7/b1",
              "target": "~oliver/abc//7/c3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|10/a|10/b3",
              "source": "~oliver/abc//10/a",
              "target": "~oliver/abc//10/b3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b1|8/b1",
              "source": "~oliver/abc//7/b1",
              "target": "~oliver/abc//8/b1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/b1|8/c1",
              "source": "~oliver/abc//8/b1",
              "target": "~oliver/abc//8/c1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/b2|9/b2",
              "source": "~oliver/abc//8/b2",
              "target": "~oliver/abc//9/b2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b3|7/c1",
              "source": "~oliver/abc//7/c1",
              "target": "~oliver/abc//7/b3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/c1|7/d",
              "source": "~oliver/abc//7/c1",
              "target": "~oliver/abc//7/d",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|10/a|10/b1",
              "source": "~oliver/abc//10/a",
              "target": "~oliver/abc//10/b1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/b1|9/b1",
              "source": "~oliver/abc//8/b1",
              "target": "~oliver/abc//9/b1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|9/b3|9/c2",
              "source": "~oliver/abc//9/b3",
              "target": "~oliver/abc//9/c2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b1|7/c1",
              "source": "~oliver/abc//7/b1",
              "target": "~oliver/abc//7/c1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|9/b3|9/c1",
              "source": "~oliver/abc//9/b3",
              "target": "~oliver/abc//9/c1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|9/a|9/b2",
              "source": "~oliver/abc//9/a",
              "target": "~oliver/abc//9/b2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/c3|7/d",
              "source": "~oliver/abc//7/c3",
              "target": "~oliver/abc//7/d",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|10/a|10/b2",
              "source": "~oliver/abc//10/a",
              "target": "~oliver/abc//10/b2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/a|8/b1",
              "source": "~oliver/abc//8/a",
              "target": "~oliver/abc//8/b1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/b1|8/c2",
              "source": "~oliver/abc//8/b1",
              "target": "~oliver/abc//8/c2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|6/c2|6/d",
              "source": "~oliver/abc//6/c2",
              "target": "~oliver/abc//6/d",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b2|7/c2",
              "source": "~oliver/abc//7/b2",
              "target": "~oliver/abc//7/c2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|11/a|11/b1",
              "source": "~oliver/abc//11/a",
              "target": "~oliver/abc//11/b1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/a|8/b2",
              "source": "~oliver/abc//8/a",
              "target": "~oliver/abc//8/b2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/b2|8/c1",
              "source": "~oliver/abc//8/b2",
              "target": "~oliver/abc//8/c1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/c2|7/d",
              "source": "~oliver/abc//7/c2",
              "target": "~oliver/abc//7/d",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|8/b2|8/c2",
              "source": "~oliver/abc//8/b2",
              "target": "~oliver/abc//8/c2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b3|7/c3",
              "source": "~oliver/abc//7/c3",
              "target": "~oliver/abc//7/b3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b2|7/c1",
              "source": "~oliver/abc//7/b2",
              "target": "~oliver/abc//7/c1",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|11/a|11/b2",
              "source": "~oliver/abc//11/a",
              "target": "~oliver/abc//11/b2",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|9/b3|9/c3",
              "source": "~oliver/abc//9/b3",
              "target": "~oliver/abc//9/c3",
              "suicide": false,
              "cond": false
            },
            {
              "id": "~oliver/abc//$edge|7/b2|7/c3",
              "source": "~oliver/abc//7/b2",
              "target": "~oliver/abc//7/c3",
              "suicide": false,
              "cond": false
            }
          ]
        }
      }
    ]
  }
}
</pre>
</summary>

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Tagged against 8.1.0 as this interface is not currently used by the UI or anything else.

**Comment by dwsutherland** [comment]
Yeah, I see another one there:
```
            {
              "id": "~oliver/abc//$edge|7/b3|7/c3",
              "source": "~oliver/abc//7/c3",
              "target": "~oliver/abc//7/b3",
              "suicide": false,
              "cond": false
            },
```
The interesting clue to where it might be happening is with the `id`, it appears to be correct (`7/b3` -> `7/c3`)... So, something's going wrong with the setting of `source` & `target`.

Do you have that workflow config handy? then I'll get a fix up as soon as I can reproduce it in a simpler form.

**Comment by dwsutherland** [comment]
(that suicide field is probably not needed anymore XD)

**Comment by oliver-sanders** [comment]
Suicide triggers are still supported and remain necessary in compat mode.

**Comment by dwsutherland** [comment]
> Suicide triggers are still supported and remain necessary in compat mode.

Ah, I thought it would just get translated into Cylc8 where they aren't needed/used.. (or are they?)

**Comment by oliver-sanders** [comment]
In Cylc 7 compatibility mode optional outputs are not available and suicide triggers are still implemented.

In "normal" mode, I think suicide triggers are tolerated, but ignored I.E. functionless. But if present the graph view should render them differently so they aren't mistaken for other edges.

**Comment by hjoliver** [comment]
> In "normal" mode, I think suicide triggers are tolerated, but ignored I.E. functionless. 

Actually, as I recall, they're function**al** but pointless :rofl: 

`foo => ! bar` actually causes `bar` to spawn, only to be removed immediately by the suicide trigger.
