### ISSUE TITLE
parsec: comma separated list items containing commas

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5120]
Spotted in relation to #5118, the "supported" syntax for multiple parameters doesn't play nicely with the inherit configuration either.

For example this workflow:

```ini
[task parameters]                                                                    
    x = 1..2           
    y = 3..4           
                       
[scheduling]           
    [[dependencies]]   
        [[[R1]]]       
            graph = foo
                       
[runtime]              
    [[I, J]]           
    [[A<x,y>]]         
    [[a1<x,y>, a2<x,y>, a3<x,y>]]
        inherit = I, "A<x,y>", J 
```

Looks fine, but doesn't validate:

```
ListValueError: (type=list) [runtime][a1<x,y>, a2<x,y>, a3<x,y>]inherit = I, "A<x,y>", J - (names containing commas must be quoted(e.g. 'foo<m,n>'))
```

The parametrised item *has* been quoted as suggested by the error message, but it still fails validation.

I found a workaround, for some reason if one of the items in the list is quoted, all of the items must be, whether they need to be or not:

```diff
     [[a1<x,y>, a2<x,y>, a3<x,y>]]
-        inherit = I, "A<x,y>", J 
+        inherit = "I", "A<x,y>", "J" 
```

Should be a simple fix, probably in the "coerser".

**Comment by MetRonnie** [comment]
This behaviour seems contradictory to me:
https://github.com/cylc/cylc-flow/blob/3d9ee950ecc16a07178d9e155d711f8222831526/cylc/flow/parsec/validate.py#L546-L552

If there is a quoted value without commas in it, it is left quoted. But if there is a quoted value with commas inside it, it is supposed to have the quotes stripped?

**Comment by hjoliver** [comment]
It looks like the first one is wrong, to me.

**Comment by oliver-sanders** [comment]
We need to be very careful with this change, best to run `cylc config` against workflows before and after the change. This output will include inheritance so any unintended behaviour change will result in diff.

**Comment by MetRonnie** [comment]
Superseded by #5167
