### ISSUE TITLE
wrapper script: consider clearing PYTHONPATH

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5124]
We advise that Cylc is installed into an isolated environment (e.g. conda / virtualenv). Unfortunately the `PYTHONPATH` environment variable can corrupt these.

Illustrative example (less extreme cases can cause problems too):

```bash
export PYTHONPATH='/path/to/python3.6/site-packages'
cylc version
Traceback ... not quite so isolated after all
```

This is very inconvenient for users who rely on `PYTHONPATH` (e.g. to load their own Python environment) as they have to unload this environment before they can run Cylc commands. If Cylc is installed in an isolated environment, then it should be isolated from stuff like this.

We might be able to do something like this:

```
PYTHONPATH= exec "${CYLC_HOME}/bin/${0##*/}" "$@"
```

Otherwise, there is the nuclear [Python] option:

```
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
```

Probably a good idea? But it does have the unwelcome side-effect of disabling `PYTHONBREAKPOINT`.

And also:

```
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE
```

Could do with a bit of investigation to work out what the consequences of these approaches are.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
(Tagged 8.1.0 but could go into 8.0.x if we can agree a solution in time)

**Comment by oliver-sanders** [comment]
Note: Users might need `PYTHONPATH` to load modules for `rose_ana` which could make a mess of things.

**Comment by hjoliver** [comment]
Unfortunately not everyone uses the wrapper!  E.g. single user installations.

What about explicitly cleaning `sys.path` at start-up?  I think that would work in conda environments.  Load a Python venv though, the system Python libs are needed.

**Comment by oliver-sanders** [comment]
I'm not sure that would work?

Unfortunately I think we might actually *need* to bodge `PYTHONPATH` for `rose_ana` which makes a right mess of things.

**Comment by oliver-sanders** [comment]
Note, this impacts Rose worse than Cylc.

**Comment by dpmatthews** [comment]
> Note, this impacts Rose worse than Cylc, however, with Rose we actually need the PYTHONPATH to be preserved because it will be required for the Rose "command".

Perhaps we need to save the PYTHONPATH in another environment variable which Rose can use before running the "command".

**Comment by oliver-sanders** [comment]
That's sounding like the best option, note the variable would have to be set in the wrapper-script and restored in the rose library code.

**Comment by wxtim** [comment]
I think that I've done the rose end, but the wrapper script is proving trickier. We don't really want to cache `PYTHONPATH` every time we run the wrapper script - otherwise it risks stripping out the path we want for messages.
