### ISSUE TITLE
review: add version/* files to dropdown menus

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5135]
The log/version files are not presently visible in Cylc Review, the Rose 2019 equivalents were.

Given the number of back-and-forths here it might be worth changing tack on how we list these files, e.g an approach along the lines of this might be better:

```
find log/ -maxdepth 2 -type f
```

**Pull requests welcome!**

**Comment by wxtim** [comment]
> The log/version files are not presently visible in Cylc Review, the Rose 2019 equivalents were.
> 
> Given the number of back-and-forths here it might be worth changing tack on how we list these files, e.g an approach along the lines of this might be better:
> 
> ```
> find log/ -maxdepth 2 -type f
> ```
> 
> **Pull requests welcome!**

I'd be happy to expose everything in log which is not in log/job - @dpmatthews  Can we agree on this approach?

**Comment by datamel** [comment]
To summarize discussion this morning with @dpmatthews the decision has been made to go with the one line fix of adding the version dir. This is to minimize interference with existing logic.
If changes are subsequently needed, a search type fix would be the preferred solution.

Note that while testing the fix, another issue has cropped up with SQLite errors and traceback visible, investigation is ongoing with this.

**Comment by datamel** [comment]
This was closed by: https://github.com/cylc/cylc-flow/pull/5140
