### ISSUE TITLE
workflow-state: check latest instance for status

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5143]
The task_states DB table gets a new entry for a given task ID if its flow numbers change. That's because we use the table to extract flow-wait status for historical tasks that already ran in this flow.

(For a given flow, the submit number of a task ID updates but we don't get a new entry).

`cylc workflow-state` wrongly assumes that any non-null query result indicates status achieved. It should only check the result for the latest matching record in the table (i.e. latest submit number).

**Comment by MetRonnie** [comment]
If this is the blocker for 8.3.0 at NIWA, could you consider splitting off the fix for this from the rest of #5809 into a new PR, and do the rest at 8.4.0. #5809 is a rather complex PR and will take a while to review, and we're hesitant to release 8.3.0 immediately after without any testing period.
