### ISSUE TITLE
play: colour formatting turned off

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5159]
Minor but annoying issue which has been kicking about for a while.

When `cylc play` re-invokes remotely the colour formatting gets turned off for some reason.

The colour formatting can be helpful as it makes errors and warnings more prominent as well as making it easier to visually filter out debug messages when debugging.

See also #4914

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Probably caused by #4562?  (Which fixes a more important bug, but hopefully we can have our cake and eat it too...)
