### ISSUE TITLE
How to re-run a task stuck in submitted or running?

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#5177]
A task can remain stuck in submitted or running if a platform  becomes unreachable (so polling cannot determine the task state).
How can you re-trigger the task?
You may be able to use `cylc remove` and then trigger the task (not tested) but that could result in the workflow shutting down if there were no other tasks in the pool.

With Cylc 7 you could have used `reset-state`

See https://cylc.discourse.group/t/7-to-8-first-steps/514/6

**Comment by hjoliver** [comment]
The simplest solution would be to take the trigger command at face value and allow retriggering of (supposedly-)already-active tasks.  The (arguable) downside of this is that task ID globs might have to be more specific, to avoid already-active tasks if you don't want to retrigger them.

Alternatively, add a new option: `cylc trigger --force`.

**Comment by dpmatthews** [comment]
Sorry, already raised as a question: #5147
