### ISSUE TITLE
Two minor bugs in consolidation tutorial

### ISSUE THREAD

**Issue by jwallwork23** [cylc/cylc-flow#5198]
I spotted two minor bugs and have proposed fixes:

* The `etc/` subdirectory is missing `met-office-sites.dat`. It seemed to work fine if I copy this file over from the previous tutorial.
* I think `allow implicit tasks = True` is missing from the scheduler, otherwise the final part doesn't work.

**Comment by MetRonnie** [comment]
> I think `allow implicit tasks = True` is missing from the scheduler, otherwise the final part doesn't work.

It works for me. Happy to discuss it on Teams if you like
