### ISSUE TITLE
7-8 `cylc suite/workflow-state` compat

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5236]
Via @dwsutherland today:

The DB polling commands don't work in either direction, and they'll need to as sites transition between Cylc 7 and 8.

(I reported that they did work some time ago, but it seems I had only tested the most basic full-state query)

**Comment by hjoliver** [comment]
8.1.0
and possibly another Cylc 7 release, although I suppose we could document how to patch the last one for those that need it.

**Comment by dwsutherland** [comment]
Thanks Hilary, I've had a look at both 👍  .. Let me know when you'd like them reviewed

**Comment by MetRonnie** [comment]
Closed by #5237
