### ISSUE TITLE
"Stalled" status?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#5256]
Currently, if a workflow is stalled, the status in the GUI and TUI just says running. There ought to be a stalled status.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Transferred to cylc-flow.

**Question:** Should we make "stalled" a top-level workflow status (along with "running" and "paused")?

We have considered this before, and it definitely would have made sense in the past, however, it's possible that the planned addition of "blocked" tasks will supersede this as blocked tasks allow users to respond to the issue *before* it results in a stall.

I think:

* This is mostly superseded by #5257
* The workflow status message should be updated to "workflow stalled" when a stall occurs
* We could consider making stalled a top-level workflow status if there's a good case for doing so

**Comment by oliver-sanders** [comment]
There may still be a case for a top-level stalled status (e.g. filtering), however, I think the cons of adding a new running'esque status outweigh the pros.

We would like to have better interfaces for identifying incomplete tasks and alerting users to them which should supersede this.
