### ISSUE TITLE
Space-separated list of queue members ignored without error

### ISSUE THREAD

**Issue by jhaiduce** [cylc/cylc-flow#5260]
**Describe the bug**
See [discussion on Element](https://matrix.to/#/!hwZqSYihGPuhDdIzIP:matrix.org/$1670255552138977aoIyT:matrix.org?via=matrix.org
)

If a space separated list is given for `flow.cylc[scheduling][queues][<queue name>]members`, rather than the required comma-separated list, cylc interprets the value as a single-element list containing a string with spaces. `cylc validate` reports the flow is valid and no errors appear in `cylc play` or `cylc log`, but cylc behaves as though the internal queue defined in `flow.cylc[scheduling][queues][<queue name>]` did not exist, ignoring any limits defined in it.

**Release version(s) and/or repository branch(es) affected?**
Have tested 8.0.1 and 8.0.3 and saw this behavior in both versions.

**Steps to reproduce the bug**

Create a flow that defines an internal queue, and put a space-delimited list in the `members` field, e.g.:
```
[scheduling]
  cycling mode = integer
  initial cycle point = 1
  runahead limit = P10
  [[queues]]
    [[[my_queue]]]
      limit = 2
      members = task1 task2
  [[graph]]
    P1 = "task1 => task2"
[runtime]
  [[task1]]
    script = "sleep 5; echo done>status"
  [[task2]]
    script = "sleep 5; echo done>status"
```

**Expected behavior**
`cylc validate` and `cylc play` should exit with an error on the above flow, since the `members` list should be comma delimited and 'task1 task2' is not a valid task name.

**Actual behavior**
`cylc validate` reports the above flow is valid, and `cylc play` executes the flow, ignoring the queue limit.

**Additional context**
Per @oliver-sanders in the [Element thread](https://matrix.to/#/!hwZqSYihGPuhDdIzIP:matrix.org/$1670256094139282eKgpQ:matrix.org?via=matrix.org):

> members is currently a "V_STRING_LIST" which is a comma-separated list which tolerates spaces (hence no error) We could try "V_SPACELESS_STRING_LIST" which forbids spaces (creating an error).

> Suggesting:
> 
>    1. Switch to spaceless string list since spaces are not valid in task names.
>    2. Validate queue members to ensure that all listed members exist in the [runtime] section.
> 
> Unfortunately we may need to do a bit of testing to ensure we don't break too many workflows with these changes.

**Comment by oliver-sanders** [comment]
Closed by #5312
