### ISSUE TITLE
codecov upload failures

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5264]
These failures are caused by an issue with Codecov hitting rate-limiting with GitHub APIs.

For more info see this discourse post: https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
#5459 is probably good enough to close this?

**Comment by hjoliver** [comment]
I think so, closing for now.

**Comment by oliver-sanders** [comment]
Sadly not :(

**Comment by MetRonnie** [comment]
May be mitigated by https://github.com/codecov/codecov-action/pull/1471

**Comment by oliver-sanders** [comment]
Ooh, that looks promising...

**Comment by MetRonnie** [comment]
Seems to be reliable again. Close again? 🤷‍♂️
