### ISSUE TITLE
clock-triggers: re-implement as xtriggers

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5285]
Cylc currently provides two mechanisms for clock-limiting tasks:

* [[xtriggers]wall_clock](https://cylc.github.io/cylc-doc/stable/html/reference/config/workflow.html#flow.cylc[scheduling][xtriggers]%3Cxtrigger%20name%3E)
  The new approach, the `@clock` trigger is used in the graph like regular dependencies. This has the advantage of transparency.
* [[special tasks]clock-trigger](https://cylc.github.io/cylc-doc/stable/html/reference/config/workflow.html#flow.cylc[scheduling][special%20tasks]clock-trigger)
  The old approach. marked as deprecated but still widely used. Allows listing of tasks which should be clock-limited.

We will presumably look to retire the old `clock-triggers` at some point after Cylc 7 back-compat mode is dropped, but this is still a way off. This means we need to keep these triggers working for the near future (which is something else to go wrong #5217).

Suggest converting clock-triggers to xtriggers at configure time. I think we can do this fairly easily at configure time something along the lines of:

```python
# config.py
def convert_clock_triggers(self):
    for string in self.cfg['scheduling']['special tasks']['clock-trigger']:
        task_name, offset  = do_something(string)
        xtrig_name = f'_cylc_clock_trigger_{task_name}'
        self.cfg['scheduling']['xtriggers'][xtrig_name] = f'wall_clock({offset})'
        taskdef = self.taskdefs[task_name]
        taskdef.add_xtrig_label(xtrig_name)
```

This way the old triggers will continue working under the new logic allowing us to retire this feature early. The old triggers will also become visible in the UI once xtrigger support is added.

**Pull requests welcome!**

**Comment by hjoliver** [comment]
Yes, good idea. Seems to me it should work fine.
