### ISSUE TITLE
Cat-log Limit

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-flow#5295]
In light of the imminent Log view work in the ui/ui-server, we should look into implementing a (configurable?) limit on the size of the file `cat-log` can return.
After discussion UK side and after a bit of investigation this morning I think this seems sensible to avoid a user trying to load a million line log file and crashing the ui-server/ui.

**Additional context**

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
I think this is going to be easier to handle at the UIS than in cat-log itself, which is ok since it's more to do with the implementation limits of the UI. We might also want to look at doing things like paging to get around the limit issue.

https://github.com/cylc/cylc-uiserver/issues/403
