### ISSUE TITLE
platform name can't start with "localhost"?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5342]
We have a platform defined with name `localhost_slurm` that is supposed to submit jobs to Slurm locally (i.e. on the scheduler host) ... but it ignores the job runner setting and just runs local background jobs.

If I change the platform name to (e.g.) `localhxst_slurm` it works as intended.

**Comment by wxtim** [comment]
This bug was introduced by https://github.com/cylc/cylc-flow/issues/4845 - I think it just needs changing from `re.match` to `re.fullmatch`.

**Comment by oliver-sanders** [comment]
Closed by #5343
