### ISSUE TITLE
graph parser: expire-all ?

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5354]
The `expire-all` trigger (valid at Cylc 7) appears to be missing from Cylc 8:

https://github.com/cylc/cylc-flow/blob/76762bbfc1ca83be88ed8b0e0a7224e6af520964/cylc/flow/graph_parser.py#L105-L116

I'm not sure whether `expire-all` was "officially supported" or just a side-effect of the way the logic worked, however, it seems like a sensible trigger condition to me. I'm not sure whether its removal was intentional, nothing springs to mind.

At Cylc 8 such a trigger would probably required a `?` modifier (as succeeded and expired are orthogonal), but should still work.

**Pull requests welcome!**

**Comment by neill-b** [comment]
Would be helpful in my use case, so thanks for raising this issue @oliver-sanders.

**Comment by hjoliver** [comment]
Even worse: #5364

**Comment by oliver-sanders** [comment]
Bumping back until #5364 is sorted.

**Comment by hjoliver** [comment]
PR done, bumping the milestone forward again.

**Comment by oliver-sanders** [comment]
This can now be attempted, however, won't necessarily work until #5364
