### ISSUE TITLE
lint: warn about `rose host-select`

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#5362]
**Describe exactly what you would like to see in an upcoming release**

Cylc lint should complain if `platform = $(rose host-select)`. Although this is supported it's not good practice in most cases because platform groups should handle having multiple suitable platforms with multiple suitable hosts.

**Pull requests welcome!**

**Comment by oliver-sanders** [comment]
Merged into https://github.com/cylc/cylc-flow/issues/4917
