### ISSUE TITLE
:expire trigger broken

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5364]
By broken I mean, it has no effect.

When implementing the spawn-on-demand scheduler, I think I must have forgotten about the `:expired` trigger, and hence removed expired tasks before triggering on that "output" (because an expired task does not have any *other* outputs).

**Comment by hjoliver** [comment]
Per #5361 - we also need to consider required outputs of expired tasks.

**Comment by hjoliver** [comment]
Oops:
```
1712 edf61d368c cylc/flow/task_pool.py (Hilary Oliver    2020-04-24 13:29:54 +1200 1712)   
          # TODO [...] expired states are useless due to immediate
          # removal under all circumstances [...]
```

**Comment by hjoliver** [comment]
@MetRonnie - have you started working on this? If not, I can post a fix pretty quickly.

**Comment by hjoliver** [comment]
I'll take over this one, it appears @MetRonnie is not working on it...

**Comment by oliver-sanders** [comment]
Have had an issue reported where a task expired DURING its second try leaving behind a job in the submitted state which subsequently could not be killed (because the task isn't in the pool). Possibly related?

**Comment by hjoliver** [comment]
Not related to the "expire trigger" as such, but a good point to note. We should not allow an already-active task to expire.
