### ISSUE TITLE
linear ancestors not so linear

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5366]
A nasty bug in the ancestor ordering which causes whole bunches of tasks to disappear from the UI!

For the following workflow:

```ini
[scheduling]             
    [[graph]]            
        R1 = A & B       
                         
[runtime]                
    [[A]]                
    [[A1]]               
        inherit = A      
    [[A2]]    
        inherit = None, A    
    [[a11]]    
        inherit = A1    
    [[a22]]    
        inherit = A2    
    [[B]]    
    [[B1]]    
        inherit = B    
    [[b]]    
        inherit = B1  
```

And this GraphQL request (run through GraphiQL):

```graphql
query {
  workflows {
    familyProxies {
      id
      ancestors {
        id
      }
    }
  }
}
```

I get this response:

```json
{
  "data": {
    "workflows": [
      {
        "id": "~/fam-test/run1",
        "familyProxies": [
          {
            "id": "~/fam-test/run1//1/B",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/A",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/B1",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              },
              {
                "id": "~/fam-test/run1//1/B"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/A1",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/A"
              },
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/A2",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/root",
            "ancestors": []
          }
        ]
      }
    ]
  }
}
```

What's interesting here is the difference between the ancestor order of A1 and B1:

```json
          {
            "id": "~/fam-test/run1//1/A1",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/A"
              },
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
```

```json
          {
            "id": "~/fam-test/run1//1/B1",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              },
              {
                "id": "~/fam-test/run1//1/B"
              }
            ]
           }
```

Despite having identical inheritance structures, the inheritance order is reversed with the `root` family at the bottom of one list and the top of the other.

Strangely it seems to be the family `A2` which introduces this behaviour with the `inherit = None` bit.

Because the UI relies on this field to compute the family tree things get confused and the tree ends up with three "root" notes, `A`, `B` & `root` which should be impossible (because there should only be one "root" node, and it should be called `root`!).

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
> not so linear

Still linear, just backward!

From a quick look, using the example above, the ancestors appear to be in the right order in the scheduler datastore, so (unless I'm wrong) the mis-ordering must be happening after that.  Over to @dwsutherland ...

**Comment by dwsutherland** [comment]
I had a play, and queried the workflow scheduler directly to eliminate all the machinery between there and that WUI:
```
    [[C1]]
        inherit = C
    [[C2]]
        inherit = C1
    [[C3]]
        inherit = C2
    [[c]]
        inherit = C3

```
```
read -r -d '' getAncestors <<_args_
{"request_string": "
query {
  workflows (ids: [\"${1}\"]){
    familyProxies {
      id
      ancestors {
        id
      }
      firstParent {
        id
      }
    }
  }
}
",
"variables": null}
_args_



# Invoke command with given request
echo "${!2}"
time cylc client $1 graphql < <(echo ${!2})
```
It appears everything up to and including the resolver has the field in order:
**data-store:**
```
~sutherlander/ancestors/run1//1/C3
['~sutherlander/ancestors/run1//1/C2', '~sutherlander/ancestors/run1//1/C1', '~sutherlander/ancestors/run1//1/C', '~sutherlander/ancestors/run1//1/root']
```
**resolver result:**
```
id: "~sutherlander/ancestors/run1//1/C3"
cycle_point: "1"
name: "C3"
family: "~sutherlander/ancestors/run1//$namespace|C3"
state: "waiting"
depth: 4
first_parent: "~sutherlander/ancestors/run1//1/C2"
child_tasks: "~sutherlander/ancestors/run1//1/c"
is_held: false
ancestors: "~sutherlander/ancestors/run1//1/C2"
ancestors: "~sutherlander/ancestors/run1//1/C1"
ancestors: "~sutherlander/ancestors/run1//1/C"
ancestors: "~sutherlander/ancestors/run1//1/root"
```
However the graphql/json packaging puts it out of order:
```
                    "id": "~sutherlander/ancestors/run1//1/C3",
                    "ancestors": [
                        {
                            "id": "~sutherlander/ancestors/run1//1/C2"
                        },
                        {
                            "id": "~sutherlander/ancestors/run1//1/C1"
                        },
                        {
                            "id": "~sutherlander/ancestors/run1//1/C"
                        },
                        {
                            "id": "~sutherlander/ancestors/run1//1/root"
                        }
                    ],
```

While I'll do some more digging to figure out exactly why.. 
Do we need to use `ancestors`? Can't we just use `firstParent`?
```
$ wsgraphql ancestors/run1 getAncestors
{"request_string": "
query {
  workflows (ids: [\"ancestors/run1\"]){
    familyProxies {
      id
      firstParent {
        id
      }
    }
  }
}
",
"variables": null}
{
    "workflows": [
        {
            "familyProxies": [
                {
                    "id": "~sutherlander/ancestors/run1//1/B",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/root"
                    }
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/B1",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/B"
                    }
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/root",
                    "firstParent": null
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/A",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/root"
                    }
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/C1",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/C"
                    }
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/A2",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/root"
                    }
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/A1",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/A"
                    }
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/C3",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/C2"
                    }
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/C2",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/C1"
                    }
                },
                {
                    "id": "~sutherlander/ancestors/run1//1/C",
                    "firstParent": {
                        "id": "~sutherlander/ancestors/run1//1/root"
                    }
                }
            ]
        }
    ]
}
```

**Comment by dwsutherland** [comment]
The graphql schema has this for the field:
```
    ancestors = graphene.List(
        lambda: FamilyProxy,
        description="""First parent ancestors.""",
        args=PROXY_ARGS,
        strip_null=STRIP_NULL_DEFAULT,
        delta_store=DELTA_STORE_DEFAULT,
        delta_type=DELTA_TYPE_DEFAULT,
        resolver=get_nodes_by_ids)
```
and `get_nodes_by_ids` returns the correct order..

**Comment by oliver-sanders** [comment]
> Do we need to use ancestors? Can't we just use firstParent?

The reason the UI uses "ancestors" is because it needs to assemble the "family tree" i.e:

* 1
  * root
    * A
      * A1
    * A2
    * B
      * B1

Whilst this is technically possible using firstParent it adds a dependency on delta order.

E.G. if the deltas arrive in this order:

* added:1
* added:1/root
* added:1/A
* added:1/A1

Then we are fine and the UI can construct the family tree, however, if the deltas come in in this order:

* added:1
* added:1/A1  # ERROR: 1/A does not exist in the family tree
* added:1/A   # ERROR: 1/root does not exist in the family tree
* added:1/root

Then we end up in trouble. In order to keep the UI data store as robust as possible it doesn't rely on delta order.

**Comment by oliver-sanders** [comment]
> and get_nodes_by_ids returns the correct order..
> but the graphql machinery spits it out in an incorrect order:

Oh, nasty, what the heck!

**Comment by oliver-sanders** [comment]
Confirmed with this diff:

```diff
diff --git a/cylc/flow/network/schema.py b/cylc/flow/network/schema.py
index b27576573..a3f7cbe28 100644
--- a/cylc/flow/network/schema.py
+++ b/cylc/flow/network/schema.py
@@ -414,7 +414,11 @@ async def get_nodes_by_ids(root, info, **args):
 
     args['ids'] = [Tokens(n_id, relative=True) for n_id in args['ids']]
     args['exids'] = [Tokens(n_id, relative=True) for n_id in args['exids']]
-    return await resolvers.get_nodes_by_ids(node_type, args)
+    ret = await resolvers.get_nodes_by_ids(node_type, args)
+    print('###')
+    for item in [(x.id, x.ancestors) for x in ret]:
+        print(item)
+    return ret
```

Which for the workflow in the OP and the following query:

```graphql
query {
  workflows {
    id
    familyProxies {
      ancestors {
        id
      }
    }
  }
}
```

Produced this output:

```
###
('~osanders/fam-test/run1//1/B1', ['~osanders/fam-test/run1//1/B', '~osanders/fam-test/run1//1/root'])
('~osanders/fam-test/run1//1/A', ['~osanders/fam-test/run1//1/root'])
('~osanders/fam-test/run1//1/A2', ['~osanders/fam-test/run1//1/root'])
('~osanders/fam-test/run1//1/B', ['~osanders/fam-test/run1//1/root'])
('~osanders/fam-test/run1//1/root', [])
('~osanders/fam-test/run1//1/A1', ['~osanders/fam-test/run1//1/A', '~osanders/fam-test/run1//1/root'])
###
('~osanders/fam-test/run1//1/root', [])
('~osanders/fam-test/run1//1/B', ['~osanders/fam-test/run1//1/root'])
###
('~osanders/fam-test/run1//1/root', [])
###
('~osanders/fam-test/run1//1/root', [])
###
('~osanders/fam-test/run1//1/root', [])
###
('~osanders/fam-test/run1//1/root', [])
('~osanders/fam-test/run1//1/A', ['~osanders/fam-test/run1//1/root'])
```

The ancestor order is correct at the point it is yielded to GraphQL.

**Comment by oliver-sanders** [comment]
>> Perhaps it's down to how Graphene interfaces with protobuf objects? How does this conversion happen?

To answer my own question:

> If the [Parent Value Object (parent)](https://docs.graphene-python.org/en/latest/types/objecttypes/#resolverparamparent) is a dictionary, the resolver will look for a dictionary key matching the field name. Otherwise, the resolver will get the attribute from the parent value object matching the field name.
>
> -- https://docs.graphene-python.org/en/latest/types/objecttypes/#id2

I think I have ruled out protobuf as a cause by returning a non-protobuf object from `get_nodes_by_ids` and serialising `ancestors` into a list myself like this:

```python
ret = await resolvers.get_nodes_by_ids(...)
ret2 = []
for item in ret:
    item2 = SimpleNamespace(
        id=item.id,
        ancestors=[x for x in item.ancestors],
    )
    ret2.append(item)
return ret2
```

I can confirm the list of ancestors returned is in the correct order but it still comes out wrong in GraphiQL.

**Comment by oliver-sanders** [comment]
I've also ruled out GraphiQL:

![Screenshot from 2023-02-15 13-23-38](https://user-images.githubusercontent.com/16705946/219039436-7d237922-6272-41c8-89a8-479a73acca47.png)

**Comment by oliver-sanders** [comment]
The jumbling happens **before** `UIServerGraphQLHandler.execute_graphql_request` as confirmed with this diff:

```diff
     async def run(self, *args, **kwargs):
         await TornadoGraphQLHandler.run(self, *args, **kwargs)
 
+    async def execute_graphql_request(
+        self,
+        method: str,
+        query: Optional[str],
+        variables: Optional[Dict[str, str]],
+        operation_name: Optional[str],
+        show_graphiql: bool = False,
+    ):
+        ret = await super().execute_graphql_request(method, query, variables, operation_name, show_graphiql)
+        from pprint import pprint
+        print('*******************************************************************')
+        ret2 = ret
+        if not isinstance(ret, dict):
+            ret2 = ret.data
+        pprint(ret2)
+        print('*******************************************************************')
+        return ret
+
 
 class SubscriptionHandler(CylcAppHandler, websocket.WebSocketHandler):
     """Endpoint for performing GraphQL subscriptions."""
```

**Comment by oliver-sanders** [comment]
Ok, this one is a right pain to debug, going to have to pass it back to the southern hemisphere crew :)

So far I have managed to narrow it down to the code between:
* `IgnoreMiddleware.async_resolve` which is the last place I've identified where the result is still correct.
* and `Promise.for_dict` which is the first place I've identified where the result is wrong.

The `IgnoreMiddleware` code is here (the return result of `next_` is correct):

https://github.com/cylc/cylc-flow/blob/c817dd9c5b50cba36232d3bef9add8dbf4e46bac/cylc/flow/network/graphql.py#L435-L437

The `Promise.for_dict` is called (via `promise_for_dict`) at the end of `graphql.execution.executor.execute_fields`. The `resolved_values` field called within the nested function `handle_success` within the `for_dict` method is wrong (i.e. jumbled).

Somewhere in between the middleware yielding the result and the "Promise" being "resolved" the results get jumbled :angry: Note the 2.x tags don't appear on their GitHub so I can't link the code.

I've been through the issues for the relevant repos but can't find anything promising (pun intended).

**Comment by dwsutherland** [comment]
Sorry, I've been occupied with operations work.

I believe the new GraphQL Core doesn't rely on `promise`, so this may be the impetus to start that migration... There may be a lot of work with downstream packages ..

**Comment by oliver-sanders** [comment]
Oh, I think I might have found it:

https://github.com/cylc/cylc-flow/blob/c817dd9c5b50cba36232d3bef9add8dbf4e46bac/cylc/flow/network/resolvers.py#L388

...

**Comment by hjoliver** [comment]
> This drops into a breakpoint whenever something tries to read the ancestors list. Pressing u in the pdb debugger moves up one level in the stack showing you what called SnitchList.__iter__ pointing at the set operation.

Nice, very clever!

**Comment by dwsutherland** [comment]
>  This bug occurs because the result returned by `cylc.flow.network.schema.get_nodes_by_ids` is somehow sent back through `cylc.flow.resovlers.get_nodes_by_ids`, which appears impossible, but `cylc.flow.network.schema.get_nodes_by_ids` is called multiple times for this operation, and that is what allows the execution of one call to interfere with the result of another one. Ouch!

Nice find!.. kinda makes sense, as family proxies are use it, then ancestors uses it (resolves into a list of family proxy ancestors).
