### ISSUE TITLE
share lib/ and bin/ directories

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5396]
### Problem

Workflows often build or install libraries and executables at runtime. Where should these be put?

You could put them into the `bin/` and `lib/` directories, but these would be overwritten by reinstallation, so you would have to list every resource you want to self-manage into the `.cylcignore` file which is fiddly.

### Proposed Solution

Add support for a `bin/` and `lib/` directory in the `share/` directory (i.e. put these in job's PATH and PYTHONPATH vars). This would help to colocate files generated at runtime and avoid the reinstall problem.

**Comment by oliver-sanders** [comment]
Meeting 2023-03-16: Do it!

**Comment by wxtim** [comment]
Do we need to create these folders on install, or is that the user's problem?

**Comment by oliver-sanders** [comment]
I think we create the "share" and "work" directories on startup? I would find the logic which does that and extend it to cover these new cases.
