### ISSUE TITLE
datastore wrong when workflow paused?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5417]
### Description

State totals wrong, as reported by scanning, in paused workflows.

### Reproducible Example

(I've seen it with a bunch of workflows, however)

```ini
[scheduling]
   [[graph]]
      R1 = "a => b1 & b2 & b3 & b4"
[runtime]
   [[a, b1, b2, b3, b4, b5]]
       script = sleep $((RANDOM % 5))
```

Pause this while `b<m>` are running.  Scan reports several, but not all, of `b<m>` succeeding after the pause.

```console
$ cylc scan -t rich --colour-blind  # after all running tasks have succeeded
bgg/run8 (paused)
    state totals   running:2 succeeded:1
    title          *null*
    description    *null*
    version        8.2.0.dev
    host           NIWA-1022450.niwa.local
    port           43072
```

The GUI gscan sidebar is also wrong.  

`cylc dump -t` and `cylc tui`, and GUI workflow views correctly show no running tasks in the workflow.

Presumably the datastore is not correctly updating state totals data.

**Comment by dwsutherland** [comment]
Looks all the same to me..
![image](https://user-images.githubusercontent.com/11400777/226241603-469d85bc-f0bd-4a95-8231-47db451b08f9.png)

But, yes, tree in both tui and wui, and graphql show no tasks (at all).. It's likely that the summary isn't being updated for some reason under these circumstances...

**Comment by dwsutherland** [comment]
Thing is, we want to show the state of the tasks just before shutdown, correct?
It might come down to the order of operations.. usually we may want to exclude tasks bound for pruning.. So that might be why it doesn't get another update.. 
The summary is only updated once a main loop iteration at most, so by the time that comes around the tasks may be flagged for pruning..

Will investigate..

**Comment by dwsutherland** [comment]
Found the issue.. 
I'm deleting the deltas of tasks that are flagged to be pruned, to avoid processing/sending them... But this happens before the state totals are calculated.. It would usually only happen with isolates and end-of-chains/leaves where they finish and then get pruned straight away.

I think this was requested by the WUI devs, so they don't have to apply deltas and then prune them (or do things out of order)..

I should be able to put this deletion down the chain a little further..
