### ISSUE TITLE
TUI natural sort - negative numbers

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#5421]
_[Reported on Discourse](https://cylc.discourse.group/t/cylc-tui-display-order/611)_

TUI should sort negative numbers before positive ones even if they occur midway through the string. However, the current behaviour is:

![TUI screenshot](https://canada1.discourse-cdn.com/free1/uploads/cylc1/original/1X/1c2e080fa2c8ab2b0d6253a668ced8b27241c25b.png)

See https://github.com/cylc/cylc-flow/blob/6fc3c58b7798e95f0aa6b0ed18b70724a2309449/cylc/flow/tui/util.py#L192-L193

**Comment by oliver-sanders** [comment]
This is a little debatable because hyphen symbols are often used as separators. For example would it make sense to reverse sorting for:

```
generate-tide-1-day
generate-tide-2-day
generate-tide-3-day
```

???

**Comment by hjoliver** [comment]
Ha, this is a tricky one!

**Comment by hjoliver** [comment]
Note what the reporting user wanted was "definition order" - as ordered in the `flow.cylc`.

**Comment by ColemanTom** [comment]
Yes, I'm not fussed about the natural sorting, but in Cylc7, the default display order was the definition order, so we order tasks in either a logical order, or the order they run. If there were a dependency on `-4 => -3 => -2 => -1 => 0 => 1 => 2 => 3`, then its nicer to visualise the tasks in the order they run in.

**Comment by oliver-sanders** [comment]
@ColemanTom I don't think that definition order sorting is likely to come back.

It's not impossible, but it is difficult and computationally expensive.

**Comment by hjoliver** [comment]
I do think definition order is kind of a funny thing. 

Surely it's easier to have a sensible string-based ordering,and in complex workflows using filtering to find target tasks quickly. Not have to remember or look up the potentially arbitrary ordering in the source config file. 

And as for dependency ordering, that's what the graph view is for. It's not really a well defined thing for a linear tree or table view.

**Comment by oliver-sanders** [comment]
I think we're agreed that considering negative numbers in "natural sort" is dubious so closing this issue.

Definition order sort is tricky and potentially expensive as it would require the UIs to maintain a full task list which could be over a hundred thousand items long, so I won't open a new issue for this right now.
