### ISSUE TITLE
cat-log: tail process timeout

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5472]
The Cylc 8 GUI now has a log view which uses `cylc cat-log` to stream its log files.

Due to the changes in https://github.com/cylc/cylc-ui/pull/1275 (and its sibling PRs) the GUI is now able to detect the situation where the `cylc cat-log` process has died, offering the user the ability to re-connect with the file.

Providing the `cat-log` process dies when the `tail` does (which it should), this means that applying a timeout to the tail command should be a viable solution for Cylc 8.

### Problem

Those cat-log processes remain until the user closes the log view or changes file/task/whatever when it is killed. When the parent `cat-log` process is killed, the `tail` process it starts should die with it.

Two problems with this approach:

1. Sometimes killing the parent doesn't kill the children.
   * We have observed `tail` processes outliving the `cat-log` in the past for remote viewing (where `ssh` is involved).
   * This bug is unconfirmed at Cylc 8 but will likely still be possible.
2. Sometimes a `cat-log` might be left running longer than necessary.
   * I.E. user has a log view open in a browser tab they forgot about.

### Proposed Solution

Apply a timeout to the tail processes to kill them after a defined period. This can be done in one of two ways:

1. Via the global config.
   * This is already possible, we just need to confirm it works and document it.
2. Via `cat-log` directly.
   * I.E. add a `--timeout` option to `cat-log`.

### Context

As of https://github.com/cylc/cylc-ui/pull/1275 (and its sibling PRs) the GUI is now able to detect the situation where the `cylc cat-log` process has died, offering the user the ability to re-connect with the file.

See also the Cylc 7 issue here: https://github.com/cylc/cylc-flow/issues/3458

**Comment by MetRonnie** [comment]
> When the parent `cat-log` process is killed, the `tail` process it starts should die with it.

Note this is currently not the case. If `cat-log` is interrupted with Ctrl+C then the `tail` is killed, but if `cat-log` is killed or terminated, the `tail` is left behind

**Comment by oliver-sanders** [comment]
We have now added a timeout for the parent cat-log process from the UIS end: https://github.com/cylc/cylc-uiserver/pull/645

This should take the child process down with it. There has been some suggestion that child processes are sometimes left behind, however, this dates back to Cylc 7 and hasn't been reproduced recently. If this issue does reproduce, then we should look at re-opening this issue or attempting to fix the issue directly.
