### ISSUE TITLE
Remove or tweak `Prerequisites.set_not_satisfied()`

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5508]
https://github.com/cylc/cylc-flow/pull/5496#pullrequestreview-1403709237

 https://cylc.github.io/cylc-admin/proposal-cylc-set.html#un-setting-prerequisites

**Comment by oliver-sanders** [comment]
> checked and it's actually not used anywhere in Cylc 8. We should either remove it, or fix it

Given it's dead code I think we should probably remove it (easy to re-write). If we do need it again, then the new implementation will get to decide the behaviour in this niche case to suit its purpose.
