### ISSUE TITLE
cylc lint - S008 is used twice

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5540]
### Description

If you look at [the `cylc lint` docs](https://cylc.github.io/cylc-doc/8.1.4/html/user-guide/writing-workflows/configuration.html#s008), S008 is used twice. Once for the shebang line missing and once for line length.

![image](https://github.com/cylc/cylc-flow/assets/15375218/7f224224-3bec-46f0-a163-e3ea024796a6)

I'm raising the issue here as it is the code here which controls those documents. 

### Reproducible Example

See documentation.

### Expected Behaviour

S008 should only be for one item, not two. I'm guessing line length was 8, then it was commented out, then uncommented out but another entry had re-used S008. 

![image](https://github.com/cylc/cylc-flow/assets/15375218/f1f24874-32a6-4ba5-af4a-08447f37c358)

**Comment by oliver-sanders** [comment]
When fixing, please add a test to ensure lint codes are unique.
