### ISSUE TITLE
cylc lint - missing jinja2 shebang excessive warnings?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5541]
### Description

If you run `cylc lint` and it finds multiple `.cylc` files, it will want a `#!jinja2` line at the top of each of them if it detects jinja2 in there. Is this required, or should it only be required in the `flow.cylc` file? Looking at https://github.com/cylc/cylc-flow/issues/4917 - that reads as though it should be like I suggest, only for the top level file.

### Reproducible Example

```bash
touch flow.cylc
echo '{{a}}' > include.cylc
cylc lint
[S008] include.cylc:1: jinja2 found: no shebang (#!jinja2)
```
### Expected Behaviour

No warning as it is not the `flow.cylc` file.

**Comment by wxtim** [comment]
Cylc lint is meant to be agnostic of what the top-level file is - unlike Cylc validate it's meant to look at all `.cylc` files, without paying attention to what is and is not included - this is to prevent issues cropping up later if an include is switched on. 

I think, however, that it's probably reasonable to assume that if the top-level `flow.cylc` has a Jinja2 shebang then jinja2 is legitimate in all other files. If @oliver-sanders agrees with this assumption, I'll work out how to do it.

**Comment by oliver-sanders** [comment]
Yes, the easy solution suggested above is to only apply this rule when the file name is `flow.cylc` which *shouldn't* be true for include files.

**Comment by oliver-sanders** [comment]
This is actually the first point of https://github.com/cylc/cylc-flow/issues/4917#issue-1273707508

**Comment by MetRonnie** [comment]
@wxtim Did #5549 address this?
