### ISSUE TITLE
cylc lint - S007 and task parameters

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5558]
### Problem

I haven't checked, but I'm guessing the current implementation for S007 (lowercase family names) does not handle task parameters? My question is, should it gain the intelligence to expand task parameters and raise warnings if they are lowercase?

e.g. the below family `FOO` contains lowercase characters after expansion.

```
[task parameters]
    # parameters: "ship", "buoy", "plane"
    # default task suffixes: _ship, _buoy, _plane
    obs = ship, buoy, plane

[scheduling]
    [[graph]]
        R1 = "FOO<obs>:succeed-all => a"
```

### Proposed Solution

1. Look for FOO<obs> type syntax
2. Check what that expands to
3. If lowercase, raise a warning

But, with this approach, it means, if that task parameter is used in a task name, then the task would be a mixture of lowercase and uppercase letters. Typically I believe people tend to try to make tasks lowercase. So perhaps, task parameters could use an extension. I don't know the best way to do it, but something like

FOO<u:obs> would convert `obs` to uppercase, and `foo<l:obs>` could convert it to lowercase?

Or perhaps this is all not really worth pursuing as it raises these new areas of syntax complexity?

**Comment by oliver-sanders** [comment]
Already on it - https://github.com/cylc/cylc-flow/pull/5556
