### ISSUE TITLE
DB: `task_pool` table does not get updated upon stall

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#5598]
### Description

Running tasks that succeed before the scheduler realises that it has stalled at this point do not get updated in the `task_pool` table.

### Reproducible Example

```ini
[scheduling]
    [[graph]]
        R1 = foo & bar
[runtime]
    [[foo]]
        script = sleep 3
    [[bar]]
        script = false
```

After running this workflow you will see in the log
```
INFO - [1/bar running job:01 flows:1] => failed
WARNING - [1/bar failed job:01 flows:1] did not complete required outputs: ['succeeded']
INFO - [1/foo running job:01 flows:1] => succeeded
ERROR - Incomplete tasks:
      * 1/bar did not complete required outputs: ['succeeded']
CRITICAL - Workflow stalled
```

But
```console
$ sqlite3 .service/db 'select * from task_pool'
1|bar|[1]|failed|0
1|foo|[1]|running|0
```

If you issue a command e.g. poll `1/bar` then the `task_pool` table gets updated the `1/foo` disappears as expected.

### Additional context

A similar thing was reported in #5239:
> the DB revealed an inconsistency with a task marked as running in the `task_pool table`, despite the succeeded output being present in the `task_outputs` table

however in that case the stall was supposedly erroneous

**Comment by oliver-sanders** [comment]
Snippet obtained by `--main-loop='log db'` which shows that the `task_events` table is being updated, but the `task_pool` table isn't.

Probably just missing a DB call on task removal.

```sql
DELETE    
  FROM task_pool    
     
INSERT    
    OR REPLACE INTO task_pool    
VALUES('1', 'bar', '[1]', 'failed', 0)    
     
INSERT    
    OR REPLACE INTO task_pool    
VALUES('1', 'foo', '[1]', 'running', 0)    
     
DELETE    
  FROM task_prerequisites    
     
UPDATE task_states    
   SET time_updated = '2023-07-05T11:52:47+01:00',    
       submit_num = 1,    
       status = 'failed'    
 WHERE name == 'bar'    
   AND CYCLE == '1'    
   AND flow_nums == '[1]'    
     
DELETE    
  FROM task_timeout_timers    
     
COMMIT    
     
BEGIN    
     
INSERT    
    OR REPLACE INTO task_events    
VALUES('foo', '1', '2023-07-05T11:52:48+01:00', 1, 'succeeded', '')    
     
UPDATE task_jobs    
   SET time_run_exit = '2023-07-05T11:52:48+01:00',    
       run_status = 0    
 WHERE CYCLE == '1'    
   AND name == 'foo'    
   AND submit_num == 1    
   AND flow_nums == '[1]'    
     
UPDATE task_outputs    
   SET outputs = '["submitted", "started", "succeeded"]'    
 WHERE CYCLE == '1'    
   AND name == 'foo'    
   AND flow_nums == '[1]'    
     
UPDATE task_states    
   SET time_updated = '2023-07-05T11:52:48+01:00',    
       status = 'succeeded',    
       flow_wait = 0,    
       is_manual_submit = 0    
 WHERE name == 'foo'    
   AND CYCLE == '1'    
   AND flow_nums == '[1]'    
   AND submit_num == 1    
     
COMMIT   
```

**Comment by oliver-sanders** [comment]
This is due to the way that we detect task pool updates, which currently involves looking for tasks with the `is_updated` flag. In this case a task has been removed from the pool so there is no task_proxy to present an `is_updated` flag:

https://github.com/cylc/cylc-flow/blob/125c4434f863cdcf3cabf0d088931684ac5a001a/cylc/flow/scheduler.py#L1690-L1711
