### ISSUE TITLE
pool: infinite loop on startup

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5603]
This workflow:

```
[scheduler]                    
    allow implicit tasks = True    
                               
[scheduling]                   
    initial cycle point = 2000    
    runahead limit = P2Y       
    [[graph]]                  
        R1/2000 = a            
        P1Y = b[-P1Y] => b 
```

When run like this:

```console
cylc play --start-cycle-point=2005
```

Will get stuck in an infinite loop on startup during which it will not log any messages. This happens before the contact file is written making it look like the scheduler isn't running which can result in multiple schedulers running for the same workflow.

**Comment by hjoliver** [comment]
Yikes, good catch.
