### ISSUE TITLE
Faster task menu navigation (set outputs)

### ISSUE THREAD

**Issue by SGallagherMet** [cylc/cylc-flow#5607]
### Problem

When I'm working on a new branching workflow I like to test it by running the suite in simulation or dummy mode and manually setting outputs. Currently this is cumbersome as there are a large number of steps required.

To set a task to succeed.

click task -> click see more -> scroll down -> click set outputs

To set a task to failed
click task -> click see more -> scroll down -> click the edit button on set outputs -> type failed  -> scroll down -> click ok

### Proposed Solution

1. Automatically expand the menu when the mouse wheel is scrolled (instead of clicking on "see more")
2. Add buttons for frequently used options to the menu items. In the example above this would mean an option to set the output to succeeded or failed directly in the menu, without having to open the edit box.

This would mean the sequence of events to set the output would be:
click task -> scroll down -> click to set output to failed or succeeded

**Comment by SGallagherMet** [comment]
Apologies, I created this on the wrong repository. I've now created https://github.com/cylc/cylc-ui/issues/1364

**Comment by wxtim** [comment]
> Apologies, I created this on the wrong repository. I've now created [cylc/cylc-ui#1364](https://github.com/cylc/cylc-ui/issues/1364)
