### ISSUE TITLE
Workflow contact UUID changes on restart

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#5615]
When restarting a workflow, the contact file UUID does not match the database UUID. But it is supposed to preserve the UUID from the DB.

A new UUID is always created at `Scheduler.__init__()` which seems dodgy:
https://github.com/cylc/cylc-flow/blob/125c4434f863cdcf3cabf0d088931684ac5a001a/cylc/flow/scheduler.py#L279

(This compounded with https://github.com/cylc/cylc-uiserver/pull/463, causes workflows played in the UI to appear remaining as stopped when they have started)

**Comment by oliver-sanders** [comment]
With https://github.com/cylc/cylc-uiserver/pull/463, this should be symptomless until we start making better use of offline data in the GUI.
