### ISSUE TITLE
set: implement the new command

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5642]
Implement accepted proposal [A New Command for Manual Task Forcing](https://github.com/cylc/cylc-admin/blob/master/docs/proposal-cylc-set.md).

* Rename `set-outputs` to `set`.
* Implement the logic for setting prereqs/outputs as per the proposal.
* Update the CLI and GraphQL schema (test this works as expected in the ui).
* Update documentation.
* This is a breaking change, add an entry into the cylc-doc changes page.

**Comment by hjoliver** [comment]
I'm currently working on this.

Subject to discussion, I've changed the new command name to `cylc set-task`.
- there's a CLI ambiguity problem (set-verbosity)
- plain `set` is arguably not specific enough
