### ISSUE TITLE
Bad recurrence exclusion warning

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5659]
See https://cylc.discourse.group/t/cannot-have-more-than-1-repetition-for-zero-duration-recurrence/705/13
```ini
[scheduler]
    cycle point format = %Y
[scheduling]
    initial cycle point = 3000
    [[graph]]
        P1Y ! ^ = "foo[-P1Y] => foo"
[runtime]
    [[foo]]
```

Validation:
```console
$ cylc validate bug
WARNING - Cannot have more than 1 repetition for zero-duration recurrence 3000.
Valid for cylc-8.3.0.dev
```
The warning refers to the exclusion point `^`.

**Comment by oliver-sanders** [comment]
@hjoliver, is the issue that the error message is wrong (i.e. "Must have **more** than 1 repetition..."), or would we rather let Cylc silently ignore the null-recurrence?

**Comment by hjoliver** [comment]
Maybe I've misunderstood how exclusions are supposed to work, but it seems to me that this:
```
P1Y !^ = ...
```
should represent a single-point exclusion - not a broken recurrence exclusion - in which case there should not be any warning message. ??

**Comment by oliver-sanders** [comment]
I think I thought that `P1Y` was `R1` for some reason.

Yes, `P1Y!^` should work, `T00!^` is a documented example, possibly a more recent breakage?

**Comment by oliver-sanders** [comment]
This warning is coming from parsing the exclusion itself, you'll get the same warning if you do:

```ini
[scheduling]
  [[graph]]
    ^ = foo # "^" gets replaced with "3000" in this case
```

The correct way of writing it is like this:

```ini
[scheduling]
  [[graph]]
    R1/^ = foo
```

And for the exclusion example:

```ini
[scheduling]
  [[graph]]
    P1Y ! R1/^ = foo
```

**Comment by oliver-sanders** [comment]
When we parse an exclusion, we first attempt to parse it as a sequence, then fall back to parsing it as a point.

It's this first attempt at parsing which causes the zero-duration warning. I've raised a PR to suppress this logging for exclusion parsing.

**Comment by oliver-sanders** [comment]
> However, going by your last comment and new PR, you've come to the same conclusion yourself

...and being the author of that functionality...
