### ISSUE TITLE
Clock-expire documentation inconsistency

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#5668]
In the reference it says

> The expiry time is specified as an offset from wall-clock time; typically it should be **negative** - see [Clock-Expire Triggers](https://cylc.github.io/cylc-doc/latest/html/user-guide/writing-workflows/scheduling.html#clockexpiretasks).

https://cylc.github.io/cylc-doc/latest/html/reference/config/workflow.html#flow.cylc[scheduling][special%20tasks]clock-expire

Whereas in the user-guide it says

> The offset should be **positive** to make the task expire if the wallclock time has gone beyond the cycle point.

https://cylc.github.io/cylc-doc/latest/html/user-guide/writing-workflows/scheduling.html#clockexpiretasks

Also it's not clear what a negative offset means IMO.

**Comment by oliver-sanders** [comment]
I've found these offsets confusing too. Might be worth looking at clock-trigger offsets also.

**Comment by oliver-sanders** [comment]
Closed by #5674
