### ISSUE TITLE
missing dependencies involving task parameters and multiple dependencies grouped together in a graph

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5670]
### Description

Task prerequisites are missing (for all cycles although examples below only highlight the first cycle) when you have triggers like `a<hh_short-1,mbr> => a<hh_short,mbr> => b<hh_short, mbr>` on one line but works correctly if made two lines

```
a<hh_short-1,mbr> => a<hh_short,mbr>
a<hh_short,mbr> => b<hh_short, mbr>
```

### Reproducible Example

Example flow.cylc file:

```
$ cat flow.cylc
#!jinja2
[cylc]
    allow implicit tasks=True
    UTC mode = True
    [[parameters]]
        short_hours = 000,012
        hh_long   = _000,_012,_024
        hh_short  = _000,_012
        mbr       = gl
    [[parameter templates]]
        short_hours  = _%(short_hours)03d
        hh_long      = %(hh_long)s
        hh_short     = %(hh_short)s
[scheduling]
    initial cycle point = 20200101T0000Z
    final cycle point = 20200101T1200Z
    [[dependencies]]
        [[[R1]]]
            graph = ic => wait<hh_long=_000,mbr>
        [[[T00,T06,T12,T18]]]
            graph = """
                a_000<mbr>[-PT6H] => a_000<mbr>
                a<hh_short-1,mbr> => a<hh_short,mbr> => b<hh_short, mbr>
                b<hh_short,mbr> => c<hh_short,mbr>
            """
        [[[T00,T12]]]
            graph = """
                  a<hh_long-1,mbr> => a<hh_long,mbr> => b<hh_long,mbr>
                  b<hh_long,mbr> => c<hh_long,mbr>
            """

[runtime]
    [[root]]
        script = false
```

Example to execute

```
CYLC_VERSION=8.2.0 cylc vip .
cylc show workflow/run1 //20200101T0000Z/b_000_gl
```

The below alternative produces the same result, with missing prereq's.

```
                a<hh_short-1,mbr> => a<hh_short,mbr>
                    => b<hh_short, mbr>
````

Using `+1` instead of `-1` shows similar behaviour.

As does having the paramater offset in a different order: `a<hh_short,mbr> => a<hh_short-1,mbr>`

### Expected Behaviour

There should be prerequisites listed of `a_000_gl`.

Instead I see:

```
$ CYLC_VERSION=8.2.0 cylc show basic-workflow/run2 //20200101T0000Z/b_000_gl
title: (not given)
description: (not given)
URL: (not given)
state: failed
prerequisites: (None)
outputs: ('-': not completed)
  - 20200101T0000Z/b_000_gl expired
  + 20200101T0000Z/b_000_gl submitted
  - 20200101T0000Z/b_000_gl submit-failed
  + 20200101T0000Z/b_000_gl started
  - 20200101T0000Z/b_000_gl succeeded
  + 20200101T0000Z/b_000_gl failed
```

If `a<hh_short-1,mbr> => a<hh_short,mbr> => b<hh_short, mbr>` and the equivalent `long` line are split over two lines as non-continuing entries:

```
wait<hh_short-1,mbr> => wait<hh_short,mbr>
wait<hh_short,mbr> => pp2grb2<hh_short, mbr>
```

The the correct prerequisites appear.

**Comment by oliver-sanders** [comment]
This is the correct behaviour due to the out-of-bounds parameter.

For more information see: https://cylc.github.io/cylc-doc/stable/html/7-to-8/major-changes/parameters.html

**Comment by ColemanTom** [comment]
Is it though? I show that positive offsets have the same requirements to split the command up. I did not realise the negative offset one, but it affects positive offsets too.
