### ISSUE TITLE
Clearer message for task not found in n=0

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5678]
From @ColemanTom on Discourse, when trying to target a future task with `cylc show`:

> It currently says that No matching n=0 tasks found: 20200101T0000Z/b_024_gl which, I don’t really understand. 

When/if a task really has to be active to satisfy a query, something like this would put less cognitive load on the user:

*20200101T0000Z/b_024_gl  is not active*.

And/or, to distinguish from requesting a non-existent task definition:

*20200101T0000Z/b_024_gl  not found in the workflow graph*

See also #5677

**Comment by oliver-sanders** [comment]
Merge with #5695?

**Comment by hjoliver** [comment]
Well this issue is really just a trivial matter of wording - the meaning of "active" is more intuitively obvious than "n=0".  Users need to know what `n` means in other contexts, but that doesn't mean we should use the term where "active" would suffice. I guess I muddied the waters a bit by suggesting the future graph bit as well.

**Comment by hjoliver** [comment]
In fact it's even more trivial than I thought - that message comes from the `cylc show` script, not the the task pool.

**Comment by oliver-sanders** [comment]
Closed by #5700
