### ISSUE TITLE
family hold beyond n=0

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5695]
Currently `cylc hold ARG` works to hold:
- future tasks, if ARG is a specific task ID
- waiting tasks in the scheduler task pool, if ARG is  a _glob_ or a *family* name

@ColemanTom wants to hold a whole family in advance - i.e. not just the family members, if any, currently in the pool. 

https://cylc.discourse.group/t/how-to-rewind-workflow-not-to-a-checkpoint/719 

It's not necessarily easy to figure out all the individual task IDs and hold them separately.

**Comment by hjoliver** [comment]
From #4246 



Me:
> >   Presumably we could figure out what the matched tasks or family members will be, and put those in the future hold list.

@oliver-sanders:
> The suggestion of expanding families is orthogonal and was previously rejected due to issues with multiple flows and graph branching.

I've kinda forgotten that conversation, sorry Oliver. But maybe we made the wrong call (or you can correct me again).

> It is possible of course, but would require more thought, for consistency it should apply to all of the "task glob" commands, but we would need to think about how that would interact with cylc reset, there may be a housekeeping problem with graph branching (if an action is run against a task which isn't run, then we will accumulate messages causing a slow memory leak unless housekept), and if expanding families, why not cycles?

We could, initially at least, only implement this for families.  A family name is simply than a glob, and less risky. There's no wildcard involved, the members are well-defined. 

Ideally we could do it with globs too, but there is as clear use case (as raised by Tom) for family hold, and we could implement that first.

The other issue you raise there also applies to individual tasks, right?  I can hold a future task, by ID, that might not ever appear in the pool because of future graph branching. If we don't make housekeeping possible somehow, that would cause a memory leak (the list of future tasks to hold), but any such leak should be small and inconsequential - it would only grow as a result of a small number of manual intervention commands.

**Comment by oliver-sanders** [comment]
IMO, we should come up with a general policy for all these commands rather than working around the limitations in each command individually e.g. #5677.

**Comment by hjoliver** [comment]
> IMO, we should come up with a general policy for all these commands rather than working around the limitations in each command individually e.g. #5677.
>
> If we are going to address this we should come up with a consistent approach which works for the relevant commands so we can implement and document it consistently rather than hashing out the details for each command separately.

If possible, but issues typically first come to light with individual commands - particular when reported by users as is the case with all of these - and need to be documented (Issues posted, I mean) as they arise. We can certainly consolidate and triage later, if appropriate.

And in the context of this particular issue, "hold" is kind of a special case - we can already hold future tasks individually, which means maintaining a list of future tasks that will be held if/when they get spawned. The problem is simply that we need to be able to hold future tasks collectively - by family name or pattern match.

I can't see much commonality with the other commands you've listed above, in terms of teeing up future behaviour.

 >  Note, currently only the "trigger" command will auto-spawn a task.

And `set-outputs` (soon to be `set`).

**Comment by hjoliver** [comment]
Superseded by #5827
