### ISSUE TITLE
Lint: Better indentation handling

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#5767]
### Problem

Cylc Lint's indentation handling only compares number of `[` to indentation for sections.

Now Lint has access to the Spec it should be able to infer the correct indentation for any non-duplicate section. Even then if sections like 'handlers' should be ok because both workflow and task handlers should have the same indentation.

**Comment by oliver-sanders** [comment]
If we implement the logic to identify invalid sections e.g. `[schdulng]`, then this should ensure the number of `[`'s is correct, which should ensure the indentation is correct.

**Comment by wxtim** [comment]
> If we implement the logic to identify invalid sections e.g. `[schdulng]`, then this should ensure the number of `[`'s is correct, which should ensure the indentation is correct.

We already check whether the number of `[` matches the indentation, what we don't check is whether key value pairs are indented correctly; Lint will not spot:

```ini
[scheduler]
        allow implicit tasks = false  # Eight spaces
```

**Comment by oliver-sanders** [comment]
It's doable, but tricky because of Jinja2. E.G. a lot of people will do this:

```
# the indentation is nicer before processing
{% for x in y %}
    {{ x }}
{% endfor %}
```

Rather than this:

```
# the indentation is nicer after processing
{% for x in y %}
{{ x }}
{% endfor %}
```

**Comment by wxtim** [comment]
> It's doable, but tricky because of Jinja2. E.G. a lot of people will do this:

In the first instance I would suggest that we should test whether `indent_size % 4 == 0` - I'm sure I tested this, but it seems to have gone missing.

In the second instance, we can at least say that a given item should not be less indented than X - e.g. `initial cycle point` should be indented _at least_ 4 spaces.

**Comment by wxtim** [comment]
#5772  Is probably the best we can do for now?
