### ISSUE TITLE
Run mode not conserved on restart

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#5781]
> check that restarting a workflow that has been running in simulation mode will restart it in simulation mode without having to specify it?
> Oliver said trying to restart in simulation mode when it had been running in live mode merely restarted in live mode.

When I tried this on master it looks like it restarts in simulation mode (on master & my branch). Ick.

That's a bug.

_Originally posted by @wxtim in https://github.com/cylc/cylc-flow/issues/5712#issuecomment-1772387213_

Example

```ini
# flow.cylc
[meta]
    purpose = """
        run this workflow with --mode live or no mode argument.

        This workflow tests whether restart maintains run mode.
        To demonstrate that task bar is run in sim mode either:

        * Check for log files for job bar (which sim mode doesn't make)
        * Add code such as

            tasks_log_list = '\n * '.join([tdef.name for tdef in taskdefs])
            LOG.debug(f'setting up {sim_mode} for tasks:\n {tasks_log_list}')

          to the method `configure_sim_modes`.
    """

[scheduler]
    allow implicit tasks = True

[scheduling]
    [[graph]]
        R1 = foo => bar

[runtime]
    [[root]]
        execution time limit = PT30S
        script = """
            sleep 20
            echo "RAN FOR REAL"
        """
    [[foo]]
        script = """
            cylc stop "${CYLC_WORKFLOW_ID}" --now --now
            while [[ ! $(grep 'INFO - DONE' "$CYLC_WORKFLOW_RUN_DIR/log/scheduler/log") ]]; do
                sleep 2
            done
            cylc play "${CYLC_WORKFLOW_ID}" --mode simulation
        """
        [[[meta]]]
            plain english = stop the workflow, and restart it in simulation mode
```

**Comment by MetRonnie** [comment]
I think this issue needs a bit of clarification. There are two cases we need to define the behaviour for:
- Starting a workflow in simulation mode; stopping it; restarting it without specifying a mode 
- Starting a workflow in live mode; stopping it; restarting it with `--mode=simulation`

**Comment by wxtim** [comment]
> Starting a workflow in simulation mode; stopping it; restarting it without specifying a mode 

I think the run mode should conserve across restarts.

**Comment by hjoliver** [comment]
> Starting a workflow in simulation mode; stopping it; restarting it without specifying a mode
> 
>    What should the behaviour be?

I agree with @wxtim - it should restart in sim mode

> Starting a workflow in live mode; stopping it; restarting it with --mode=simulation
> 
>     If it restarts in live mode that's a bug

Agreed.

**Comment by wxtim** [comment]
I ended up with this table:
```
+--------------------+--------+-------+-------+
| ↓restart \ start → | live   | sim   | dummy |
+====================+========+=======+=======+
| live               | live   | sim * | ???   |
| sim                | live * | sim   | ???   |
| dummy              | ???    | ???   | dummy |
+--------------------+--------+-------+-------+


* A warning ought to be emitted, since we're discarding user input.
```

Questions -

* Do we want to test Dummy mode restarts too?
* Should we warn or hard-fail if users set a `--mode=?` which we won't respect?

**Comment by hjoliver** [comment]
> Should we warn or hard-fail if users set a --mode=?

hard fail

**Comment by hjoliver** [comment]
IMO same goes for dummy mode as for sim mode.  They're really the same thing, with respect to live mode.  Neither one runs real tasks that generate real outputs, which is what matters if you want to restart in a different mode.

**Comment by MetRonnie** [comment]
Some options like `--icp` cause the `cylc play` command to exit 1 on restart with a suitable error message. Are you proposing doing the same thing for `--mode`?

**Comment by wxtim** [comment]
> Some options like `--icp` cause the `cylc play` command to exit 1 on restart with a suitable error message. Are you proposing doing the same thing for `--mode`?

Yes. I think it's much nicer than carrying on doing something the user has every reason not to expect.

**Comment by wxtim** [comment]
However, @hjoliver  - does it make sense to stop people restarting in a different mode if we're going to allow them to override live mode by broadcasting to tasks?
