### ISSUE TITLE
'InputError: max rotation -1' error after 'cylc clean'

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc-flow#5816]
hi there, 

posting this with reference to [this ](https://cylc.discourse.group/t/cylc-run-myworkflow-runn-not-recreated-after-cylc-clean/803) question on the cylc discourse forum...

if i run cylc clean on the most recent instance of a workflow then i’ve noticed that the symbolic link called runN is not recreated after the clean and this seems to cause an error.

for example…
```
> cylc vip
[launches run1]
> cylc vip
[launches run2]
> cylc stop  -k foo/run2
> cylc clean -y foo/run2
> cylc log foo
InputError: max rotation -1
```

shouldn’t the runN sym link in ~/cylc-run/foo be recreated and point to run1?

cheers,

**Comment by hjoliver** [comment]
It's debatable whether the runN link should be recreated (should the "latest run" decrement if the actual latest run(s) get deleted? - probably not).

But either way the error message is unhelpful and wrong.

**Comment by jonnyhtw** [comment]
@hjoliver would a more helpful error be something as simple as...

`log file for runN not available`

?

**Comment by jonnyhtw** [comment]
![image](https://github.com/cylc/cylc-flow/assets/12940715/31f5cfb4-75fa-4f28-ab15-c441e65abc83)

**Comment by hjoliver** [comment]
Lemme think about that @jonnyhtw (no time this arvo). It seems to me we should be able wind back a step and check that the `runN` link exists in the first place, to get a more sensible message.

**Comment by jonnyhtw** [comment]
> Lemme think about that @jonnyhtw (no time this arvo). It seems to me we should be able wind back a step and check that the `runN` link exists in the first place, to get a more sensible message.

sounds good 😄

**Comment by oliver-sanders** [comment]
Main point, replace the cryptic `max rotation -1` with `no file found` or something like that

`cylc log foo` would normally resolve to `cylc log foo/runN` unless you've deleted the latest run but not the previous ones.
