### ISSUE TITLE
cylc set-verbosity does not set CYLC_DEBUG

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#5829]
If I run a workflow using `--debug` then in the job scripts I get `export CYLC_VERBOSE=true` and `export CYLC_DEBUG=true`. However, if I run the workflow at normal verbosity and then set it to debug using `cylc set-verbosity` only `CYLC_VERBOSE` gets set to true in the job scripts (`CYLC_DEBUG` remains false).

`--debug` is defined as equivalent to `-v -v` in the `cylc play` help (i.e. it is just a verbosity level) so I would expect `cylc set-verbosity DEBUG` to result in `export CYLC_DEBUG=true` in the job scripts.

**Comment by oliver-sanders** [comment]
Context:

In debug mode the `CYLC_DEBUG` environment variable gets set to `true` which turns on some extra debugging.

The following two commands are identical:

```
$ cylc <command> -v -v
$ cylc <command> --deubg
```

The `cylc set-verbosity` command allows you to change the verbosity argument whilst the scheduler is running.

This is the code that gets run as a result of a `cylc set-verbosity` call:

https://github.com/cylc/cylc-flow/blob/b1342972b1d77257cb09dea7fb436ac75f0fddf1/cylc/flow/scheduler.py#L1068-L1075

This is the code that turns the verbosity into the `CYLC_DEBUG` environment variable:

https://github.com/cylc/cylc-flow/blob/b1342972b1d77257cb09dea7fb436ac75f0fddf1/cylc/flow/job_file.py#L176-L177

**Comment by oliver-sanders** [comment]
Minimal example to test:

```ini
[scheduling]
    [[graph]]
        R1 = test

[runtime]
    [[test]]
         script = echo "CYLC_DEBUG=$CYLC_DEBUG"
```

**Comment by oliver-sanders** [comment]
Closed by https://github.com/cylc/cylc-flow/pull/5854
