### ISSUE TITLE
graph parser: absolute dependency offset on the RHS

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5844]
At Cylc 7, absolute cycle points on the RHS of an expression resulted in a GraphParseError, e.g:

```
crunch_numbers => collate_results[2003]
```

Would result in:

```
GraphParseError: ERROR, illegal cycle point offset on the right: crunch_numbers  =>  collate_results[2003]
```

Whereas at Cylc 8 the error is not raised and the `=> collate_results[2003]` dependency is ignored.

**Comment by wxtim** [comment]
At Cylc 7 _ALL_ cycle points on the RHS of an expression were illegal, not just absolute ones.

**Comment by oliver-sanders** [comment]
> The original check was removed at:
https://github.com/cylc/cylc-flow/pull/4343/files#diff-71ac7d6076a521f20d45c1d1e06c9bfc8069d38f2b90ece99ef2d0f9434236feR104

@wxtim, I don't think that link is correct.

**Comment by wxtim** [comment]
> > The original check was removed at:
> > https://github.com/cylc/cylc-flow/pull/4343/files#diff-71ac7d6076a521f20d45c1d1e06c9bfc8069d38f2b90ece99ef2d0f9434236feR104
> 
> @wxtim, I don't think that link is correct.

I think it is, but it's hidden behind a "large diffs are not displayed".

**Comment by oliver-sanders** [comment]
These lines:

https://github.com/cylc/cylc-flow/pull/4343/files#diff-be87b3fcb20fc3228166ad53af61efb79f0d0c84ee01fcd0c9e3092c788e0b93L374-L377

?

**Comment by wxtim** [comment]
> That link is for some timer code.
> 
> These lines:
> 
> https://github.com/cylc/cylc-flow/pull/4343/files#diff-be87b3fcb20fc3228166ad53af61efb79f0d0c84ee01fcd0c9e3092c788e0b93L374-L377
> 
> ?

Can I show you in person?
