### ISSUE TITLE
Don't record satisfied clock triggers in the DB 

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5911]
Currently all satisfied xtriggers get stored in the DB xtriggers table. This includes clock triggers, and "retry delay" triggers (which are implemented via clock triggers).

These really don't need to be stored in the DB
- clock triggers will likely be the main cause of xtrigger table bloat
- calling a clock trigger again unnecessarily, e.g. after restart, is quick (i.e. it doesn't matter) - a synchronous wall-time check, not an asynchronous sub-process call like for other xtriggers

**Comment by wxtim** [comment]
I think I've done this, and I'm just writing tests for it, but I'll be refraining from pushing a branch util https://github.com/cylc/cylc-flow/pull/5908 is in on master.
