### ISSUE TITLE
Start paused or held, then manually trigger individual tasks

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5912]
See https://cylc.discourse.group/t/is-it-not-possible-to-trigger-a-task-while-paused/853

At the moment I think we have to use `--hold-after=P` with P earlier than the initial point.

Can we:
- allow triggering of individual tasks when the workflow is paused
and/or
- new `cylc play --hold-all` option, to start with all tasks held (at least all initial tasks, and possibly all future tasks kind of like the way hold-after-point works)

**Comment by oliver-sanders** [comment]
This does it:

```
cylc play --pause
cylc hold '*'
cylc play
```

IMO this is sufficient.

**Comment by hjoliver** [comment]
Yeah I commented on that on the thread (before I saw your response here). 

I think that's fine so long as users understand:
- why it works 
- why that only holds the initial tasks, not future ones
- and (relatedly) why `cylc hold '*'` seemingly does nothing if the workflow isn't started with `--pause`

All of which isn't exactly intuitively obvious to most users. 

It's our usual problem, that the old Cylc 7 task pool, as inconsistent and un-justified as it was, happened to have enough pre-spawned tasks in it that `cylc hold` seemed to do what they naively expected most of the time.

**Comment by oliver-sanders** [comment]
At present the best way to do this is using the "hold after cycle point" as this ensures that any tasks spawned by the triggered task are also held.

Documenting that intervention here: https://github.com/cylc/cylc-doc/pull/739

With #5827 this issue will go away, so it's a simple hold all, trigger, release all.

If we're ok with this, suggest superseding with #5827

**Comment by hjoliver** [comment]
Hold-after-cycle-point is really not intuitive for this use case, but I'm OK with superseding this so long was we can get `cylc hold '*'` done pretty soon (and documenting the current intervention is good).
