### ISSUE TITLE
batched job polling?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#5941]
Apparently, polling individual jobs can stress a resource manager if there's a large number of them. 

From a colleague:
> To avoid spamming the slurm controller, in snakemake they use a kind of cache where they store the state of jobs returned by slurm (squeue or sacct) once every minute, all requests per job access the cache to avoid overloading slurm.

Potentially, we could do that, and only target individual jobs once they change status or disappear from the general list.

**Comment by hjoliver** [comment]
> If you want to see (and "borrow" + improve ) the snakemake caching implementation https://github.com/Snakemake-Profiles/slurm/blob/master/%7B%7Bcookiecutter.profile_name%7D%7D/slurm-sidecar.py

**Comment by oliver-sanders** [comment]
We already have batched polling logic.

Slurm polling is setup with this command:

https://github.com/cylc/cylc-flow/blob/efb3016cf96c6db2d3be2f0818cd661e9bc788b0/cylc/flow/job_runner_handlers/slurm.py#L124-L126

Which is provided with a list of the job IDs we are interested in:

https://github.com/cylc/cylc-flow/blob/efb3016cf96c6db2d3be2f0818cd661e9bc788b0/cylc/flow/job_runner_mgr.py#L489-L491

`POLL_CMD` docs: https://cylc.github.io/cylc-doc/stable/html/plugins/job-runners/index.html#cylc.flow.job_runner_handlers.documentation.ExampleHandler.POLL_CMD

**Comment by hjoliver** [comment]
👍  Ah, sweet, I forgot about that.
