### ISSUE TITLE
pre-initial: inconsistent handling for format 4 reccurences

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5946]
The pre-initial condition is handled differently for some recurrences to others.

E.G:

```ini
[scheduler]
    cycle point format = CCYY
    allow implicit tasks = True

[scheduling]
    initial cycle point = 2000
    final cycle point = 2010
    [[graph]]
        # cycle forwards
        R3/2000/P1Y = f[-P1Y] => f

        # cycle backwards
        R3/P1Y/2010 = b[-P1Y] => b
```

The pre-initial condition is applied to the first recurrence, but not to the second:

![graph](https://github.com/cylc/cylc-flow/assets/16705946/5e7c3481-5af8-4d14-b3ef-1d8432878d09)

This behaviour appears consistent with Cylc 7 but doesn't make a whole lot of sense.

See also https://github.com/cylc/cylc-flow/issues/5945

**Comment by hjoliver** [comment]
I haven't looked at the code yet, but it might suggest a problem identifying the "first point" in the (so-called) backward recurrence. Or the "first point after the initial cycle point" ...

**Comment by oliver-sanders** [comment]
I tried jamming in a `P1Y` recurrence to check that the issue wasn't an interaction with the runahead limit, but it behaved the same.

**Comment by hjoliver** [comment]
See the discussion on #5945 - if I haven't got my wires badly crossed, this didn't work in Cylc 7 either, because pre-initial ignore of inter-cycle deps was only ever for the workflow ICP, it wasn't applied to individual sequences that start after the ICP.

**Comment by oliver-sanders** [comment]
> This didn't work in Cylc 7 either

Please see the description above where I wrote:

> This behaviour appears consistent with Cylc 7 but doesn't make a whole lot of sense.

I think you've got muddled between the two issues. These may have the same underlying cause but I've written them up separately from the perspective of behaviours.

**Comment by hjoliver** [comment]
So is your main point here essentially a duplicate of #1936 ?

**Comment by oliver-sanders** [comment]
Yes, gotcha.
