### ISSUE TITLE
New variable like ROSE_DATAC?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5960]
### Problem

I use `ROSE_DATAC` a lot. I'm going to guess many other people do too. I feel like it would be logical for Cylc to have its own variable which is similar as I'm sure people who do not use `rose` would reference that path a lot too. Yes, it is very easy to construct it oneself, but it feels reasoanble to have it built-in with Cylc.

### Proposed Solution

Add a new variable, perhaps `CYLC_CYCLE_SHARE_DIR` (and perhaps a work equivalent, `CYLC_CYCLE_WORK_DIR`) which is `${CYLC_WORKFLOW_SHARE_DIR}/${CYLC_TASK_CYCLE_POINT}`.

**Comment by MetRonnie** [comment]
What is the use case for `CYLC_CYCLE_WORK_DIR`? Note there is already `CYLC_TASK_WORK_DIR` which is `<workflow-run-dir>/work/<cycle>/<task>`

**Comment by dpmatthews** [comment]
Note that:
* `rose task-env` also creates the directories (not sure this is made clear in the documentation).
* Additional `ROSE_DATAC????` variables are supported for cycle time offsets - I think this is an important part of the functionality.

See https://metomi.github.io/rose/doc/html/api/command-reference.html#rose-task-env

We could support this directly in Cylc.
However, given that there are no real barriers to using Rose with Cylc 8, I see this as very low priority.

**Comment by hjoliver** [comment]
In principle Cylc should support this directly, but for the moment I agree with Dave (priorities). It's easy enough to use Rose or to roll your own cycle-specific share directories.

**Comment by ColemanTom** [comment]
Sorry, for some reason I did not see the responses, lost in my email I guess.

I'll close this. I did not realise it was `rose` making the directories, and I definitely can imagine (maybe have) use cases where the `share/cycle/CYCLEPOINT` directory is not relevant to the system, so making the directory doesn't seem ideal, but if this variable existed, people would assume it would.
