### ISSUE TITLE
help text oddity in `-z` option for cylc play

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5964]
### Description

Look at https://github.com/cylc/cylc-flow/blob/master/cylc/flow/option_parsers.py#L340-L341 - I am struggling to understand the meaning of the `+s` and `+ s` in the help text. I'm guessing its a bug from something, but if it has some special meaning it would be great to know what it is (or have it fixed if it is a bug).

**Comment by oliver-sanders** [comment]
Closed by #5970
