### ISSUE TITLE
VR: Check workflow stopped if updating template vars from plugin

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#5966]
Ref: https://cylc.discourse.group/t/jinja2-variable-differences-in-config-files-new-ones-are-not-being-respected/885
Ref: https://github.com/cylc/cylc-flow/pull/5297

### Description

VR check whether template variables have been changed using the CLI and raises an error if the workflow is running.

If you change the template variables using a plugin, however, this check is not carried out. 

The check is currently carried out here:
https://github.com/cylc/cylc-flow/blob/57fe4ae7e1a65d82ac650c596a2f4fdb4b49abf1/cylc/flow/scripts/validate_reinstall.py#L102

### Reproducible Example

```
#!jinja2
# flow.cylc
[scheduler]
    allow implicit tasks = True
[scheduling]
    initial cycle point = 1000
    [[graph]]
        R1 = {{task}} => bar
```

```
cylc vip workflow --pause -S 'task="foo"'
cylc vr workflow --pause -S 'task="bar"'

# Witnesss that change hasn't happend after the reload.
grep "R1 =" ~/cylc-run/basic.stone/runN/log/config/*

cylc stop workflow

cylc vr workflow --pause -S 'task="bar"'

# OK now
grep "R1 =" ~/cylc-run/basic.stone/runN/log/config/*
```

**Comment by wxtim** [comment]
I'm actaully not sure that this is correct. Re-install takes `-S` but not `-s`.

The real question is whether it all behaves as expected and there are no nasty surprises for the user. I'm going to develop a couple of tests which will attempt to quantify what is going on.

**Comment by oliver-sanders** [comment]
The `-S` option applies to (re)install, so you should be able to use it for both cases.

I.E. I think this is a bug not a lack of CLI validation. So closing this as superseded by https://github.com/cylc/cylc-flow/issues/5968

Please reopen if I've got the wrong end of the stick.
