### ISSUE TITLE
event handlers: add configurable timeout

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5980]
Spotted in the wild: a workflow's shutdown handler stuck in an infinite loop preventing the scheduler from exiting.

Propose applying a (global.cylc) configurable timeout to all workflow and task event handlers.

**Comment by hjoliver** [comment]
It sure is wild out there.

**Comment by oliver-sanders** [comment]
Turns out we already have a timeout via the subprocpool, the default is 10 mins. We probably just didn't wait long enough for this to kick in.

10 mins is quite long, but might be needed for some remote operations. There may be a use case for specifying event handler timeouts separately, but this will probably do for now.

https://cylc.github.io/cylc-doc/stable/html/reference/config/global.html#global.cylc[scheduler]process%20pool%20timeout
