### ISSUE TITLE
Contact file getting removed when host self-id is hardwired to localhost

### ISSUE THREAD

**Issue by retro486** [cylc/cylc-flow#6004]
This is a two-part issue, the first being why we had to hardwire the self identifier to "localhost" and the other is listed here when we do that. Edit: #6005 is the other half of this issue.

At seemingly random intervals (usually within a few minutes), workflows' contact files disappear and suites continue to run until their internal health check notices the disappearance and then self-destruct with:
_(Note the line numbers might be off because I added some inline LOG.debug's to try and trace what was happening but I've had no luck.)_
```
CRITICAL - An uncaught error caused Cylc to shut down.
    If you think this was an issue in Cylc, please report the following traceback to the developers.
    https://github.com/cylc/cylc-flow/issues/new?assignees=&labels=bug&template=bug.md&title=;
2024-02-28T21:07:22Z ERROR - /home/user/cylc-run/test/run15/.service/contact: contact file corrupted/modified and may be left
    Traceback (most recent call last):
      File "/home/user/mambaforge/envs/cylc8/lib/python3.9/site-packages/cylc/flow/scheduler.py", line 640, in run_scheduler
        await self.main_loop()
      File "/home/user/mambaforge/envs/cylc8/lib/python3.9/site-packages/cylc/flow/scheduler.py", line 1809, in main_loop
        await asyncio.gather(
      File "/home/user/mambaforge/envs/cylc8/lib/python3.9/site-packages/cylc/flow/main_loop/__init__.py", line 195, in _wrapper
        raise MainLoopPluginException(exc) from None
    cylc.flow.main_loop.MainLoopPluginException: /home/user/cylc-run/test/run15/.service/contact: contact file corrupted/modified and may be left
```

The config we're using:
```
[scheduler]
    UTC mode = True

    [[host self-identification]]
        method = hardwired
        host = localhost

    [[run hosts]]
        available = localhost
        ports = 43301 .. 43399

[install]
    source dirs = /etc/cylc8/suites

    [[symlink dirs]]
        [[[localhost]]]
            run = /var/job/cylc8

[platforms]
    [[localhost]]
        job runner = slurm
        job name length maximum = 236
        global init-script = """
            . ${HOME}/cylc8.env
        """
```
Full debug output of the workflow log of the most recent attempt, as close to when the contact file goes missing as I can get it, 
is attached. Note it doesn't show an exception about the missing contact file... It seems the health check only runs every 15 minutes so it hadn't been caught yet.
[debug_output.txt](https://github.com/cylc/cylc-flow/files/14451753/debug_output.txt)

**Comment by oliver-sanders** [comment]
The hardwired address should be configured to return a FQDN or IP address.

Returning `localhost` probably isn't going to work.

**Comment by retro486** [comment]
Unfortunately, when we try to hardcode to a hostname, Cylc doesn't recognize that it's the local host and attempts to SSH to it, which is being blocked by our HPC admin, so using localhost was the only way to force Cylc to skip the ssh. It feels like an edge-case, but between localhost causing unexpected behavior and the FQDN unpredictability in #6005, perhaps consider a brute-force flag for the platform definitions? Something like "is remote" or "use ssh" or something to explicitly tell Cylc to treat it like localhost for installs and other commands but allow it to bind to an actual interface rather than the loopback. Does that make sense?

**Comment by oliver-sanders** [comment]
Cylc should be smart enough not to SSH to localhost (it does check before doing this).

However, the hostname you configure needs to be consistent with `socket.gethostbyname_ex`. Try configuring it to the result of running this command:

```console
$ python -c "import socket; print(socket.gethostbyname_ex('vld601')[0])"
```

However, it's worth trying address mode first as this is a nicer solution.

**Comment by retro486** [comment]
Should I use the hostname in the "run hosts" and "platforms" sections and use the IP in the self-identification section? Or IP everywhere?

**Comment by oliver-sanders** [comment]
See conversation on https://github.com/cylc/cylc-flow/issues/6005

I'm closing this issue in favour of https://github.com/cylc/cylc-flow/issues/3768 which should provide us with a way forward.
