### ISSUE TITLE
tutorial: sleep if not doing anything

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#6041]
### Problem

Tutorial tasks run too fast to see in TUI and GUI, especially for the scheduling tutorials.

### Proposed Solution

Add sleeps to tutorials to slow the running of early examples down.

### Alternative proposed solution

Wait for task-by-task run mode setting provided as part of the skip mode work and use simulation mode instead. In my opinion this is better for learners because `[TASK]run mode = simulation` makes it very explicit that the task isn't running anything real.

**Comment by oliver-sanders** [comment]
Putting a simple 2-4s sleep in for now so we can get this deployed before the next training session.

@wxtim, feel free to re-open if you had something fancier in mind.

**Comment by wxtim** [comment]
> Putting a simple 2-4s sleep in for now so we can get this deployed before the next training session.
> 
> @wxtim, feel free to re-open if you had something fancier in mind.

I am fine with this.
