### ISSUE TITLE
missing s after string templates in documentation

### ISSUE THREAD

**Issue by Diquan-BOM** [cylc/cylc-flow#6050]
https://github.com/cylc/cylc-flow/blob/69fbe03de7ed851a2fe1513614a97405ac3eaf7f/cylc/flow/xtrigger_mgr.py#L63

**Comment by Diquan-BOM** [comment]
Just a small change to the documentation, adding the s after the string templates happy to do the pull request myself if wanted.

**Comment by hjoliver** [comment]
Thanks, good spotting. Please do put up a PR!
