### ISSUE TITLE
suicide triggers broken

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6066]
This example works (tasks a and c automatically removed, workflow shuts down) in Cylc 7 but stalls in Cylc 8:

```ini
# suite.rc
[scheduling]
    cycling mode = integer
    initial cycle point = 1
    [[dependencies]]
        [[[R1]]]
            graph = """
                a & b => c
                a:fail => !a & !c
            """

[runtime]
    [[a]]
        script = false
    [[b,c]]
```

This example also stalls in Cylc 8:

```ini
# flow.cylc
[scheduling]
    cycling mode = integer
    initial cycle point = 1
    [[dependencies]]
        [[[R1]]]
            graph = """
                a? & b => c
                a:fail? => !a & !c
            """

[runtime]
    [[a]]
        script = false
    [[b,c]]
```

Slightly related to https://github.com/cylc/cylc-flow/issues/5729 as this covers some or all of the remaining use cases for suicide triggers.

**Comment by hjoliver** [comment]
On 8.2.x, this diff is enough to make it work, but not on master.
```diff
-    [[b,c]]
+    [[b,c]]
+        script = sleep 2
```
Looks like something to do with suicide interfering with the record of previous spawning....

**Comment by hjoliver** [comment]
The two cases look almost identical until:
- "1/c already spawned in flow 1" 👍 
- OR 1/c gets spawned again, which causes the problem 👎 

![image](https://github.com/cylc/cylc-flow/assets/2362137/4ce7449c-8538-4d60-8eea-3103161a0e9f)

**Comment by hjoliver** [comment]
If `b` succeeds before `a` fails:
- `b` spawns `c`, then `a` removes `c` 👍 

If `a` fails before `b` succeeds:
- `a` spawns and removes `c`, then `b` spawns `c` again (causing a stall) 👎
