### ISSUE TITLE
help string tweak for `cylc stop`

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#6126]
```
$ cylc stop --help | grep -B1 -A5 mode
By default stopping workflows wait for submitted and running tasks to complete
before shutting down. You can change this behaviour with the --mode option.

There are several shutdown methods:

  1. (default) stop after current active tasks finish
  2. (--now) stop immediately, orphaning current active tasks
```

The text `You can change this behaviour with the --mode option` made me think there was a `--mode` option which wasn't showing up in the help syntax, or maybe one was there and removed. I believe it is just referring to the `--kill`, `--now` type options? I'm not sure how, but could the text here be adapted to not say `--mode` which looks like a real option?

**Comment by MetRonnie** [comment]
Closed by #6233?
