### ISSUE TITLE
triggering a queued task in a different flow has no effect

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6174]
It would appear that it is not possible to trigger a task in a different flow when it is queued. This could, potentially, be true of waiting states in general, investigation needed.

Example workflow:

```ini
[scheduling]
    [[graph]]
        R1 = foo
[runtime]
    [[foo]]

```

Instructions to reproduce:

```console
$ cylc vip --pause
$ cylc trigger <workflow>//1/foo --flow=2
$ cylc play <workflow>
$ sleep 5
$ sqlite3 ~/cylc-run/one/run1/.service/db 'select * from task_outputs'
1|foo|[1]|["submitted", "started", "succeeded"]
```

The new flow is logged:

```
INFO - New flow: 2 (no description) 
```

However, the task does not run in it:

```
INFO - [1/foo:waiting] => preparing
```

As evidenced by the DB showing the resulting task outputs as existing in flow `[1]`.

**Comment by wxtim** [comment]
Have replicated this with a runahead limited task.

**Comment by oliver-sanders** [comment]
Should be fixed in Hillary's PR, try it out.
