### ISSUE TITLE
Stalled paused workflows incorrectly have running status

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#6199]
### Description

Stall a workflow. Whilst stalled the top level pause button will be unavailable.

![image](https://github.com/cylc/cylc-ui/assets/26465611/0b9a8c91-a4ff-4f2f-a2f2-25fca1fd7e7f)

You can still pause the workflow
  * Via the burger bar drop-down
  * In Tui 🐦‍
  * On the CLI

Which suggests that it's a GUI issue.

**Comment by MetRonnie** [comment]
A cylc-flow bug, as it turns out
