### ISSUE TITLE
More robust handing of user provided environment variables in job scripts

### ISSUE THREAD

**Issue by jfrost-mo** [cylc/cylc-flow#6202]
### Problem

It is currently difficult to pass arbitrary text into a job from rose edit, due to the many layers of interpretation that variables go through. One of these layers is inside of job scripts, where variables are stored within double quotes (`"`), which can cause contained quotes to be matched and cause trouble, as well as `$MY_VAR` variable references being interpreted.

### Proposed Solution

A [here document](https://www.gnu.org/software/bash/manual/html_node/Redirections.html#Here-Documents) with an obscure terminating sequence should be sufficient to avoid this.

**Comment by jfrost-mo** [comment]
To consider: Do we want variable interpretation inside the environment variables? I think the current implementation does.

**Comment by hjoliver** [comment]
Seems like a reasonable proposal.

> Do we want variable interpretation inside the environment variables? I think the current implementation does.

Yes, trying to recall why, I think it's to allow this sort of thing:
```
XDIR=/a/b/c
CAT=${XDIR}/y
DOG=${XDIR}/z
```

**Comment by ColemanTom** [comment]
Without looking too closely at this discussion or topic, `HERE` strings/documents do write temporary files to disk. Is this desired? It can lead to unexpected failures if the temporary area they write to is full for example. It can also, if that filesystem is under high strain for whatever reason, cause a slowdown in performance.

```
$ bash -c 'lsof -a -p $$ -d0' << EOF
> EOF
COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lsof    ... ... 0r   REG    8,4        0 1678 /tmp/sh-thd.vZ6gYE (deleted)
```

**Comment by hjoliver** [comment]
Hmm, yes that might be a problem @ColemanTom .  In fact I think this hit us already, some time back. I'll see if I can dig up the history.

**Comment by hjoliver** [comment]
Here it is:

https://github.com/cylc/cylc-flow/blob/f8d0510adc5dfbd7218e029c2c37c89b6d2edd6a/cylc/flow/etc/job.sh#L64-L66

Might be a show-stopper sorry @jfrost-mo (otherwise we wouldn't have switched back and left that comment for future reference).

**Comment by jfrost-mo** [comment]
Ah, fair enough. I didn't know that here-documents were implemented with temporary files. You learn something new every day.

**Comment by oliver-sanders** [comment]
> Ah, fair enough. I didn't know that here-documents were implemented with temporary files. 

Indeed they are, I'm afraid this is a show stopper.

**Comment by oliver-sanders** [comment]
If you do not want shell expansion, then one thing you can do is to store arbitrary text in a file. In Rose apps, anything located in the `file/` directory will be installed when the app is run. The downside is that this less visible through Rose Edit which is unable to edit them directly.

An alternative approach might be to use single quotes. The quotes used are [within our control](https://github.com/cylc/cylc-flow/pull/6203/files#diff-aa38b5fdd47f514009d0aacd8e9d24b176ad9ca13cd8ae5e3f8b3aff26ba8069L260-L263), intelligent selection is possible.

**Comment by jfrost-mo** [comment]
I feel like some explicit quoting with [shlex.quote](https://docs.python.org/3/library/shlex.html#shlex.quote) should be possible, however that blocks variable interpretation.

For my own use case I'm interesting in supporting values containing quotes in rose edit, but I may just have to encode them before passing them through cylc.

**Comment by oliver-sanders** [comment]
The easiest solution is probably to use an `env-script`:

```ini
[runtime]
  [[mytask]]
    env-script = """
      export ENV_VAR_TEMPLATE1='foo_${BAR}_baz'
      export ENV_VAR_TEMPLATE2='pub_${QUX}'
    """
    script = rose task-run
```
