### ISSUE TITLE
cylc lint and CYLC_SUITE_DEF_PATH variable (rule U013) message is not complete

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#6205]
### Description

Cylc lint, running on a variable `CYLC_SUITE_DEF_PATH` does not provide a properly resolved explanation of the linting failure, `[U013] flow.cylc:3: Obsolete environment variables: {vars}`. If the variable is, for example, `CYLC_SUITE_NAME`, then it will provide a useful message, `[U012] flow.cylc:3: Deprecated environment variables: ['CYLC_SUITE_NAME: CYLC_WORKFLOW_ID']`.

NOTE: Using `cylc-flow=8.3.0`

### Reproducible Example

flow.cylc: 

```
[runtime]
    [[root]]
        script = echo $CYLC_SUITE_DEF_PATH
```

```
$ cylc lint
[U013] flow.cylc:3: Obsolete environment variables: {vars}

Checked /tmp/basic-workflow against ['728', 'style'] rules and found 1 issue.
```

### Expected Behaviour

`{vars}` should say what the variable is (and if possible, a suitable alternative if one exists).

**Comment by hjoliver** [comment]
That looks an `f-string` with the "f" missing.

**Comment by ColemanTom** [comment]
Looking at the code, partially. 

```
    'U013': {
        'short': (
            'Obsolete environment variables: {vars}'),
        'rst': (
            'The following environment variables are obsolete:\n\n'
            + ''.join([f'\n * ``{old}``' for old in OBSOLETE_ENV_VARS])
        ),
```

So, lacking the `f` in the `short` and `rst` version, but `vars` is never defined for the `short` version I don't think.

**Comment by wxtim** [comment]
Sorry, this is a bit obscure, but you don't define an f-string here: The function should return a dictionary to be passed to the format function as kwargs, but doesnt - for example:

```
def check(line):
    if '42' in line:
         return {'vars': 42}
    return {}

```

**Comment by ColemanTom** [comment]
I think this can be closed? Unless there is more to this than the MR which merged last week?
