### ISSUE TITLE
Color tags appearing in CLI output for already running workflow

### ISSUE THREAD

**Issue by elliotfontaine** [cylc/cylc-flow#6227]
### Description

```
fontain@srv-rtmet:~/github/RTMet$ cylc install bioreactor-workflow -r 20240712_experiment
INSTALLED bioreactor-workflow/20240712_experiment from /home/fontain/github/RTMet/cylc-src/bioreactor-workflow
<yellow>NOTE: 1 run of "bioreactor-workflow" is already active:</yellow>
  ▶ bioreactor-workflow/influxdb-guide srv-rtmet.redacted 3946088
You can stop it with:
  cylc stop bioreactor-workflow/influxdb-guide
See "cylc stop --help" for options.
```

It could my terminal emulator (though it happened with both Command Prompt and VSCode integrated terminal). But it
doesn't show a ANSI code but some HTML looking tags. It's like they haven't been parsed prior to be displayed ?

### Reproducible Example

Install a new run of a workflow while another run is already active.

### Expected Behaviour

Display the text in yellow or don't show the tags.

**Comment by hjoliver** [comment]
(I've noticed this too, but hadn't got around to investigating)
