### ISSUE TITLE
glblcfg: platform not found

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6244]
We are seeing multiple reports of issues where platforms which are defined in the global configuration are reported as not being found at task submission time.

To activate this bug:
* Write a workflow which gas a task that runs on a remote platform.
* Add a `rose-suite.conf` file.
* Run the workflow in `--debug` mode.

Although some reports suggest that the issue can be replicated without the `--debug` flag, we have yet to reproduce this ourselves.

The origin of the bug is a feature that was added to cylc-rose (released in conjunction with cylc-flow 8.3.0): https://github.com/cylc/cylc-rose/pull/269/files#diff-aa4c6cd8a676c24d08145f471d2e3830f1e41677a6cd1d1b9ce0fd93ced9c6c8R877-R878

This feature reloads the global configuration (`glbl_cfg().load()`). The reload wipes the platforms in the process, but this only appears to happen when `--debug` is set for reasons not yet understood.

**Comment by oliver-sanders** [comment]
Reproducible example?

**Comment by ScottWales** [comment]
A suspicion that I have is that when debug is enabled the global config is read as part of logging messages, which happens before or at the same time as when Rose reloads the configuration. Potentially some sort of async race?

**Comment by wxtim** [comment]
> Reproducible example?

It's in `$HOME/cylc-src/bugs/` with an appropriate name, but it was a very, very simple workflow, with an empty `rose-suite.conf`.

**Comment by oliver-sanders** [comment]
> It's in $HOME/cylc-src/bugs/ with an appropriate name

This example does not reproduce the bug without using `--debug`.

**Comment by MetRonnie** [comment]
This diff fixes the problem by avoiding `.get()`ing the global config on every log call.

```diff
diff --git a/cylc/flow/loggingutil.py b/cylc/flow/loggingutil.py
index 3d77bdcb0..a46c09db3 100644
--- a/cylc/flow/loggingutil.py
+++ b/cylc/flow/loggingutil.py
@@ -161,4 +161,9 @@ class RotatingLogFileHandler(logging.FileHandler):
         self.log_num: Optional[int] = None  # null value until log file created
 
+        self.max_bytes = glbl_cfg().get(
+            ['scheduler', 'logging', 'maximum size in bytes'])
+        if self.max_bytes < self.MIN_BYTES:  # No silly value
+            self.max_bytes = self.MIN_BYTES
+
     def emit(self, record):
         """Emit a record, rollover log if necessary."""
@@ -197,8 +202,4 @@ class RotatingLogFileHandler(logging.FileHandler):
         if self.log_num is None or self.stream is None:
             return True
-        max_bytes = glbl_cfg().get(
-            ['scheduler', 'logging', 'maximum size in bytes'])
-        if max_bytes < self.MIN_BYTES:  # No silly value
-            max_bytes = self.MIN_BYTES
         msg = "%s\n" % self.format(record)
         try:
@@ -208,5 +209,5 @@ class RotatingLogFileHandler(logging.FileHandler):
             # intended to catch - ValueError: I/O operation on closed file
             raise SystemExit(exc)
-        return self.stream.tell() + len(msg.encode('utf8')) >= max_bytes
+        return self.stream.tell() + len(msg.encode('utf8')) >= self.max_bytes
 
     @property
```

But it loses the ability for a change to `global.cylc[scheduler][logging]maximum size in bytes` to affect a running workflow (do we even want this?)

**Comment by MetRonnie** [comment]
I think accessing the global config during a logging emission is fundamentally flawed, as it can cause the global config to be expanded in between the `self.dense.clear()` and `self.expand()` when loading the config. Because `self.sparse` was cleared before this there is nothing to expand with if expansion happens too early

https://github.com/cylc/cylc-flow/blob/52d523d85e99f23f020420d12e537621c7ed10a5/cylc/flow/cfgspec/globalcfg.py#L2010-L2031

**Comment by oliver-sanders** [comment]
Accessing the global config whilst it is being reloaded is definitely flawed!

Does moving the `LOG.debug` up a couple of lines fix it, or are there other `LOG.debug` statements out there to worry about?

**Comment by MetRonnie** [comment]
> Does moving the `LOG.debug` up a couple of lines fix it, or are there other `LOG.debug` statements out there to worry about?

There are quite a few other `LOG.debug`s to worry about. (Also the ZMQ Authenticator has been passed the Cylc log to use for its logging which is why you see stuff like "ZAP reply" and "curve response" or whatever in the logs in debug - I think we should reconsider this)





> Curiously, this bug is only activated when the config is reloaded (from cylc-rose), the same `load` method is called when the config is loaded in the first instance, but that doesn't cause the bug?

Yes I was wondering about this. I haven't looked into why the first load doesn't hit the problem.

**Comment by oliver-sanders** [comment]
The use of the global config to configure logging and the use of the logger in the authenticator are both perfectly reasonable, I don't think we should back out of either (it would be easier to back out of the cylc-rose feature that reloads the cached global config instance).

Note, reloading the cached global config instance is something we have never done before.

**Comment by oliver-sanders** [comment]
> Could we solve this by loading a new global config instance and swapping it for the cached instance

Looks like this works nicely.

**Comment by oliver-sanders** [comment]
@MetRonnie, I've put up a couple of PRs along the lines of the above suggestion which appear to do the job.

See what you think.

**Comment by MetRonnie** [comment]
> > Curiously, this bug is only activated when the config is reloaded (from cylc-rose), the same `load` method is called when the config is loaded in the first instance, but that doesn't cause the bug?
> 
> Yes I was wondering about this. I haven't looked into why the first load doesn't hit the problem.

Ah ok, the answer was simply that the logging handler had not been instantiated by the time the first config load!

**Comment by MetRonnie** [comment]
> The use of the global config to configure logging and the use of the logger in the authenticator are both perfectly reasonable, I don't think we should back out of either

Note my diff does not back out of using the global config to configure logging, it simply caches the results on instantiation of the logging handler and avoids any possibility of modifying the config object during a logging emission.
