### ISSUE TITLE
examples: irregular cycling

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6272]
Document a use case we occasionally see at our site where a workflow must cycle over an irregular list of dates.

Illustrative example:

```
#!jinja2
{% set dates = ['2000-01-01', '2022-01-05', '2024-01-07', '2024-01-10'] %}

[scheduling]
  initial cycle point = 1000-01-01
  [[graph]]
    {% for date in dates %}
    R1/{{date}} = "task1"
    {% endfor %}
```

These workflows are often used for "case studies":

* They may need to incorporate regular cycling.
* They may need inter-cycle dependencies (use Jinja2 + isodatetime to compute the cycle offset).

**Comment by wxtim** [comment]
Not dissimilar to https://github.com/wxtim/workflows/blob/cylc-8/strange-parameters/flow.cylc which uses a custom prime number cycling.
