### ISSUE TITLE
should generate_graph_children() filter out abs deps from other cycles

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6290]
There's an `if` statement in the code that filters out absolute dependencies from other cycles.

It's not entirely clear why this statement was added, the corresponding statement in `generate_graph_parents` was removed, should this one be removed too?

See this comment:

> What about this equivalent bit in `generate_graph_children()`?
https://github.com/cylc/cylc-flow/blob/4d6430a7f0905201c1206f18c2f348d26a82b32e/cylc/flow/taskdef.py#L49-L51
>
> _Originally posted by @MetRonnie in https://github.com/cylc/cylc-flow/issues/6103#issuecomment-2245420604_
            

* Are there any consequences to this statement? Are there graphs where this could cause a bug?
* Are there any consequences to removing this statement? E.G. Does it impact performance, causing double counting?

@dwsutherland, any insights welcome.

**Comment by dwsutherland** [comment]
Not entirely sure.. Because the children of `[^]` are potentially infinite, where the parents are not?
Don't think I was the original author (although possible?)

**Comment by oliver-sanders** [comment]
> Not entirely sure.. Because the children of [^] are potentially infinite, where the parents are not?

That makes good sense!

**Comment by oliver-sanders** [comment]
With the change to grah-parents, abs deps seem to be working as expected, @MetRonnie, please close if you're happy with this explanation.

**Comment by MetRonnie** [comment]
We do seem to have coverage for the `continue` statement, but I'm struggling to understand how it could be reached.

As we are in the `generate_graph_children` function, for an absolute trigger won't the point always be the parent point?

I.e. for `foo[5] => bar`, when we generate the graph children for `5/foo`, the parent point of the trigger `foo[5]` is 5

**Comment by MetRonnie** [comment]
Ok I've managed to figure out a case where this `continue` is hit
```
        P1 = foo
        R1/2 = foo[1] => pub
```

Without this `continue`, it results in edges that shouldn't exist (only `1/foo -> 2/pub` should exist):

![image](https://github.com/user-attachments/assets/acf5e549-be34-4c64-b624-a6ed5dc65072)
