### ISSUE TITLE
GraphParseError does not print name of non-family namespace that caused error

### ISSUE THREAD

**Issue by uwagura** [cylc/cylc-flow#6331]
### Description

In version 8.3.3 of cylc, `GraphParseError` does not include the name of the namespace that produced the error
### Reproducible Example

Run a command like `cylc graph .` on the following workflow:
```
[scheduling]
    [[graph]]
            R1 = "prep => not-fam:succeed-all => final"
[runtime]
    [[prep]]
    [[not-fam]]
    [[final]]

```
### Expected Behaviour

The above workflow will give you an error that says 
```
GraphParseError: family trigger on non-family namespace {expr}
```
When I believe that it should say
```
GraphParseError: family trigger on non-family namespace not-fam
```
I think this error is just caused by a missing `f` in the following format string. Although it is a small issue, I thought I'd let the development team know just in case the issue occurs in other places as well.
https://github.com/cylc/cylc-flow/blob/cadf1ef057145873f869092ffcab9784ad7c082e/cylc/flow/graph_parser.py#L644-L648

**Comment by oliver-sanders** [comment]
Closed by #6332
