### ISSUE TITLE
xtrigger wall_clock offset trimmed to `cycle point format`

### ISSUE THREAD

**Issue by dwsutherland** [cylc/cylc-flow#6423]
### Description

The xtrigger `wall_clock` offset is trimmed to precision of `cycle point format`

### Reproducible Example
```
[scheduler]
    cycle point format = CCYYMMDDThh
    allow implicit tasks = True
[scheduling]
    initial cycle point = 20241017T00
    [[xtriggers]]
        clock_PT25M = wall_clock(offset=PT25M):PT20S
    [[graph]]
        T-00 = """
@clock_PT25M => a
"""

[runtime]
    [[root]]
        script = sleep $((1 + $RANDOM % 10))
```
![image](https://github.com/user-attachments/assets/26766960-179c-4acd-8d72-c33fa433ad7d)

### Expected Behaviour

The `wall_clock` offset should not be restricted by the cycle point precision

![image](https://github.com/user-attachments/assets/4fef56a5-6f39-462c-b7a6-f0410e67567a)

**Comment by MetRonnie** [comment]
I thought the cycle point format _is_ a limit on the precision of the cycling of the workflow?

**Comment by dwsutherland** [comment]
So I just need to use the `point` in:
`trigger_time = point + ISO8601Interval(offset_str)`
to create a higher resolution before this addition.
Will do tomorrow

**Comment by dwsutherland** [comment]
> N.B. while the cycle point format _is_ a limit on the precision of the cycling of the workflow, you're right it should still be possible to define an hour-precision cycle would be triggered at e.g. 25 mins past the wall clock hour.

Yeah, we have justified uses at NIWA .. i.e. observed data comes in at 35min past the hour, but we only need hourly cycling..
This has changed between Cylc7 and Cylc8, it use to work.

**Comment by dwsutherland** [comment]
Fix is up, and precision valid to seconds:
![image](https://github.com/user-attachments/assets/a22a3f2e-223a-4087-b7f3-3fdc2af23b79)
