### ISSUE TITLE
scheduler: gracefully handle SIGTERM and more gracefully handle SIGINT

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6438]
To facilitate Cylc development in `--no-detach` mode, the scheduler handles the SIGINT signal.

As far as I'm aware, this is a development feature that isn't really intended for production purposes. When SIGINT is received, Cylc handles it like an internal error and performs a panic shutdown:

https://github.com/cylc/cylc-flow/blob/4aa492d95c82bc55ac2f49b7beeefb057fcae48c/cylc/flow/scheduler.py#L674-L675

Note, `except KeyboardInterrupt` is a Python mechanism for intercepting SIGINT.

This panic shutdown isn't the most elegant, the filesystem might not be left as intended and Cylc does not handle SIGTERM at all. A use case has recently been raised for handling signals with graceful shutdown.

**Proposal:**
* Handle both SIGINT and SIGTERM from within the detached scheduler.
* Trigger a `StopMode.REQUEST_NOW_NOW` shutdown for either signal.

**TODO:**
* [x] Implement.
* [x] Functional test.
* [x] Document.

**Comment by hjoliver** [comment]
100% agreed. Not sure it even needs to be a "question" (remove the label if you like!)
