### ISSUE TITLE
Lint: `=> \` Deprecated at Cylc 6.

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-flow#6456]
### New rules proposal.

The backslash in `=> \`  hasn't been required but there was no upgrade or obsolete message because it's inside the graph. Lint should probably point this out.

Additionally, consider a second almost identical rule for `& \` and `| \` both of which are unecessary at Cylc 8. I'm in favour because;

- Users _should_ be upgrading from Cylc 7 and back and forward compatible workflows should be becoming less common.
- Users can always use `pyproject.toml` to disable the rule.

**Comment by oliver-sanders** [comment]
(changed milestone to match PR)
