### ISSUE TITLE
EmPy: Drop support

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#6458]
Cylc has provided EmPy support for a few years, however, it has had very little uptake in that time.

* EmPy support was provided at the request of a project which has since moved away from it.
* Support has been broken since November 2023, however, this has gone [unreported until recently](https://github.com/cylc/cylc-flow/pull/6248).
* It would appear that no Cylc users are making use of EmPy support (they can't be, it's broken).
* Cylc-EmPy integration is poorly developed in contrast to Jinja2 support.
* EmPy is a high risk dependency (single maintainer, no public source repo, intermittent release cycle).

As a result we have agreed to retire support ([meeting 2024-11-04](https://github.com/cylc/cylc-admin/issues/188#issuecomment-2225293775)).

Cylc's preprocessor logic is fairly well abstracted (shebang to identify preprocessor, relatively simple to write a preprocessor module, Cylc&Rose both abstract template variable arguments from the preprocessor engine) so supporting other preprocessors remains possible, though probably something we would want to confine to a plugin rather than accepting into the core repository. We should aim to abstract the pre-processor interface to make this more pluggable in the future.

TODO:
* [ ] Cylc Flow (remove references, add helpful error message)
* [ ] Cylc Rose (remove references)
* [ ] Docs (remove references)
* [ ] Syntax files (we can remove references here, but don't *need* to).

**Comment by MetRonnie** [comment]
I think ideally we would want to do this in 8.5 and just put a deprecation warning in 8.4? Or do we think we literally don't have any EmPy users?
