### ISSUE TITLE
Reload global config on demand

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#6486]
https://cylc.discourse.group/t/how-to-force-global-cylc-get-reloaded-reevaluated/1063

Currently users have to stop and restart workflows to update global config.

Question: should we provide global config reload on demand?

**Comment by oliver-sanders** [comment]
Duplicate of https://github.com/cylc/cylc-flow/issues/3762

**Comment by hjoliver** [comment]
It's not exactly a duplicate - this is about on-demand reload, but I'll add a note to the other issue.

**Comment by oliver-sanders** [comment]
Yes, the other issue is about doing this on a timer, not on reload, but the functionality / changes required to make it work are common so I will merge this use case in.
