### ISSUE TITLE
Delay before commands work after workflow startup

### ISSUE THREAD

**Issue by dpmatthews** [cylc/cylc-flow#6504]
### Description

There is an unexpected delay before many cylc commands work after workflow startup.

### Reproducible Example

If I run a workflow, `cylc ping` (and other commands) still fail after 20s.

```
$ cylc vip -n start-up-test; sleep 20s; cylc ping start-up-test
...
WorkflowStopped: start-up-test/run1 is not running
```

However, if I run `cylc scan` first, `cylc ping` works immediately after start-up.

This needs run hosts enabled to reproduce; it is not reproduceable if using `--host=localhost`.

### Expected Behaviour

All commands should be able to interact with workflows immediately after startup.

**Comment by MetRonnie** [comment]
(Edited for clarity around run hosts)

**Comment by dpmatthews** [comment]
Superceded by #6506
