### ISSUE TITLE
Use {varname} automatic file descriptor instead of hardcoding a number when setting BASH_XTRACEFD?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#6515]
### Problem

I was doing some work which involved setting some output redirection up. I remembered that Cylc sometimes did some in the `job.sh`. For example:

```
            exec 19>>"${CYLC_RUN_DIR}/${CYLC_WORKFLOW_ID}/log/job/${CYLC_TASK_JOB}/job.xtrace"
            export BASH_XTRACEFD=19
```

### Proposed Solution

I wasn't sure if it was fair to assume bash 4.1, but if so, perhaps using varname style automatic file descriptors would be safer.

```
            exec {CYLC_BASH_XTRACEFD}>>"${CYLC_RUN_DIR}/${CYLC_WORKFLOW_ID}/log/job/${CYLC_TASK_JOB}/job.xtrace"
            export BASH_XTRACEFD=${CYLC_BASH_EXTRACEEFD}
```

If that assumption isn't safe, then similar can be done using by iterating over numbers from 19 upwards, checking if its in /dev/fd already, and if not, using that number (just then requires an eval to setup the `exec` line).

Or, perhaps I'm being overly paranoid of overlapping file descriptors.

**Comment by oliver-sanders** [comment]
> I wasn't sure if it was fair to assume bash 4.1

Unfortunately, we still require compatibility with older versions of Bash for certain platforms.

This requirement will reduce in time, however, a few operating systems are moving away from Bash. E.G, mac os has Bash 3 installed by default.

**Comment by hjoliver** [comment]
@ColemanTom - are you concerned that fd 19 might be used for something else?  If so, is that really possible in the context of a Cylc job script?

**Comment by ColemanTom** [comment]
> @ColemanTom - are you concerned that fd 19 might be used for something else? If so, is that really possible in the context of a Cylc job script?

It was a very low risk (I also didn't realise that fd 19 didn't flow into child processors, so even lower a risk than I realised). Given the requirements of supporting early versions of bash, and the low risk, I'll close it.
