### ISSUE TITLE
suite database: task and job status

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc-flow#864]
Cylc has changed a lot since we implemented the task states and events database in #198. It is about time that we rethink the data model. This is a list of things I can think of, roughly arranged in possible tables.

Job status:
- [ ] time created/updated?
- [X] task name
- [X] cycle
- [X] job (i.e. submit) number
- [ ] job type (normal, submit retry, run retry, manual trigger originator)
- [X] submit status
- [X] run status
- [X] run signal
- [X] time of submit
- [X] time run init
- [X] time run exit
- [ ] time disappeared
- [X] user@host of submit
- [X] batch system name
- [X] batch system job ID
- [ ] cost (e.g. memory, CPUs, wall clock, if possible or relevant)

Task pool/status:
- [X] time created/updated
- [X] task name
- [X] cycle
- [X] n-jobs
- [x] n-submit-retries
- [x] n-execute-retries
- [X] has spawned its successor? (Or store successor cycle?)
- [ ] status (improved?)
  - held:
    - held by prerequisites
    - held by runahead
    - held by queue
    - held by user?
    - held by shutdown?
    - (anything else?)
  - active
    - job submitting
    - job submitted
    - job running
    - waiting to re-submit a new job
  - complete (state of final job)
    - submit-failed
    - disappeared
    - run-ok
    - run-failed

Task status change:
- [ ] time
- [ ] task name
- [ ] cycle
- [ ] old value
- [ ] new value
- [ ] change originator (if change is the result of a user request)

Do we need to store task prerequisites? If so:

Task prerequisites and outputs:
- [ ] task name
- [ ] cycle
- [ ] prerequisite/output
- [ ] time when this prerequisite is met or output is done

See also #421, #705, #1032.

**Comment by matthewrmshin** [comment]
Job status and log files table implemented in #1493.

**Comment by benfitzpatrick** [comment]
@matthewrmshin, please strike through stuff that's done.

**Comment by matthewrmshin** [comment]
A user mentioned that it would be useful to be able to easily find out if a task's status has been reset by a user command or not via Rose Bush. Currently, we can only find this information via the suite log. If we have a table to record task status change time and originator in the database, we should be able to display the information via Rose Bush (or successor).

**Comment by oliver-sanders** [comment]
Most of this is now done. We are considering a DB refactor, closing this as superseded by #3872.
