### ISSUE TITLE
limit task pool size

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#987]
Currently (on the iso8601 branch) the runahead limit is a suite-wide parameter that acts as follows: each task proxy spawns a 'waiting' successor when it enters the 'submitted' state.  If a waiting task is beyond the runahead limit, it goes into a special pool that does not participate in dependency matching.  Tasks under the limit drop back into the main pool.  So at least one instance of every defined task proxy exists at any one time, more if one or more instances are submitted or running at the time. Only those below the runahead limit will impact scheduling performance (but all affect cylc's memory footprint).  Note that tasks do not spawn multiple waiting instances out to the runahead limit.

@matthewrmshin has some ideas on how to avoid a suite-wide runahead limit...

[edit: it seems the focus of this issue is really on limiting the task pool size, which is one function of the runahead limit but not the only one - we may still need it as well (see below).]

**Comment by hjoliver** [comment]
[meeting]
 * agreed we should move to spawn immediate graph descendants of active tasks
 * we'll need to be able to operate on tasks that are not in the pool yet or have left it

**Comment by benfitzpatrick** [comment]
When we change the spawning behaviour (see the superseded issue #1538) so that there is not an implicit task successors submit dependency, we need to be able to report possible changes in behaviour in cylc validate
